# uncompyle6 version 3.7.4
# Python bytecode 2.4 (62061)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/uncompyle6/semantics/customize38.py
# Compiled at: 2019-12-14 21:32:13
"""Isolate Python 3.8 version-specific semantic actions here.
"""
from uncompyle6.semantics.consts import TABLE_DIRECT

def customize_for_version38(self, version):
    TABLE_DIRECT.update({'async_for_stmt38': ('%|async for %c in %c:\n%+%c%-%-\n\n', (7, 'store'), (0, 'expr'), (8, 'for_block')), 'async_forelse_stmt38': ('%|async for %c in %c:\n%+%c%-%|else:\n%+%c%-\n\n', (7, 'store'), (0, 'expr'), (8, 'for_block'), (-1, 'else_suite')), 'async_with_stmt38': ('%|async with %c:\n%+%|%c%-', (0, 'expr'), 7), 'async_with_as_stmt38': ('%|async with %c as %c:\n%+%|%c%-', (0, 'expr'), (6, 'store'), (7, 'suite_stmts')), 'except_handler38': ('%c', (2, 'except_stmts')), 'except_handler38a': ('%c', (-2, 'stmts')), 'except_ret38a': ('return %c', (4, 'expr')), 'except_ret38': ('%|return %c\n', (1, 'expr')), 'for38': ('%|for %c in %c:\n%+%c%-\n\n', (2, 'store'), (0, 'expr'), (3, 'for_block')), 'forelsestmt38': ('%|for %c in %c:\n%+%c%-%|else:\n%+%c%-\n\n', (2, 'store'), (0, 'expr'), (3, 'for_block'), -2), 'forelselaststmt38': ('%|for %c in %c:\n%+%c%-%|else:\n%+%c%-', (2, 'store'), (0, 'expr'), (3, 'for_block'), -2), 'forelselaststmtl38': ('%|for %c in %c:\n%+%c%-%|else:\n%+%c%-\n\n', (2, 'store'), (0, 'expr'), (3, 'for_block'), -2), 'ifpoplaststmtl': ('%|if %c:\n%+%c%-', (0, 'testexpr'), (2, 'c_stmts')), 'ifstmtl': ('%|if %c:\n%+%c%-', (0, 'testexpr'), (1, '_ifstmts_jumpl')), 'whilestmt38': ('%|while %c:\n%+%c%-\n\n', (1, 'testexpr'), 2), 'whileTruestmt38': ('%|while True:\n%+%c%-\n\n', 1), 'try_elsestmtl38': ('%|try:\n%+%c%-%c%|else:\n%+%c%-', (1, 'suite_stmts_opt'), (3, 'except_handler38'), (5, 'else_suitel')), 'try_except38': ('%|try:\n%+%c\n%-%|except:\n%|%-%c\n\n', (-2, 'suite_stmts_opt'), (-1, 'except_handler38a')), 'try_except_ret38': ('%|try:\n%+%|return %c%-\n%|except:\n%+%|%c%-\n\n', (1, 'expr'), (-1, 'except_ret38a')), 'tryfinally38rstmt': ('%|try:\n%+%c%-%|finally:\n%+%c%-\n\n', (3, 'returns'), 6), 'tryfinally38stmt': ('%|try:\n%+%c%-%|finally:\n%+%c%-\n\n', (1, 'suite_stmts_opt'), (6, 'suite_stmts_opt')), 'tryfinally38astmt': ('%|try:\n%+%c%-%|finally:\n%+%c%-\n\n', (2, 'suite_stmts_opt'), (8, 'suite_stmts_opt')), 'named_expr': ('%c := %c', (2, 'store'), (0, 'expr'))})