# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.9-intel/egg/wysihtml5/conf/defaults.py
# Compiled at: 2014-01-19 03:33:05
from django.conf import settings
WYSIHTML5_EDITOR = {'name': 'null', 
   'style': 'true', 
   'toolbar': 'null', 
   'autoLink': 'true', 
   'parserRules': 'wysihtml5ParserRules', 
   'parser': 'wysihtml5.dom.parse || Prototype.K', 
   'composerClassName': '"wysihtml5-editor"', 
   'bodyClassName': '"wysihtml5-supported"', 
   'useLineBreaks': 'true', 
   'stylesheets': '["%s"]' % (settings.STATIC_URL + 'wysihtml5/css/stylesheet.css'), 
   'placeholderText': 'null', 
   'allowObjectResizing': 'true', 
   'supportTouchDevices': 'true'}
WYSIHTML5_TOOLBAR = {'formatBlockHeader': {'active': True, 
                         'command_name': 'formatBlock', 
                         'render_icon': 'wysihtml5.widgets.render_formatBlockHeader_icon'}, 
   'formatBlockParagraph': {'active': True, 
                            'command_name': 'formatBlock', 
                            'render_icon': 'wysihtml5.widgets.render_formatBlockParagraph_icon'}, 
   'bold': {'active': True, 
            'command_name': 'bold', 
            'render_icon': 'wysihtml5.widgets.render_bold_icon'}, 
   'italic': {'active': True, 
              'command_name': 'italic', 
              'render_icon': 'wysihtml5.widgets.render_italic_icon'}, 
   'underline': {'active': True, 
                 'command_name': 'underline', 
                 'render_icon': 'wysihtml5.widgets.render_underline_icon'}, 
   'justifyLeft': {'active': True, 
                   'command_name': 'justifyLeft', 
                   'render_icon': 'wysihtml5.widgets.render_justifyLeft_icon'}, 
   'justifyCenter': {'active': True, 
                     'command_name': 'justifyCenter', 
                     'render_icon': 'wysihtml5.widgets.render_justifyCenter_icon'}, 
   'justifyRight': {'active': True, 
                    'command_name': 'justifyRight', 
                    'render_icon': 'wysihtml5.widgets.render_justifyRight_icon'}, 
   'insertOrderedList': {'active': True, 
                         'command_name': 'insertOrderedList', 
                         'render_icon': 'wysihtml5.widgets.render_insertOrderedList_icon'}, 
   'insertUnorderedList': {'active': True, 
                           'command_name': 'insertUnorderedList', 
                           'render_icon': 'wysihtml5.widgets.render_insertUnorderedList_icon'}, 
   'insertImage': {'active': True, 
                   'command_name': 'insertImage', 
                   'render_icon': 'wysihtml5.widgets.render_insertImage_icon', 
                   'render_dialog': 'wysihtml5.widgets.render_insertImage_dialog'}, 
   'createLink': {'active': True, 
                  'command_name': 'createLink', 
                  'render_icon': 'wysihtml5.widgets.render_createLink_icon', 
                  'render_dialog': 'wysihtml5.widgets.render_createLink_dialog'}, 
   'insertHTML': {'active': True, 
                  'command_name': 'insertHTML', 
                  'command_value': '<blockquote>quote</blockquote>', 
                  'render_icon': 'wysihtml5.widgets.render_insertHTML_icon'}, 
   'foreColor': {'active': True, 
                 'command_name': 'foreColor', 
                 'render_icon': 'wysihtml5.widgets.render_foreColor_icon'}, 
   'changeView': {'active': True, 
                  'command_name': 'change_view', 
                  'render_icon': 'wysihtml5.widgets.render_changeView_icon'}}
WYSIHTML5_ALLOWED_TAGS = 'h1 h2 h3 h4 h5 h6 div p b i u ul ol li span img a blockquote'