# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /usr/local/lib/python2.7/site-packages/gohttp/_gohttplib.py
# Compiled at: 2016-05-21 17:28:00
import _cffi_backend
ffi = _cffi_backend.FFI('gohttp._gohttplib', _version=9729, _types='\x00\x00\x03\r\x00\x00\x08\x01\x00\x00\x1b\x03\x00\x00\x07\x01\x00\x00\x00\x0f\x00\x00\x1c\r\x00\x00\x02\x11\x00\x00\x00\x0f\x00\x00\x1c\r\x00\x00\x02\x11\x00\x00\x0c\x03\x00\x00\x00\x0f\x00\x00\x1c\r\x00\x00\x08\x01\x00\x00\x19\x03\x00\x00\x00\x0f\x00\x00\x1c\r\x00\x00\x08\x01\x00\x00\x0e\x11\x00\x00\n\x11\x00\x00\x00\x0f\x00\x00\x1c\r\x00\x00\x08\x01\x00\x00\x07\x01\x00\x00\x00\x0f\x00\x00\x00\t\x00\x00\x1b\x03\x00\x00\x02\x01\x00\x00\x00\x01', _globals=('\x00\x00\x10#Call_HandleFunc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '\x00\x00\x08#HandleFunc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '\x00\x00\x05#ListenAndServe',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '\x00\x00\x00#ResponseWriter_Write',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 '\x00\x00\x15#ResponseWriter_WriteHeader',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0), _struct_unions=(('\x00\x00\x00\x19\x00\x00\x00\x02Request_', '\x00\x00\x1a\x11Method', '\x00\x00\x1a\x11Host', '\x00\x00\x1a\x11URL'), ), _typenames=('\x00\x00\x00\x0cFuncPtr',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '\x00\x00\x00\x19Request',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           '\x00\x00\x00\x01ResponseWriterPtr'))