# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/travis/build/honeynet/beeswarm/beeswarm/shared/message_enum.py
# Compiled at: 2016-11-12 07:38:04
from enum import Enum

class Messages(Enum):
    STOP = 'STOP'
    START = 'START'
    CONFIG = 'CONFIG'
    CONFIG_FULL = 'CONFIG_FULL'
    CONFIG_ARCHITECTURE = 'CONFIG_ARCHITECTURE'
    BROADCAST = 'BROADCAST'
    OK = 'OK'
    FAIL = 'FAIL'
    KEY = 'KEY'
    CERT = 'CERT'
    SESSION_HONEYPOT = 'SESSION_HONEYPOT'
    SESSION_PART_HONEYPOT_SESSION_START = 'SESSION_PART_HONEYPOT_SESSION_START'
    SESSION_PART_HONEYPOT_AUTH = 'SESSION_PART_HONEYPOT_AUTH'
    SESSION_CLIENT = 'SESSION_CLIENT'
    SET_CONFIG_ITEM = 'SET'
    GET_CONFIG_ITEM = 'GET'
    GET_ZMQ_KEYS = 'GET_ZMQ_KEYS'
    DELETE_ZMQ_KEYS = 'DELETE_ZMQ_KEYS'
    PING = 'PING'
    PONG = 'PING'
    IP = 'IP'
    DRONE_WANT_CONFIG = 'DRONE_WANT_CONFIG'
    DRONE_CONFIG = 'DRONE_CONFIG'
    BAIT_USER_ADD = 'BAIT_USER_ADD'
    BAIT_USER_DELETE = 'BAIT_USER_DELETE'
    GET_BAIT_USERS = 'GET_BAIT_USERS'
    DRONE_DELETE = 'DRONE_DELETE'
    DRONE_ADD = 'DRONE_ADD'
    DELETED_DUE_TO_MERGE = 'DELETED_DUE_TO_MERGE'
    SESSION = 'SESSION'
    GET_DB_STATS = 'GET_DB_STATS'
    GET_SESSIONS_ALL = 'GET_SESSIONS_ALL'
    GET_SESSIONS_BAIT = 'GET_SESSIONS_BAIT'
    GET_SESSIONS_ATTACKS = 'GET_SESSIONS_ATTACKS'
    GET_SESSION_TRANSCRIPT = 'GET_SESSION_TRANSCRIPT'
    GET_SESSION_CREDENTIALS = 'GET_SESSION_CREDENTIALS'
    GET_DRONE_LIST = 'GET_DRONE_LIST'
    CONFIG_DRONE = 'CONFIG_DRONE'
    PING_ALL_DRONES = 'PING_ALL_DRONES'