# uncompyle6 version 3.6.7
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: build\bdist.win-amd64\egg\mysqlmapper\mysql\info\xml_info.py
# Compiled at: 2020-04-03 04:05:31
# Size of source mod 2**32: 2907 bytes
table_xml = '\n<xml>\n    <mapper column="TABLE_NAME" parameter="Name"/>\n    <mapper column="ENGINE" parameter="Engine"/>\n    <mapper column="TABLE_COLLATION" parameter="Collation"/>\n    <mapper column="TABLE_COMMENT" parameter="Comment"/>\n    <mapper column="IFNULL(AUTO_INCREMENT, -1)" parameter="AutoIncrement"/>\n    <sql>\n        <key>GetList</key>\n        <value>\n            SELECT\n                TABLE_NAME, ENGINE, TABLE_COLLATION, TABLE_COMMENT, IFNULL(AUTO_INCREMENT, -1)\n            FROM\n                information_schema.TABLES\n            WHERE\n                TABLE_SCHEMA = #{ data_base_name } AND TABLE_TYPE = \'BASE TABLE\'\n        </value>\n    </sql>\n</xml>\n'
column_xml = '\n<xml>\n    <mapper column="ORDINAL_POSITION" parameter="Number"/>\n    <mapper column="COLUMN_NAME" parameter="Name"/>\n    <mapper column="COLUMN_TYPE" parameter="Type"/>\n    <mapper column="IS_NULLABLE" parameter="NullAble"/>\n    <mapper column="COLUMN_DEFAULT" parameter="Defaule"/>\n    <mapper column="COLUMN_COMMENT" parameter="Comment"/>\n    <sql>\n        <key>GetList</key>\n        <value>\n            SELECT\n                ORDINAL_POSITION,\n                COLUMN_NAME,\n                COLUMN_TYPE,\n                IS_NULLABLE,\n                IFNULL(COLUMN_DEFAULT, \'\'),\n                COLUMN_COMMENT\n            FROM\n                information_schema.COLUMNS\n            WHERE\n                TABLE_SCHEMA = #{ data_base_name } AND TABLE_NAME = #{ table_name }\n        </value>\n    </sql>\n</xml>\n'
index_xml = '\n<xml>\n    <mapper column="INDEX_NAME" parameter="Name"/>\n    <mapper column="COLUMN_NAME" parameter="ColumnName"/>\n    <mapper column="NON_UNIQUE" parameter="Unique"/>\n    <mapper column="INDEX_TYPE" parameter="Type"/>\n    <sql>\n        <key>GetList</key>\n        <value>\n            SELECT\n                INDEX_NAME,\n                COLUMN_NAME,\n                NON_UNIQUE,\n                INDEX_TYPE\n            FROM\n                information_schema.STATISTICS\n            WHERE\n                TABLE_SCHEMA = #{ data_base_name } AND TABLE_NAME = #{ table_name }\n        </value>\n    </sql>\n</xml>\n'
key_xml = '\n<xml>\n    <mapper column="COLUMN_NAME" parameter="ColumnName"/>\n    <mapper column="REFERENCED_TABLE_NAME" parameter="RelyTable"/>\n    <mapper column="REFERENCED_COLUMN_NAME" parameter="RelyColumnName"/>\n    <sql>\n        <key>GetList</key>\n        <value>\n            SELECT\n                COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME\n            FROM\n                information_schema.KEY_COLUMN_USAGE\n            WHERE\n                CONSTRAINT_NAME != \'PRIMARY\' AND\n                TABLE_SCHEMA = REFERENCED_TABLE_SCHEMA AND\n                TABLE_SCHEMA = #{ data_base_name } AND TABLE_NAME = #{ table_name }\n        </value>\n    </sql>\n</xml>\n'