# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: ./guild/external/pip/_vendor/html5lib/constants.py
# Compiled at: 2019-09-10 15:18:29
from __future__ import absolute_import, division, unicode_literals
import string
EOF = None
E = {b'null-character': b'Null character in input stream, replaced with U+FFFD.', 
   b'invalid-codepoint': b'Invalid codepoint in stream.', 
   b'incorrectly-placed-solidus': b'Solidus (/) incorrectly placed in tag.', 
   b'incorrect-cr-newline-entity': b'Incorrect CR newline entity, replaced with LF.', 
   b'illegal-windows-1252-entity': b'Entity used with illegal number (windows-1252 reference).', 
   b'cant-convert-numeric-entity': b"Numeric entity couldn't be converted to character (codepoint U+%(charAsInt)08x).", 
   b'illegal-codepoint-for-numeric-entity': b'Numeric entity represents an illegal codepoint: U+%(charAsInt)08x.', 
   b'numeric-entity-without-semicolon': b"Numeric entity didn't end with ';'.", 
   b'expected-numeric-entity-but-got-eof': b'Numeric entity expected. Got end of file instead.', 
   b'expected-numeric-entity': b'Numeric entity expected but none found.', 
   b'named-entity-without-semicolon': b"Named entity didn't end with ';'.", 
   b'expected-named-entity': b'Named entity expected. Got none.', 
   b'attributes-in-end-tag': b'End tag contains unexpected attributes.', 
   b'self-closing-flag-on-end-tag': b'End tag contains unexpected self-closing flag.', 
   b'expected-tag-name-but-got-right-bracket': b"Expected tag name. Got '>' instead.", 
   b'expected-tag-name-but-got-question-mark': b"Expected tag name. Got '?' instead. (HTML doesn't support processing instructions.)", 
   b'expected-tag-name': b'Expected tag name. Got something else instead', 
   b'expected-closing-tag-but-got-right-bracket': b"Expected closing tag. Got '>' instead. Ignoring '</>'.", 
   b'expected-closing-tag-but-got-eof': b'Expected closing tag. Unexpected end of file.', 
   b'expected-closing-tag-but-got-char': b"Expected closing tag. Unexpected character '%(data)s' found.", 
   b'eof-in-tag-name': b'Unexpected end of file in the tag name.', 
   b'expected-attribute-name-but-got-eof': b'Unexpected end of file. Expected attribute name instead.', 
   b'eof-in-attribute-name': b'Unexpected end of file in attribute name.', 
   b'invalid-character-in-attribute-name': b'Invalid character in attribute name', 
   b'duplicate-attribute': b'Dropped duplicate attribute on tag.', 
   b'expected-end-of-tag-name-but-got-eof': b'Unexpected end of file. Expected = or end of tag.', 
   b'expected-attribute-value-but-got-eof': b'Unexpected end of file. Expected attribute value.', 
   b'expected-attribute-value-but-got-right-bracket': b"Expected attribute value. Got '>' instead.", 
   b'equals-in-unquoted-attribute-value': b'Unexpected = in unquoted attribute', 
   b'unexpected-character-in-unquoted-attribute-value': b'Unexpected character in unquoted attribute', 
   b'invalid-character-after-attribute-name': b'Unexpected character after attribute name.', 
   b'unexpected-character-after-attribute-value': b'Unexpected character after attribute value.', 
   b'eof-in-attribute-value-double-quote': b'Unexpected end of file in attribute value (").', 
   b'eof-in-attribute-value-single-quote': b"Unexpected end of file in attribute value (').", 
   b'eof-in-attribute-value-no-quotes': b'Unexpected end of file in attribute value.', 
   b'unexpected-EOF-after-solidus-in-tag': b'Unexpected end of file in tag. Expected >', 
   b'unexpected-character-after-solidus-in-tag': b'Unexpected character after / in tag. Expected >', 
   b'expected-dashes-or-doctype': b"Expected '--' or 'DOCTYPE'. Not found.", 
   b'unexpected-bang-after-double-dash-in-comment': b'Unexpected ! after -- in comment', 
   b'unexpected-space-after-double-dash-in-comment': b'Unexpected space after -- in comment', 
   b'incorrect-comment': b'Incorrect comment.', 
   b'eof-in-comment': b'Unexpected end of file in comment.', 
   b'eof-in-comment-end-dash': b'Unexpected end of file in comment (-)', 
   b'unexpected-dash-after-double-dash-in-comment': b"Unexpected '-' after '--' found in comment.", 
   b'eof-in-comment-double-dash': b'Unexpected end of file in comment (--).', 
   b'eof-in-comment-end-space-state': b'Unexpected end of file in comment.', 
   b'eof-in-comment-end-bang-state': b'Unexpected end of file in comment.', 
   b'unexpected-char-in-comment': b'Unexpected character in comment found.', 
   b'need-space-after-doctype': b"No space after literal string 'DOCTYPE'.", 
   b'expected-doctype-name-but-got-right-bracket': b'Unexpected > character. Expected DOCTYPE name.', 
   b'expected-doctype-name-but-got-eof': b'Unexpected end of file. Expected DOCTYPE name.', 
   b'eof-in-doctype-name': b'Unexpected end of file in DOCTYPE name.', 
   b'eof-in-doctype': b'Unexpected end of file in DOCTYPE.', 
   b'expected-space-or-right-bracket-in-doctype': b"Expected space or '>'. Got '%(data)s'", 
   b'unexpected-end-of-doctype': b'Unexpected end of DOCTYPE.', 
   b'unexpected-char-in-doctype': b'Unexpected character in DOCTYPE.', 
   b'eof-in-innerhtml': b'XXX innerHTML EOF', 
   b'unexpected-doctype': b'Unexpected DOCTYPE. Ignored.', 
   b'non-html-root': b'html needs to be the first start tag.', 
   b'expected-doctype-but-got-eof': b'Unexpected End of file. Expected DOCTYPE.', 
   b'unknown-doctype': b'Erroneous DOCTYPE.', 
   b'expected-doctype-but-got-chars': b'Unexpected non-space characters. Expected DOCTYPE.', 
   b'expected-doctype-but-got-start-tag': b'Unexpected start tag (%(name)s). Expected DOCTYPE.', 
   b'expected-doctype-but-got-end-tag': b'Unexpected end tag (%(name)s). Expected DOCTYPE.', 
   b'end-tag-after-implied-root': b'Unexpected end tag (%(name)s) after the (implied) root element.', 
   b'expected-named-closing-tag-but-got-eof': b'Unexpected end of file. Expected end tag (%(name)s).', 
   b'two-heads-are-not-better-than-one': b'Unexpected start tag head in existing head. Ignored.', 
   b'unexpected-end-tag': b'Unexpected end tag (%(name)s). Ignored.', 
   b'unexpected-start-tag-out-of-my-head': b'Unexpected start tag (%(name)s) that can be in head. Moved.', 
   b'unexpected-start-tag': b'Unexpected start tag (%(name)s).', 
   b'missing-end-tag': b'Missing end tag (%(name)s).', 
   b'missing-end-tags': b'Missing end tags (%(name)s).', 
   b'unexpected-start-tag-implies-end-tag': b'Unexpected start tag (%(startName)s) implies end tag (%(endName)s).', 
   b'unexpected-start-tag-treated-as': b'Unexpected start tag (%(originalName)s). Treated as %(newName)s.', 
   b'deprecated-tag': b"Unexpected start tag %(name)s. Don't use it!", 
   b'unexpected-start-tag-ignored': b'Unexpected start tag %(name)s. Ignored.', 
   b'expected-one-end-tag-but-got-another': b'Unexpected end tag (%(gotName)s). Missing end tag (%(expectedName)s).', 
   b'end-tag-too-early': b'End tag (%(name)s) seen too early. Expected other end tag.', 
   b'end-tag-too-early-named': b'Unexpected end tag (%(gotName)s). Expected end tag (%(expectedName)s).', 
   b'end-tag-too-early-ignored': b'End tag (%(name)s) seen too early. Ignored.', 
   b'adoption-agency-1.1': b'End tag (%(name)s) violates step 1, paragraph 1 of the adoption agency algorithm.', 
   b'adoption-agency-1.2': b'End tag (%(name)s) violates step 1, paragraph 2 of the adoption agency algorithm.', 
   b'adoption-agency-1.3': b'End tag (%(name)s) violates step 1, paragraph 3 of the adoption agency algorithm.', 
   b'adoption-agency-4.4': b'End tag (%(name)s) violates step 4, paragraph 4 of the adoption agency algorithm.', 
   b'unexpected-end-tag-treated-as': b'Unexpected end tag (%(originalName)s). Treated as %(newName)s.', 
   b'no-end-tag': b'This element (%(name)s) has no end tag.', 
   b'unexpected-implied-end-tag-in-table': b'Unexpected implied end tag (%(name)s) in the table phase.', 
   b'unexpected-implied-end-tag-in-table-body': b'Unexpected implied end tag (%(name)s) in the table body phase.', 
   b'unexpected-char-implies-table-voodoo': b'Unexpected non-space characters in table context caused voodoo mode.', 
   b'unexpected-hidden-input-in-table': b'Unexpected input with type hidden in table context.', 
   b'unexpected-form-in-table': b'Unexpected form in table context.', 
   b'unexpected-start-tag-implies-table-voodoo': b'Unexpected start tag (%(name)s) in table context caused voodoo mode.', 
   b'unexpected-end-tag-implies-table-voodoo': b'Unexpected end tag (%(name)s) in table context caused voodoo mode.', 
   b'unexpected-cell-in-table-body': b'Unexpected table cell start tag (%(name)s) in the table body phase.', 
   b'unexpected-cell-end-tag': b'Got table cell end tag (%(name)s) while required end tags are missing.', 
   b'unexpected-end-tag-in-table-body': b'Unexpected end tag (%(name)s) in the table body phase. Ignored.', 
   b'unexpected-implied-end-tag-in-table-row': b'Unexpected implied end tag (%(name)s) in the table row phase.', 
   b'unexpected-end-tag-in-table-row': b'Unexpected end tag (%(name)s) in the table row phase. Ignored.', 
   b'unexpected-select-in-select': b'Unexpected select start tag in the select phase treated as select end tag.', 
   b'unexpected-input-in-select': b'Unexpected input start tag in the select phase.', 
   b'unexpected-start-tag-in-select': b'Unexpected start tag token (%(name)s in the select phase. Ignored.', 
   b'unexpected-end-tag-in-select': b'Unexpected end tag (%(name)s) in the select phase. Ignored.', 
   b'unexpected-table-element-start-tag-in-select-in-table': b'Unexpected table element start tag (%(name)s) in the select in table phase.', 
   b'unexpected-table-element-end-tag-in-select-in-table': b'Unexpected table element end tag (%(name)s) in the select in table phase.', 
   b'unexpected-char-after-body': b'Unexpected non-space characters in the after body phase.', 
   b'unexpected-start-tag-after-body': b'Unexpected start tag token (%(name)s) in the after body phase.', 
   b'unexpected-end-tag-after-body': b'Unexpected end tag token (%(name)s) in the after body phase.', 
   b'unexpected-char-in-frameset': b'Unexpected characters in the frameset phase. Characters ignored.', 
   b'unexpected-start-tag-in-frameset': b'Unexpected start tag token (%(name)s) in the frameset phase. Ignored.', 
   b'unexpected-frameset-in-frameset-innerhtml': b'Unexpected end tag token (frameset) in the frameset phase (innerHTML).', 
   b'unexpected-end-tag-in-frameset': b'Unexpected end tag token (%(name)s) in the frameset phase. Ignored.', 
   b'unexpected-char-after-frameset': b'Unexpected non-space characters in the after frameset phase. Ignored.', 
   b'unexpected-start-tag-after-frameset': b'Unexpected start tag (%(name)s) in the after frameset phase. Ignored.', 
   b'unexpected-end-tag-after-frameset': b'Unexpected end tag (%(name)s) in the after frameset phase. Ignored.', 
   b'unexpected-end-tag-after-body-innerhtml': b'Unexpected end tag after body(innerHtml)', 
   b'expected-eof-but-got-char': b'Unexpected non-space characters. Expected end of file.', 
   b'expected-eof-but-got-start-tag': b'Unexpected start tag (%(name)s). Expected end of file.', 
   b'expected-eof-but-got-end-tag': b'Unexpected end tag (%(name)s). Expected end of file.', 
   b'eof-in-table': b'Unexpected end of file. Expected table content.', 
   b'eof-in-select': b'Unexpected end of file. Expected select content.', 
   b'eof-in-frameset': b'Unexpected end of file. Expected frameset content.', 
   b'eof-in-script-in-script': b'Unexpected end of file. Expected script content.', 
   b'eof-in-foreign-lands': b'Unexpected end of file. Expected foreign content', 
   b'non-void-element-with-trailing-solidus': b'Trailing solidus not allowed on element %(name)s', 
   b'unexpected-html-element-in-foreign-content': b'Element %(name)s not allowed in a non-html context', 
   b'unexpected-end-tag-before-html': b'Unexpected end tag (%(name)s) before html.', 
   b'unexpected-inhead-noscript-tag': b'Element %(name)s not allowed in a inhead-noscript context', 
   b'eof-in-head-noscript': b'Unexpected end of file. Expected inhead-noscript content', 
   b'char-in-head-noscript': b'Unexpected non-space character. Expected inhead-noscript content', 
   b'XXX-undefined-error': b'Undefined error (this sucks and should be fixed)'}
namespaces = {b'html': b'http://www.w3.org/1999/xhtml', 
   b'mathml': b'http://www.w3.org/1998/Math/MathML', 
   b'svg': b'http://www.w3.org/2000/svg', 
   b'xlink': b'http://www.w3.org/1999/xlink', 
   b'xml': b'http://www.w3.org/XML/1998/namespace', 
   b'xmlns': b'http://www.w3.org/2000/xmlns/'}
scopingElements = frozenset([
 (
  namespaces[b'html'], b'applet'),
 (
  namespaces[b'html'], b'caption'),
 (
  namespaces[b'html'], b'html'),
 (
  namespaces[b'html'], b'marquee'),
 (
  namespaces[b'html'], b'object'),
 (
  namespaces[b'html'], b'table'),
 (
  namespaces[b'html'], b'td'),
 (
  namespaces[b'html'], b'th'),
 (
  namespaces[b'mathml'], b'mi'),
 (
  namespaces[b'mathml'], b'mo'),
 (
  namespaces[b'mathml'], b'mn'),
 (
  namespaces[b'mathml'], b'ms'),
 (
  namespaces[b'mathml'], b'mtext'),
 (
  namespaces[b'mathml'], b'annotation-xml'),
 (
  namespaces[b'svg'], b'foreignObject'),
 (
  namespaces[b'svg'], b'desc'),
 (
  namespaces[b'svg'], b'title')])
formattingElements = frozenset([
 (
  namespaces[b'html'], b'a'),
 (
  namespaces[b'html'], b'b'),
 (
  namespaces[b'html'], b'big'),
 (
  namespaces[b'html'], b'code'),
 (
  namespaces[b'html'], b'em'),
 (
  namespaces[b'html'], b'font'),
 (
  namespaces[b'html'], b'i'),
 (
  namespaces[b'html'], b'nobr'),
 (
  namespaces[b'html'], b's'),
 (
  namespaces[b'html'], b'small'),
 (
  namespaces[b'html'], b'strike'),
 (
  namespaces[b'html'], b'strong'),
 (
  namespaces[b'html'], b'tt'),
 (
  namespaces[b'html'], b'u')])
specialElements = frozenset([
 (
  namespaces[b'html'], b'address'),
 (
  namespaces[b'html'], b'applet'),
 (
  namespaces[b'html'], b'area'),
 (
  namespaces[b'html'], b'article'),
 (
  namespaces[b'html'], b'aside'),
 (
  namespaces[b'html'], b'base'),
 (
  namespaces[b'html'], b'basefont'),
 (
  namespaces[b'html'], b'bgsound'),
 (
  namespaces[b'html'], b'blockquote'),
 (
  namespaces[b'html'], b'body'),
 (
  namespaces[b'html'], b'br'),
 (
  namespaces[b'html'], b'button'),
 (
  namespaces[b'html'], b'caption'),
 (
  namespaces[b'html'], b'center'),
 (
  namespaces[b'html'], b'col'),
 (
  namespaces[b'html'], b'colgroup'),
 (
  namespaces[b'html'], b'command'),
 (
  namespaces[b'html'], b'dd'),
 (
  namespaces[b'html'], b'details'),
 (
  namespaces[b'html'], b'dir'),
 (
  namespaces[b'html'], b'div'),
 (
  namespaces[b'html'], b'dl'),
 (
  namespaces[b'html'], b'dt'),
 (
  namespaces[b'html'], b'embed'),
 (
  namespaces[b'html'], b'fieldset'),
 (
  namespaces[b'html'], b'figure'),
 (
  namespaces[b'html'], b'footer'),
 (
  namespaces[b'html'], b'form'),
 (
  namespaces[b'html'], b'frame'),
 (
  namespaces[b'html'], b'frameset'),
 (
  namespaces[b'html'], b'h1'),
 (
  namespaces[b'html'], b'h2'),
 (
  namespaces[b'html'], b'h3'),
 (
  namespaces[b'html'], b'h4'),
 (
  namespaces[b'html'], b'h5'),
 (
  namespaces[b'html'], b'h6'),
 (
  namespaces[b'html'], b'head'),
 (
  namespaces[b'html'], b'header'),
 (
  namespaces[b'html'], b'hr'),
 (
  namespaces[b'html'], b'html'),
 (
  namespaces[b'html'], b'iframe'),
 (
  namespaces[b'html'], b'image'),
 (
  namespaces[b'html'], b'img'),
 (
  namespaces[b'html'], b'input'),
 (
  namespaces[b'html'], b'isindex'),
 (
  namespaces[b'html'], b'li'),
 (
  namespaces[b'html'], b'link'),
 (
  namespaces[b'html'], b'listing'),
 (
  namespaces[b'html'], b'marquee'),
 (
  namespaces[b'html'], b'menu'),
 (
  namespaces[b'html'], b'meta'),
 (
  namespaces[b'html'], b'nav'),
 (
  namespaces[b'html'], b'noembed'),
 (
  namespaces[b'html'], b'noframes'),
 (
  namespaces[b'html'], b'noscript'),
 (
  namespaces[b'html'], b'object'),
 (
  namespaces[b'html'], b'ol'),
 (
  namespaces[b'html'], b'p'),
 (
  namespaces[b'html'], b'param'),
 (
  namespaces[b'html'], b'plaintext'),
 (
  namespaces[b'html'], b'pre'),
 (
  namespaces[b'html'], b'script'),
 (
  namespaces[b'html'], b'section'),
 (
  namespaces[b'html'], b'select'),
 (
  namespaces[b'html'], b'style'),
 (
  namespaces[b'html'], b'table'),
 (
  namespaces[b'html'], b'tbody'),
 (
  namespaces[b'html'], b'td'),
 (
  namespaces[b'html'], b'textarea'),
 (
  namespaces[b'html'], b'tfoot'),
 (
  namespaces[b'html'], b'th'),
 (
  namespaces[b'html'], b'thead'),
 (
  namespaces[b'html'], b'title'),
 (
  namespaces[b'html'], b'tr'),
 (
  namespaces[b'html'], b'ul'),
 (
  namespaces[b'html'], b'wbr'),
 (
  namespaces[b'html'], b'xmp'),
 (
  namespaces[b'svg'], b'foreignObject')])
htmlIntegrationPointElements = frozenset([
 (
  namespaces[b'mathml'], b'annotation-xml'),
 (
  namespaces[b'svg'], b'foreignObject'),
 (
  namespaces[b'svg'], b'desc'),
 (
  namespaces[b'svg'], b'title')])
mathmlTextIntegrationPointElements = frozenset([
 (
  namespaces[b'mathml'], b'mi'),
 (
  namespaces[b'mathml'], b'mo'),
 (
  namespaces[b'mathml'], b'mn'),
 (
  namespaces[b'mathml'], b'ms'),
 (
  namespaces[b'mathml'], b'mtext')])
adjustSVGAttributes = {b'attributename': b'attributeName', 
   b'attributetype': b'attributeType', 
   b'basefrequency': b'baseFrequency', 
   b'baseprofile': b'baseProfile', 
   b'calcmode': b'calcMode', 
   b'clippathunits': b'clipPathUnits', 
   b'contentscripttype': b'contentScriptType', 
   b'contentstyletype': b'contentStyleType', 
   b'diffuseconstant': b'diffuseConstant', 
   b'edgemode': b'edgeMode', 
   b'externalresourcesrequired': b'externalResourcesRequired', 
   b'filterres': b'filterRes', 
   b'filterunits': b'filterUnits', 
   b'glyphref': b'glyphRef', 
   b'gradienttransform': b'gradientTransform', 
   b'gradientunits': b'gradientUnits', 
   b'kernelmatrix': b'kernelMatrix', 
   b'kernelunitlength': b'kernelUnitLength', 
   b'keypoints': b'keyPoints', 
   b'keysplines': b'keySplines', 
   b'keytimes': b'keyTimes', 
   b'lengthadjust': b'lengthAdjust', 
   b'limitingconeangle': b'limitingConeAngle', 
   b'markerheight': b'markerHeight', 
   b'markerunits': b'markerUnits', 
   b'markerwidth': b'markerWidth', 
   b'maskcontentunits': b'maskContentUnits', 
   b'maskunits': b'maskUnits', 
   b'numoctaves': b'numOctaves', 
   b'pathlength': b'pathLength', 
   b'patterncontentunits': b'patternContentUnits', 
   b'patterntransform': b'patternTransform', 
   b'patternunits': b'patternUnits', 
   b'pointsatx': b'pointsAtX', 
   b'pointsaty': b'pointsAtY', 
   b'pointsatz': b'pointsAtZ', 
   b'preservealpha': b'preserveAlpha', 
   b'preserveaspectratio': b'preserveAspectRatio', 
   b'primitiveunits': b'primitiveUnits', 
   b'refx': b'refX', 
   b'refy': b'refY', 
   b'repeatcount': b'repeatCount', 
   b'repeatdur': b'repeatDur', 
   b'requiredextensions': b'requiredExtensions', 
   b'requiredfeatures': b'requiredFeatures', 
   b'specularconstant': b'specularConstant', 
   b'specularexponent': b'specularExponent', 
   b'spreadmethod': b'spreadMethod', 
   b'startoffset': b'startOffset', 
   b'stddeviation': b'stdDeviation', 
   b'stitchtiles': b'stitchTiles', 
   b'surfacescale': b'surfaceScale', 
   b'systemlanguage': b'systemLanguage', 
   b'tablevalues': b'tableValues', 
   b'targetx': b'targetX', 
   b'targety': b'targetY', 
   b'textlength': b'textLength', 
   b'viewbox': b'viewBox', 
   b'viewtarget': b'viewTarget', 
   b'xchannelselector': b'xChannelSelector', 
   b'ychannelselector': b'yChannelSelector', 
   b'zoomandpan': b'zoomAndPan'}
adjustMathMLAttributes = {b'definitionurl': b'definitionURL'}
adjustForeignAttributes = {b'xlink:actuate': (
                    b'xlink', b'actuate', namespaces[b'xlink']), 
   b'xlink:arcrole': (
                    b'xlink', b'arcrole', namespaces[b'xlink']), 
   b'xlink:href': (
                 b'xlink', b'href', namespaces[b'xlink']), 
   b'xlink:role': (
                 b'xlink', b'role', namespaces[b'xlink']), 
   b'xlink:show': (
                 b'xlink', b'show', namespaces[b'xlink']), 
   b'xlink:title': (
                  b'xlink', b'title', namespaces[b'xlink']), 
   b'xlink:type': (
                 b'xlink', b'type', namespaces[b'xlink']), 
   b'xml:base': (
               b'xml', b'base', namespaces[b'xml']), 
   b'xml:lang': (
               b'xml', b'lang', namespaces[b'xml']), 
   b'xml:space': (
                b'xml', b'space', namespaces[b'xml']), 
   b'xmlns': (
            None, b'xmlns', namespaces[b'xmlns']), 
   b'xmlns:xlink': (
                  b'xmlns', b'xlink', namespaces[b'xmlns'])}
unadjustForeignAttributes = dict([ ((ns, local), qname) for qname, (prefix, local, ns) in adjustForeignAttributes.items()
                                 ])
spaceCharacters = frozenset([
 b'\t',
 b'\n',
 b'\x0c',
 b' ',
 b'\r'])
tableInsertModeElements = frozenset([
 b'table',
 b'tbody',
 b'tfoot',
 b'thead',
 b'tr'])
asciiLowercase = frozenset(string.ascii_lowercase)
asciiUppercase = frozenset(string.ascii_uppercase)
asciiLetters = frozenset(string.ascii_letters)
digits = frozenset(string.digits)
hexDigits = frozenset(string.hexdigits)
asciiUpper2Lower = dict([ (ord(c), ord(c.lower())) for c in string.ascii_uppercase
                        ])
headingElements = ('h1', 'h2', 'h3', 'h4', 'h5', 'h6')
voidElements = frozenset([
 b'base',
 b'command',
 b'event-source',
 b'link',
 b'meta',
 b'hr',
 b'br',
 b'img',
 b'embed',
 b'param',
 b'area',
 b'col',
 b'input',
 b'source',
 b'track'])
cdataElements = frozenset([b'title', b'textarea'])
rcdataElements = frozenset([
 b'style',
 b'script',
 b'xmp',
 b'iframe',
 b'noembed',
 b'noframes',
 b'noscript'])
booleanAttributes = {b'': frozenset([b'irrelevant', b'itemscope']), 
   b'style': frozenset([b'scoped']), 
   b'img': frozenset([b'ismap']), 
   b'audio': frozenset([b'autoplay', b'controls']), 
   b'video': frozenset([b'autoplay', b'controls']), 
   b'script': frozenset([b'defer', b'async']), 
   b'details': frozenset([b'open']), 
   b'datagrid': frozenset([b'multiple', b'disabled']), 
   b'command': frozenset([b'hidden', b'disabled', b'checked', b'default']), 
   b'hr': frozenset([b'noshade']), 
   b'menu': frozenset([b'autosubmit']), 
   b'fieldset': frozenset([b'disabled', b'readonly']), 
   b'option': frozenset([b'disabled', b'readonly', b'selected']), 
   b'optgroup': frozenset([b'disabled', b'readonly']), 
   b'button': frozenset([b'disabled', b'autofocus']), 
   b'input': frozenset([b'disabled', b'readonly', b'required', b'autofocus', b'checked', b'ismap']), 
   b'select': frozenset([b'disabled', b'readonly', b'autofocus', b'multiple']), 
   b'output': frozenset([b'disabled', b'readonly']), 
   b'iframe': frozenset([b'seamless'])}
entitiesWindows1252 = (8364, 65533, 8218, 402, 8222, 8230, 8224, 8225, 710, 8240, 352,
                       8249, 338, 65533, 381, 65533, 65533, 8216, 8217, 8220, 8221,
                       8226, 8211, 8212, 732, 8482, 353, 8250, 339, 65533, 382, 376)
xmlEntities = frozenset([b'lt;', b'gt;', b'amp;', b'apos;', b'quot;'])
entities = {b'AElig': b'Æ', 
   b'AElig;': b'Æ', 
   b'AMP': b'&', 
   b'AMP;': b'&', 
   b'Aacute': b'Á', 
   b'Aacute;': b'Á', 
   b'Abreve;': b'Ă', 
   b'Acirc': b'Â', 
   b'Acirc;': b'Â', 
   b'Acy;': b'А', 
   b'Afr;': b'𝔄', 
   b'Agrave': b'À', 
   b'Agrave;': b'À', 
   b'Alpha;': b'Α', 
   b'Amacr;': b'Ā', 
   b'And;': b'⩓', 
   b'Aogon;': b'Ą', 
   b'Aopf;': b'𝔸', 
   b'ApplyFunction;': b'\u2061', 
   b'Aring': b'Å', 
   b'Aring;': b'Å', 
   b'Ascr;': b'𝒜', 
   b'Assign;': b'≔', 
   b'Atilde': b'Ã', 
   b'Atilde;': b'Ã', 
   b'Auml': b'Ä', 
   b'Auml;': b'Ä', 
   b'Backslash;': b'∖', 
   b'Barv;': b'⫧', 
   b'Barwed;': b'⌆', 
   b'Bcy;': b'Б', 
   b'Because;': b'∵', 
   b'Bernoullis;': b'ℬ', 
   b'Beta;': b'Β', 
   b'Bfr;': b'𝔅', 
   b'Bopf;': b'𝔹', 
   b'Breve;': b'˘', 
   b'Bscr;': b'ℬ', 
   b'Bumpeq;': b'≎', 
   b'CHcy;': b'Ч', 
   b'COPY': b'©', 
   b'COPY;': b'©', 
   b'Cacute;': b'Ć', 
   b'Cap;': b'⋒', 
   b'CapitalDifferentialD;': b'ⅅ', 
   b'Cayleys;': b'ℭ', 
   b'Ccaron;': b'Č', 
   b'Ccedil': b'Ç', 
   b'Ccedil;': b'Ç', 
   b'Ccirc;': b'Ĉ', 
   b'Cconint;': b'∰', 
   b'Cdot;': b'Ċ', 
   b'Cedilla;': b'¸', 
   b'CenterDot;': b'·', 
   b'Cfr;': b'ℭ', 
   b'Chi;': b'Χ', 
   b'CircleDot;': b'⊙', 
   b'CircleMinus;': b'⊖', 
   b'CirclePlus;': b'⊕', 
   b'CircleTimes;': b'⊗', 
   b'ClockwiseContourIntegral;': b'∲', 
   b'CloseCurlyDoubleQuote;': b'”', 
   b'CloseCurlyQuote;': b'’', 
   b'Colon;': b'∷', 
   b'Colone;': b'⩴', 
   b'Congruent;': b'≡', 
   b'Conint;': b'∯', 
   b'ContourIntegral;': b'∮', 
   b'Copf;': b'ℂ', 
   b'Coproduct;': b'∐', 
   b'CounterClockwiseContourIntegral;': b'∳', 
   b'Cross;': b'⨯', 
   b'Cscr;': b'𝒞', 
   b'Cup;': b'⋓', 
   b'CupCap;': b'≍', 
   b'DD;': b'ⅅ', 
   b'DDotrahd;': b'⤑', 
   b'DJcy;': b'Ђ', 
   b'DScy;': b'Ѕ', 
   b'DZcy;': b'Џ', 
   b'Dagger;': b'‡', 
   b'Darr;': b'↡', 
   b'Dashv;': b'⫤', 
   b'Dcaron;': b'Ď', 
   b'Dcy;': b'Д', 
   b'Del;': b'∇', 
   b'Delta;': b'Δ', 
   b'Dfr;': b'𝔇', 
   b'DiacriticalAcute;': b'´', 
   b'DiacriticalDot;': b'˙', 
   b'DiacriticalDoubleAcute;': b'˝', 
   b'DiacriticalGrave;': b'`', 
   b'DiacriticalTilde;': b'˜', 
   b'Diamond;': b'⋄', 
   b'DifferentialD;': b'ⅆ', 
   b'Dopf;': b'𝔻', 
   b'Dot;': b'¨', 
   b'DotDot;': b'⃜', 
   b'DotEqual;': b'≐', 
   b'DoubleContourIntegral;': b'∯', 
   b'DoubleDot;': b'¨', 
   b'DoubleDownArrow;': b'⇓', 
   b'DoubleLeftArrow;': b'⇐', 
   b'DoubleLeftRightArrow;': b'⇔', 
   b'DoubleLeftTee;': b'⫤', 
   b'DoubleLongLeftArrow;': b'⟸', 
   b'DoubleLongLeftRightArrow;': b'⟺', 
   b'DoubleLongRightArrow;': b'⟹', 
   b'DoubleRightArrow;': b'⇒', 
   b'DoubleRightTee;': b'⊨', 
   b'DoubleUpArrow;': b'⇑', 
   b'DoubleUpDownArrow;': b'⇕', 
   b'DoubleVerticalBar;': b'∥', 
   b'DownArrow;': b'↓', 
   b'DownArrowBar;': b'⤓', 
   b'DownArrowUpArrow;': b'⇵', 
   b'DownBreve;': b'̑', 
   b'DownLeftRightVector;': b'⥐', 
   b'DownLeftTeeVector;': b'⥞', 
   b'DownLeftVector;': b'↽', 
   b'DownLeftVectorBar;': b'⥖', 
   b'DownRightTeeVector;': b'⥟', 
   b'DownRightVector;': b'⇁', 
   b'DownRightVectorBar;': b'⥗', 
   b'DownTee;': b'⊤', 
   b'DownTeeArrow;': b'↧', 
   b'Downarrow;': b'⇓', 
   b'Dscr;': b'𝒟', 
   b'Dstrok;': b'Đ', 
   b'ENG;': b'Ŋ', 
   b'ETH': b'Ð', 
   b'ETH;': b'Ð', 
   b'Eacute': b'É', 
   b'Eacute;': b'É', 
   b'Ecaron;': b'Ě', 
   b'Ecirc': b'Ê', 
   b'Ecirc;': b'Ê', 
   b'Ecy;': b'Э', 
   b'Edot;': b'Ė', 
   b'Efr;': b'𝔈', 
   b'Egrave': b'È', 
   b'Egrave;': b'È', 
   b'Element;': b'∈', 
   b'Emacr;': b'Ē', 
   b'EmptySmallSquare;': b'◻', 
   b'EmptyVerySmallSquare;': b'▫', 
   b'Eogon;': b'Ę', 
   b'Eopf;': b'𝔼', 
   b'Epsilon;': b'Ε', 
   b'Equal;': b'⩵', 
   b'EqualTilde;': b'≂', 
   b'Equilibrium;': b'⇌', 
   b'Escr;': b'ℰ', 
   b'Esim;': b'⩳', 
   b'Eta;': b'Η', 
   b'Euml': b'Ë', 
   b'Euml;': b'Ë', 
   b'Exists;': b'∃', 
   b'ExponentialE;': b'ⅇ', 
   b'Fcy;': b'Ф', 
   b'Ffr;': b'𝔉', 
   b'FilledSmallSquare;': b'◼', 
   b'FilledVerySmallSquare;': b'▪', 
   b'Fopf;': b'𝔽', 
   b'ForAll;': b'∀', 
   b'Fouriertrf;': b'ℱ', 
   b'Fscr;': b'ℱ', 
   b'GJcy;': b'Ѓ', 
   b'GT': b'>', 
   b'GT;': b'>', 
   b'Gamma;': b'Γ', 
   b'Gammad;': b'Ϝ', 
   b'Gbreve;': b'Ğ', 
   b'Gcedil;': b'Ģ', 
   b'Gcirc;': b'Ĝ', 
   b'Gcy;': b'Г', 
   b'Gdot;': b'Ġ', 
   b'Gfr;': b'𝔊', 
   b'Gg;': b'⋙', 
   b'Gopf;': b'𝔾', 
   b'GreaterEqual;': b'≥', 
   b'GreaterEqualLess;': b'⋛', 
   b'GreaterFullEqual;': b'≧', 
   b'GreaterGreater;': b'⪢', 
   b'GreaterLess;': b'≷', 
   b'GreaterSlantEqual;': b'⩾', 
   b'GreaterTilde;': b'≳', 
   b'Gscr;': b'𝒢', 
   b'Gt;': b'≫', 
   b'HARDcy;': b'Ъ', 
   b'Hacek;': b'ˇ', 
   b'Hat;': b'^', 
   b'Hcirc;': b'Ĥ', 
   b'Hfr;': b'ℌ', 
   b'HilbertSpace;': b'ℋ', 
   b'Hopf;': b'ℍ', 
   b'HorizontalLine;': b'─', 
   b'Hscr;': b'ℋ', 
   b'Hstrok;': b'Ħ', 
   b'HumpDownHump;': b'≎', 
   b'HumpEqual;': b'≏', 
   b'IEcy;': b'Е', 
   b'IJlig;': b'Ĳ', 
   b'IOcy;': b'Ё', 
   b'Iacute': b'Í', 
   b'Iacute;': b'Í', 
   b'Icirc': b'Î', 
   b'Icirc;': b'Î', 
   b'Icy;': b'И', 
   b'Idot;': b'İ', 
   b'Ifr;': b'ℑ', 
   b'Igrave': b'Ì', 
   b'Igrave;': b'Ì', 
   b'Im;': b'ℑ', 
   b'Imacr;': b'Ī', 
   b'ImaginaryI;': b'ⅈ', 
   b'Implies;': b'⇒', 
   b'Int;': b'∬', 
   b'Integral;': b'∫', 
   b'Intersection;': b'⋂', 
   b'InvisibleComma;': b'\u2063', 
   b'InvisibleTimes;': b'\u2062', 
   b'Iogon;': b'Į', 
   b'Iopf;': b'𝕀', 
   b'Iota;': b'Ι', 
   b'Iscr;': b'ℐ', 
   b'Itilde;': b'Ĩ', 
   b'Iukcy;': b'І', 
   b'Iuml': b'Ï', 
   b'Iuml;': b'Ï', 
   b'Jcirc;': b'Ĵ', 
   b'Jcy;': b'Й', 
   b'Jfr;': b'𝔍', 
   b'Jopf;': b'𝕁', 
   b'Jscr;': b'𝒥', 
   b'Jsercy;': b'Ј', 
   b'Jukcy;': b'Є', 
   b'KHcy;': b'Х', 
   b'KJcy;': b'Ќ', 
   b'Kappa;': b'Κ', 
   b'Kcedil;': b'Ķ', 
   b'Kcy;': b'К', 
   b'Kfr;': b'𝔎', 
   b'Kopf;': b'𝕂', 
   b'Kscr;': b'𝒦', 
   b'LJcy;': b'Љ', 
   b'LT': b'<', 
   b'LT;': b'<', 
   b'Lacute;': b'Ĺ', 
   b'Lambda;': b'Λ', 
   b'Lang;': b'⟪', 
   b'Laplacetrf;': b'ℒ', 
   b'Larr;': b'↞', 
   b'Lcaron;': b'Ľ', 
   b'Lcedil;': b'Ļ', 
   b'Lcy;': b'Л', 
   b'LeftAngleBracket;': b'⟨', 
   b'LeftArrow;': b'←', 
   b'LeftArrowBar;': b'⇤', 
   b'LeftArrowRightArrow;': b'⇆', 
   b'LeftCeiling;': b'⌈', 
   b'LeftDoubleBracket;': b'⟦', 
   b'LeftDownTeeVector;': b'⥡', 
   b'LeftDownVector;': b'⇃', 
   b'LeftDownVectorBar;': b'⥙', 
   b'LeftFloor;': b'⌊', 
   b'LeftRightArrow;': b'↔', 
   b'LeftRightVector;': b'⥎', 
   b'LeftTee;': b'⊣', 
   b'LeftTeeArrow;': b'↤', 
   b'LeftTeeVector;': b'⥚', 
   b'LeftTriangle;': b'⊲', 
   b'LeftTriangleBar;': b'⧏', 
   b'LeftTriangleEqual;': b'⊴', 
   b'LeftUpDownVector;': b'⥑', 
   b'LeftUpTeeVector;': b'⥠', 
   b'LeftUpVector;': b'↿', 
   b'LeftUpVectorBar;': b'⥘', 
   b'LeftVector;': b'↼', 
   b'LeftVectorBar;': b'⥒', 
   b'Leftarrow;': b'⇐', 
   b'Leftrightarrow;': b'⇔', 
   b'LessEqualGreater;': b'⋚', 
   b'LessFullEqual;': b'≦', 
   b'LessGreater;': b'≶', 
   b'LessLess;': b'⪡', 
   b'LessSlantEqual;': b'⩽', 
   b'LessTilde;': b'≲', 
   b'Lfr;': b'𝔏', 
   b'Ll;': b'⋘', 
   b'Lleftarrow;': b'⇚', 
   b'Lmidot;': b'Ŀ', 
   b'LongLeftArrow;': b'⟵', 
   b'LongLeftRightArrow;': b'⟷', 
   b'LongRightArrow;': b'⟶', 
   b'Longleftarrow;': b'⟸', 
   b'Longleftrightarrow;': b'⟺', 
   b'Longrightarrow;': b'⟹', 
   b'Lopf;': b'𝕃', 
   b'LowerLeftArrow;': b'↙', 
   b'LowerRightArrow;': b'↘', 
   b'Lscr;': b'ℒ', 
   b'Lsh;': b'↰', 
   b'Lstrok;': b'Ł', 
   b'Lt;': b'≪', 
   b'Map;': b'⤅', 
   b'Mcy;': b'М', 
   b'MediumSpace;': b'\u205f', 
   b'Mellintrf;': b'ℳ', 
   b'Mfr;': b'𝔐', 
   b'MinusPlus;': b'∓', 
   b'Mopf;': b'𝕄', 
   b'Mscr;': b'ℳ', 
   b'Mu;': b'Μ', 
   b'NJcy;': b'Њ', 
   b'Nacute;': b'Ń', 
   b'Ncaron;': b'Ň', 
   b'Ncedil;': b'Ņ', 
   b'Ncy;': b'Н', 
   b'NegativeMediumSpace;': b'\u200b', 
   b'NegativeThickSpace;': b'\u200b', 
   b'NegativeThinSpace;': b'\u200b', 
   b'NegativeVeryThinSpace;': b'\u200b', 
   b'NestedGreaterGreater;': b'≫', 
   b'NestedLessLess;': b'≪', 
   b'NewLine;': b'\n', 
   b'Nfr;': b'𝔑', 
   b'NoBreak;': b'\u2060', 
   b'NonBreakingSpace;': b'\xa0', 
   b'Nopf;': b'ℕ', 
   b'Not;': b'⫬', 
   b'NotCongruent;': b'≢', 
   b'NotCupCap;': b'≭', 
   b'NotDoubleVerticalBar;': b'∦', 
   b'NotElement;': b'∉', 
   b'NotEqual;': b'≠', 
   b'NotEqualTilde;': b'≂̸', 
   b'NotExists;': b'∄', 
   b'NotGreater;': b'≯', 
   b'NotGreaterEqual;': b'≱', 
   b'NotGreaterFullEqual;': b'≧̸', 
   b'NotGreaterGreater;': b'≫̸', 
   b'NotGreaterLess;': b'≹', 
   b'NotGreaterSlantEqual;': b'⩾̸', 
   b'NotGreaterTilde;': b'≵', 
   b'NotHumpDownHump;': b'≎̸', 
   b'NotHumpEqual;': b'≏̸', 
   b'NotLeftTriangle;': b'⋪', 
   b'NotLeftTriangleBar;': b'⧏̸', 
   b'NotLeftTriangleEqual;': b'⋬', 
   b'NotLess;': b'≮', 
   b'NotLessEqual;': b'≰', 
   b'NotLessGreater;': b'≸', 
   b'NotLessLess;': b'≪̸', 
   b'NotLessSlantEqual;': b'⩽̸', 
   b'NotLessTilde;': b'≴', 
   b'NotNestedGreaterGreater;': b'⪢̸', 
   b'NotNestedLessLess;': b'⪡̸', 
   b'NotPrecedes;': b'⊀', 
   b'NotPrecedesEqual;': b'⪯̸', 
   b'NotPrecedesSlantEqual;': b'⋠', 
   b'NotReverseElement;': b'∌', 
   b'NotRightTriangle;': b'⋫', 
   b'NotRightTriangleBar;': b'⧐̸', 
   b'NotRightTriangleEqual;': b'⋭', 
   b'NotSquareSubset;': b'⊏̸', 
   b'NotSquareSubsetEqual;': b'⋢', 
   b'NotSquareSuperset;': b'⊐̸', 
   b'NotSquareSupersetEqual;': b'⋣', 
   b'NotSubset;': b'⊂⃒', 
   b'NotSubsetEqual;': b'⊈', 
   b'NotSucceeds;': b'⊁', 
   b'NotSucceedsEqual;': b'⪰̸', 
   b'NotSucceedsSlantEqual;': b'⋡', 
   b'NotSucceedsTilde;': b'≿̸', 
   b'NotSuperset;': b'⊃⃒', 
   b'NotSupersetEqual;': b'⊉', 
   b'NotTilde;': b'≁', 
   b'NotTildeEqual;': b'≄', 
   b'NotTildeFullEqual;': b'≇', 
   b'NotTildeTilde;': b'≉', 
   b'NotVerticalBar;': b'∤', 
   b'Nscr;': b'𝒩', 
   b'Ntilde': b'Ñ', 
   b'Ntilde;': b'Ñ', 
   b'Nu;': b'Ν', 
   b'OElig;': b'Œ', 
   b'Oacute': b'Ó', 
   b'Oacute;': b'Ó', 
   b'Ocirc': b'Ô', 
   b'Ocirc;': b'Ô', 
   b'Ocy;': b'О', 
   b'Odblac;': b'Ő', 
   b'Ofr;': b'𝔒', 
   b'Ograve': b'Ò', 
   b'Ograve;': b'Ò', 
   b'Omacr;': b'Ō', 
   b'Omega;': b'Ω', 
   b'Omicron;': b'Ο', 
   b'Oopf;': b'𝕆', 
   b'OpenCurlyDoubleQuote;': b'“', 
   b'OpenCurlyQuote;': b'’', 
   b'Or;': b'⩔', 
   b'Oscr;': b'𝒪', 
   b'Oslash': b'Ø', 
   b'Oslash;': b'Ø', 
   b'Otilde': b'Õ', 
   b'Otilde;': b'Õ', 
   b'Otimes;': b'⨷', 
   b'Ouml': b'Ö', 
   b'Ouml;': b'Ö', 
   b'OverBar;': b'‾', 
   b'OverBrace;': b'⏞', 
   b'OverBracket;': b'⎴', 
   b'OverParenthesis;': b'⏜', 
   b'PartialD;': b'∂', 
   b'Pcy;': b'П', 
   b'Pfr;': b'𝔓', 
   b'Phi;': b'Φ', 
   b'Pi;': b'Π', 
   b'PlusMinus;': b'±', 
   b'Poincareplane;': b'ℌ', 
   b'Popf;': b'ℙ', 
   b'Pr;': b'⪻', 
   b'Precedes;': b'≺', 
   b'PrecedesEqual;': b'⪯', 
   b'PrecedesSlantEqual;': b'≼', 
   b'PrecedesTilde;': b'≾', 
   b'Prime;': b'″', 
   b'Product;': b'∏', 
   b'Proportion;': b'∷', 
   b'Proportional;': b'∝', 
   b'Pscr;': b'𝒫', 
   b'Psi;': b'Ψ', 
   b'QUOT': b'"', 
   b'QUOT;': b'"', 
   b'Qfr;': b'𝔔', 
   b'Qopf;': b'ℚ', 
   b'Qscr;': b'𝒬', 
   b'RBarr;': b'⤐', 
   b'REG': b'®', 
   b'REG;': b'®', 
   b'Racute;': b'Ŕ', 
   b'Rang;': b'⟫', 
   b'Rarr;': b'↠', 
   b'Rarrtl;': b'⤖', 
   b'Rcaron;': b'Ř', 
   b'Rcedil;': b'Ŗ', 
   b'Rcy;': b'Р', 
   b'Re;': b'ℜ', 
   b'ReverseElement;': b'∋', 
   b'ReverseEquilibrium;': b'⇋', 
   b'ReverseUpEquilibrium;': b'⥯', 
   b'Rfr;': b'ℜ', 
   b'Rho;': b'Ρ', 
   b'RightAngleBracket;': b'⟩', 
   b'RightArrow;': b'→', 
   b'RightArrowBar;': b'⇥', 
   b'RightArrowLeftArrow;': b'⇄', 
   b'RightCeiling;': b'⌉', 
   b'RightDoubleBracket;': b'⟧', 
   b'RightDownTeeVector;': b'⥝', 
   b'RightDownVector;': b'⇂', 
   b'RightDownVectorBar;': b'⥕', 
   b'RightFloor;': b'⌋', 
   b'RightTee;': b'⊢', 
   b'RightTeeArrow;': b'↦', 
   b'RightTeeVector;': b'⥛', 
   b'RightTriangle;': b'⊳', 
   b'RightTriangleBar;': b'⧐', 
   b'RightTriangleEqual;': b'⊵', 
   b'RightUpDownVector;': b'⥏', 
   b'RightUpTeeVector;': b'⥜', 
   b'RightUpVector;': b'↾', 
   b'RightUpVectorBar;': b'⥔', 
   b'RightVector;': b'⇀', 
   b'RightVectorBar;': b'⥓', 
   b'Rightarrow;': b'⇒', 
   b'Ropf;': b'ℝ', 
   b'RoundImplies;': b'⥰', 
   b'Rrightarrow;': b'⇛', 
   b'Rscr;': b'ℛ', 
   b'Rsh;': b'↱', 
   b'RuleDelayed;': b'⧴', 
   b'SHCHcy;': b'Щ', 
   b'SHcy;': b'Ш', 
   b'SOFTcy;': b'Ь', 
   b'Sacute;': b'Ś', 
   b'Sc;': b'⪼', 
   b'Scaron;': b'Š', 
   b'Scedil;': b'Ş', 
   b'Scirc;': b'Ŝ', 
   b'Scy;': b'С', 
   b'Sfr;': b'𝔖', 
   b'ShortDownArrow;': b'↓', 
   b'ShortLeftArrow;': b'←', 
   b'ShortRightArrow;': b'→', 
   b'ShortUpArrow;': b'↑', 
   b'Sigma;': b'Σ', 
   b'SmallCircle;': b'∘', 
   b'Sopf;': b'𝕊', 
   b'Sqrt;': b'√', 
   b'Square;': b'□', 
   b'SquareIntersection;': b'⊓', 
   b'SquareSubset;': b'⊏', 
   b'SquareSubsetEqual;': b'⊑', 
   b'SquareSuperset;': b'⊐', 
   b'SquareSupersetEqual;': b'⊒', 
   b'SquareUnion;': b'⊔', 
   b'Sscr;': b'𝒮', 
   b'Star;': b'⋆', 
   b'Sub;': b'⋐', 
   b'Subset;': b'⋐', 
   b'SubsetEqual;': b'⊆', 
   b'Succeeds;': b'≻', 
   b'SucceedsEqual;': b'⪰', 
   b'SucceedsSlantEqual;': b'≽', 
   b'SucceedsTilde;': b'≿', 
   b'SuchThat;': b'∋', 
   b'Sum;': b'∑', 
   b'Sup;': b'⋑', 
   b'Superset;': b'⊃', 
   b'SupersetEqual;': b'⊇', 
   b'Supset;': b'⋑', 
   b'THORN': b'Þ', 
   b'THORN;': b'Þ', 
   b'TRADE;': b'™', 
   b'TSHcy;': b'Ћ', 
   b'TScy;': b'Ц', 
   b'Tab;': b'\t', 
   b'Tau;': b'Τ', 
   b'Tcaron;': b'Ť', 
   b'Tcedil;': b'Ţ', 
   b'Tcy;': b'Т', 
   b'Tfr;': b'𝔗', 
   b'Therefore;': b'∴', 
   b'Theta;': b'Θ', 
   b'ThickSpace;': b'\u205f\u200a', 
   b'ThinSpace;': b'\u2009', 
   b'Tilde;': b'∼', 
   b'TildeEqual;': b'≃', 
   b'TildeFullEqual;': b'≅', 
   b'TildeTilde;': b'≈', 
   b'Topf;': b'𝕋', 
   b'TripleDot;': b'⃛', 
   b'Tscr;': b'𝒯', 
   b'Tstrok;': b'Ŧ', 
   b'Uacute': b'Ú', 
   b'Uacute;': b'Ú', 
   b'Uarr;': b'↟', 
   b'Uarrocir;': b'⥉', 
   b'Ubrcy;': b'Ў', 
   b'Ubreve;': b'Ŭ', 
   b'Ucirc': b'Û', 
   b'Ucirc;': b'Û', 
   b'Ucy;': b'У', 
   b'Udblac;': b'Ű', 
   b'Ufr;': b'𝔘', 
   b'Ugrave': b'Ù', 
   b'Ugrave;': b'Ù', 
   b'Umacr;': b'Ū', 
   b'UnderBar;': b'_', 
   b'UnderBrace;': b'⏟', 
   b'UnderBracket;': b'⎵', 
   b'UnderParenthesis;': b'⏝', 
   b'Union;': b'⋃', 
   b'UnionPlus;': b'⊎', 
   b'Uogon;': b'Ų', 
   b'Uopf;': b'𝕌', 
   b'UpArrow;': b'↑', 
   b'UpArrowBar;': b'⤒', 
   b'UpArrowDownArrow;': b'⇅', 
   b'UpDownArrow;': b'↕', 
   b'UpEquilibrium;': b'⥮', 
   b'UpTee;': b'⊥', 
   b'UpTeeArrow;': b'↥', 
   b'Uparrow;': b'⇑', 
   b'Updownarrow;': b'⇕', 
   b'UpperLeftArrow;': b'↖', 
   b'UpperRightArrow;': b'↗', 
   b'Upsi;': b'ϒ', 
   b'Upsilon;': b'Υ', 
   b'Uring;': b'Ů', 
   b'Uscr;': b'𝒰', 
   b'Utilde;': b'Ũ', 
   b'Uuml': b'Ü', 
   b'Uuml;': b'Ü', 
   b'VDash;': b'⊫', 
   b'Vbar;': b'⫫', 
   b'Vcy;': b'В', 
   b'Vdash;': b'⊩', 
   b'Vdashl;': b'⫦', 
   b'Vee;': b'⋁', 
   b'Verbar;': b'‖', 
   b'Vert;': b'‖', 
   b'VerticalBar;': b'∣', 
   b'VerticalLine;': b'|', 
   b'VerticalSeparator;': b'❘', 
   b'VerticalTilde;': b'≀', 
   b'VeryThinSpace;': b'\u200a', 
   b'Vfr;': b'𝔙', 
   b'Vopf;': b'𝕍', 
   b'Vscr;': b'𝒱', 
   b'Vvdash;': b'⊪', 
   b'Wcirc;': b'Ŵ', 
   b'Wedge;': b'⋀', 
   b'Wfr;': b'𝔚', 
   b'Wopf;': b'𝕎', 
   b'Wscr;': b'𝒲', 
   b'Xfr;': b'𝔛', 
   b'Xi;': b'Ξ', 
   b'Xopf;': b'𝕏', 
   b'Xscr;': b'𝒳', 
   b'YAcy;': b'Я', 
   b'YIcy;': b'Ї', 
   b'YUcy;': b'Ю', 
   b'Yacute': b'Ý', 
   b'Yacute;': b'Ý', 
   b'Ycirc;': b'Ŷ', 
   b'Ycy;': b'Ы', 
   b'Yfr;': b'𝔜', 
   b'Yopf;': b'𝕐', 
   b'Yscr;': b'𝒴', 
   b'Yuml;': b'Ÿ', 
   b'ZHcy;': b'Ж', 
   b'Zacute;': b'Ź', 
   b'Zcaron;': b'Ž', 
   b'Zcy;': b'З', 
   b'Zdot;': b'Ż', 
   b'ZeroWidthSpace;': b'\u200b', 
   b'Zeta;': b'Ζ', 
   b'Zfr;': b'ℨ', 
   b'Zopf;': b'ℤ', 
   b'Zscr;': b'𝒵', 
   b'aacute': b'á', 
   b'aacute;': b'á', 
   b'abreve;': b'ă', 
   b'ac;': b'∾', 
   b'acE;': b'∾̳', 
   b'acd;': b'∿', 
   b'acirc': b'â', 
   b'acirc;': b'â', 
   b'acute': b'´', 
   b'acute;': b'´', 
   b'acy;': b'а', 
   b'aelig': b'æ', 
   b'aelig;': b'æ', 
   b'af;': b'\u2061', 
   b'afr;': b'𝔞', 
   b'agrave': b'à', 
   b'agrave;': b'à', 
   b'alefsym;': b'ℵ', 
   b'aleph;': b'ℵ', 
   b'alpha;': b'α', 
   b'amacr;': b'ā', 
   b'amalg;': b'⨿', 
   b'amp': b'&', 
   b'amp;': b'&', 
   b'and;': b'∧', 
   b'andand;': b'⩕', 
   b'andd;': b'⩜', 
   b'andslope;': b'⩘', 
   b'andv;': b'⩚', 
   b'ang;': b'∠', 
   b'ange;': b'⦤', 
   b'angle;': b'∠', 
   b'angmsd;': b'∡', 
   b'angmsdaa;': b'⦨', 
   b'angmsdab;': b'⦩', 
   b'angmsdac;': b'⦪', 
   b'angmsdad;': b'⦫', 
   b'angmsdae;': b'⦬', 
   b'angmsdaf;': b'⦭', 
   b'angmsdag;': b'⦮', 
   b'angmsdah;': b'⦯', 
   b'angrt;': b'∟', 
   b'angrtvb;': b'⊾', 
   b'angrtvbd;': b'⦝', 
   b'angsph;': b'∢', 
   b'angst;': b'Å', 
   b'angzarr;': b'⍼', 
   b'aogon;': b'ą', 
   b'aopf;': b'𝕒', 
   b'ap;': b'≈', 
   b'apE;': b'⩰', 
   b'apacir;': b'⩯', 
   b'ape;': b'≊', 
   b'apid;': b'≋', 
   b'apos;': b"'", 
   b'approx;': b'≈', 
   b'approxeq;': b'≊', 
   b'aring': b'å', 
   b'aring;': b'å', 
   b'ascr;': b'𝒶', 
   b'ast;': b'*', 
   b'asymp;': b'≈', 
   b'asympeq;': b'≍', 
   b'atilde': b'ã', 
   b'atilde;': b'ã', 
   b'auml': b'ä', 
   b'auml;': b'ä', 
   b'awconint;': b'∳', 
   b'awint;': b'⨑', 
   b'bNot;': b'⫭', 
   b'backcong;': b'≌', 
   b'backepsilon;': b'϶', 
   b'backprime;': b'‵', 
   b'backsim;': b'∽', 
   b'backsimeq;': b'⋍', 
   b'barvee;': b'⊽', 
   b'barwed;': b'⌅', 
   b'barwedge;': b'⌅', 
   b'bbrk;': b'⎵', 
   b'bbrktbrk;': b'⎶', 
   b'bcong;': b'≌', 
   b'bcy;': b'б', 
   b'bdquo;': b'„', 
   b'becaus;': b'∵', 
   b'because;': b'∵', 
   b'bemptyv;': b'⦰', 
   b'bepsi;': b'϶', 
   b'bernou;': b'ℬ', 
   b'beta;': b'β', 
   b'beth;': b'ℶ', 
   b'between;': b'≬', 
   b'bfr;': b'𝔟', 
   b'bigcap;': b'⋂', 
   b'bigcirc;': b'◯', 
   b'bigcup;': b'⋃', 
   b'bigodot;': b'⨀', 
   b'bigoplus;': b'⨁', 
   b'bigotimes;': b'⨂', 
   b'bigsqcup;': b'⨆', 
   b'bigstar;': b'★', 
   b'bigtriangledown;': b'▽', 
   b'bigtriangleup;': b'△', 
   b'biguplus;': b'⨄', 
   b'bigvee;': b'⋁', 
   b'bigwedge;': b'⋀', 
   b'bkarow;': b'⤍', 
   b'blacklozenge;': b'⧫', 
   b'blacksquare;': b'▪', 
   b'blacktriangle;': b'▴', 
   b'blacktriangledown;': b'▾', 
   b'blacktriangleleft;': b'◂', 
   b'blacktriangleright;': b'▸', 
   b'blank;': b'␣', 
   b'blk12;': b'▒', 
   b'blk14;': b'░', 
   b'blk34;': b'▓', 
   b'block;': b'█', 
   b'bne;': b'=⃥', 
   b'bnequiv;': b'≡⃥', 
   b'bnot;': b'⌐', 
   b'bopf;': b'𝕓', 
   b'bot;': b'⊥', 
   b'bottom;': b'⊥', 
   b'bowtie;': b'⋈', 
   b'boxDL;': b'╗', 
   b'boxDR;': b'╔', 
   b'boxDl;': b'╖', 
   b'boxDr;': b'╓', 
   b'boxH;': b'═', 
   b'boxHD;': b'╦', 
   b'boxHU;': b'╩', 
   b'boxHd;': b'╤', 
   b'boxHu;': b'╧', 
   b'boxUL;': b'╝', 
   b'boxUR;': b'╚', 
   b'boxUl;': b'╜', 
   b'boxUr;': b'╙', 
   b'boxV;': b'║', 
   b'boxVH;': b'╬', 
   b'boxVL;': b'╣', 
   b'boxVR;': b'╠', 
   b'boxVh;': b'╫', 
   b'boxVl;': b'╢', 
   b'boxVr;': b'╟', 
   b'boxbox;': b'⧉', 
   b'boxdL;': b'╕', 
   b'boxdR;': b'╒', 
   b'boxdl;': b'┐', 
   b'boxdr;': b'┌', 
   b'boxh;': b'─', 
   b'boxhD;': b'╥', 
   b'boxhU;': b'╨', 
   b'boxhd;': b'┬', 
   b'boxhu;': b'┴', 
   b'boxminus;': b'⊟', 
   b'boxplus;': b'⊞', 
   b'boxtimes;': b'⊠', 
   b'boxuL;': b'╛', 
   b'boxuR;': b'╘', 
   b'boxul;': b'┘', 
   b'boxur;': b'└', 
   b'boxv;': b'│', 
   b'boxvH;': b'╪', 
   b'boxvL;': b'╡', 
   b'boxvR;': b'╞', 
   b'boxvh;': b'┼', 
   b'boxvl;': b'┤', 
   b'boxvr;': b'├', 
   b'bprime;': b'‵', 
   b'breve;': b'˘', 
   b'brvbar': b'¦', 
   b'brvbar;': b'¦', 
   b'bscr;': b'𝒷', 
   b'bsemi;': b'⁏', 
   b'bsim;': b'∽', 
   b'bsime;': b'⋍', 
   b'bsol;': b'\\', 
   b'bsolb;': b'⧅', 
   b'bsolhsub;': b'⟈', 
   b'bull;': b'•', 
   b'bullet;': b'•', 
   b'bump;': b'≎', 
   b'bumpE;': b'⪮', 
   b'bumpe;': b'≏', 
   b'bumpeq;': b'≏', 
   b'cacute;': b'ć', 
   b'cap;': b'∩', 
   b'capand;': b'⩄', 
   b'capbrcup;': b'⩉', 
   b'capcap;': b'⩋', 
   b'capcup;': b'⩇', 
   b'capdot;': b'⩀', 
   b'caps;': b'∩︀', 
   b'caret;': b'⁁', 
   b'caron;': b'ˇ', 
   b'ccaps;': b'⩍', 
   b'ccaron;': b'č', 
   b'ccedil': b'ç', 
   b'ccedil;': b'ç', 
   b'ccirc;': b'ĉ', 
   b'ccups;': b'⩌', 
   b'ccupssm;': b'⩐', 
   b'cdot;': b'ċ', 
   b'cedil': b'¸', 
   b'cedil;': b'¸', 
   b'cemptyv;': b'⦲', 
   b'cent': b'¢', 
   b'cent;': b'¢', 
   b'centerdot;': b'·', 
   b'cfr;': b'𝔠', 
   b'chcy;': b'ч', 
   b'check;': b'✓', 
   b'checkmark;': b'✓', 
   b'chi;': b'χ', 
   b'cir;': b'○', 
   b'cirE;': b'⧃', 
   b'circ;': b'ˆ', 
   b'circeq;': b'≗', 
   b'circlearrowleft;': b'↺', 
   b'circlearrowright;': b'↻', 
   b'circledR;': b'®', 
   b'circledS;': b'Ⓢ', 
   b'circledast;': b'⊛', 
   b'circledcirc;': b'⊚', 
   b'circleddash;': b'⊝', 
   b'cire;': b'≗', 
   b'cirfnint;': b'⨐', 
   b'cirmid;': b'⫯', 
   b'cirscir;': b'⧂', 
   b'clubs;': b'♣', 
   b'clubsuit;': b'♣', 
   b'colon;': b':', 
   b'colone;': b'≔', 
   b'coloneq;': b'≔', 
   b'comma;': b',', 
   b'commat;': b'@', 
   b'comp;': b'∁', 
   b'compfn;': b'∘', 
   b'complement;': b'∁', 
   b'complexes;': b'ℂ', 
   b'cong;': b'≅', 
   b'congdot;': b'⩭', 
   b'conint;': b'∮', 
   b'copf;': b'𝕔', 
   b'coprod;': b'∐', 
   b'copy': b'©', 
   b'copy;': b'©', 
   b'copysr;': b'℗', 
   b'crarr;': b'↵', 
   b'cross;': b'✗', 
   b'cscr;': b'𝒸', 
   b'csub;': b'⫏', 
   b'csube;': b'⫑', 
   b'csup;': b'⫐', 
   b'csupe;': b'⫒', 
   b'ctdot;': b'⋯', 
   b'cudarrl;': b'⤸', 
   b'cudarrr;': b'⤵', 
   b'cuepr;': b'⋞', 
   b'cuesc;': b'⋟', 
   b'cularr;': b'↶', 
   b'cularrp;': b'⤽', 
   b'cup;': b'∪', 
   b'cupbrcap;': b'⩈', 
   b'cupcap;': b'⩆', 
   b'cupcup;': b'⩊', 
   b'cupdot;': b'⊍', 
   b'cupor;': b'⩅', 
   b'cups;': b'∪︀', 
   b'curarr;': b'↷', 
   b'curarrm;': b'⤼', 
   b'curlyeqprec;': b'⋞', 
   b'curlyeqsucc;': b'⋟', 
   b'curlyvee;': b'⋎', 
   b'curlywedge;': b'⋏', 
   b'curren': b'¤', 
   b'curren;': b'¤', 
   b'curvearrowleft;': b'↶', 
   b'curvearrowright;': b'↷', 
   b'cuvee;': b'⋎', 
   b'cuwed;': b'⋏', 
   b'cwconint;': b'∲', 
   b'cwint;': b'∱', 
   b'cylcty;': b'⌭', 
   b'dArr;': b'⇓', 
   b'dHar;': b'⥥', 
   b'dagger;': b'†', 
   b'daleth;': b'ℸ', 
   b'darr;': b'↓', 
   b'dash;': b'‐', 
   b'dashv;': b'⊣', 
   b'dbkarow;': b'⤏', 
   b'dblac;': b'˝', 
   b'dcaron;': b'ď', 
   b'dcy;': b'д', 
   b'dd;': b'ⅆ', 
   b'ddagger;': b'‡', 
   b'ddarr;': b'⇊', 
   b'ddotseq;': b'⩷', 
   b'deg': b'°', 
   b'deg;': b'°', 
   b'delta;': b'δ', 
   b'demptyv;': b'⦱', 
   b'dfisht;': b'⥿', 
   b'dfr;': b'𝔡', 
   b'dharl;': b'⇃', 
   b'dharr;': b'⇂', 
   b'diam;': b'⋄', 
   b'diamond;': b'⋄', 
   b'diamondsuit;': b'♦', 
   b'diams;': b'♦', 
   b'die;': b'¨', 
   b'digamma;': b'ϝ', 
   b'disin;': b'⋲', 
   b'div;': b'÷', 
   b'divide': b'÷', 
   b'divide;': b'÷', 
   b'divideontimes;': b'⋇', 
   b'divonx;': b'⋇', 
   b'djcy;': b'ђ', 
   b'dlcorn;': b'⌞', 
   b'dlcrop;': b'⌍', 
   b'dollar;': b'$', 
   b'dopf;': b'𝕕', 
   b'dot;': b'˙', 
   b'doteq;': b'≐', 
   b'doteqdot;': b'≑', 
   b'dotminus;': b'∸', 
   b'dotplus;': b'∔', 
   b'dotsquare;': b'⊡', 
   b'doublebarwedge;': b'⌆', 
   b'downarrow;': b'↓', 
   b'downdownarrows;': b'⇊', 
   b'downharpoonleft;': b'⇃', 
   b'downharpoonright;': b'⇂', 
   b'drbkarow;': b'⤐', 
   b'drcorn;': b'⌟', 
   b'drcrop;': b'⌌', 
   b'dscr;': b'𝒹', 
   b'dscy;': b'ѕ', 
   b'dsol;': b'⧶', 
   b'dstrok;': b'đ', 
   b'dtdot;': b'⋱', 
   b'dtri;': b'▿', 
   b'dtrif;': b'▾', 
   b'duarr;': b'⇵', 
   b'duhar;': b'⥯', 
   b'dwangle;': b'⦦', 
   b'dzcy;': b'џ', 
   b'dzigrarr;': b'⟿', 
   b'eDDot;': b'⩷', 
   b'eDot;': b'≑', 
   b'eacute': b'é', 
   b'eacute;': b'é', 
   b'easter;': b'⩮', 
   b'ecaron;': b'ě', 
   b'ecir;': b'≖', 
   b'ecirc': b'ê', 
   b'ecirc;': b'ê', 
   b'ecolon;': b'≕', 
   b'ecy;': b'э', 
   b'edot;': b'ė', 
   b'ee;': b'ⅇ', 
   b'efDot;': b'≒', 
   b'efr;': b'𝔢', 
   b'eg;': b'⪚', 
   b'egrave': b'è', 
   b'egrave;': b'è', 
   b'egs;': b'⪖', 
   b'egsdot;': b'⪘', 
   b'el;': b'⪙', 
   b'elinters;': b'⏧', 
   b'ell;': b'ℓ', 
   b'els;': b'⪕', 
   b'elsdot;': b'⪗', 
   b'emacr;': b'ē', 
   b'empty;': b'∅', 
   b'emptyset;': b'∅', 
   b'emptyv;': b'∅', 
   b'emsp13;': b'\u2004', 
   b'emsp14;': b'\u2005', 
   b'emsp;': b'\u2003', 
   b'eng;': b'ŋ', 
   b'ensp;': b'\u2002', 
   b'eogon;': b'ę', 
   b'eopf;': b'𝕖', 
   b'epar;': b'⋕', 
   b'eparsl;': b'⧣', 
   b'eplus;': b'⩱', 
   b'epsi;': b'ε', 
   b'epsilon;': b'ε', 
   b'epsiv;': b'ϵ', 
   b'eqcirc;': b'≖', 
   b'eqcolon;': b'≕', 
   b'eqsim;': b'≂', 
   b'eqslantgtr;': b'⪖', 
   b'eqslantless;': b'⪕', 
   b'equals;': b'=', 
   b'equest;': b'≟', 
   b'equiv;': b'≡', 
   b'equivDD;': b'⩸', 
   b'eqvparsl;': b'⧥', 
   b'erDot;': b'≓', 
   b'erarr;': b'⥱', 
   b'escr;': b'ℯ', 
   b'esdot;': b'≐', 
   b'esim;': b'≂', 
   b'eta;': b'η', 
   b'eth': b'ð', 
   b'eth;': b'ð', 
   b'euml': b'ë', 
   b'euml;': b'ë', 
   b'euro;': b'€', 
   b'excl;': b'!', 
   b'exist;': b'∃', 
   b'expectation;': b'ℰ', 
   b'exponentiale;': b'ⅇ', 
   b'fallingdotseq;': b'≒', 
   b'fcy;': b'ф', 
   b'female;': b'♀', 
   b'ffilig;': b'ﬃ', 
   b'fflig;': b'ﬀ', 
   b'ffllig;': b'ﬄ', 
   b'ffr;': b'𝔣', 
   b'filig;': b'ﬁ', 
   b'fjlig;': b'fj', 
   b'flat;': b'♭', 
   b'fllig;': b'ﬂ', 
   b'fltns;': b'▱', 
   b'fnof;': b'ƒ', 
   b'fopf;': b'𝕗', 
   b'forall;': b'∀', 
   b'fork;': b'⋔', 
   b'forkv;': b'⫙', 
   b'fpartint;': b'⨍', 
   b'frac12': b'½', 
   b'frac12;': b'½', 
   b'frac13;': b'⅓', 
   b'frac14': b'¼', 
   b'frac14;': b'¼', 
   b'frac15;': b'⅕', 
   b'frac16;': b'⅙', 
   b'frac18;': b'⅛', 
   b'frac23;': b'⅔', 
   b'frac25;': b'⅖', 
   b'frac34': b'¾', 
   b'frac34;': b'¾', 
   b'frac35;': b'⅗', 
   b'frac38;': b'⅜', 
   b'frac45;': b'⅘', 
   b'frac56;': b'⅚', 
   b'frac58;': b'⅝', 
   b'frac78;': b'⅞', 
   b'frasl;': b'⁄', 
   b'frown;': b'⌢', 
   b'fscr;': b'𝒻', 
   b'gE;': b'≧', 
   b'gEl;': b'⪌', 
   b'gacute;': b'ǵ', 
   b'gamma;': b'γ', 
   b'gammad;': b'ϝ', 
   b'gap;': b'⪆', 
   b'gbreve;': b'ğ', 
   b'gcirc;': b'ĝ', 
   b'gcy;': b'г', 
   b'gdot;': b'ġ', 
   b'ge;': b'≥', 
   b'gel;': b'⋛', 
   b'geq;': b'≥', 
   b'geqq;': b'≧', 
   b'geqslant;': b'⩾', 
   b'ges;': b'⩾', 
   b'gescc;': b'⪩', 
   b'gesdot;': b'⪀', 
   b'gesdoto;': b'⪂', 
   b'gesdotol;': b'⪄', 
   b'gesl;': b'⋛︀', 
   b'gesles;': b'⪔', 
   b'gfr;': b'𝔤', 
   b'gg;': b'≫', 
   b'ggg;': b'⋙', 
   b'gimel;': b'ℷ', 
   b'gjcy;': b'ѓ', 
   b'gl;': b'≷', 
   b'glE;': b'⪒', 
   b'gla;': b'⪥', 
   b'glj;': b'⪤', 
   b'gnE;': b'≩', 
   b'gnap;': b'⪊', 
   b'gnapprox;': b'⪊', 
   b'gne;': b'⪈', 
   b'gneq;': b'⪈', 
   b'gneqq;': b'≩', 
   b'gnsim;': b'⋧', 
   b'gopf;': b'𝕘', 
   b'grave;': b'`', 
   b'gscr;': b'ℊ', 
   b'gsim;': b'≳', 
   b'gsime;': b'⪎', 
   b'gsiml;': b'⪐', 
   b'gt': b'>', 
   b'gt;': b'>', 
   b'gtcc;': b'⪧', 
   b'gtcir;': b'⩺', 
   b'gtdot;': b'⋗', 
   b'gtlPar;': b'⦕', 
   b'gtquest;': b'⩼', 
   b'gtrapprox;': b'⪆', 
   b'gtrarr;': b'⥸', 
   b'gtrdot;': b'⋗', 
   b'gtreqless;': b'⋛', 
   b'gtreqqless;': b'⪌', 
   b'gtrless;': b'≷', 
   b'gtrsim;': b'≳', 
   b'gvertneqq;': b'≩︀', 
   b'gvnE;': b'≩︀', 
   b'hArr;': b'⇔', 
   b'hairsp;': b'\u200a', 
   b'half;': b'½', 
   b'hamilt;': b'ℋ', 
   b'hardcy;': b'ъ', 
   b'harr;': b'↔', 
   b'harrcir;': b'⥈', 
   b'harrw;': b'↭', 
   b'hbar;': b'ℏ', 
   b'hcirc;': b'ĥ', 
   b'hearts;': b'♥', 
   b'heartsuit;': b'♥', 
   b'hellip;': b'…', 
   b'hercon;': b'⊹', 
   b'hfr;': b'𝔥', 
   b'hksearow;': b'⤥', 
   b'hkswarow;': b'⤦', 
   b'hoarr;': b'⇿', 
   b'homtht;': b'∻', 
   b'hookleftarrow;': b'↩', 
   b'hookrightarrow;': b'↪', 
   b'hopf;': b'𝕙', 
   b'horbar;': b'―', 
   b'hscr;': b'𝒽', 
   b'hslash;': b'ℏ', 
   b'hstrok;': b'ħ', 
   b'hybull;': b'⁃', 
   b'hyphen;': b'‐', 
   b'iacute': b'í', 
   b'iacute;': b'í', 
   b'ic;': b'\u2063', 
   b'icirc': b'î', 
   b'icirc;': b'î', 
   b'icy;': b'и', 
   b'iecy;': b'е', 
   b'iexcl': b'¡', 
   b'iexcl;': b'¡', 
   b'iff;': b'⇔', 
   b'ifr;': b'𝔦', 
   b'igrave': b'ì', 
   b'igrave;': b'ì', 
   b'ii;': b'ⅈ', 
   b'iiiint;': b'⨌', 
   b'iiint;': b'∭', 
   b'iinfin;': b'⧜', 
   b'iiota;': b'℩', 
   b'ijlig;': b'ĳ', 
   b'imacr;': b'ī', 
   b'image;': b'ℑ', 
   b'imagline;': b'ℐ', 
   b'imagpart;': b'ℑ', 
   b'imath;': b'ı', 
   b'imof;': b'⊷', 
   b'imped;': b'Ƶ', 
   b'in;': b'∈', 
   b'incare;': b'℅', 
   b'infin;': b'∞', 
   b'infintie;': b'⧝', 
   b'inodot;': b'ı', 
   b'int;': b'∫', 
   b'intcal;': b'⊺', 
   b'integers;': b'ℤ', 
   b'intercal;': b'⊺', 
   b'intlarhk;': b'⨗', 
   b'intprod;': b'⨼', 
   b'iocy;': b'ё', 
   b'iogon;': b'į', 
   b'iopf;': b'𝕚', 
   b'iota;': b'ι', 
   b'iprod;': b'⨼', 
   b'iquest': b'¿', 
   b'iquest;': b'¿', 
   b'iscr;': b'𝒾', 
   b'isin;': b'∈', 
   b'isinE;': b'⋹', 
   b'isindot;': b'⋵', 
   b'isins;': b'⋴', 
   b'isinsv;': b'⋳', 
   b'isinv;': b'∈', 
   b'it;': b'\u2062', 
   b'itilde;': b'ĩ', 
   b'iukcy;': b'і', 
   b'iuml': b'ï', 
   b'iuml;': b'ï', 
   b'jcirc;': b'ĵ', 
   b'jcy;': b'й', 
   b'jfr;': b'𝔧', 
   b'jmath;': b'ȷ', 
   b'jopf;': b'𝕛', 
   b'jscr;': b'𝒿', 
   b'jsercy;': b'ј', 
   b'jukcy;': b'є', 
   b'kappa;': b'κ', 
   b'kappav;': b'ϰ', 
   b'kcedil;': b'ķ', 
   b'kcy;': b'к', 
   b'kfr;': b'𝔨', 
   b'kgreen;': b'ĸ', 
   b'khcy;': b'х', 
   b'kjcy;': b'ќ', 
   b'kopf;': b'𝕜', 
   b'kscr;': b'𝓀', 
   b'lAarr;': b'⇚', 
   b'lArr;': b'⇐', 
   b'lAtail;': b'⤛', 
   b'lBarr;': b'⤎', 
   b'lE;': b'≦', 
   b'lEg;': b'⪋', 
   b'lHar;': b'⥢', 
   b'lacute;': b'ĺ', 
   b'laemptyv;': b'⦴', 
   b'lagran;': b'ℒ', 
   b'lambda;': b'λ', 
   b'lang;': b'⟨', 
   b'langd;': b'⦑', 
   b'langle;': b'⟨', 
   b'lap;': b'⪅', 
   b'laquo': b'«', 
   b'laquo;': b'«', 
   b'larr;': b'←', 
   b'larrb;': b'⇤', 
   b'larrbfs;': b'⤟', 
   b'larrfs;': b'⤝', 
   b'larrhk;': b'↩', 
   b'larrlp;': b'↫', 
   b'larrpl;': b'⤹', 
   b'larrsim;': b'⥳', 
   b'larrtl;': b'↢', 
   b'lat;': b'⪫', 
   b'latail;': b'⤙', 
   b'late;': b'⪭', 
   b'lates;': b'⪭︀', 
   b'lbarr;': b'⤌', 
   b'lbbrk;': b'❲', 
   b'lbrace;': b'{', 
   b'lbrack;': b'[', 
   b'lbrke;': b'⦋', 
   b'lbrksld;': b'⦏', 
   b'lbrkslu;': b'⦍', 
   b'lcaron;': b'ľ', 
   b'lcedil;': b'ļ', 
   b'lceil;': b'⌈', 
   b'lcub;': b'{', 
   b'lcy;': b'л', 
   b'ldca;': b'⤶', 
   b'ldquo;': b'“', 
   b'ldquor;': b'„', 
   b'ldrdhar;': b'⥧', 
   b'ldrushar;': b'⥋', 
   b'ldsh;': b'↲', 
   b'le;': b'≤', 
   b'leftarrow;': b'←', 
   b'leftarrowtail;': b'↢', 
   b'leftharpoondown;': b'↽', 
   b'leftharpoonup;': b'↼', 
   b'leftleftarrows;': b'⇇', 
   b'leftrightarrow;': b'↔', 
   b'leftrightarrows;': b'⇆', 
   b'leftrightharpoons;': b'⇋', 
   b'leftrightsquigarrow;': b'↭', 
   b'leftthreetimes;': b'⋋', 
   b'leg;': b'⋚', 
   b'leq;': b'≤', 
   b'leqq;': b'≦', 
   b'leqslant;': b'⩽', 
   b'les;': b'⩽', 
   b'lescc;': b'⪨', 
   b'lesdot;': b'⩿', 
   b'lesdoto;': b'⪁', 
   b'lesdotor;': b'⪃', 
   b'lesg;': b'⋚︀', 
   b'lesges;': b'⪓', 
   b'lessapprox;': b'⪅', 
   b'lessdot;': b'⋖', 
   b'lesseqgtr;': b'⋚', 
   b'lesseqqgtr;': b'⪋', 
   b'lessgtr;': b'≶', 
   b'lesssim;': b'≲', 
   b'lfisht;': b'⥼', 
   b'lfloor;': b'⌊', 
   b'lfr;': b'𝔩', 
   b'lg;': b'≶', 
   b'lgE;': b'⪑', 
   b'lhard;': b'↽', 
   b'lharu;': b'↼', 
   b'lharul;': b'⥪', 
   b'lhblk;': b'▄', 
   b'ljcy;': b'љ', 
   b'll;': b'≪', 
   b'llarr;': b'⇇', 
   b'llcorner;': b'⌞', 
   b'llhard;': b'⥫', 
   b'lltri;': b'◺', 
   b'lmidot;': b'ŀ', 
   b'lmoust;': b'⎰', 
   b'lmoustache;': b'⎰', 
   b'lnE;': b'≨', 
   b'lnap;': b'⪉', 
   b'lnapprox;': b'⪉', 
   b'lne;': b'⪇', 
   b'lneq;': b'⪇', 
   b'lneqq;': b'≨', 
   b'lnsim;': b'⋦', 
   b'loang;': b'⟬', 
   b'loarr;': b'⇽', 
   b'lobrk;': b'⟦', 
   b'longleftarrow;': b'⟵', 
   b'longleftrightarrow;': b'⟷', 
   b'longmapsto;': b'⟼', 
   b'longrightarrow;': b'⟶', 
   b'looparrowleft;': b'↫', 
   b'looparrowright;': b'↬', 
   b'lopar;': b'⦅', 
   b'lopf;': b'𝕝', 
   b'loplus;': b'⨭', 
   b'lotimes;': b'⨴', 
   b'lowast;': b'∗', 
   b'lowbar;': b'_', 
   b'loz;': b'◊', 
   b'lozenge;': b'◊', 
   b'lozf;': b'⧫', 
   b'lpar;': b'(', 
   b'lparlt;': b'⦓', 
   b'lrarr;': b'⇆', 
   b'lrcorner;': b'⌟', 
   b'lrhar;': b'⇋', 
   b'lrhard;': b'⥭', 
   b'lrm;': b'\u200e', 
   b'lrtri;': b'⊿', 
   b'lsaquo;': b'‹', 
   b'lscr;': b'𝓁', 
   b'lsh;': b'↰', 
   b'lsim;': b'≲', 
   b'lsime;': b'⪍', 
   b'lsimg;': b'⪏', 
   b'lsqb;': b'[', 
   b'lsquo;': b'’', 
   b'lsquor;': b'‚', 
   b'lstrok;': b'ł', 
   b'lt': b'<', 
   b'lt;': b'<', 
   b'ltcc;': b'⪦', 
   b'ltcir;': b'⩹', 
   b'ltdot;': b'⋖', 
   b'lthree;': b'⋋', 
   b'ltimes;': b'⋉', 
   b'ltlarr;': b'⥶', 
   b'ltquest;': b'⩻', 
   b'ltrPar;': b'⦖', 
   b'ltri;': b'◃', 
   b'ltrie;': b'⊴', 
   b'ltrif;': b'◂', 
   b'lurdshar;': b'⥊', 
   b'luruhar;': b'⥦', 
   b'lvertneqq;': b'≨︀', 
   b'lvnE;': b'≨︀', 
   b'mDDot;': b'∺', 
   b'macr': b'¯', 
   b'macr;': b'¯', 
   b'male;': b'♂', 
   b'malt;': b'✠', 
   b'maltese;': b'✠', 
   b'map;': b'↦', 
   b'mapsto;': b'↦', 
   b'mapstodown;': b'↧', 
   b'mapstoleft;': b'↤', 
   b'mapstoup;': b'↥', 
   b'marker;': b'▮', 
   b'mcomma;': b'⨩', 
   b'mcy;': b'м', 
   b'mdash;': b'—', 
   b'measuredangle;': b'∡', 
   b'mfr;': b'𝔪', 
   b'mho;': b'℧', 
   b'micro': b'µ', 
   b'micro;': b'µ', 
   b'mid;': b'∣', 
   b'midast;': b'*', 
   b'midcir;': b'⫰', 
   b'middot': b'·', 
   b'middot;': b'·', 
   b'minus;': b'−', 
   b'minusb;': b'⊟', 
   b'minusd;': b'∸', 
   b'minusdu;': b'⨪', 
   b'mlcp;': b'⫛', 
   b'mldr;': b'…', 
   b'mnplus;': b'∓', 
   b'models;': b'⊧', 
   b'mopf;': b'𝕞', 
   b'mp;': b'∓', 
   b'mscr;': b'𝓂', 
   b'mstpos;': b'∾', 
   b'mu;': b'μ', 
   b'multimap;': b'⊸', 
   b'mumap;': b'⊸', 
   b'nGg;': b'⋙̸', 
   b'nGt;': b'≫⃒', 
   b'nGtv;': b'≫̸', 
   b'nLeftarrow;': b'⇍', 
   b'nLeftrightarrow;': b'⇎', 
   b'nLl;': b'⋘̸', 
   b'nLt;': b'≪⃒', 
   b'nLtv;': b'≪̸', 
   b'nRightarrow;': b'⇏', 
   b'nVDash;': b'⊯', 
   b'nVdash;': b'⊮', 
   b'nabla;': b'∇', 
   b'nacute;': b'ń', 
   b'nang;': b'∠⃒', 
   b'nap;': b'≉', 
   b'napE;': b'⩰̸', 
   b'napid;': b'≋̸', 
   b'napos;': b'ŉ', 
   b'napprox;': b'≉', 
   b'natur;': b'♮', 
   b'natural;': b'♮', 
   b'naturals;': b'ℕ', 
   b'nbsp': b'\xa0', 
   b'nbsp;': b'\xa0', 
   b'nbump;': b'≎̸', 
   b'nbumpe;': b'≏̸', 
   b'ncap;': b'⩃', 
   b'ncaron;': b'ň', 
   b'ncedil;': b'ņ', 
   b'ncong;': b'≇', 
   b'ncongdot;': b'⩭̸', 
   b'ncup;': b'⩂', 
   b'ncy;': b'н', 
   b'ndash;': b'–', 
   b'ne;': b'≠', 
   b'neArr;': b'⇗', 
   b'nearhk;': b'⤤', 
   b'nearr;': b'↗', 
   b'nearrow;': b'↗', 
   b'nedot;': b'≐̸', 
   b'nequiv;': b'≢', 
   b'nesear;': b'⤨', 
   b'nesim;': b'≂̸', 
   b'nexist;': b'∄', 
   b'nexists;': b'∄', 
   b'nfr;': b'𝔫', 
   b'ngE;': b'≧̸', 
   b'nge;': b'≱', 
   b'ngeq;': b'≱', 
   b'ngeqq;': b'≧̸', 
   b'ngeqslant;': b'⩾̸', 
   b'nges;': b'⩾̸', 
   b'ngsim;': b'≵', 
   b'ngt;': b'≯', 
   b'ngtr;': b'≯', 
   b'nhArr;': b'⇎', 
   b'nharr;': b'↮', 
   b'nhpar;': b'⫲', 
   b'ni;': b'∋', 
   b'nis;': b'⋼', 
   b'nisd;': b'⋺', 
   b'niv;': b'∋', 
   b'njcy;': b'њ', 
   b'nlArr;': b'⇍', 
   b'nlE;': b'≦̸', 
   b'nlarr;': b'↚', 
   b'nldr;': b'‥', 
   b'nle;': b'≰', 
   b'nleftarrow;': b'↚', 
   b'nleftrightarrow;': b'↮', 
   b'nleq;': b'≰', 
   b'nleqq;': b'≦̸', 
   b'nleqslant;': b'⩽̸', 
   b'nles;': b'⩽̸', 
   b'nless;': b'≮', 
   b'nlsim;': b'≴', 
   b'nlt;': b'≮', 
   b'nltri;': b'⋪', 
   b'nltrie;': b'⋬', 
   b'nmid;': b'∤', 
   b'nopf;': b'𝕟', 
   b'not': b'¬', 
   b'not;': b'¬', 
   b'notin;': b'∉', 
   b'notinE;': b'⋹̸', 
   b'notindot;': b'⋵̸', 
   b'notinva;': b'∉', 
   b'notinvb;': b'⋷', 
   b'notinvc;': b'⋶', 
   b'notni;': b'∌', 
   b'notniva;': b'∌', 
   b'notnivb;': b'⋾', 
   b'notnivc;': b'⋽', 
   b'npar;': b'∦', 
   b'nparallel;': b'∦', 
   b'nparsl;': b'⫽⃥', 
   b'npart;': b'∂̸', 
   b'npolint;': b'⨔', 
   b'npr;': b'⊀', 
   b'nprcue;': b'⋠', 
   b'npre;': b'⪯̸', 
   b'nprec;': b'⊀', 
   b'npreceq;': b'⪯̸', 
   b'nrArr;': b'⇏', 
   b'nrarr;': b'↛', 
   b'nrarrc;': b'⤳̸', 
   b'nrarrw;': b'↝̸', 
   b'nrightarrow;': b'↛', 
   b'nrtri;': b'⋫', 
   b'nrtrie;': b'⋭', 
   b'nsc;': b'⊁', 
   b'nsccue;': b'⋡', 
   b'nsce;': b'⪰̸', 
   b'nscr;': b'𝓃', 
   b'nshortmid;': b'∤', 
   b'nshortparallel;': b'∦', 
   b'nsim;': b'≁', 
   b'nsime;': b'≄', 
   b'nsimeq;': b'≄', 
   b'nsmid;': b'∤', 
   b'nspar;': b'∦', 
   b'nsqsube;': b'⋢', 
   b'nsqsupe;': b'⋣', 
   b'nsub;': b'⊄', 
   b'nsubE;': b'⫅̸', 
   b'nsube;': b'⊈', 
   b'nsubset;': b'⊂⃒', 
   b'nsubseteq;': b'⊈', 
   b'nsubseteqq;': b'⫅̸', 
   b'nsucc;': b'⊁', 
   b'nsucceq;': b'⪰̸', 
   b'nsup;': b'⊅', 
   b'nsupE;': b'⫆̸', 
   b'nsupe;': b'⊉', 
   b'nsupset;': b'⊃⃒', 
   b'nsupseteq;': b'⊉', 
   b'nsupseteqq;': b'⫆̸', 
   b'ntgl;': b'≹', 
   b'ntilde': b'ñ', 
   b'ntilde;': b'ñ', 
   b'ntlg;': b'≸', 
   b'ntriangleleft;': b'⋪', 
   b'ntrianglelefteq;': b'⋬', 
   b'ntriangleright;': b'⋫', 
   b'ntrianglerighteq;': b'⋭', 
   b'nu;': b'ν', 
   b'num;': b'#', 
   b'numero;': b'№', 
   b'numsp;': b'\u2007', 
   b'nvDash;': b'⊭', 
   b'nvHarr;': b'⤄', 
   b'nvap;': b'≍⃒', 
   b'nvdash;': b'⊬', 
   b'nvge;': b'≥⃒', 
   b'nvgt;': b'>⃒', 
   b'nvinfin;': b'⧞', 
   b'nvlArr;': b'⤂', 
   b'nvle;': b'≤⃒', 
   b'nvlt;': b'<⃒', 
   b'nvltrie;': b'⊴⃒', 
   b'nvrArr;': b'⤃', 
   b'nvrtrie;': b'⊵⃒', 
   b'nvsim;': b'∼⃒', 
   b'nwArr;': b'⇖', 
   b'nwarhk;': b'⤣', 
   b'nwarr;': b'↖', 
   b'nwarrow;': b'↖', 
   b'nwnear;': b'⤧', 
   b'oS;': b'Ⓢ', 
   b'oacute': b'ó', 
   b'oacute;': b'ó', 
   b'oast;': b'⊛', 
   b'ocir;': b'⊚', 
   b'ocirc': b'ô', 
   b'ocirc;': b'ô', 
   b'ocy;': b'о', 
   b'odash;': b'⊝', 
   b'odblac;': b'ő', 
   b'odiv;': b'⨸', 
   b'odot;': b'⊙', 
   b'odsold;': b'⦼', 
   b'oelig;': b'œ', 
   b'ofcir;': b'⦿', 
   b'ofr;': b'𝔬', 
   b'ogon;': b'˛', 
   b'ograve': b'ò', 
   b'ograve;': b'ò', 
   b'ogt;': b'⧁', 
   b'ohbar;': b'⦵', 
   b'ohm;': b'Ω', 
   b'oint;': b'∮', 
   b'olarr;': b'↺', 
   b'olcir;': b'⦾', 
   b'olcross;': b'⦻', 
   b'oline;': b'‾', 
   b'olt;': b'⧀', 
   b'omacr;': b'ō', 
   b'omega;': b'ω', 
   b'omicron;': b'ο', 
   b'omid;': b'⦶', 
   b'ominus;': b'⊖', 
   b'oopf;': b'𝕠', 
   b'opar;': b'⦷', 
   b'operp;': b'⦹', 
   b'oplus;': b'⊕', 
   b'or;': b'∨', 
   b'orarr;': b'↻', 
   b'ord;': b'⩝', 
   b'order;': b'ℴ', 
   b'orderof;': b'ℴ', 
   b'ordf': b'ª', 
   b'ordf;': b'ª', 
   b'ordm': b'º', 
   b'ordm;': b'º', 
   b'origof;': b'⊶', 
   b'oror;': b'⩖', 
   b'orslope;': b'⩗', 
   b'orv;': b'⩛', 
   b'oscr;': b'ℴ', 
   b'oslash': b'ø', 
   b'oslash;': b'ø', 
   b'osol;': b'⊘', 
   b'otilde': b'õ', 
   b'otilde;': b'õ', 
   b'otimes;': b'⊗', 
   b'otimesas;': b'⨶', 
   b'ouml': b'ö', 
   b'ouml;': b'ö', 
   b'ovbar;': b'⌽', 
   b'par;': b'∥', 
   b'para': b'¶', 
   b'para;': b'¶', 
   b'parallel;': b'∥', 
   b'parsim;': b'⫳', 
   b'parsl;': b'⫽', 
   b'part;': b'∂', 
   b'pcy;': b'п', 
   b'percnt;': b'%', 
   b'period;': b'.', 
   b'permil;': b'‰', 
   b'perp;': b'⊥', 
   b'pertenk;': b'‱', 
   b'pfr;': b'𝔭', 
   b'phi;': b'φ', 
   b'phiv;': b'ϕ', 
   b'phmmat;': b'ℳ', 
   b'phone;': b'☎', 
   b'pi;': b'π', 
   b'pitchfork;': b'⋔', 
   b'piv;': b'ϖ', 
   b'planck;': b'ℏ', 
   b'planckh;': b'ℎ', 
   b'plankv;': b'ℏ', 
   b'plus;': b'+', 
   b'plusacir;': b'⨣', 
   b'plusb;': b'⊞', 
   b'pluscir;': b'⨢', 
   b'plusdo;': b'∔', 
   b'plusdu;': b'⨥', 
   b'pluse;': b'⩲', 
   b'plusmn': b'±', 
   b'plusmn;': b'±', 
   b'plussim;': b'⨦', 
   b'plustwo;': b'⨧', 
   b'pm;': b'±', 
   b'pointint;': b'⨕', 
   b'popf;': b'𝕡', 
   b'pound': b'£', 
   b'pound;': b'£', 
   b'pr;': b'≺', 
   b'prE;': b'⪳', 
   b'prap;': b'⪷', 
   b'prcue;': b'≼', 
   b'pre;': b'⪯', 
   b'prec;': b'≺', 
   b'precapprox;': b'⪷', 
   b'preccurlyeq;': b'≼', 
   b'preceq;': b'⪯', 
   b'precnapprox;': b'⪹', 
   b'precneqq;': b'⪵', 
   b'precnsim;': b'⋨', 
   b'precsim;': b'≾', 
   b'prime;': b'′', 
   b'primes;': b'ℙ', 
   b'prnE;': b'⪵', 
   b'prnap;': b'⪹', 
   b'prnsim;': b'⋨', 
   b'prod;': b'∏', 
   b'profalar;': b'⌮', 
   b'profline;': b'⌒', 
   b'profsurf;': b'⌓', 
   b'prop;': b'∝', 
   b'propto;': b'∝', 
   b'prsim;': b'≾', 
   b'prurel;': b'⊰', 
   b'pscr;': b'𝓅', 
   b'psi;': b'ψ', 
   b'puncsp;': b'\u2008', 
   b'qfr;': b'𝔮', 
   b'qint;': b'⨌', 
   b'qopf;': b'𝕢', 
   b'qprime;': b'⁗', 
   b'qscr;': b'𝓆', 
   b'quaternions;': b'ℍ', 
   b'quatint;': b'⨖', 
   b'quest;': b'?', 
   b'questeq;': b'≟', 
   b'quot': b'"', 
   b'quot;': b'"', 
   b'rAarr;': b'⇛', 
   b'rArr;': b'⇒', 
   b'rAtail;': b'⤜', 
   b'rBarr;': b'⤏', 
   b'rHar;': b'⥤', 
   b'race;': b'∽̱', 
   b'racute;': b'ŕ', 
   b'radic;': b'√', 
   b'raemptyv;': b'⦳', 
   b'rang;': b'⟩', 
   b'rangd;': b'⦒', 
   b'range;': b'⦥', 
   b'rangle;': b'⟩', 
   b'raquo': b'»', 
   b'raquo;': b'»', 
   b'rarr;': b'→', 
   b'rarrap;': b'⥵', 
   b'rarrb;': b'⇥', 
   b'rarrbfs;': b'⤠', 
   b'rarrc;': b'⤳', 
   b'rarrfs;': b'⤞', 
   b'rarrhk;': b'↪', 
   b'rarrlp;': b'↬', 
   b'rarrpl;': b'⥅', 
   b'rarrsim;': b'⥴', 
   b'rarrtl;': b'↣', 
   b'rarrw;': b'↝', 
   b'ratail;': b'⤚', 
   b'ratio;': b'∶', 
   b'rationals;': b'ℚ', 
   b'rbarr;': b'⤍', 
   b'rbbrk;': b'❳', 
   b'rbrace;': b'}', 
   b'rbrack;': b']', 
   b'rbrke;': b'⦌', 
   b'rbrksld;': b'⦎', 
   b'rbrkslu;': b'⦐', 
   b'rcaron;': b'ř', 
   b'rcedil;': b'ŗ', 
   b'rceil;': b'⌉', 
   b'rcub;': b'}', 
   b'rcy;': b'р', 
   b'rdca;': b'⤷', 
   b'rdldhar;': b'⥩', 
   b'rdquo;': b'”', 
   b'rdquor;': b'”', 
   b'rdsh;': b'↳', 
   b'real;': b'ℜ', 
   b'realine;': b'ℛ', 
   b'realpart;': b'ℜ', 
   b'reals;': b'ℝ', 
   b'rect;': b'▭', 
   b'reg': b'®', 
   b'reg;': b'®', 
   b'rfisht;': b'⥽', 
   b'rfloor;': b'⌋', 
   b'rfr;': b'𝔯', 
   b'rhard;': b'⇁', 
   b'rharu;': b'⇀', 
   b'rharul;': b'⥬', 
   b'rho;': b'ρ', 
   b'rhov;': b'ϱ', 
   b'rightarrow;': b'→', 
   b'rightarrowtail;': b'↣', 
   b'rightharpoondown;': b'⇁', 
   b'rightharpoonup;': b'⇀', 
   b'rightleftarrows;': b'⇄', 
   b'rightleftharpoons;': b'⇌', 
   b'rightrightarrows;': b'⇉', 
   b'rightsquigarrow;': b'↝', 
   b'rightthreetimes;': b'⋌', 
   b'ring;': b'˚', 
   b'risingdotseq;': b'≓', 
   b'rlarr;': b'⇄', 
   b'rlhar;': b'⇌', 
   b'rlm;': b'\u200f', 
   b'rmoust;': b'⎱', 
   b'rmoustache;': b'⎱', 
   b'rnmid;': b'⫮', 
   b'roang;': b'⟭', 
   b'roarr;': b'⇾', 
   b'robrk;': b'⟧', 
   b'ropar;': b'⦆', 
   b'ropf;': b'𝕣', 
   b'roplus;': b'⨮', 
   b'rotimes;': b'⨵', 
   b'rpar;': b')', 
   b'rpargt;': b'⦔', 
   b'rppolint;': b'⨒', 
   b'rrarr;': b'⇉', 
   b'rsaquo;': b'›', 
   b'rscr;': b'𝓇', 
   b'rsh;': b'↱', 
   b'rsqb;': b']', 
   b'rsquo;': b'’', 
   b'rsquor;': b'’', 
   b'rthree;': b'⋌', 
   b'rtimes;': b'⋊', 
   b'rtri;': b'▹', 
   b'rtrie;': b'⊵', 
   b'rtrif;': b'▸', 
   b'rtriltri;': b'⧎', 
   b'ruluhar;': b'⥨', 
   b'rx;': b'℞', 
   b'sacute;': b'ś', 
   b'sbquo;': b'‚', 
   b'sc;': b'≻', 
   b'scE;': b'⪴', 
   b'scap;': b'⪸', 
   b'scaron;': b'š', 
   b'sccue;': b'≽', 
   b'sce;': b'⪰', 
   b'scedil;': b'ş', 
   b'scirc;': b'ŝ', 
   b'scnE;': b'⪶', 
   b'scnap;': b'⪺', 
   b'scnsim;': b'⋩', 
   b'scpolint;': b'⨓', 
   b'scsim;': b'≿', 
   b'scy;': b'с', 
   b'sdot;': b'⋅', 
   b'sdotb;': b'⊡', 
   b'sdote;': b'⩦', 
   b'seArr;': b'⇘', 
   b'searhk;': b'⤥', 
   b'searr;': b'↘', 
   b'searrow;': b'↘', 
   b'sect': b'§', 
   b'sect;': b'§', 
   b'semi;': b';', 
   b'seswar;': b'⤩', 
   b'setminus;': b'∖', 
   b'setmn;': b'∖', 
   b'sext;': b'✶', 
   b'sfr;': b'𝔰', 
   b'sfrown;': b'⌢', 
   b'sharp;': b'♯', 
   b'shchcy;': b'щ', 
   b'shcy;': b'ш', 
   b'shortmid;': b'∣', 
   b'shortparallel;': b'∥', 
   b'shy': b'\xad', 
   b'shy;': b'\xad', 
   b'sigma;': b'σ', 
   b'sigmaf;': b'ς', 
   b'sigmav;': b'ς', 
   b'sim;': b'∼', 
   b'simdot;': b'⩪', 
   b'sime;': b'≃', 
   b'simeq;': b'≃', 
   b'simg;': b'⪞', 
   b'simgE;': b'⪠', 
   b'siml;': b'⪝', 
   b'simlE;': b'⪟', 
   b'simne;': b'≆', 
   b'simplus;': b'⨤', 
   b'simrarr;': b'⥲', 
   b'slarr;': b'←', 
   b'smallsetminus;': b'∖', 
   b'smashp;': b'⨳', 
   b'smeparsl;': b'⧤', 
   b'smid;': b'∣', 
   b'smile;': b'⌣', 
   b'smt;': b'⪪', 
   b'smte;': b'⪬', 
   b'smtes;': b'⪬︀', 
   b'softcy;': b'ь', 
   b'sol;': b'/', 
   b'solb;': b'⧄', 
   b'solbar;': b'⌿', 
   b'sopf;': b'𝕤', 
   b'spades;': b'♠', 
   b'spadesuit;': b'♠', 
   b'spar;': b'∥', 
   b'sqcap;': b'⊓', 
   b'sqcaps;': b'⊓︀', 
   b'sqcup;': b'⊔', 
   b'sqcups;': b'⊔︀', 
   b'sqsub;': b'⊏', 
   b'sqsube;': b'⊑', 
   b'sqsubset;': b'⊏', 
   b'sqsubseteq;': b'⊑', 
   b'sqsup;': b'⊐', 
   b'sqsupe;': b'⊒', 
   b'sqsupset;': b'⊐', 
   b'sqsupseteq;': b'⊒', 
   b'squ;': b'□', 
   b'square;': b'□', 
   b'squarf;': b'▪', 
   b'squf;': b'▪', 
   b'srarr;': b'→', 
   b'sscr;': b'𝓈', 
   b'ssetmn;': b'∖', 
   b'ssmile;': b'⌣', 
   b'sstarf;': b'⋆', 
   b'star;': b'☆', 
   b'starf;': b'★', 
   b'straightepsilon;': b'ϵ', 
   b'straightphi;': b'ϕ', 
   b'strns;': b'¯', 
   b'sub;': b'⊂', 
   b'subE;': b'⫅', 
   b'subdot;': b'⪽', 
   b'sube;': b'⊆', 
   b'subedot;': b'⫃', 
   b'submult;': b'⫁', 
   b'subnE;': b'⫋', 
   b'subne;': b'⊊', 
   b'subplus;': b'⪿', 
   b'subrarr;': b'⥹', 
   b'subset;': b'⊂', 
   b'subseteq;': b'⊆', 
   b'subseteqq;': b'⫅', 
   b'subsetneq;': b'⊊', 
   b'subsetneqq;': b'⫋', 
   b'subsim;': b'⫇', 
   b'subsub;': b'⫕', 
   b'subsup;': b'⫓', 
   b'succ;': b'≻', 
   b'succapprox;': b'⪸', 
   b'succcurlyeq;': b'≽', 
   b'succeq;': b'⪰', 
   b'succnapprox;': b'⪺', 
   b'succneqq;': b'⪶', 
   b'succnsim;': b'⋩', 
   b'succsim;': b'≿', 
   b'sum;': b'∑', 
   b'sung;': b'♪', 
   b'sup1': b'¹', 
   b'sup1;': b'¹', 
   b'sup2': b'²', 
   b'sup2;': b'²', 
   b'sup3': b'³', 
   b'sup3;': b'³', 
   b'sup;': b'⊃', 
   b'supE;': b'⫆', 
   b'supdot;': b'⪾', 
   b'supdsub;': b'⫘', 
   b'supe;': b'⊇', 
   b'supedot;': b'⫄', 
   b'suphsol;': b'⟉', 
   b'suphsub;': b'⫗', 
   b'suplarr;': b'⥻', 
   b'supmult;': b'⫂', 
   b'supnE;': b'⫌', 
   b'supne;': b'⊋', 
   b'supplus;': b'⫀', 
   b'supset;': b'⊃', 
   b'supseteq;': b'⊇', 
   b'supseteqq;': b'⫆', 
   b'supsetneq;': b'⊋', 
   b'supsetneqq;': b'⫌', 
   b'supsim;': b'⫈', 
   b'supsub;': b'⫔', 
   b'supsup;': b'⫖', 
   b'swArr;': b'⇙', 
   b'swarhk;': b'⤦', 
   b'swarr;': b'↙', 
   b'swarrow;': b'↙', 
   b'swnwar;': b'⤪', 
   b'szlig': b'ß', 
   b'szlig;': b'ß', 
   b'target;': b'⌖', 
   b'tau;': b'τ', 
   b'tbrk;': b'⎴', 
   b'tcaron;': b'ť', 
   b'tcedil;': b'ţ', 
   b'tcy;': b'т', 
   b'tdot;': b'⃛', 
   b'telrec;': b'⌕', 
   b'tfr;': b'𝔱', 
   b'there4;': b'∴', 
   b'therefore;': b'∴', 
   b'theta;': b'θ', 
   b'thetasym;': b'ϑ', 
   b'thetav;': b'ϑ', 
   b'thickapprox;': b'≈', 
   b'thicksim;': b'∼', 
   b'thinsp;': b'\u2009', 
   b'thkap;': b'≈', 
   b'thksim;': b'∼', 
   b'thorn': b'þ', 
   b'thorn;': b'þ', 
   b'tilde;': b'˜', 
   b'times': b'×', 
   b'times;': b'×', 
   b'timesb;': b'⊠', 
   b'timesbar;': b'⨱', 
   b'timesd;': b'⨰', 
   b'tint;': b'∭', 
   b'toea;': b'⤨', 
   b'top;': b'⊤', 
   b'topbot;': b'⌶', 
   b'topcir;': b'⫱', 
   b'topf;': b'𝕥', 
   b'topfork;': b'⫚', 
   b'tosa;': b'⤩', 
   b'tprime;': b'‴', 
   b'trade;': b'™', 
   b'triangle;': b'▵', 
   b'triangledown;': b'▿', 
   b'triangleleft;': b'◃', 
   b'trianglelefteq;': b'⊴', 
   b'triangleq;': b'≜', 
   b'triangleright;': b'▹', 
   b'trianglerighteq;': b'⊵', 
   b'tridot;': b'◬', 
   b'trie;': b'≜', 
   b'triminus;': b'⨺', 
   b'triplus;': b'⨹', 
   b'trisb;': b'⧍', 
   b'tritime;': b'⨻', 
   b'trpezium;': b'⏢', 
   b'tscr;': b'𝓉', 
   b'tscy;': b'ц', 
   b'tshcy;': b'ћ', 
   b'tstrok;': b'ŧ', 
   b'twixt;': b'≬', 
   b'twoheadleftarrow;': b'↞', 
   b'twoheadrightarrow;': b'↠', 
   b'uArr;': b'⇑', 
   b'uHar;': b'⥣', 
   b'uacute': b'ú', 
   b'uacute;': b'ú', 
   b'uarr;': b'↑', 
   b'ubrcy;': b'ў', 
   b'ubreve;': b'ŭ', 
   b'ucirc': b'û', 
   b'ucirc;': b'û', 
   b'ucy;': b'у', 
   b'udarr;': b'⇅', 
   b'udblac;': b'ű', 
   b'udhar;': b'⥮', 
   b'ufisht;': b'⥾', 
   b'ufr;': b'𝔲', 
   b'ugrave': b'ù', 
   b'ugrave;': b'ù', 
   b'uharl;': b'↿', 
   b'uharr;': b'↾', 
   b'uhblk;': b'▀', 
   b'ulcorn;': b'⌜', 
   b'ulcorner;': b'⌜', 
   b'ulcrop;': b'⌏', 
   b'ultri;': b'◸', 
   b'umacr;': b'ū', 
   b'uml': b'¨', 
   b'uml;': b'¨', 
   b'uogon;': b'ų', 
   b'uopf;': b'𝕦', 
   b'uparrow;': b'↑', 
   b'updownarrow;': b'↕', 
   b'upharpoonleft;': b'↿', 
   b'upharpoonright;': b'↾', 
   b'uplus;': b'⊎', 
   b'upsi;': b'υ', 
   b'upsih;': b'ϒ', 
   b'upsilon;': b'υ', 
   b'upuparrows;': b'⇈', 
   b'urcorn;': b'⌝', 
   b'urcorner;': b'⌝', 
   b'urcrop;': b'⌎', 
   b'uring;': b'ů', 
   b'urtri;': b'◹', 
   b'uscr;': b'𝓊', 
   b'utdot;': b'⋰', 
   b'utilde;': b'ũ', 
   b'utri;': b'▵', 
   b'utrif;': b'▴', 
   b'uuarr;': b'⇈', 
   b'uuml': b'ü', 
   b'uuml;': b'ü', 
   b'uwangle;': b'⦧', 
   b'vArr;': b'⇕', 
   b'vBar;': b'⫨', 
   b'vBarv;': b'⫩', 
   b'vDash;': b'⊨', 
   b'vangrt;': b'⦜', 
   b'varepsilon;': b'ϵ', 
   b'varkappa;': b'ϰ', 
   b'varnothing;': b'∅', 
   b'varphi;': b'ϕ', 
   b'varpi;': b'ϖ', 
   b'varpropto;': b'∝', 
   b'varr;': b'↕', 
   b'varrho;': b'ϱ', 
   b'varsigma;': b'ς', 
   b'varsubsetneq;': b'⊊︀', 
   b'varsubsetneqq;': b'⫋︀', 
   b'varsupsetneq;': b'⊋︀', 
   b'varsupsetneqq;': b'⫌︀', 
   b'vartheta;': b'ϑ', 
   b'vartriangleleft;': b'⊲', 
   b'vartriangleright;': b'⊳', 
   b'vcy;': b'в', 
   b'vdash;': b'⊢', 
   b'vee;': b'∨', 
   b'veebar;': b'⊻', 
   b'veeeq;': b'≚', 
   b'vellip;': b'⋮', 
   b'verbar;': b'|', 
   b'vert;': b'|', 
   b'vfr;': b'𝔳', 
   b'vltri;': b'⊲', 
   b'vnsub;': b'⊂⃒', 
   b'vnsup;': b'⊃⃒', 
   b'vopf;': b'𝕧', 
   b'vprop;': b'∝', 
   b'vrtri;': b'⊳', 
   b'vscr;': b'𝓋', 
   b'vsubnE;': b'⫋︀', 
   b'vsubne;': b'⊊︀', 
   b'vsupnE;': b'⫌︀', 
   b'vsupne;': b'⊋︀', 
   b'vzigzag;': b'⦚', 
   b'wcirc;': b'ŵ', 
   b'wedbar;': b'⩟', 
   b'wedge;': b'∧', 
   b'wedgeq;': b'≙', 
   b'weierp;': b'℘', 
   b'wfr;': b'𝔴', 
   b'wopf;': b'𝕨', 
   b'wp;': b'℘', 
   b'wr;': b'≀', 
   b'wreath;': b'≀', 
   b'wscr;': b'𝓌', 
   b'xcap;': b'⋂', 
   b'xcirc;': b'◯', 
   b'xcup;': b'⋃', 
   b'xdtri;': b'▽', 
   b'xfr;': b'𝔵', 
   b'xhArr;': b'⟺', 
   b'xharr;': b'⟷', 
   b'xi;': b'ξ', 
   b'xlArr;': b'⟸', 
   b'xlarr;': b'⟵', 
   b'xmap;': b'⟼', 
   b'xnis;': b'⋻', 
   b'xodot;': b'⨀', 
   b'xopf;': b'𝕩', 
   b'xoplus;': b'⨁', 
   b'xotime;': b'⨂', 
   b'xrArr;': b'⟹', 
   b'xrarr;': b'⟶', 
   b'xscr;': b'𝓍', 
   b'xsqcup;': b'⨆', 
   b'xuplus;': b'⨄', 
   b'xutri;': b'△', 
   b'xvee;': b'⋁', 
   b'xwedge;': b'⋀', 
   b'yacute': b'ý', 
   b'yacute;': b'ý', 
   b'yacy;': b'я', 
   b'ycirc;': b'ŷ', 
   b'ycy;': b'ы', 
   b'yen': b'¥', 
   b'yen;': b'¥', 
   b'yfr;': b'𝔶', 
   b'yicy;': b'ї', 
   b'yopf;': b'𝕪', 
   b'yscr;': b'𝓎', 
   b'yucy;': b'ю', 
   b'yuml': b'ÿ', 
   b'yuml;': b'ÿ', 
   b'zacute;': b'ź', 
   b'zcaron;': b'ž', 
   b'zcy;': b'з', 
   b'zdot;': b'ż', 
   b'zeetrf;': b'ℨ', 
   b'zeta;': b'ζ', 
   b'zfr;': b'𝔷', 
   b'zhcy;': b'ж', 
   b'zigrarr;': b'⇝', 
   b'zopf;': b'𝕫', 
   b'zscr;': b'𝓏', 
   b'zwj;': b'\u200d', 
   b'zwnj;': b'\u200c'}
replacementCharacters = {0: b'�', 
   13: b'\r', 
   128: b'€', 
   129: b'\x81', 
   130: b'‚', 
   131: b'ƒ', 
   132: b'„', 
   133: b'…', 
   134: b'†', 
   135: b'‡', 
   136: b'ˆ', 
   137: b'‰', 
   138: b'Š', 
   139: b'‹', 
   140: b'Œ', 
   141: b'\x8d', 
   142: b'Ž', 
   143: b'\x8f', 
   144: b'\x90', 
   145: b'’', 
   146: b'’', 
   147: b'“', 
   148: b'”', 
   149: b'•', 
   150: b'–', 
   151: b'—', 
   152: b'˜', 
   153: b'™', 
   154: b'š', 
   155: b'›', 
   156: b'œ', 
   157: b'\x9d', 
   158: b'ž', 
   159: b'Ÿ'}
tokenTypes = {b'Doctype': 0, 
   b'Characters': 1, 
   b'SpaceCharacters': 2, 
   b'StartTag': 3, 
   b'EndTag': 4, 
   b'EmptyTag': 5, 
   b'Comment': 6, 
   b'ParseError': 7}
tagTokenTypes = frozenset([tokenTypes[b'StartTag'], tokenTypes[b'EndTag'],
 tokenTypes[b'EmptyTag']])
prefixes = dict([ (v, k) for k, v in namespaces.items() ])
prefixes[b'http://www.w3.org/1998/Math/MathML'] = b'math'

class DataLossWarning(UserWarning):
    """Raised when the current tree is unable to represent the input data"""
    pass


class _ReparseException(Exception):
    pass