# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\vtpl_api\models\engine_task_zone_setting.py
# Compiled at: 2019-11-14 01:19:39
# Size of source mod 2**32: 4874 bytes
"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""
import pprint, re, six

class EngineTaskZoneSetting(object):
    __doc__ = 'NOTE: This class is auto generated by OpenAPI Generator.\n    Ref: https://openapi-generator.tech\n\n    Do not edit the class manually.\n    '
    openapi_types = {'reference_width':'int', 
     'reference_height':'int', 
     'zones':'list[Zone]'}
    attribute_map = {'reference_width':'referenceWidth', 
     'reference_height':'referenceHeight', 
     'zones':'zones'}

    def __init__(self, reference_width=None, reference_height=None, zones=None):
        """EngineTaskZoneSetting - a model defined in OpenAPI"""
        self._reference_width = None
        self._reference_height = None
        self._zones = None
        self.discriminator = None
        if reference_width is not None:
            self.reference_width = reference_width
        if reference_height is not None:
            self.reference_height = reference_height
        if zones is not None:
            self.zones = zones

    @property
    def reference_width(self):
        """Gets the reference_width of this EngineTaskZoneSetting.  # noqa: E501

        Reference width on which zones are relevent  # noqa: E501

        :return: The reference_width of this EngineTaskZoneSetting.  # noqa: E501
        :rtype: int
        """
        return self._reference_width

    @reference_width.setter
    def reference_width(self, reference_width):
        """Sets the reference_width of this EngineTaskZoneSetting.

        Reference width on which zones are relevent  # noqa: E501

        :param reference_width: The reference_width of this EngineTaskZoneSetting.  # noqa: E501
        :type: int
        """
        self._reference_width = reference_width

    @property
    def reference_height(self):
        """Gets the reference_height of this EngineTaskZoneSetting.  # noqa: E501

        Reference height on which zones are relevent  # noqa: E501

        :return: The reference_height of this EngineTaskZoneSetting.  # noqa: E501
        :rtype: int
        """
        return self._reference_height

    @reference_height.setter
    def reference_height(self, reference_height):
        """Sets the reference_height of this EngineTaskZoneSetting.

        Reference height on which zones are relevent  # noqa: E501

        :param reference_height: The reference_height of this EngineTaskZoneSetting.  # noqa: E501
        :type: int
        """
        self._reference_height = reference_height

    @property
    def zones(self):
        """Gets the zones of this EngineTaskZoneSetting.  # noqa: E501

        :return: The zones of this EngineTaskZoneSetting.  # noqa: E501
        :rtype: list[Zone]
        """
        return self._zones

    @zones.setter
    def zones(self, zones):
        """Sets the zones of this EngineTaskZoneSetting.

        :param zones: The zones of this EngineTaskZoneSetting.  # noqa: E501
        :type: list[Zone]
        """
        self._zones = zones

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}
        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x:                 if hasattr(x, 'to_dict'):
x.to_dict() # Avoid dead code: x, value))
            elif hasattr(value, 'to_dict'):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item:                 if hasattr(item[1], 'to_dict'):
(item[0], item[1].to_dict()) # Avoid dead code: item, value.items()))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EngineTaskZoneSetting):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other