# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\vtpl_api\models\links_self_self.py
# Compiled at: 2019-11-14 01:19:39
# Size of source mod 2**32: 3428 bytes
"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""
import pprint, re, six

class LinksSelfSelf(object):
    __doc__ = 'NOTE: This class is auto generated by OpenAPI Generator.\n    Ref: https://openapi-generator.tech\n\n    Do not edit the class manually.\n    '
    openapi_types = {'title':'str', 
     'href':'str'}
    attribute_map = {'title':'title', 
     'href':'href'}

    def __init__(self, title=None, href=None):
        """LinksSelfSelf - a model defined in OpenAPI"""
        self._title = None
        self._href = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if href is not None:
            self.href = href

    @property
    def title(self):
        """Gets the title of this LinksSelfSelf.  # noqa: E501

        :return: The title of this LinksSelfSelf.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this LinksSelfSelf.

        :param title: The title of this LinksSelfSelf.  # noqa: E501
        :type: str
        """
        self._title = title

    @property
    def href(self):
        """Gets the href of this LinksSelfSelf.  # noqa: E501

        :return: The href of this LinksSelfSelf.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this LinksSelfSelf.

        :param href: The href of this LinksSelfSelf.  # noqa: E501
        :type: str
        """
        self._href = href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}
        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x:                 if hasattr(x, 'to_dict'):
x.to_dict() # Avoid dead code: x, value))
            elif hasattr(value, 'to_dict'):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item:                 if hasattr(item[1], 'to_dict'):
(item[0], item[1].to_dict()) # Avoid dead code: item, value.items()))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinksSelfSelf):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other