# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/sw_logger/consts.py
# Compiled at: 2018-02-07 05:07:39
ACTION_CREATED = 'created'
ACTION_UPDATED = 'updated'
ACTION_DELETED = 'deleted'
ACTION_OTHER = 'other'
ACTION_CHOICES = (
 (
  ACTION_CREATED, ACTION_CREATED),
 (
  ACTION_UPDATED, ACTION_UPDATED),
 (
  ACTION_DELETED, ACTION_DELETED),
 (
  ACTION_OTHER, ACTION_OTHER))
LOG_LEVEL_CRITICAL = 'CRITICAL'
LOG_LEVEL_ERROR = 'ERROR'
LOG_LEVEL_WARNING = 'WARNING'
LOG_LEVEL_INFO = 'INFO'
LOG_LEVEL_DEBUG = 'DEBUG'
LOG_LEVEL_NOTSET = 'NOTSET'
LOG_LEVEL_CHOICES = (
 (
  LOG_LEVEL_CRITICAL, LOG_LEVEL_CRITICAL),
 (
  LOG_LEVEL_ERROR, LOG_LEVEL_ERROR),
 (
  LOG_LEVEL_WARNING, LOG_LEVEL_WARNING),
 (
  LOG_LEVEL_INFO, LOG_LEVEL_INFO),
 (
  LOG_LEVEL_DEBUG, LOG_LEVEL_DEBUG),
 (
  LOG_LEVEL_NOTSET, LOG_LEVEL_NOTSET))