# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.9-x86_64/egg/amundsen_common/models/index_map.py
# Compiled at: 2020-04-10 11:06:25
# Size of source mod 2**32: 3542 bytes
import textwrap
TABLE_INDEX_MAP = textwrap.dedent('\n    {\n    "mappings":{\n        "table":{\n          "properties": {\n            "name": {\n              "type":"text",\n              "analyzer": "simple",\n              "fields": {\n                "raw": {\n                  "type": "keyword"\n                }\n              }\n            },\n            "schema": {\n              "type":"text",\n              "analyzer": "simple",\n              "fields": {\n                "raw": {\n                  "type": "keyword"\n                }\n              }\n            },\n            "display_name": {\n              "type": "keyword"\n            },\n            "last_updated_timestamp": {\n              "type": "date",\n              "format": "epoch_second"\n            },\n            "description": {\n              "type": "text",\n              "analyzer": "simple"\n            },\n            "column_names": {\n              "type":"text",\n              "analyzer": "simple",\n              "fields": {\n                "raw": {\n                  "type": "keyword"\n                }\n              }\n            },\n            "column_descriptions": {\n              "type": "text",\n              "analyzer": "simple"\n            },\n            "tags": {\n              "type": "keyword"\n            },\n            "badges": {\n              "type": "keyword"\n            },\n            "cluster": {\n              "type": "text"\n            },\n            "database": {\n              "type": "text",\n              "analyzer": "simple",\n              "fields": {\n                "raw": {\n                  "type": "keyword"\n                }\n              }\n            },\n            "key": {\n              "type": "keyword"\n            },\n            "total_usage":{\n              "type": "long"\n            },\n            "unique_usage": {\n              "type": "long"\n            }\n          }\n        }\n      }\n    }\n    ')
USER_INDEX_MAP = textwrap.dedent('\n{\n"mappings":{\n    "user":{\n      "properties": {\n        "email": {\n          "type":"text",\n          "analyzer": "simple",\n          "fields": {\n            "raw": {\n              "type": "keyword"\n            }\n          }\n        },\n        "first_name": {\n          "type":"text",\n          "analyzer": "simple",\n          "fields": {\n            "raw": {\n              "type": "keyword"\n            }\n          }\n        },\n        "last_name": {\n          "type":"text",\n          "analyzer": "simple",\n          "fields": {\n            "raw": {\n              "type": "keyword"\n            }\n          }\n        },\n        "name": {\n          "type":"text",\n          "analyzer": "simple",\n          "fields": {\n            "raw": {\n              "type": "keyword"\n            }\n          }\n        },\n        "total_read":{\n          "type": "long"\n        },\n        "total_own": {\n          "type": "long"\n        },\n        "total_follow": {\n          "type": "long"\n        }\n      }\n    }\n  }\n}')