from setuptools import setup

setup(name='yollapay',
      version='0.0.4',
      description="The gateway to pay.",
      long_description="",
      classifiers=["Development Status :: 2 - Pre-Alpha",
                   "Environment :: Console",
                   "Intended Audience :: Developers",
                   "License :: OSI Approved :: Apache Software License",
                   "Programming Language :: Python",
                   "Programming Language :: Python :: 2",
                   "Programming Language :: Python :: 3",
                   "Topic :: Office/Business :: Financial"],
      keywords='payment gateway pay credit card check processing',
      author='@yollapay',
      author_email='hello@yollapay.com',
      url='https://github.com/yollapay/yollapay-py',
      license='Apache v2',
      packages=["yollapay"],
      include_package_data=True,
      zip_safe=True,
      install_requires=["requests==2.0.0",
                        "valideer==0.3",
                        "timestring==1.4.4"],
      entry_points={'console_scripts': ['yollapay=yollapay.yollapay:main']})
