# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\mappyfile\tokens.py
# Compiled at: 2020-01-11 08:01:06
COMPOSITE_NAMES = frozenset(('\n    align\n    anchorpoint\n    angle\n    antialias\n    backgroundcolor\n    bandsitem\n    bindvals\n    browseformat\n    buffer\n    character\n    class\n    classitem\n    classgroup\n    color\n    compfilter\n    composite\n    compop\n    config\n    connection\n    connectiontype\n    data\n    datapattern\n    debug\n    driver\n    dump\n    empty\n    encoding\n    end\n    error\n    expression\n    extent\n    extension\n    feature\n    filled\n    filter\n    filteritem\n    footer\n    font\n    fontset\n    force\n    formatoption\n    from\n    gap\n    geomtransform\n    grid\n    gridstep\n    graticule\n    group\n    header\n    image\n    imagecolor\n    imagetype\n    imagequality\n    imagemode\n    imagepath\n    temppath\n    imageurl\n    include\n    index\n    initialgap\n    interlace\n    intervals\n    join\n    keyimage\n    keysize\n    keyspacing\n    label\n    labelcache\n    labelformat\n    labelitem\n    labelmaxscale\n    labelmaxscaledenom\n    labelminscale\n    labelminscaledenom\n    labelrequires\n    latlon\n    layer\n    leader\n    legendformat\n    linecap\n    linejoin\n    linejoinmaxsize\n    log\n    map\n    marker\n    markersize\n    mask\n    maxarcs\n    maxboxsize\n    maxdistance\n    maxfeatures\n    maxinterval\n    maxscale\n    maxscaledenom\n    maxgeowidth\n    maxlength\n    maxsize\n    maxsubdivide\n    maxtemplate\n    maxwidth\n\n    mimetype\n    minarcs\n    minboxsize\n    mindistance\n    repeatdistance\n    maxoverlapangle\n    minfeaturesize\n    mininterval\n    minscale\n    minscaledenom\n    mingeowidth\n    minlength\n    minsize\n    minsubdivide\n    mintemplate\n    minwidth\n    name\n    offset\n    offsite\n    opacity\n    outlinecolor\n    outlinewidth\n    outputformat\n    overlaybackgroundcolor\n    overlaycolor\n    overlaymaxsize\n    overlayminsize\n    overlayoutlinecolor\n    overlaysize\n    overlaysymbol\n    partials\n    pattern\n    points\n    items\n    position\n    postlabelcache\n    priority\n    processing\n    projection\n    queryformat\n    reference\n    region\n    relativeto\n    requires\n    resolution\n    defresolution\n    scale\n    scaledenom\n    scaletoken\n    shadowcolor\n    shadowsize\n    shapepath\n    size\n    sizeunits\n    status\n    style\n    styleitem\n    symbol\n    symbolscale\n    symbolscaledenom\n    symbolset\n    table\n    template\n    templatepattern\n    text\n    tileindex\n    tileitem\n    tilesrs\n    title\n    to\n    tolerance\n    toleranceunits\n    transparency\n    transparent\n    transform\n    type\n    units\n    utfdata\n    utfitem\n\n\n\n    width\n    wkt\n    wrap\n').split())
SINGLETON_COMPOSITE_NAMES = frozenset(('\n    cluster\n    connectionoptions\n    grid\n    leader\n    legend\n    metadata\n    pattern\n    projection\n    querymap\n    reference\n    scalebar\n    validation\n    values\n    web\n').split())
ATTRIBUTE_NAMES = frozenset(('\narea\nlength\ntostring\ncommify\nround\nupper\nlower\ninitcap\nfirstcap\n\nbuffer\ndifference\nsimplify\nsimplifypt\ngeneralize\nsmoothsia\njavascript\n\nintersects\ndisjoint\ntouches\noverlaps\ncrosses\nwithin\ncontains\nequals\nbeyond\ndwithin\n\nfromtext\n\ntrue\nfalse\n\ncolorrange\ndatarange\nrangeitem\n\n\nannotation\nauto\nauto2\nbevel\nbitmap\nbutt\ncc\ncenter\nchart\ncircle\ncl\ncr\ncsv\npostgresql\nmysql\ndefault\ndd\nellipse\nembed\nfalse\nfeet\nfollow\ngiant\nhatch\nkerneldensity\nhilite\ninches\nkilometers\nlarge\nlc\nleft\nline\nll\nlr\nmedium\nmeters\nnauticalmiles\nmiles\nmiter\nmultiple\nnone\nnormal\noff\nogr\non\none-to-one\none-to-many\noraclespatial\npercentages\npixmap\npixels\npoint\npolygon\npostgis\nplugin\nquery\nraster\nright\nround\nselected\nsimple\nsingle\nsmall\nsquare\nsvg\npolaroffset\ntiny\ntriangle\ntrue\ntruetype\nuc\nul\nur\nunion\nuvraster\ncontour\nvector\nwfs\nwms\n\nqstring\nbase\ndefault_base\nows_onlineresource\nows_srs\nows_enable_request\nms_errorfile\n').split()) | COMPOSITE_NAMES
REPEATED_KEYS = ('processing', 'formatoption', 'include', 'data')