# uncompyle6 version 3.7.4
# Python bytecode 2.4 (62061)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-i686/egg/cblog/templates/featured.py
# Compiled at: 2006-12-08 09:21:52
import sys, os, os.path
from os.path import getmtime, exists
import time, types, __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters, Cheetah.ErrorCatchers as ErrorCatchers
from cblog.templates.SiteTemplate import SiteTemplate
try:
    (
     True, False)
except NameError:
    True, False = 1 == 1, 1 == 0

VFFSL = valueFromFrameOrSearchList
VFSL = valueFromSearchList
VFN = valueForName
currentTime = time.time
__CHEETAH_version__ = '2.0rc7'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 7)
__CHEETAH_genTime__ = 1165587712.78116
__CHEETAH_genTimestamp__ = 'Fri Dec  8 15:21:52 2006'
__CHEETAH_src__ = 'featured.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Dec  8 14:43:37 2006'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError('This template was compiled with Cheetah version %s. Templates compiled before version %s must be recompiled.' % (__CHEETAH_version__, RequiredCheetahVersion))

class featured(SiteTemplate):
    __module__ = __name__

    def __init__(self, *args, **KWs):
        SiteTemplate.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = ('searchList namespaces filter filtersLib errorCatcher').split()
            for (k, v) in KWs.items():
                if k in allowedKWs:
                    cheetahKWArgs[k] = v

            self._initCheetahInstance(**cheetahKWArgs)

    def pagetitle(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('  <title>')
        _v = VFFSL(SL, 'tg.blogtitle', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${tg.blogtitle}'))
        write(': Featured articles</title>\n')
        return _dummyTrans and trans.response().getvalue() or ''

    def pagecontent(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('<h1>Featured articles</h1>\n\n<p class="firstpar">This is a list of posts that are still worth reading, even if they have disappeared from the frontpage already. Mostly somewhat longer articles.</p>\n\n')
        items = VFN(VFFSL(SL, 'tg', False), 'ipeek', False)(VFFSL(SL, 'reviews', False))
        write('\n<div class="blogroll">\n')
        if items:
            for review in VFFSL(SL, 'items', False):
                write('  <div class="article">\n    <h1 class="title"><a href="')
                _v = VFN(VFFSL(SL, 'tg', False), 'url', False)('/article/%s' % review.entry.id)
                if _v is not None:
                    write(_filter(_v, rawExpr="${tg.url('/article/%s' % review.entry.id)}"))
                write('"\n      >')
                _v = VFFSL(SL, 'review.entry.title', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${review.entry.title}'))
                write('</a></h1>\n\n    <p class="byline">posted by <span\n      class="author">')
                _v = VFFSL(SL, 'review.entry.author.display_name', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${review.entry.author.display_name}'))
                write('</span> on\n      <span class="date">')
                _v = VFN(VFFSL(SL, 'tg', False), 'format_date', False)(VFFSL(SL, 'review.entry.created', False))
                if _v is not None:
                    write(_filter(_v, rawExpr='${tg.format_date($review.entry.created)}'))
                write('</span> in\n      <span class="tags">')
                _v = VFN(VFFSL(SL, 'tg', False), 'format_tags', False)(VFFSL(SL, 'review.entry.tags', False))
                if _v is not None:
                    write(_filter(_v, rawExpr='${tg.format_tags($review.entry.tags)}'))
                write('</span>\n      (recommended by <span class="author">')
                _v = VFFSL(SL, 'review.author.display_name', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${review.author.display_name}'))
                write('</span>)\n    </p>\n\n    <p class="eteaser">')
                _v = VFFSL(SL, 'review.html_text', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${review.html_text}'))
                write('</p>\n\n    <p><a class="readon" href="')
                _v = VFN(VFFSL(SL, 'tg', False), 'url', False)('/article/%s' % VFFSL(SL, 'review.entry.id', False))
                if _v is not None:
                    write(_filter(_v, rawExpr="${tg.url('/article/%s' % $review.entry.id)}"))
                write('"\n      >Read featured article &hellip;</a></p>\n\n  </div>\n')

            write('\n')
        else:
            write('<p>No featured articles found.</p>\n')
        write('</div>\n')
        return _dummyTrans and trans.response().getvalue() or ''

    def writeBody(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('\n\n\n')
        return _dummyTrans and trans.response().getvalue() or ''

    _CHEETAH__instanceInitialized = False
    _CHEETAH_version = __CHEETAH_version__
    _CHEETAH_versionTuple = __CHEETAH_versionTuple__
    _CHEETAH_genTime = __CHEETAH_genTime__
    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__
    _CHEETAH_src = __CHEETAH_src__
    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__
    _mainCheetahMethod_for_featured = 'writeBody'


if not hasattr(featured, '_initCheetahAttributes'):
    templateAPIClass = getattr(featured, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(featured)
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=featured()).run()