# uncompyle6 version 3.7.4
# Python bytecode 2.4 (62061)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-i686/egg/cblog/templates/view.py
# Compiled at: 2006-12-08 09:21:53
import sys, os, os.path
from os.path import getmtime, exists
import time, types, __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters, Cheetah.ErrorCatchers as ErrorCatchers
from cblog.templates.SiteTemplate import SiteTemplate
try:
    (
     True, False)
except NameError:
    True, False = 1 == 1, 1 == 0

VFFSL = valueFromFrameOrSearchList
VFSL = valueFromSearchList
VFN = valueForName
currentTime = time.time
__CHEETAH_version__ = '2.0rc7'
__CHEETAH_versionTuple__ = (2, 0, 0, 'candidate', 7)
__CHEETAH_genTime__ = 1165587713.032932
__CHEETAH_genTimestamp__ = 'Fri Dec  8 15:21:53 2006'
__CHEETAH_src__ = 'view.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Dec  8 15:21:39 2006'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError('This template was compiled with Cheetah version %s. Templates compiled before version %s must be recompiled.' % (__CHEETAH_version__, RequiredCheetahVersion))

class view(SiteTemplate):
    __module__ = __name__

    def __init__(self, *args, **KWs):
        SiteTemplate.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = ('searchList namespaces filter filtersLib errorCatcher').split()
            for (k, v) in KWs.items():
                if k in allowedKWs:
                    cheetahKWArgs[k] = v

            self._initCheetahInstance(**cheetahKWArgs)

    def pagetitle(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('  <title>')
        _v = VFFSL(SL, 'tg.blogtitle', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${tg.blogtitle}'))
        write(': ')
        _v = VFFSL(SL, 'entry.title', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${entry.title}'))
        write('</title>\n')
        return _dummyTrans and trans.response().getvalue() or ''

    def pagecontent(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('<div id="detailview">\n\n  <p id="commentlink"><a href="#" class="show_commentlink">Add a comment</a></p>\n\n  <div class="article">\n    <h1 class="title">')
        _v = VFFSL(SL, 'entry.title', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${entry.title}'))
        write('</h1>\n\n')
        if VFFSL(SL, 'comment_form', False):
            write('    ')
            _v = VFFSL(SL, 'comment_form', False)(value=dict(id=VFFSL(SL, 'entry.id', False)), submit_text=_('Add Comment'), action=VFN(VFFSL(SL, 'tg', False), 'url', False)('/add_comment'), form_attrs=dict(id='commentform'))
            if _v is not None:
                write(_filter(_v, rawExpr="${comment_form(value=dict(id=$entry.id),\n      submit_text=_(u'Add Comment'),\n      action=$tg.url('/add_comment'),\n      form_attrs=dict(id='commentform'))}"))
            write('\n')
        write('\n')
        if VFFSL(SL, 'tg.identity.user_name', False) == VFFSL(SL, 'entry.author.user_name', False):
            write('    <p class="actionlinks">\n      <a href="')
            _v = VFN(VFFSL(SL, 'tg', False), 'url', False)('/edit_article/%i') % VFFSL(SL, 'entry.id', False)
            if _v is not None:
                write(_filter(_v, rawExpr="${tg.url('/edit_article/%i') % $entry.id}"))
            write('">Edit article</a>\n    </p>\n')
        write('\n    <p class="byline"><a href="')
        _v = VFN(VFFSL(SL, 'tg', False), 'url', False)('/article/%s' % VFFSL(SL, 'entry.id', False))
        if _v is not None:
            write(_filter(_v, rawExpr="${tg.url('/article/%s' % $entry.id)}"))
        write('">#</a>\n      posted by <span\n      class="author">')
        _v = VFFSL(SL, 'entry.author.display_name', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${entry.author.display_name}'))
        write('</span> on\n      <span class="date">')
        _v = VFN(VFFSL(SL, 'tg', False), 'format_date', False)(VFFSL(SL, 'entry.created', False))
        if _v is not None:
            write(_filter(_v, rawExpr='${tg.format_date($entry.created)}'))
        write('</span> in\n      <span class="tags">')
        _v = VFN(VFFSL(SL, 'tg', False), 'format_tags', False)(VFFSL(SL, 'entry.tags', False))
        if _v is not None:
            write(_filter(_v, rawExpr='${tg.format_tags($entry.tags)}'))
        write('</span></p>\n\n    ')
        _v = VFFSL(SL, 'entry.html_text', False)
        if _v is not None:
            write(_filter(_v, rawExpr='${entry.html_text}'))
        write('\n  </div>\n\n  <div id="comments">\n')
        items = VFN(VFFSL(SL, 'tg', False), 'ipeek', False)(VFFSL(SL, 'comments', False))
        count = VFFSL(SL, 'entry.comment_count', False)
        if VFFSL(SL, 'items', False):
            write('    <div class="header">\n      <a name="comments"></a><h2>Reader comments</h2>\n\n      <p>There are ')
            _v = VFFSL(SL, 'count', False)
            if _v is not None:
                write(_filter(_v, rawExpr='${count}'))
            write(' comment')
            if VFFSL(SL, 'count', False) != 1:
                write('s')
            write(' on this article.\n      <a href="#" class="show_commentlink">Add a comment now...</a></p>\n    </div>\n\n')
            for (cnum, comment) in enumerate(VFFSL(SL, 'items', False)):
                authorcomment = VFFSL(SL, 'comment.email', False) == VFFSL(SL, 'entry.author.email_address', False)
                write('      <div class="comment')
                if VFFSL(SL, 'authorcomment', False):
                    write(' authorcomment')
                write('">\n\n')
                if VFN(VFFSL(SL, 'tg', False), 'config', False)('gravatars.show', False):
                    write('        ')
                    _v = VFN(VFFSL(SL, 'tg_gravatar', False), 'display', False)(VFFSL(SL, 'comment.email', False))
                    if _v is not None:
                        write(_filter(_v, rawExpr='${tg_gravatar.display($comment.email)}'))
                    write('\n')
                write('\n        <p class="byline">\n          <a class="num" href="#comment-')
                _v = VFFSL(SL, 'comment.id', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${comment.id}'))
                write('">')
                _v = VFFSL(SL, 'cnum', False) + 1
                if _v is not None:
                    write(_filter(_v, rawExpr='${cnum+1}'))
                write('</a>\n          <a name="comment-')
                _v = VFFSL(SL, 'comment.id', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${comment.id}'))
                write('"></a>\n          <span class="author">')
                _v = VFN(VFFSL(SL, 'tg', False), 'format_author', False)(comment)
                if _v is not None:
                    write(_filter(_v, rawExpr='${tg.format_author(comment)}'))
                write('</span>\n          said on\n          <span class="date">')
                _v = VFN(VFFSL(SL, 'tg', False), 'format_date', False)(comment.created)
                if _v is not None:
                    write(_filter(_v, rawExpr='${tg.format_date(comment.created)}'))
                write('</span>:</p>\n\n        <div class="text">\n          ')
                _v = VFFSL(SL, 'comment.html_text', False)
                if _v is not None:
                    write(_filter(_v, rawExpr='${comment.html_text}'))
                write('\n        </div>\n\n      </div>\n')

        else:
            write('    <div class="header">\n      <a name="comments"></a><h2>Reader comments</h2>\n\n      <p><a name="comments"></a>There are no comments on this article yet.\n      <a href="#" class="show_commentlink">Add a comment now...</a></p>\n    </div>\n')
        write('\n  </div>\n</div>\n')
        return _dummyTrans and trans.response().getvalue() or ''

    def writeBody(self, **KWS):
        trans = KWS.get('trans')
        if not trans:
            if not self._CHEETAH__isBuffering and not callable(self.transaction):
                trans = self.transaction
            trans = trans or DummyTransaction()
            _dummyTrans = True
        else:
            _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        write('\n\n\n')
        return _dummyTrans and trans.response().getvalue() or ''

    _CHEETAH__instanceInitialized = False
    _CHEETAH_version = __CHEETAH_version__
    _CHEETAH_versionTuple = __CHEETAH_versionTuple__
    _CHEETAH_genTime = __CHEETAH_genTime__
    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__
    _CHEETAH_src = __CHEETAH_src__
    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__
    _mainCheetahMethod_for_view = 'writeBody'


if not hasattr(view, '_initCheetahAttributes'):
    templateAPIClass = getattr(view, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(view)
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=view()).run()