# uncompyle6 version 3.7.4
# Python bytecode 2.5 (62131)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/donn/Projects/pythoning/fui/trunk/fuimodules/strings.py
# Compiled at: 2008-02-10 04:47:37
appname = 'fui'
version = '0.0.7'
licence = 'License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law'
copyright = 'Copyright (C) 2008 Donn.C.Ingle'
contact = 'donn.ingle@gmail.com'
warranty = 'This program is distributed in the\nhope that it will be useful, but WITHOUT ANY\nWARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR\nPURPOSE.  See the GNU General Public License for\nmore details.'
allvars = {'appname': appname, 'vers': version, 'copyright': copyright, 'lic': licence, 'warranty': warranty, 'contact': contact}
verString = _('%(appname)s %(vers)s\n%(copyright)s\n%(lic)s') % allvars
url = 'http://pypi.python.org/pypi/fui'
description = _("%(appname)s - select and copy/move files & Directories on the command-line in a way very similar to how it's done in a gui with copy/cut and paste.\n") % allvars
long_description = _("By *selecting* filenames/directories into a selection set you can add and remove names quite simply. Once done, you'd go to another directory (even in another console or tab) and then you can copy (or move) the selection to there.\n\n(So, you can select some files using normal wildcards; here for example, all the png files):\n  ``%(appname)s bling blang bong *.png``\n(Then move to another folder) \n  ``cd someotherplace``\n(Add some more files)\n  ``%(appname)s socks shorts shirts`` \n(Then you decide you don't want *shorts* or *wibble.png*)\n  ``%(appname)s --exclude shorts wibble.png``\n(Now you want to copy those somewhere)\n  ``cd whereIwantStuff``\n\n  ``%(appname)s --copy``\n\n(done!)\n\nCopying/moving is done recursively when directories are involved. More help is available via --help\n\nThe idea was to imitate the process in a typical file-manager gui. I know there are many ways to do this with grep and backticks and other tricks, but I wanted a simple way that I could remember :)\n\n**Caution:** This is alpha software and I have not tested it nearly enough. Don't go using it on your vital data because it might eat it all up. Certainly give it a go until you get the feel and start to trust it.\n\nI hope it helps someone out there.\n") % allvars
help = _("%(appname)s [Options] [Files]\nFiles:\nThis is a list of filenames or directory names.\nYou can use all the tricks like `ls *.png` as long\nas you use spaces to separate items.\n\nYou can also pipe names into %(appname)s, for example:\nls *.jpg | %(appname)s\n\n%(appname)s's default mode is 'select'. This means that\nto select files, you simply name them and use no\noptions, like this:\n %(appname)s a b c pic.jpg *.png cheese\n\nTo remove an item, say one that snuck-in during\na glob like *.jpg, you do this:\n %(appname)s --exclude tomato.jpg fish.jpg eggs.jpg\n\nFinally, go to your target directory and, for\nexample, copy those files to it:\n %(appname)s --copy\n\nTo keep your selection do this:\n %(appname)s --keep --copy\nThen you can use it again elsewhere.\n\nOptions:\n  -v --version  Show program's version number and exit.\n  -h --help     Show this help message and exit.\n  -l --list     Show what's in the selection set.\n  -f --flush    Clear the selection set.\n  -e name ..[name] --exclude name ..[name]\n                Exclude name (and any listed names \n                separated by spaces) from the selection\n                set.\n  -c --copy     Will copy all the named files or\n                directories into the current directory.\n                The list will be cleared after this\n                unless you add -k or --keep\n  -m --move     Does the same as -c, but moves the\n                named items to the current directory.\n  -k --keep     Signals move/copy to retain your \n                selection set so you can use it again.\n\n%(appname)s - the fake copy/paste user interface !\n===\n%(copyright)s\n\n%(warranty)s\n\nReport bugs to %(contact)s\n") % allvars