# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/insights/parsers/tests/test_cobbler_modules_conf.py
# Compiled at: 2019-05-16 13:41:33
from insights.tests import context_wrap
from insights.parsers.cobbler_modules_conf import CobblerModulesConf
conf_content = ('\n# cobbler module configuration file\n# =================================\n\n# authentication:\n# what users can log into the WebUI and Read-Write XMLRPC?\n# choices:\n#    authn_denyall    -- no one (default)\n#    authn_configfile -- use /etc/cobbler/users.digest (for basic setups)\n#    authn_passthru   -- ask Apache to handle it (used for kerberos)\n#    authn_ldap       -- authenticate against LDAP\n#    authn_spacewalk  -- ask Spacewalk/Satellite (experimental)\n#    authn_testing    -- username/password is always testing/testing (debug)\n#    (user supplied)  -- you may write your own module\n# WARNING: this is a security setting, do not choose an option blindly.\n# for more information:\n# https://fedorahosted.org/cobbler/wiki/CobblerWebInterface\n# https://fedorahosted.org/cobbler/wiki/CustomizableSecurity\n# https://fedorahosted.org/cobbler/wiki/CobblerWithKerberos\n# https://fedorahosted.org/cobbler/wiki/CobblerWithLdap\n\n[authentication]\nmodule = authn_spacewalk\n\n# authorization:\n# once a user has been cleared by the WebUI/XMLRPC, what can they do?\n# choices:\n#    authz_allowall   -- full access for all authneticated users (default)\n#    authz_ownership  -- use users.conf, but add object ownership semantics\n#    (user supplied)  -- you may write your own module\n# WARNING: this is a security setting, do not choose an option blindly.\n# If you want to further restrict cobbler with ACLs for various groups,\n# pick authz_ownership.  authz_allowall does not support ACLs.  configfile\n# does but does not support object ownership which is useful as an additional\n# layer of control.\n\n# for more information:\n# https://fedorahosted.org/cobbler/wiki/CobblerWebInterface\n# https://fedorahosted.org/cobbler/wiki/CustomizableSecurity\n# https://fedorahosted.org/cobbler/wiki/CustomizableAuthorization\n# https://fedorahosted.org/cobbler/wiki/AuthorizationWithOwnership\n# https://fedorahosted.org/cobbler/wiki/AclFeature\n\n[authorization]\nmodule = authz_allowall\n\n# dns:\n# chooses the DNS management engine if manage_dns is enabled\n# in /etc/cobbler/settings, which is off by default.\n# choices:\n#    manage_bind    -- default, uses BIND/named\n#    manage_dnsmasq -- uses dnsmasq, also must select dnsmasq for dhcp below\n# NOTE: more configuration is still required in /etc/cobbler\n# for more information:\n# https://fedorahosted.org/cobbler/wiki/ManageDns\n\n[dns]\nmodule = manage_bind\n\n# dhcp:\n# chooses the DHCP management engine if manage_dhcp is enabled\n# in /etc/cobbler/settings, which is off by default.\n# choices:\n#    manage_isc     -- default, uses ISC dhcpd\n#    manage_dnsmasq -- uses dnsmasq, also must select dnsmasq for dns above\n# NOTE: more configuration is still required in /etc/cobbler\n# for more information:\n# https://fedorahosted.org/cobbler/wiki/ManageDhcp\n\n[dhcp]\nmodule = manage_isc\n\n#--------------------------------------------------\n').strip()

def test_cobbler_modules_conf():
    result = CobblerModulesConf(context_wrap(conf_content))
    assert result.get('authentication', 'module') == 'authn_spacewalk'
    assert result.get('dhcp', 'module') == 'manage_isc'