# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Users/svpino/dev/tensorflow-object-detection-sagemaker/todl/tensorflow-object-detection/research/object_detection/protos/argmax_matcher_pb2.py
# Compiled at: 2020-04-05 21:16:38
# Size of source mod 2**32: 4457 bytes
import google.protobuf as _descriptor
import google.protobuf as _message
import google.protobuf as _reflection
import google.protobuf as _symbol_database
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor.FileDescriptor(name='object_detection/protos/argmax_matcher.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n,object_detection/protos/argmax_matcher.proto\x12\x17object_detection.protos"\xec\x01\n\rArgMaxMatcher\x12\x1e\n\x11matched_threshold\x18\x01 \x01(\x02:\x030.5\x12 \n\x13unmatched_threshold\x18\x02 \x01(\x02:\x030.5\x12 \n\x11ignore_thresholds\x18\x03 \x01(\x08:\x05false\x12,\n\x1enegatives_lower_than_unmatched\x18\x04 \x01(\x08:\x04true\x12\'\n\x18force_match_for_each_row\x18\x05 \x01(\x08:\x05false\x12 \n\x11use_matmul_gather\x18\x06 \x01(\x08:\x05false')
_ARGMAXMATCHER = _descriptor.Descriptor(name='ArgMaxMatcher',
  full_name='object_detection.protos.ArgMaxMatcher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
 _descriptor.FieldDescriptor(name='matched_threshold',
   full_name='object_detection.protos.ArgMaxMatcher.matched_threshold',
   index=0,
   number=1,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(0.5)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='unmatched_threshold',
   full_name='object_detection.protos.ArgMaxMatcher.unmatched_threshold',
   index=1,
   number=2,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(0.5)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='ignore_thresholds',
   full_name='object_detection.protos.ArgMaxMatcher.ignore_thresholds',
   index=2,
   number=3,
   type=8,
   cpp_type=7,
   label=1,
   has_default_value=True,
   default_value=False,
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='negatives_lower_than_unmatched',
   full_name='object_detection.protos.ArgMaxMatcher.negatives_lower_than_unmatched',
   index=3,
   number=4,
   type=8,
   cpp_type=7,
   label=1,
   has_default_value=True,
   default_value=True,
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='force_match_for_each_row',
   full_name='object_detection.protos.ArgMaxMatcher.force_match_for_each_row',
   index=4,
   number=5,
   type=8,
   cpp_type=7,
   label=1,
   has_default_value=True,
   default_value=False,
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='use_matmul_gather',
   full_name='object_detection.protos.ArgMaxMatcher.use_matmul_gather',
   index=5,
   number=6,
   type=8,
   cpp_type=7,
   label=1,
   has_default_value=True,
   default_value=False,
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR)],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[],
  serialized_start=74,
  serialized_end=310)
DESCRIPTOR.message_types_by_name['ArgMaxMatcher'] = _ARGMAXMATCHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
ArgMaxMatcher = _reflection.GeneratedProtocolMessageType('ArgMaxMatcher', (_message.Message,), {'DESCRIPTOR':_ARGMAXMATCHER, 
 '__module__':'object_detection.protos.argmax_matcher_pb2'})
_sym_db.RegisterMessage(ArgMaxMatcher)