# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Users/svpino/dev/tensorflow-object-detection-sagemaker/todl/tensorflow-object-detection/research/object_detection/protos/faster_rcnn_box_coder_pb2.py
# Compiled at: 2020-04-05 21:16:38
# Size of source mod 2**32: 3487 bytes
import google.protobuf as _descriptor
import google.protobuf as _message
import google.protobuf as _reflection
import google.protobuf as _symbol_database
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor.FileDescriptor(name='object_detection/protos/faster_rcnn_box_coder.proto',
  package='object_detection.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n3object_detection/protos/faster_rcnn_box_coder.proto\x12\x17object_detection.protos"o\n\x12FasterRcnnBoxCoder\x12\x13\n\x07y_scale\x18\x01 \x01(\x02:\x0210\x12\x13\n\x07x_scale\x18\x02 \x01(\x02:\x0210\x12\x17\n\x0cheight_scale\x18\x03 \x01(\x02:\x015\x12\x16\n\x0bwidth_scale\x18\x04 \x01(\x02:\x015')
_FASTERRCNNBOXCODER = _descriptor.Descriptor(name='FasterRcnnBoxCoder',
  full_name='object_detection.protos.FasterRcnnBoxCoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
 _descriptor.FieldDescriptor(name='y_scale',
   full_name='object_detection.protos.FasterRcnnBoxCoder.y_scale',
   index=0,
   number=1,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(10)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='x_scale',
   full_name='object_detection.protos.FasterRcnnBoxCoder.x_scale',
   index=1,
   number=2,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(10)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='height_scale',
   full_name='object_detection.protos.FasterRcnnBoxCoder.height_scale',
   index=2,
   number=3,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(5)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='width_scale',
   full_name='object_detection.protos.FasterRcnnBoxCoder.width_scale',
   index=3,
   number=4,
   type=2,
   cpp_type=6,
   label=1,
   has_default_value=True,
   default_value=(float(5)),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR)],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[],
  serialized_start=80,
  serialized_end=191)
DESCRIPTOR.message_types_by_name['FasterRcnnBoxCoder'] = _FASTERRCNNBOXCODER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
FasterRcnnBoxCoder = _reflection.GeneratedProtocolMessageType('FasterRcnnBoxCoder', (_message.Message,), {'DESCRIPTOR':_FASTERRCNNBOXCODER, 
 '__module__':'object_detection.protos.faster_rcnn_box_coder_pb2'})
_sym_db.RegisterMessage(FasterRcnnBoxCoder)