# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /tmp/pip-install-m_4qh6p6/docutils/docutils/parsers/rst/languages/de.py
# Compiled at: 2019-07-30 18:47:12
# Size of source mod 2**32: 3442 bytes
"""
German-language mappings for language-dependent features of
reStructuredText.
"""
__docformat__ = 'reStructuredText'
directives = {'achtung':'attention', 
 'vorsicht':'caution', 
 'code':'code', 
 'gefahr':'danger', 
 'fehler':'error', 
 'hinweis':'hint', 
 'wichtig':'important', 
 'notiz':'note', 
 'tipp':'tip', 
 'warnung':'warning', 
 'ermahnung':'admonition', 
 'kasten':'sidebar', 
 'seitenkasten':'sidebar', 
 'seitenleiste':'sidebar', 
 'thema':'topic', 
 'zeilenblock':'line-block', 
 'parsed-literal (translation required)':'parsed-literal', 
 'rubrik':'rubric', 
 'epigraph':'epigraph', 
 'highlights':'highlights', 
 'pull-quote':'pull-quote', 
 'seitenansprache':'pull-quote', 
 'zusammengesetzt':'compound', 
 'verbund':'compound', 
 'container':'container', 
 'tabelle':'table', 
 'csv-tabelle':'csv-table', 
 'listentabelle':'list-table', 
 'mathe':'math', 
 'formel':'math', 
 'meta':'meta', 
 'bild':'image', 
 'abbildung':'figure', 
 'unverändert':'raw', 
 'roh':'raw', 
 'einfügen':'include', 
 'ersetzung':'replace', 
 'ersetzen':'replace', 
 'ersetze':'replace', 
 'unicode':'unicode', 
 'datum':'date', 
 'klasse':'class', 
 'rolle':'role', 
 'standardrolle':'default-role', 
 'titel':'title', 
 'inhalt':'contents', 
 'kapitelnummerierung':'sectnum', 
 'abschnittsnummerierung':'sectnum', 
 'linkziel-fußnoten':'target-notes', 
 'kopfzeilen':'header', 
 'fußzeilen':'footer'}
roles = {'abkürzung':'abbreviation', 
 'akronym':'acronym', 
 'code':'code', 
 'index':'index', 
 'tiefgestellt':'subscript', 
 'hochgestellt':'superscript', 
 'titel-referenz':'title-reference', 
 'pep-referenz':'pep-reference', 
 'rfc-referenz':'rfc-reference', 
 'betonung':'emphasis', 
 'betont':'emphasis', 
 'fett':'strong', 
 'wörtlich':'literal', 
 'mathe':'math', 
 'benannte-referenz':'named-reference', 
 'unbenannte-referenz':'anonymous-reference', 
 'fußfnoten-referenz':'footnote-reference', 
 'zitat-referenz':'citation-reference', 
 'ersetzungs-referenz':'substitution-reference', 
 'ziel':'target', 
 'uri-referenz':'uri-reference', 
 'unverändert':'raw', 
 'roh':'raw'}