# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /tmp/pip-install-m_4qh6p6/docutils/docutils/parsers/rst/languages/eo.py
# Compiled at: 2019-07-30 18:47:12
# Size of source mod 2**32: 3815 bytes
"""
Esperanto-language mappings for language-dependent features of
reStructuredText.
"""
__docformat__ = 'reStructuredText'
directives = {'atentu':'attention', 
 'zorgu':'caution', 
 'code (translation required)':'code', 
 'dangxero':'danger', 
 'danĝero':'danger', 
 'eraro':'error', 
 'spuro':'hint', 
 'grava':'important', 
 'noto':'note', 
 'helpeto':'tip', 
 'averto':'warning', 
 'admono':'admonition', 
 'flankteksto':'sidebar', 
 'temo':'topic', 
 'linea-bloko':'line-block', 
 'analizota-literalo':'parsed-literal', 
 'rubriko':'rubric', 
 'epigrafo':'epigraph', 
 'elstarajxoj':'highlights', 
 'elstaraĵoj':'highlights', 
 'ekstera-citajxo':'pull-quote', 
 'ekstera-citaĵo':'pull-quote', 
 'kombinajxo':'compound', 
 'kombinaĵo':'compound', 
 'tekstingo':'container', 
 'enhavilo':'container', 
 'tabelo':'table', 
 'tabelo-vdk':'csv-table', 
 'tabelo-csv':'csv-table', 
 'tabelo-lista':'list-table', 
 'meta':'meta', 
 'math (translation required)':'math', 
 'bildo':'image', 
 'figuro':'figure', 
 'inkludi':'include', 
 'senanaliza':'raw', 
 'anstatauxi':'replace', 
 'anstataŭi':'replace', 
 'unicode':'unicode', 
 'dato':'date', 
 'klaso':'class', 
 'rolo':'role', 
 'preterlasita-rolo':'default-role', 
 'titolo':'title', 
 'enhavo':'contents', 
 'seknum':'sectnum', 
 'sekcia-numerado':'sectnum', 
 'kapsekcio':'header', 
 'piedsekcio':'footer', 
 'celaj-notoj':'target-notes', 
 'restructuredtext-test-directive':'restructuredtext-test-directive'}
roles = {'mallongigo':'abbreviation', 
 'mall':'abbreviation', 
 'komenclitero':'acronym', 
 'kl':'acronym', 
 'code (translation required)':'code', 
 'indekso':'index', 
 'i':'index', 
 'subskribo':'subscript', 
 'sub':'subscript', 
 'supraskribo':'superscript', 
 'sup':'superscript', 
 'titola-referenco':'title-reference', 
 'titolo':'title-reference', 
 't':'title-reference', 
 'pep-referenco':'pep-reference', 
 'pep':'pep-reference', 
 'rfc-referenco':'rfc-reference', 
 'rfc':'rfc-reference', 
 'emfazo':'emphasis', 
 'forta':'strong', 
 'litera':'literal', 
 'math (translation required)':'math', 
 'nomita-referenco':'named-reference', 
 'nenomita-referenco':'anonymous-reference', 
 'piednota-referenco':'footnote-reference', 
 'citajxo-referenco':'citation-reference', 
 'citaĵo-referenco':'citation-reference', 
 'anstatauxa-referenco':'substitution-reference', 
 'anstataŭa-referenco':'substitution-reference', 
 'celo':'target', 
 'uri-referenco':'uri-reference', 
 'uri':'uri-reference', 
 'url':'uri-reference', 
 'senanaliza':'raw'}