# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /tmp/pip-install-m_4qh6p6/docutils/docutils/parsers/rst/languages/he.py
# Compiled at: 2019-07-30 18:47:12
# Size of source mod 2**32: 3624 bytes
"""
English-language mappings for language-dependent features of
reStructuredText.
"""
__docformat__ = 'reStructuredText'
directives = {'תשומת לב':'attention', 
 'זהירות':'caution', 
 'code (translation required)':'code', 
 'סכנה':'danger', 
 'שגיאה':'error', 
 'רמז':'hint', 
 'חשוב':'important', 
 'הערה':'note', 
 'טיפ':'tip', 
 'אזהרה':'warning', 
 'admonition':'admonition', 
 'sidebar':'sidebar', 
 'topic':'topic', 
 'line-block':'line-block', 
 'parsed-literal':'parsed-literal', 
 'rubric':'rubric', 
 'epigraph':'epigraph', 
 'highlights':'highlights', 
 'pull-quote':'pull-quote', 
 'compound':'compound', 
 'container':'container', 
 'table':'table', 
 'csv-table':'csv-table', 
 'list-table':'list-table', 
 'meta':'meta', 
 'math (translation required)':'math', 
 'תמונה':'image', 
 'figure':'figure', 
 'include':'include', 
 'raw':'raw', 
 'replace':'replace', 
 'unicode':'unicode', 
 'date':'date', 
 'סגנון':'class', 
 'role':'role', 
 'default-role':'default-role', 
 'title':'title', 
 'תוכן':'contents', 
 'sectnum':'sectnum', 
 'section-numbering':'sectnum', 
 'header':'header', 
 'footer':'footer', 
 'target-notes':'target-notes', 
 'restructuredtext-test-directive':'restructuredtext-test-directive'}
roles = {'abbreviation':'abbreviation', 
 'ab':'abbreviation', 
 'acronym':'acronym', 
 'ac':'acronym', 
 'code (translation required)':'code', 
 'index':'index', 
 'i':'index', 
 'תחתי':'subscript', 
 'sub':'subscript', 
 'עילי':'superscript', 
 'sup':'superscript', 
 'title-reference':'title-reference', 
 'title':'title-reference', 
 't':'title-reference', 
 'pep-reference':'pep-reference', 
 'pep':'pep-reference', 
 'rfc-reference':'rfc-reference', 
 'rfc':'rfc-reference', 
 'emphasis':'emphasis', 
 'strong':'strong', 
 'literal':'literal', 
 'math (translation required)':'math', 
 'named-reference':'named-reference', 
 'anonymous-reference':'anonymous-reference', 
 'footnote-reference':'footnote-reference', 
 'citation-reference':'citation-reference', 
 'substitution-reference':'substitution-reference', 
 'target':'target', 
 'uri-reference':'uri-reference', 
 'uri':'uri-reference', 
 'url':'uri-reference', 
 'raw':'raw'}