# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.8-intel/egg/atomac/ldtpd/constants.py
# Compiled at: 2013-02-13 13:37:18
"""Constants class."""
abbreviated_roles = {'AXWindow': 'frm', 
   'AXTextArea': 'txt', 
   'AXTextField': 'txt', 
   'AXButton': 'btn', 
   'AXStaticText': 'lbl', 
   'AXRadioButton': 'rbtn', 
   'AXSlider': 'sldr', 
   'AXCell': 'tblc', 
   'AXImage': 'img', 
   'AXToolbar': 'tbar', 
   'AXScrollBar': 'scbr', 
   'AXMenuItem': 'mnu', 
   'AXMenu': 'mnu', 
   'AXMenuBar': 'mnu', 
   'AXMenuBarItem': 'mnu', 
   'AXCheckBox': 'chk', 
   'AXTabGroup': 'ptl', 
   'AXList': 'lst', 
   'AXMenuButton': 'cbo', 
   'AXRow': 'tblc', 
   'AXColumn': 'col', 
   'AXTable': 'tbl', 
   'AXScrollArea': 'sar', 
   'AXOutline': 'otl', 
   'AXValueIndicator': 'val', 
   'AXDisclosureTriangle': 'dct', 
   'AXGroup': 'grp', 
   'AXPopUpButton': 'pubtn', 
   'AXApplication': 'app', 
   'AXDocItem': 'doc', 
   'AXHeading': 'tch', 
   'AXGenericElement': 'gen'}
ldtp_class_type = {'AXWindow': 'frame', 
   'AXApplication': 'application', 
   'AXTextArea': 'text', 
   'AXTextField': 'text', 
   'AXButton': 'push_button', 
   'AXStaticText': 'label', 
   'AXRadioButton': 'radion_button', 
   'AXSlider': 'slider', 
   'AXCell': 'table_cell', 
   'AXImage': 'image', 
   'AXToolbar': 'toolbar', 
   'AXScrollBar': 'scroll_bar', 
   'AXMenuItem': 'menu_item', 
   'AXMenu': 'menu', 
   'AXMenuBar': 'menu_bar', 
   'AXMenuBarItem': 'menu_bar_item', 
   'AXCheckBox': 'check_box', 
   'AXTabGroup': 'page_tab_list', 
   'AXList': 'list', 
   'AXColumn': 'column', 
   'AXRow': 'table_cell', 
   'AXTable': 'table', 
   'AXScrollArea': 'scroll_area', 
   'AXPopUpButton': 'popup_button', 
   'AXDocItem': 'doc_item', 
   'AXHeading': 'heading', 
   'AXGenericElement': 'generic_element'}