# uncompyle6 version 3.6.7
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: /home/thomas/software/codegra.fs/env/lib/python3.7/site-packages/codegra_fs/constants.py
# Compiled at: 2018-10-29 13:27:58
# Size of source mod 2**32: 3264 bytes
fixed_mode_help = 'Mount the original files as read only. It is still\npossible to create new files, but it is not possible to alter or delete\nexisting files. The files shown are always the student revision files. The\ncreated new files are only visible during a single session, they are **NOT**\nuploaded to the server.'
rubric_edit_help = 'Make it possible to delete rubric items or categories\nusing the `.cg-edit-rubric.md` files.\n\nNote: this feature is experimental and can lead to data loss!'
assigned_only_help = 'Only show submissions that are assigned to you. This\nonly has effect if submissions are assigned and you are one of the\nassignees.'
mountpoint_help = 'Mountpoint for the file system. This should be an existing\nempty directory.'
password_help = "Your CodeGra.de password, don't pass this option if you want\nto pass your password over stdin. You can also use the `CGFS_PASSWORD`\nenvironment variable to pass your password."
url_help = "The url to find the api. This defaults to\n'https://codegra.de/api/v1/'. This is most likely\n'https://{UNIVERSITY}.codegra.de/api/v1/' where '{UNIVERSITY}' is your\nuniversity (for example 'uva' for the University of Amsterdam and 'ut' for the\nUniversity of Twente).  This value can also be passed as an environment\nvariable 'CGAPI_BASE_URL'"
all_submissions_help = 'See all submissions not just the latest submissions\nof students.'
cgfs_epilog = 'supported environment variables:\n CGAPI_BASE_URL         Used as the value for the `--url` flag. It can be very\n                        convenient to set this environment variable in your\n                        `.bashrc` file (or equivalent).\n CGFS_PASSWORD          Used as your password. Please take care when using this\n                        environment variable as all processes can read\n                        environment variables meaning this could easily leak\n                        your password. We recommend piping your password, see\n                        the last example for how to do this.\n\nexamples:\n  cgfs -u https://uva.codegra.de/api/v1/ -m user ~/mount\n                        Mount the file system from https://uva.codegra.de/\n                        showing only your assignments in the directory\n                        "$HOME/mount".  You will be prompted for a password.\n  cgfs -u https://uva.codegra.de/api/v1/ -fm user ~/mount\n                        Same as above but mount in fixed mode, which means you\n                        cannot change or add files. This is useful for\n                        automatic grading as you cannot upload grade scripts by\n                        mistake. You will be prompted for a password.\n  CGFS_PASSWORD=mypass cgfs -u https://uva.codegra.de/api/v1/ -mf user ~/mount\n                        Same as above but mount using an environment\n                        variable. You will not be prompted for a password. This\n                        option can be insecure!\n  pass codegrade | cgfs -u https://uva.codegra.de/api/v1/ -mf user ~/mount\n                        Same as above but pipe password from your password\n                        manager. This is safer than above as your password will\n                        not be saved to your history file.\n'