# uncompyle6 version 3.7.4
# Python bytecode 2.6 (62161)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-i686/egg/coils/foundation/tzdata.py
# Compiled at: 2012-10-12 07:02:39
COILS_TIMEZONES = [
 {'abbreviation': 'GMT+0500', 'description': 'GMT+5', 'code': 'Etc/GMT+5'},
 {'abbreviation': 'GMT+1200', 'description': 'GMT+12', 
    'code': 'Etc/GMT+12'},
 {'abbreviation': 'MET', 'description': 'Poland', 
    'code': 'MET'},
 {'abbreviation': 'GMT-0300', 'description': 'GMT-3', 
    'code': 'Etc/GMT-3'},
 {'abbreviation': 'CST', 'description': 'US/Central', 
    'code': 'US/Central'},
 {'abbreviation': 'GMT-0500', 'description': 'GMT-5', 
    'code': 'Etc/GMT-5'},
 {'abbreviation': 'HST', 'description': 'US/Hawaii', 
    'code': 'US/Hawaii'},
 {'abbreviation': 'GMT-1200', 'description': 'GMT-12', 
    'code': 'Etc/GMT-12'},
 {'abbreviation': 'MST', 'description': 'US/Mountain', 
    'code': 'US/Mountain'},
 {'abbreviation': 'SST', 'description': 'Singapore', 
    'code': 'Singapore'},
 {'abbreviation': 'GMT+0700', 'description': 'GMT+7', 
    'code': 'Etc/GMT+7'},
 {'abbreviation': 'NZDT', 'description': 'NZ', 
    'code': 'NZ'},
 {'abbreviation': 'PST', 'description': 'US/Pacific', 
    'code': 'US/Pacific'},
 {'abbreviation': 'EST', 'description': 'US/Eastern', 
    'code': 'EST'},
 {'abbreviation': 'GMT-0700', 'description': 'GMT-7', 
    'code': 'Etc/GMT-7'},
 {'abbreviation': 'GMT+0200', 'description': 'GMT+2', 
    'code': 'Etc/GMT+2'},
 {'abbreviation': 'GMT+1100', 'description': 'GMT+11', 
    'code': 'Etc/GMT+11'},
 {'abbreviation': 'GMT-0200', 'description': 'GMT-2', 
    'code': 'Etc/GMT-2'},
 {'abbreviation': 'GMT-1100', 'description': 'GMT-11', 
    'code': 'Etc/GMT-11'},
 {'abbreviation': 'EET', 'description': 'Turkey', 
    'code': 'Turkey'},
 {'abbreviation': 'GMT', 'description': 'GMT', 
    'code': 'GMT'},
 {'abbreviation': 'GMT+0400', 'description': 'GMT+4', 
    'code': 'Etc/GMT-4'},
 {'abbreviation': 'JST', 'description': 'Japan', 
    'code': 'Japan'},
 {'abbreviation': 'GMT+0100', 'description': 'GMT+1', 
    'code': 'Etc/GMT+1'},
 {'abbreviation': 'GMT-1000', 'description': 'GMT-10', 
    'code': 'Etc/GMT-10'},
 {'abbreviation': 'GMT+0800', 'description': 'GMT+8', 
    'code': 'Etc/GMT+8'},
 {'abbreviation': 'GMT-0100', 'description': 'GMT-1', 
    'code': 'Etc/GMT-1'},
 {'abbreviation': 'GMT-0800', 'description': 'GMT-8', 
    'code': 'Etc/GMT-8'},
 {'abbreviation': 'GMT+0300', 'description': 'GMT+3', 
    'code': 'Etc/GMT+3'},
 {'abbreviation': 'GMT', 'description': 'GMT', 
    'code': 'UTC'}]