# uncompyle6 version 3.7.4
# Python bytecode 2.5 (62131)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.3-fat/egg/jquery/release.py
# Compiled at: 2008-02-08 10:48:29
version = '1.2.3'
description = 'Jquery javascript library for TurboGears'
long_description = '\n\nFeature\n===============\n\njquery is a jquery javascript library wrapper and ajax helper for happy\nTurboGears web designers.\n\nAvailable widgets\n====================\n\n  * Jquery (basic jquery libray wrapper for Turbogears)\n\nIt also contains 3 extra ajax widgets based on jquery.\n\n  * addCallback / link_to_remote(target ,update, href, callback)\n        \n  * addPeriodBack / periodically_call_remote(update, href, interval)\n\n  * addFormback / form_remote_tag(target, update, href)\n\nWhich are inspired from Ruby on Rails/pquery and give them the twisted syntax.\n    \n\nInstall\n==============\nUse setuptools to install::\n    \n    $easy_install jquery\n\n\nUsage\n==============\n\njquery\n~~~~~~~~~\n\ninclude in config/app.cfg::\n\n    tg.include_widgets = [\'jquery.jquery\']\n\njquery ajax\n~~~~~~~~~~~~~\n\nimport in controllers.py::\n\n    from jquery import addCallback\n    from jquery import addPeriodback\n    from jquery import addFormback\n    ....\n    return dict(addCallback = addCallback, \n            addPeriodback = addPeriodback)\n\n.. note:: \n    Update notice form 1.1.2 jquery widget: you need return dict(link = addPeriodback) instead of \n    return dict(link = addPeriodback()) in the following versions\n\n\n\nin template::\n    \n    [div id="timelink"][a href = "#"]get time[/a][/div]\n    [div id="timediv"][/div]\n    ${addCallback(target="timelink" ,update="timediv", href="/time")}\n    \nor::\n\n    [div id="timediv"][/div]\n    ${addPeriodback(update="timediv", href="/time", interval="3000")}\n\nor:: \n\n    [form class="timelink" action="ajax"  method="get" ]\n       Field : [input type="text" name="field" /][br /]\n       [input type="submit" /] \n    [/form]\n    [div id="timediv"][/div]\n    ${addFormback(target="timelink", update="timediv", href="ajax")}\n\nThe addCallback/addPeriodback could be placed anywhere in your template.\nCheck http://docs.turbogears.org/1.0/RemoteLink for detail.\n\nReference\n============\n\n    - jquery http://jquery.com\n    - pquery http://www.ngcoders.com/pquery/\n\nSource\n============\n\nSource is available in \n\nhttp://svn.turbogears.org/projects/tgJquery/trunk\n\n\nHistory\n=============\n\n1.2.3:\n\n  * update to jquery 1.2.3\n  * host in TurboGears svn\n\n1.2.2:\n\n  * update to jquery 1.2.2\n  \n1.1.2w2: \n\n  * new twisted style ajax call\n  * new addFormback/form_remote_tag call\n  * passing ajax function no need extra \'()\' at all.\n\n\n'
author = 'Fred Lin'
email = 'gasolin+tg@gmail.com'
copyright = 'Fred Lin 2007'
license = 'MIT'