# uncompyle6 version 3.6.7
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: /Users/gdelraye/Documents/workspace/plotsettings/build/lib/plotsettings/journals.py
# Compiled at: 2014-11-14 01:29:37
__doc__ = "\nDictionary of plot settings for submission to academic journals.\n\nThe structure of the dictionary 'journals' must adhere to the following structure::\n\n    journals = {'journal1':      {'rcParams':     {'param1': value1,\n                                                   'param2': value2 ...}, \n                                  'figsize':      {'param1': value1,\n                                                   'param2': value2 ...},\n                                  'panel_labels': {'param1': value1,\n                                                   'param2': value2 ...},\n                'journal2':      {'rcParams':     {'param1': value1,\n                                                   'param2': value2 ...}, \n                                  'figsize':      {'param1': value1,\n                                                   'param2': value2 ...},\n                                  'panel_labels': {'param1': value1,\n                                                   'param2': value2 ...},\n                'journal3'...\n                }\n\nwhere 'journalx' are the identifying names of academic journals (e.g. 'Nature'), with\nthe specifications for each journal being divided into 3 dictionaries:\n\n    * *rcParams*: All parameters are optional. Any valid input to pyplot.rcParams (for\n      example font name and sizes, default linewidths) is accepted. Definitions of valid \n      keys to rcParams can be found `here <http://matplotlib.org/users/customizing.html>`_.\n    * *figsize*: Set figure dimension calculations. Requires the parameters column_width, \n      gutter_width, and units. The parameter max_height is optional. See below for details.\n    * *panel_labels*: Set default panel labels (e.g. A, B, C). All parameters are optional.\n      See below for details.\n  \nThe possible non-rcParams parameters are:\n    \n    * *figsize*:\n    \n        * *column_width* (required) - the maximum width a figure is allowed to be while still \n          fitting withing a single column.\n        * *gutter_width* (required) - the width of the gutter (space between columns). This can \n          usually be found by comparing the maximum width that a journal allows for a single-\n          column figure with the maximum width of a 2-column figure. For example, PLoS One\n          allows a 1-column figure to be 83 mm in width and a 2-column figure to be 173.5 mm,\n          meaning that the gutter width (173.5 - 83*2) must be 7.5 mm wide.\n        * *max_height* (optional) - the maximum height a figure is allowed to be while fitting \n          on a single page (i.e. the page height).\n        * *units* (required) - the units in which the above are reported. Can be one of 'mm', \n          'cm', 'inch', or 'pts'\n    \n    * panel_labels:\n    \n        * *label_weight* (optional) - the font weight of panel annotations (e.g. A, B, C etc.).\n          Default is 'bold'\n        * *label_case* (optional) - whether to capitalize ('upper') or not capitalize\n          ('lower') the panel labels.\n        * *label_prefix* (optional) - characters to prepend to panel label (e.g. if the desired\n          label style is (A), (B), etc., set label_prefix to ')').\n        * *label_suffix* (optional) - characters to append to panel label (e.g. if the desired\n          label style is a., b., etc., set label_suffix = '.')\n\nValues for many of these settings can be found in the journal's Author Information page. For example,\nthe settings for the Proceedings of the Royal Society B can be found in\n`<http://rspb.royalsocietypublishing.org/site/misc/preparing-article.xhtml>`_\n\nSome notes:\n    * Absolute minimum linewidth is typically 0.1pt - don't go below this,\n      and for prominent lines (e.g. plot lines) use 1 pt.\n\nCreated on Oct 10, 2014\n\n@author: gdelraye\n"
journals = {'Cell': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                         'xtick.labelsize': 9, 
                         'ytick.labelsize': 9, 
                         'legend.fontsize': 9, 
                         'lines.markersize': 3, 
                         'font.size': 9, 
                         'font.family': 'sans-serif', 
                         'font.sans-serif': [
                                           'Helvetica'], 
                         'text.usetex': False}, 
            'figsize': {'column_width': 85, 'gutter_width': 4, 
                        'units': 'mm'}, 
            'panel_labels': {'fontweight': 'bold', 'case': 'upper', 
                             'prefix': '', 
                             'suffix': ''}}, 
   'Copeia': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                           'xtick.labelsize': 9, 
                           'ytick.labelsize': 9, 
                           'legend.fontsize': 9, 
                           'lines.markersize': 3, 
                           'font.size': 9, 
                           'font.family': 'sans-serif', 
                           'font.sans-serif': [
                                             'Helvetica'], 
                           'text.usetex': False}, 
              'figsize': {'column_width': 96, 'gutter_width': 6, 
                          'max_height': 245, 
                          'units': 'mm'}, 
              'panel_labels': {'fontweight': 'bold', 'case': 'upper', 
                               'prefix': '', 
                               'suffix': ''}}, 
   'DSRII': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 8, 
                          'xtick.labelsize': 8, 
                          'ytick.labelsize': 8, 
                          'legend.fontsize': 8, 
                          'lines.markersize': 3, 
                          'font.size': 8, 
                          'font.family': 'sans-serif', 
                          'font.sans-serif': [
                                            'Arial'], 
                          'text.usetex': False}, 
             'figsize': {'column_width': 90, 'gutter_width': 10, 
                         'max_height': 240, 
                         'units': 'mm', 
                         'fontsize': 8}, 
             'panel_labels': {}}, 
   'EcolLett': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                             'xtick.labelsize': 9, 
                             'ytick.labelsize': 9, 
                             'legend.fontsize': 9, 
                             'lines.markersize': 3, 
                             'font.size': 9, 
                             'font.family': 'sans-serif', 
                             'font.sans-serif': [
                                               'Arial'], 
                             'text.usetex': False}, 
                'figsize': {'column_width': 82, 'gutter_width': 9, 
                            'units': 'mm'}, 
                'panel_labels': {}}, 
   'GlobChangeBio': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                                  'xtick.labelsize': 9, 
                                  'ytick.labelsize': 9, 
                                  'legend.fontsize': 9, 
                                  'lines.markersize': 3, 
                                  'font.size': 9, 
                                  'font.family': 'sans-serif', 
                                  'font.sans-serif': [
                                                    'Arial'], 
                                  'text.usetex': False}, 
                     'figsize': {'column_width': 80, 'gutter_width': 9, 
                                 'units': 'mm'}, 
                     'panel_labels': {'fontweight': 'bold', 'case': 'lower', 
                                      'prefix': '(', 
                                      'suffix': ')'}}, 
   'GlobEnvChange': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 7, 
                                  'xtick.labelsize': 7, 
                                  'ytick.labelsize': 7, 
                                  'legend.fontsize': 7, 
                                  'lines.markersize': 3, 
                                  'font.size': 7, 
                                  'font.family': 'sans-serif', 
                                  'font.sans-serif': [
                                                    'Arial'], 
                                  'text.usetex': False}, 
                     'figsize': {'column_width': 90, 'gutter_width': 10, 
                                 'max_height': 240, 
                                 'units': 'mm'}, 
                     'panel_labels': {}}, 
   'IntCompBiol': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                                'xtick.labelsize': 9, 
                                'ytick.labelsize': 9, 
                                'legend.fontsize': 9, 
                                'lines.markersize': 3, 
                                'font.size': 9, 
                                'font.family': 'sans-serif', 
                                'font.sans-serif': [
                                                  'Arial'], 
                                'text.usetex': False}, 
                   'figsize': {'column_width': 88, 'gutter_width': 8, 
                               'units': 'mm'}, 
                   'panel_labels': {'fontweight': 'bold', 'case': 'upper', 
                                    'prefix': '', 
                                    'suffix': ''}}, 
   'JEB': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 8, 
                        'xtick.labelsize': 8, 
                        'ytick.labelsize': 8, 
                        'legend.fontsize': 8, 
                        'lines.markersize': 3, 
                        'font.size': 8, 
                        'font.family': 'sans-serif', 
                        'font.sans-serif': [
                                          'Arial'], 
                        'text.usetex': False}, 
           'figsize': {'column_width': 85, 'gutter_width': 10, 
                       'max_height': 210, 
                       'units': 'mm'}, 
           'panel_labels': {}}, 
   'LimnolOcean': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 10, 
                                'xtick.labelsize': 10, 
                                'ytick.labelsize': 10, 
                                'legend.fontsize': 10, 
                                'lines.markersize': 3, 
                                'font.size': 10, 
                                'font.family': 'serif', 
                                'font.serif': [
                                             'Times New Roman'], 
                                'text.usetex': False}, 
                   'figsize': {'column_width': 89, 'gutter_width': 6, 
                               'max_height': 232, 
                               'units': 'mm'}, 
                   'panel_labels': {'case': 'upper', 'prefix': '', 
                                    'suffix': ''}}, 
   'MEPS': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                         'xtick.labelsize': 9, 
                         'ytick.labelsize': 9, 
                         'legend.fontsize': 9, 
                         'lines.markersize': 3, 
                         'font.size': 9, 
                         'font.family': 'sans-serif', 
                         'font.sans-serif': [
                                           'Arial'], 
                         'text.usetex': False}, 
            'figsize': {'column_width': 81, 'gutter_width': 7, 
                        'max_height': 225, 
                        'units': 'mm'}, 
            'panel_labels': {}}, 
   'Nature': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 7, 
                           'xtick.labelsize': 7, 
                           'ytick.labelsize': 7, 
                           'legend.fontsize': 7, 
                           'lines.markersize': 3, 
                           'font.size': 7, 
                           'font.family': 'serif', 
                           'font.serif': [
                                        'Times New Roman'], 
                           'text.usetex': False}, 
              'figsize': {'column_width': 89, 'gutter_width': 5, 
                          'max_height': 247, 
                          'units': 'mm'}, 
              'panel_labels': {'case': 'lower', 'fontweight': 'bold', 
                               'prefix': '', 
                               'suffix': '', 
                               'fontsize': 8}}, 
   'Oecologia': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 8, 
                              'xtick.labelsize': 8, 
                              'ytick.labelsize': 8, 
                              'legend.fontsize': 8, 
                              'lines.markersize': 3, 
                              'font.size': 8, 
                              'font.family': 'sans-serif', 
                              'font.sans-serif': [
                                                'Arial'], 
                              'text.usetex': False}, 
                 'figsize': {'column_width': 84, 'gutter_width': 6, 
                             'max_height': 234, 
                             'units': 'mm'}, 
                 'panel_labels': {'case': 'lower', 'fontweight': 'normal', 
                                  'prefix': '', 
                                  'suffix': '', 
                                  'fontsize': 9}}, 
   'PLOSBio': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                            'xtick.labelsize': 9, 
                            'ytick.labelsize': 9, 
                            'legend.fontsize': 9, 
                            'lines.markersize': 3, 
                            'font.size': 9, 
                            'font.family': 'sans-serif', 
                            'font.sans-serif': [
                                              'Arial'], 
                            'text.usetex': False}, 
               'figsize': {'column_width': 83, 'gutter_width': 7.5, 
                           'max_height': 233.5, 
                           'units': 'mm'}, 
               'panel_labels': {}}, 
   'PLOSOne': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                            'xtick.labelsize': 9, 
                            'ytick.labelsize': 9, 
                            'legend.fontsize': 9, 
                            'lines.markersize': 3, 
                            'font.size': 9, 
                            'font.family': 'sans-serif', 
                            'font.sans-serif': [
                                              'Arial'], 
                            'text.usetex': False}, 
               'figsize': {'column_width': 83, 'gutter_width': 7.5, 
                           'max_height': 233.5, 
                           'units': 'mm'}, 
               'panel_labels': {}}, 
   'PNAS': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 8, 
                         'xtick.labelsize': 8, 
                         'ytick.labelsize': 8, 
                         'legend.fontsize': 8, 
                         'lines.markersize': 3, 
                         'font.size': 8, 
                         'font.family': 'sans-serif', 
                         'font.sans-serif': [
                                           'Arial'], 
                         'text.usetex': False}, 
            'figsize': {'column_width': 87, 'gutter_width': 4, 
                        'max_height': 240, 
                        'units': 'mm'}, 
            'panel_labels': {}}, 
   'Presentation': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 18, 
                                 'xtick.labelsize': 18, 
                                 'ytick.labelsize': 18, 
                                 'legend.fontsize': 18, 
                                 'lines.markersize': 3, 
                                 'font.size': 18, 
                                 'font.family': 'sans-serif', 
                                 'font.sans-serif': [
                                                   'Arial'], 
                                 'text.usetex': False}, 
                    'figsize': {'column_width': 5, 'gutter_width': 0, 
                                'max_height': 7.5, 
                                'units': 'inch'}, 
                    'panel_labels': {'fontweight': 'bold', 'case': 'upper', 
                                     'prefix': '', 
                                     'suffix': ''}}, 
   'ProcRoySocB': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 9, 
                                'xtick.labelsize': 9, 
                                'ytick.labelsize': 9, 
                                'legend.fontsize': 9, 
                                'lines.markersize': 3, 
                                'font.size': 9, 
                                'font.family': 'serif', 
                                'font.serif': [
                                             'Times New Roman'], 
                                'text.usetex': False}, 
                   'figsize': {'column_width': 84, 'gutter_width': 7, 
                               'max_height': 250, 
                               'units': 'mm'}, 
                   'panel_labels': {'fontweight': 'bold', 'case': 'lower', 
                                    'prefix': '(', 
                                    'suffix': ')', 
                                    'fontsize': 11}}, 
   'Science': {'rcParams': {'backend': 'pdf', 'axes.labelsize': 7, 
                            'xtick.labelsize': 7, 
                            'ytick.labelsize': 7, 
                            'legend.fontsize': 7, 
                            'lines.markersize': 3, 
                            'font.size': 7, 
                            'font.family': 'sans-serif', 
                            'font.sans-serif': [
                                              'Helvetica'], 
                            'text.usetex': False}, 
               'figsize': {'column_width': 55, 'gutter_width': 10, 
                           'units': 'mm'}, 
               'panel_labels': {'fontweight': 'bold', 'case': 'upper', 
                                'prefix': '', 
                                'suffix': ''}}}