# uncompyle6 version 3.7.4
# Python bytecode 2.6 (62161)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\ymsg\const.py
# Compiled at: 2009-11-05 06:13:18
YAHOO_PAGER_HOST = 'scsa.msg.yahoo.com'
YAHOO_PAGER_PORT = 5050
YAHOO_TOKEN_URL = 'https://login.yahoo.com/config/pwtoken_get?src=ymsgr&ts=&login=%s&passwd=%s&chal=%s'
YAHOO_LOGIN_URL = 'https://login.yahoo.com/config/pwtoken_login?src=ymsgr&ts=&token=%s'
YAHOO_SERVICE_LOGON = 1
YAHOO_SERVICE_LOGOFF = 2
YAHOO_SERVICE_MESSAGE = 6
YAHOO_SERVICE_PING = 18
YAHOO_SERVICE_HANDSHAKE = 76
YAHOO_SERVICE_AUTHRESP = 84
YAHOO_SERVICE_AUTH = 87
YAHOO_STATUS_AVAILABLE = 0
YAHOO_STATUS_BRB = 1
YAHOO_STATUS_BUSY = 2
YAHOO_STATUS_NOTATHOME = 3
YAHOO_STATUS_NOTATDESK = 4
YAHOO_STATUS_NOTINOFFICE = 5
YAHOO_STATUS_ONPHONE = 6
YAHOO_STATUS_ONVACATION = 7
YAHOO_STATUS_OUTTOLUNCH = 8
YAHOO_STATUS_STEPPEDOUT = 9
YAHOO_STATUS_INVISIBLE = 12
YAHOO_STATUS_CUSTOM = 99
YAHOO_RETCODE_OK = 1
YAHOO_RETCODE_ERR_SRVCON = 2
YAHOO_RETCODE_ERR_UPMISSING = 3
YAHOO_RETCODE_ERR_UHASAT = 4
YAHOO_RETCODE_ERR_LOGIN = 5
YAHOO_RETCODE_ERR_UDEACTIVATED = 6
YAHOO_RETCODE_ERR_UNOTEXIST = 7
YAHOO_RETCODE_ERR_LOCKED = 8