# uncompyle6 version 3.7.4
# Python bytecode 2.4 (62061)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\turbogears\i18n\data\de_CH.py
# Compiled at: 2011-03-26 09:19:59
languages = {'gv': 'Manx', 'gu': 'Gujarati', 'gd': 'Schottisch-Gälisch', 'ga': 'Irisch', 'gn': 'Guarani', 'gl': 'Galizisch', 'la': 'Latein', 'ln': 'Lingala', 'lo': 'Laotisch', 'tt': 'Tatarisch', 'tr': 'Türkisch', 'ts': 'Tsonga', 'lv': 'Lettisch', 'to': 'Tongaisch', 'lt': 'Litauisch', 'tk': 'Turkmenisch', 'th': 'Thai', 'ti': 'Tigrinja', 'tg': 'Tadschikisch', 'te': 'Telugu', 'haw': 'Hawaiianisch', 'yi': 'Jiddisch', 'yo': 'Joruba', 'de': 'Deutsch', 'da': 'Dänisch', 'dz': 'Bhutanisch', 'st': 'Sotho', 'qu': 'Quechua', 'el': 'Griechisch', 'eo': 'Esperanto', 'en': 'Englisch', 'zh': 'Chinesisch', 'za': 'Zhuang', 'uk': 'Ukrainisch', 'eu': 'Baskisch', 'et': 'Estnisch', 'es': 'Spanisch', 'ru': 'Russisch', 'rw': 'Ruandisch', 'rm': 'Rätoromanisch', 'rn': 'Kirundi', 'ro': 'Rumänisch', 'bn': 'Bengalisch', 'be': 'Weißrussisch', 'bg': 'Bulgarisch', 'ba': 'Baschkirisch', 'wo': 'Wolof', 'jv': 'Javanisch', 'bo': 'Tibetisch', 'bh': 'Biharisch', 'bi': 'Bislama', 'br': 'Bretonisch', 'ja': 'Japanisch', 'om': 'Oromo', 'oc': 'Okzitanisch', 'tw': 'Twi', 'or': 'Orija', 'xh': 'Xhosa', 'co': 'Korsisch', 'ca': 'Katalanisch', 'cy': 'Walisisch', 'cs': 'Tschechisch', 'zap': 'Zapotekisch', 'ps': 'Afghanisch (Paschtu)', 'pt': 'Portugiesisch', 'tl': 'Tagalog', 'pa': 'Pandschabisch', 'vi': 'Vietnamesisch', 'pl': 'Polnisch', 'hy': 'Armenisch', 'hr': 'Kroatisch', 'iu': 'Inukitut', 'hu': 'Ungarisch', 'hi': 'Hindi', 'ha': 'Hausa', 'he': 'Hebräisch', 'mg': 'Madagassisch', 'uz': 'Usbekisch', 'ml': 'Malayalam', 'mo': 'Moldauisch', 'mn': 'Mongolisch', 'mi': 'Maori', 'ik': 'Inupiak', 'mk': 'Mazedonisch', 'ur': 'Urdu', 'mt': 'Maltesisch', 'ms': 'Malaiisch', 'mr': 'Marathi', 'ug': 'Uigur', 'ta': 'Tamilisch', 'my': 'Burmesisch', 'aa': 'Afar', 'ab': 'Abchasisch', 'ss': 'Swazi', 'af': 'Afrikaans', 'tn': 'Setswana', 'sw': 'Suaheli', 'is': 'Isländisch', 'am': 'Amharisch', 'it': 'Italienisch', 'sv': 'Schwedisch', 'ia': 'Interlingua', 'as': 'Assamesisch', 'ar': 'Arabisch', 'su': 'Sudanesisch', 'zu': 'Zulu', 'ay': 'Aymara', 'az': 'Aserbaidschanisch', 'ie': 'Interlingue', 'id': 'Indonesisch', 'sk': 'Slowakisch', 'nl': 'Niederländisch', 'nn': 'Norwegisch Nynorsk', 'no': 'Norwegisch', 'na': 'Nauruisch', 'nb': 'Norwegisch Bokmål', 'ne': 'Nepalesisch', 'vo': 'Volapük', 'fr': 'Französisch', 'sm': 'Samoanisch', 'fy': 'Friesisch', 'fa': 'Persisch', 'fi': 'Finnisch', 'fj': 'Fidschianisch', 'sa': 'Sanskrit', 'fo': 'Färöisch', 'ka': 'Georgisch', 'kk': 'Kasachisch', 'sr': 'Serbisch', 'sq': 'Albanisch', 'ko': 'Koreanisch', 'kn': 'Kannada', 'km': 'Kambodschanisch', 'kl': 'Grönländisch', 'ks': 'Kaschmirisch', 'si': 'Singhalesisch', 'sh': 'Serbo-Kroatisch', 'so': 'Somali', 'sn': 'Shona', 'ku': 'Kurdisch', 'sl': 'Slowenisch', 'ky': 'Kirgisisch', 'sg': 'Sango', 'sd': 'Sindhi'}
countries = {'BD': 'Bangladesh', 'RW': 'Rwanda', 'DJ': 'Djibouti', 'BN': 'Brunei', 'MH': 'Marshall-Inseln', 'ST': 'Sao Tomé und Principe', 'BW': 'Botswana', 'GB': 'Grossbritannien', 'SB': 'Salomon-Inseln', 'ZW': 'Zimbabwe', 'CV': 'Kapverden'}
months = [
 'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
abbrMonths = [
 'Jan', 'Feb', 'Mrz', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']
days = [
 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag']
abbrDays = [
 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So']
dateFormats = {'medium': '%d.%m.%Y', 'full': '%%(dayname)s, %d. %%(monthname)s %Y', 'long': '%d. %%(monthname)s %Y', 'short': '%d.%m.%y'}
numericSymbols = {'group': "'", 'nativeZeroDigit': '0', 'exponential': 'E', 'perMille': '‰', 'nan': '�', 'decimal': '.', 'percentSign': '%', 'list': ';', 'patternDigit': '#', 'plusSign': '+', 'infinity': '∞', 'minusSign': '-'}