# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.14-intel/egg/tnefparse/mapi.py
# Compiled at: 2018-12-01 10:41:34
"""MAPI attribute definitions"""
import logging, sys
from decimal import Decimal
from .util import apptime, dbl64, float32, guid, int8, int16, int32, int64, systime, uint8, uint16, uint32, uint64
if sys.hexversion < 50331648:
    range = xrange
logger = logging.getLogger('mapi-decode')
SZMAPI_UNSPECIFIED = 0
SZMAPI_NULL = 1
SZMAPI_SHORT = 2
SZMAPI_INT = 3
SZMAPI_FLOAT = 4
SZMAPI_DOUBLE = 5
SZMAPI_CURRENCY = 6
SZMAPI_APPTIME = 7
SZMAPI_ERROR = 10
SZMAPI_BOOLEAN = 11
SZMAPI_OBJECT = 13
SZMAPI_INT8BYTE = 20
SZMAPI_STRING = 30
SZMAPI_UNICODE_STRING = 31
SZMAPI_SYSTIME = 64
SZMAPI_CLSID = 72
SZMAPI_BINARY = 258
SZMAPI_BEATS_THE_HELL_OUTTA_ME = 51
MULTI_VALUE_FLAG = 4096
GUID_EXISTS_FLAG = 32768

def decode_mapi(data, codepage='cp1252', starting_offset=None):
    """decode MAPI types"""
    dataLen = len(data)
    attrs = []
    offset = starting_offset or 0
    num_properties = uint32(data[offset:offset + 4])
    offset += 4
    try:
        for i in range(num_properties):
            if offset >= dataLen:
                logger.warn("Skipping property '%i'" % i)
                continue
            attr_type = uint16(data[offset:offset + 2])
            offset += 2
            attr_name = uint16(data[offset:offset + 2])
            offset += 2
            guid_id = ''
            guid_name = None
            guid_prop = None
            if attr_name >= GUID_EXISTS_FLAG:
                guid_id = guid(data, offset)
                offset += 16
                kind = uint32(data[offset:offset + 4])
                offset += 4
                if kind == 0:
                    guid_prop = uint32(data[offset:offset + 4])
                    offset += 4
                else:
                    iidLen = uint32(data[offset:offset + 4])
                    offset += 4
                    q, r = divmod(iidLen, 4)
                    if r != 0:
                        iidLen += 4 - r
                    guid_name = data[offset:offset + iidLen].decode('utf-16')
                    offset += iidLen
            num_mv_properties = None
            if MULTI_VALUE_FLAG & attr_type:
                attr_type ^= MULTI_VALUE_FLAG
                num_mv_properties = uint32(data[offset:offset + 4])
                offset += 4
            for mv in range(num_mv_properties or 1):
                try:
                    attr_data, offset = parse_property(data, offset, attr_name, attr_type, codepage, num_mv_properties)
                    attr = TNEFMAPI_Attribute(attr_type, attr_name, attr_data, guid_id, guid_name, guid_prop)
                    attrs.append(attr)
                except Exception:
                    logger.debug('Attribute type: 0x%4.4x', attr_type)
                    logger.debug('Attribute name: 0x%4.4x (%s)', attr_name, TNEFMAPI_Attribute.codes.get(attr_name))
                    raise

            if (num_mv_properties or 1) % 2 and attr_type in (SZMAPI_SHORT, SZMAPI_BOOLEAN):
                offset += 2

    except Exception as e:
        import traceback
        stack = traceback.format_exc()
        logger.error('decode_mapi Exception %s' % e)
        logger.debug(stack)

    if starting_offset is not None:
        return (offset, attrs)
    else:
        return attrs
        return


def parse_property(data, offset, attr_name, attr_type, codepage, is_multi):
    attr_data = None
    if attr_type in (SZMAPI_SHORT, SZMAPI_BOOLEAN):
        attr_data = data[offset:offset + 2]
        offset += 2
    elif attr_type in (SZMAPI_INT, SZMAPI_FLOAT, SZMAPI_ERROR):
        attr_data = data[offset:offset + 4]
        offset += 4
    elif attr_type in (SZMAPI_DOUBLE, SZMAPI_APPTIME, SZMAPI_CURRENCY, SZMAPI_INT8BYTE, SZMAPI_SYSTIME):
        attr_data = data[offset:offset + 8]
        offset += 8
    elif attr_type == SZMAPI_CLSID:
        attr_data = data[offset:offset + 16]
        offset += 16
    elif attr_type in (SZMAPI_STRING, SZMAPI_UNICODE_STRING, SZMAPI_OBJECT, SZMAPI_BINARY, SZMAPI_UNSPECIFIED):
        if is_multi:
            num_vals = 1
        else:
            num_vals = uint32(data[offset:offset + 4])
            offset += 4
        attr_data = []
        for j in range(num_vals):
            length = uint32(data[offset:offset + 4])
            offset += 4
            q, r = divmod(length, 4)
            if r != 0:
                length += 4 - r
            if attr_type == SZMAPI_UNICODE_STRING:
                attr_data.append(data[offset:offset + length].decode('utf-16'))
            elif attr_type == SZMAPI_STRING:
                attr_data.append(data[offset:offset + length].decode(codepage))
            else:
                attr_data.append(data[offset:offset + length])
            offset += length

    else:
        raise ValueError('Unknown MAPI type 0x%4.4x' % attr_type)
    return (attr_data, offset)


class TNEFMAPI_Attribute(object):
    """represents a mapi attribute

    Property reference docs:

    https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/mapping-canonical-property-names-to-mapi-names#tagged-properties
    https://fossies.org/linux/libpst/xml/MAPI_definitions.pdf

    Most these properties represent PidTag properties
    """
    MAPI_ACKNOWLEDGEMENT_MODE = 1
    MAPI_ALTERNATE_RECIPIENT_ALLOWED = 2
    MAPI_AUTHORIZING_USERS = 3
    MAPI_AUTO_FORWARD_COMMENT = 4
    MAPI_AUTO_FORWARDED = 5
    MAPI_CONTENT_CONFIDENTIALITY_ALGORITHM_ID = 6
    MAPI_CONTENT_CORRELATOR = 7
    MAPI_CONTENT_IDENTIFIER = 8
    MAPI_CONTENT_LENGTH = 9
    MAPI_CONTENT_RETURN_REQUESTED = 10
    MAPI_CONVERSATION_KEY = 11
    MAPI_CONVERSION_EITS = 12
    MAPI_CONVERSION_WITH_LOSS_PROHIBITED = 13
    MAPI_CONVERTED_EITS = 14
    MAPI_DEFERRED_DELIVERY_TIME = 15
    MAPI_DELIVER_TIME = 16
    MAPI_DISCARD_REASON = 17
    MAPI_DISCLOSURE_OF_RECIPIENTS = 18
    MAPI_DL_EXPANSION_HISTORY = 19
    MAPI_DL_EXPANSION_PROHIBITED = 20
    MAPI_EXPIRY_TIME = 21
    MAPI_IMPLICIT_CONVERSION_PROHIBITED = 22
    MAPI_IMPORTANCE = 23
    MAPI_IPM_ID = 24
    MAPI_LATEST_DELIVERY_TIME = 25
    MAPI_MESSAGE_CLASS = 26
    MAPI_MESSAGE_DELIVERY_ID = 27
    MAPI_MESSAGE_SECURITY_LABEL = 30
    MAPI_OBSOLETED_IPMS = 31
    MAPI_ORIGINALLY_INTENDED_RECIPIENT_NAME = 32
    MAPI_ORIGINAL_EITS = 33
    MAPI_ORIGINATOR_CERTIFICATE = 34
    MAPI_ORIGINATOR_DELIVERY_REPORT_REQUESTED = 35
    MAPI_ORIGINATOR_RETURN_ADDRESS = 36
    MAPI_PARENT_KEY = 37
    MAPI_PRIORITY = 38
    MAPI_ORIGIN_CHECK = 39
    MAPI_PROOF_OF_SUBMISSION_REQUESTED = 40
    MAPI_READ_RECEIPT_REQUESTED = 41
    MAPI_RECEIPT_TIME = 42
    MAPI_RECIPIENT_REASSIGNMENT_PROHIBITED = 43
    MAPI_REDIRECTION_HISTORY = 44
    MAPI_RELATED_IPMS = 45
    MAPI_ORIGINAL_SENSITIVITY = 46
    MAPI_LANGUAGES = 47
    MAPI_REPLY_TIME = 48
    MAPI_REPORT_TAG = 49
    MAPI_REPORT_TIME = 50
    MAPI_RETURNED_IPM = 51
    MAPI_SECURITY = 52
    MAPI_INCOMPLETE_COPY = 53
    MAPI_SENSITIVITY = 54
    MAPI_SUBJECT = 55
    MAPI_SUBJECT_IPM = 56
    MAPI_CLIENT_SUBMIT_TIME = 57
    MAPI_REPORT_NAME = 58
    MAPI_SENT_REPRESENTING_SEARCH_KEY = 59
    MAPI_X400_CONTENT_TYPE = 60
    MAPI_SUBJECT_PREFIX = 61
    MAPI_NON_RECEIPT_REASON = 62
    MAPI_RECEIVED_BY_ENTRYID = 63
    MAPI_RECEIVED_BY_NAME = 64
    MAPI_SENT_REPRESENTING_ENTRYID = 65
    MAPI_SENT_REPRESENTING_NAME = 66
    MAPI_RCVD_REPRESENTING_ENTRYID = 67
    MAPI_RCVD_REPRESENTING_NAME = 68
    MAPI_REPORT_ENTRYID = 69
    MAPI_READ_RECEIPT_ENTRYID = 70
    MAPI_MESSAGE_SUBMISSION_ID = 71
    MAPI_PROVIDER_SUBMIT_TIME = 72
    MAPI_ORIGINAL_SUBJECT = 73
    MAPI_DISC_VAL = 74
    MAPI_ORIG_MESSAGE_CLASS = 75
    MAPI_ORIGINAL_AUTHOR_ENTRYID = 76
    MAPI_ORIGINAL_AUTHOR_NAME = 77
    MAPI_ORIGINAL_SUBMIT_TIME = 78
    MAPI_REPLY_RECIPIENT_ENTRIES = 79
    MAPI_REPLY_RECIPIENT_NAMES = 80
    MAPI_RECEIVED_BY_SEARCH_KEY = 81
    MAPI_RCVD_REPRESENTING_SEARCH_KEY = 82
    MAPI_READ_RECEIPT_SEARCH_KEY = 83
    MAPI_REPORT_SEARCH_KEY = 84
    MAPI_ORIGINAL_DELIVERY_TIME = 85
    MAPI_ORIGINAL_AUTHOR_SEARCH_KEY = 86
    MAPI_MESSAGE_TO_ME = 87
    MAPI_MESSAGE_CC_ME = 88
    MAPI_MESSAGE_RECIP_ME = 89
    MAPI_ORIGINAL_SENDER_NAME = 90
    MAPI_ORIGINAL_SENDER_ENTRYID = 91
    MAPI_ORIGINAL_SENDER_SEARCH_KEY = 92
    MAPI_ORIGINAL_SENT_REPRESENTING_NAME = 93
    MAPI_ORIGINAL_SENT_REPRESENTING_ENTRYID = 94
    MAPI_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY = 95
    MAPI_START_DATE = 96
    MAPI_END_DATE = 97
    MAPI_OWNER_APPT_ID = 98
    MAPI_RESPONSE_REQUESTED = 99
    MAPI_SENT_REPRESENTING_ADDRTYPE = 100
    MAPI_SENT_REPRESENTING_EMAIL_ADDRESS = 101
    MAPI_ORIGINAL_SENDER_ADDRTYPE = 102
    MAPI_ORIGINAL_SENDER_EMAIL_ADDRESS = 103
    MAPI_ORIGINAL_SENT_REPRESENTING_ADDRTYPE = 104
    MAPI_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS = 105
    MAPI_CONVERSATION_TOPIC = 112
    MAPI_CONVERSATION_INDEX = 113
    MAPI_ORIGINAL_DISPLAY_BCC = 114
    MAPI_ORIGINAL_DISPLAY_CC = 115
    MAPI_ORIGINAL_DISPLAY_TO = 116
    MAPI_RECEIVED_BY_ADDRTYPE = 117
    MAPI_RECEIVED_BY_EMAIL_ADDRESS = 118
    MAPI_RCVD_REPRESENTING_ADDRTYPE = 119
    MAPI_RCVD_REPRESENTING_EMAIL_ADDRESS = 120
    MAPI_ORIGINAL_AUTHOR_ADDRTYPE = 121
    MAPI_ORIGINAL_AUTHOR_EMAIL_ADDRESS = 122
    MAPI_ORIGINALLY_INTENDED_RECIP_ADDRTYPE = 123
    MAPI_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS = 124
    MAPI_TRANSPORT_MESSAGE_HEADERS = 125
    MAPI_DELEGATION = 126
    MAPI_TNEF_CORRELATION_KEY = 127
    MAPI_BODY = 4096
    MAPI_REPORT_TEXT = 4097
    MAPI_ORIGINATOR_AND_DL_EXPANSION_HISTORY = 4098
    MAPI_REPORTING_DL_NAME = 4099
    MAPI_REPORTING_MTA_CERTIFICATE = 4100
    MAPI_RTF_SYNC_BODY_CRC = 4102
    MAPI_RTF_SYNC_BODY_COUNT = 4103
    MAPI_RTF_SYNC_BODY_TAG = 4104
    MAPI_RTF_COMPRESSED = 4105
    MAPI_RTF_SYNC_PREFIX_COUNT = 4112
    MAPI_RTF_SYNC_TRAILING_COUNT = 4113
    MAPI_ORIGINALLY_INTENDED_RECIP_ENTRYID = 4114
    MAPI_BODY_HTML = 4115
    MAPI_SMTP_MESSAGE_ID = 4149
    MAPI_CONTENT_INTEGRITY_CHECK = 3072
    MAPI_EXPLICIT_CONVERSION = 3073
    MAPI_IPM_RETURN_REQUESTED = 3074
    MAPI_MESSAGE_TOKEN = 3075
    MAPI_NDR_REASON_CODE = 3076
    MAPI_NDR_DIAG_CODE = 3077
    MAPI_NON_RECEIPT_NOTIFICATION_REQUESTED = 3078
    MAPI_DELIVERY_POINT = 3079
    MAPI_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED = 3080
    MAPI_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT = 3081
    MAPI_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY = 3082
    MAPI_PHYSICAL_DELIVERY_MODE = 3083
    MAPI_PHYSICAL_DELIVERY_REPORT_REQUEST = 3084
    MAPI_PHYSICAL_FORWARDING_ADDRESS = 3085
    MAPI_PHYSICAL_FORWARDING_ADDRESS_REQUESTED = 3086
    MAPI_PHYSICAL_FORWARDING_PROHIBITED = 3087
    MAPI_PHYSICAL_RENDITION_ATTRIBUTES = 3088
    MAPI_PROOF_OF_DELIVERY = 3089
    MAPI_PROOF_OF_DELIVERY_REQUESTED = 3090
    MAPI_RECIPIENT_CERTIFICATE = 3091
    MAPI_RECIPIENT_NUMBER_FOR_ADVICE = 3092
    MAPI_RECIPIENT_TYPE = 3093
    MAPI_REGISTERED_MAIL_TYPE = 3094
    MAPI_REPLY_REQUESTED = 3095
    MAPI_REQUESTED_DELIVERY_METHOD = 3096
    MAPI_SENDER_ENTRYID = 3097
    MAPI_SENDER_NAME = 3098
    MAPI_SUPPLEMENTARY_INFO = 3099
    MAPI_TYPE_OF_MTS_USER = 3100
    MAPI_SENDER_SEARCH_KEY = 3101
    MAPI_SENDER_ADDRTYPE = 3102
    MAPI_SENDER_EMAIL_ADDRESS = 3103
    MAPI_CURRENT_VERSION = 3584
    MAPI_DELETE_AFTER_SUBMIT = 3585
    MAPI_DISPLAY_BCC = 3586
    MAPI_DISPLAY_CC = 3587
    MAPI_DISPLAY_TO = 3588
    MAPI_PARENT_DISPLAY = 3589
    MAPI_MESSAGE_DELIVERY_TIME = 3590
    MAPI_MESSAGE_FLAGS = 3591
    MAPI_MESSAGE_SIZE = 3592
    MAPI_PARENT_ENTRYID = 3593
    MAPI_SENTMAIL_ENTRYID = 3594
    MAPI_CORRELATE = 3596
    MAPI_CORRELATE_MTSID = 3597
    MAPI_DISCRETE_VALUES = 3598
    MAPI_RESPONSIBILITY = 3599
    MAPI_SPOOLER_STATUS = 3600
    MAPI_TRANSPORT_STATUS = 3601
    MAPI_MESSAGE_RECIPIENTS = 3602
    MAPI_MESSAGE_ATTACHMENTS = 3603
    MAPI_SUBMIT_FLAGS = 3604
    MAPI_RECIPIENT_STATUS = 3605
    MAPI_TRANSPORT_KEY = 3606
    MAPI_MSG_STATUS = 3607
    MAPI_MESSAGE_DOWNLOAD_TIME = 3608
    MAPI_CREATION_VERSION = 3609
    MAPI_MODIFY_VERSION = 3610
    MAPI_HASATTACH = 3611
    MAPI_BODY_CRC = 3612
    MAPI_NORMALIZED_SUBJECT = 3613
    MAPI_RTF_IN_SYNC = 3615
    MAPI_ATTACH_SIZE = 3616
    MAPI_ATTACH_NUM = 3617
    MAPI_PREPROCESS = 3618
    MAPI_ORIGINATING_MTA_CERTIFICATE = 3621
    MAPI_PROOF_OF_SUBMISSION = 3622
    MAPI_ENTRYID = 4095
    MAPI_OBJECT_TYPE = 4094
    MAPI_ICON = 4093
    MAPI_MINI_ICON = 4092
    MAPI_STORE_ENTRYID = 4091
    MAPI_STORE_RECORD_KEY = 4090
    MAPI_RECORD_KEY = 4089
    MAPI_MAPPING_SIGNATURE = 4088
    MAPI_ACCESS_LEVEL = 4087
    MAPI_INSTANCE_KEY = 4086
    MAPI_ROW_TYPE = 4085
    MAPI_ACCESS = 4084
    MAPI_ROWID = 12288
    MAPI_DISPLAY_NAME = 12289
    MAPI_ADDRTYPE = 12290
    MAPI_EMAIL_ADDRESS = 12291
    MAPI_COMMENT = 12292
    MAPI_DEPTH = 12293
    MAPI_PROVIDER_DISPLAY = 12294
    MAPI_CREATION_TIME = 12295
    MAPI_LAST_MODIFICATION_TIME = 12296
    MAPI_RESOURCE_FLAGS = 12297
    MAPI_PROVIDER_DLL_NAME = 12298
    MAPI_SEARCH_KEY = 12299
    MAPI_PROVIDER_UID = 12300
    MAPI_PROVIDER_ORDINAL = 12301
    MAPI_FORM_VERSION = 13057
    MAPI_FORM_CLSID = 13058
    MAPI_FORM_CONTACT_NAME = 13059
    MAPI_FORM_CATEGORY = 13060
    MAPI_FORM_CATEGORY_SUB = 13061
    MAPI_FORM_HOST_MAP = 13062
    MAPI_FORM_HIDDEN = 13063
    MAPI_FORM_DESIGNER_NAME = 13064
    MAPI_FORM_DESIGNER_GUID = 13065
    MAPI_FORM_MESSAGE_BEHAVIOR = 13066
    MAPI_DEFAULT_STORE = 13312
    MAPI_STORE_SUPPORT_MASK = 13325
    MAPI_STORE_STATE = 13326
    MAPI_IPM_SUBTREE_SEARCH_KEY = 13328
    MAPI_IPM_OUTBOX_SEARCH_KEY = 13329
    MAPI_IPM_WASTEBASKET_SEARCH_KEY = 13330
    MAPI_IPM_SENTMAIL_SEARCH_KEY = 13331
    MAPI_MDB_PROVIDER = 13332
    MAPI_RECEIVE_FOLDER_SETTINGS = 13333
    MAPI_VALID_FOLDER_MASK = 13791
    MAPI_IPM_SUBTREE_ENTRYID = 13792
    MAPI_IPM_OUTBOX_ENTRYID = 13794
    MAPI_IPM_WASTEBASKET_ENTRYID = 13795
    MAPI_IPM_SENTMAIL_ENTRYID = 13796
    MAPI_VIEWS_ENTRYID = 13797
    MAPI_COMMON_VIEWS_ENTRYID = 13798
    MAPI_FINDER_ENTRYID = 13799
    MAPI_CONTAINER_FLAGS = 13824
    MAPI_FOLDER_TYPE = 13825
    MAPI_CONTENT_COUNT = 13826
    MAPI_CONTENT_UNREAD = 13827
    MAPI_CREATE_TEMPLATES = 13828
    MAPI_DETAILS_TABLE = 13829
    MAPI_SEARCH = 13831
    MAPI_SELECTABLE = 13833
    MAPI_SUBFOLDERS = 13834
    MAPI_STATUS = 13835
    MAPI_ANR = 13836
    MAPI_CONTENTS_SORT_ORDER = 13837
    MAPI_CONTAINER_HIERARCHY = 13838
    MAPI_CONTAINER_CONTENTS = 13839
    MAPI_FOLDER_ASSOCIATED_CONTENTS = 13840
    MAPI_DEF_CREATE_DL = 13841
    MAPI_DEF_CREATE_MAILUSER = 13842
    MAPI_CONTAINER_CLASS = 13843
    MAPI_CONTAINER_MODIFY_VERSION = 13844
    MAPI_AB_PROVIDER_ID = 13845
    MAPI_DEFAULT_VIEW_ENTRYID = 13846
    MAPI_ASSOC_CONTENT_COUNT = 13847
    MAPI_ATTACHMENT_X400_PARAMETERS = 14080
    MAPI_ATTACH_DATA_OBJ = 14081
    MAPI_ATTACH_ENCODING = 14082
    MAPI_ATTACH_EXTENSION = 14083
    MAPI_ATTACH_FILENAME = 14084
    MAPI_ATTACH_METHOD = 14085
    MAPI_ATTACH_LONG_FILENAME = 14087
    MAPI_ATTACH_PATHNAME = 14088
    MAPI_ATTACH_RENDERING = 14089
    MAPI_ATTACH_TAG = 14090
    MAPI_RENDERING_POSITION = 14091
    MAPI_ATTACH_TRANSPORT_NAME = 14092
    MAPI_ATTACH_LONG_PATHNAME = 14093
    MAPI_ATTACH_MIME_TAG = 14094
    MAPI_ATTACH_ADDITIONAL_INFO = 14095
    MAPI_ATTACH_MIME_SEQUENCE = 14096
    MAPI_ATTACH_CONTENT_ID = 14098
    MAPI_ATTACH_CONTENT_LOCATION = 14099
    MAPI_ATTACH_FLAGS = 14100
    MAPI_DISPLAY_TYPE = 14592
    MAPI_TEMPLATEID = 14594
    MAPI_PRIMARY_CAPABILITY = 14596
    MAPI_7BIT_DISPLAY_NAME = 14847
    MAPI_ACCOUNT = 14848
    MAPI_ALTERNATE_RECIPIENT = 14849
    MAPI_CALLBACK_TELEPHONE_NUMBER = 14850
    MAPI_CONVERSION_PROHIBITED = 14851
    MAPI_DISCLOSE_RECIPIENTS = 14852
    MAPI_GENERATION = 14853
    MAPI_GIVEN_NAME = 14854
    MAPI_GOVERNMENT_ID_NUMBER = 14855
    MAPI_BUSINESS_TELEPHONE_NUMBER = 14856
    MAPI_HOME_TELEPHONE_NUMBER = 14857
    MAPI_INITIALS = 14858
    MAPI_KEYWORD = 14859
    MAPI_LANGUAGE = 14860
    MAPI_LOCATION = 14861
    MAPI_MAIL_PERMISSION = 14862
    MAPI_MHS_COMMON_NAME = 14863
    MAPI_ORGANIZATIONAL_ID_NUMBER = 14864
    MAPI_SURNAME = 14865
    MAPI_ORIGINAL_ENTRYID = 14866
    MAPI_ORIGINAL_DISPLAY_NAME = 14867
    MAPI_ORIGINAL_SEARCH_KEY = 14868
    MAPI_POSTAL_ADDRESS = 14869
    MAPI_COMPANY_NAME = 14870
    MAPI_TITLE = 14871
    MAPI_DEPARTMENT_NAME = 14872
    MAPI_OFFICE_LOCATION = 14873
    MAPI_PRIMARY_TELEPHONE_NUMBER = 14874
    MAPI_BUSINESS2_TELEPHONE_NUMBER = 14875
    MAPI_MOBILE_TELEPHONE_NUMBER = 14876
    MAPI_RADIO_TELEPHONE_NUMBER = 14877
    MAPI_CAR_TELEPHONE_NUMBER = 14878
    MAPI_OTHER_TELEPHONE_NUMBER = 14879
    MAPI_TRANSMITABLE_DISPLAY_NAME = 14880
    MAPI_PAGER_TELEPHONE_NUMBER = 14881
    MAPI_USER_CERTIFICATE = 14882
    MAPI_PRIMARY_FAX_NUMBER = 14883
    MAPI_BUSINESS_FAX_NUMBER = 14884
    MAPI_HOME_FAX_NUMBER = 14885
    MAPI_COUNTRY = 14886
    MAPI_LOCALITY = 14887
    MAPI_STATE_OR_PROVINCE = 14888
    MAPI_STREET_ADDRESS = 14889
    MAPI_POSTAL_CODE = 14890
    MAPI_POST_OFFICE_BOX = 14891
    MAPI_TELEX_NUMBER = 14892
    MAPI_ISDN_NUMBER = 14893
    MAPI_ASSISTANT_TELEPHONE_NUMBER = 14894
    MAPI_HOME2_TELEPHONE_NUMBER = 14895
    MAPI_ASSISTANT = 14896
    MAPI_SEND_RICH_INFO = 14912
    MAPI_WEDDING_ANNIVERSARY = 14913
    MAPI_BIRTHDAY = 14914
    MAPI_HOBBIES = 14915
    MAPI_MIDDLE_NAME = 14916
    MAPI_DISPLAY_NAME_PREFIX = 14917
    MAPI_PROFESSION = 14918
    MAPI_PREFERRED_BY_NAME = 14919
    MAPI_SPOUSE_NAME = 14920
    MAPI_COMPUTER_NETWORK_NAME = 14921
    MAPI_CUSTOMER_ID = 14922
    MAPI_TTYTDD_PHONE_NUMBER = 14923
    MAPI_FTP_SITE = 14924
    MAPI_GENDER = 14925
    MAPI_MANAGER_NAME = 14926
    MAPI_NICKNAME = 14927
    MAPI_PERSONAL_HOME_PAGE = 14928
    MAPI_BUSINESS_HOME_PAGE = 14929
    MAPI_CONTACT_VERSION = 14930
    MAPI_CONTACT_ENTRYIDS = 14931
    MAPI_CONTACT_ADDRTYPES = 14932
    MAPI_CONTACT_DEFAULT_ADDRESS_INDEX = 14933
    MAPI_CONTACT_EMAIL_ADDRESSES = 14934
    MAPI_COMPANY_MAIN_PHONE_NUMBER = 14935
    MAPI_CHILDRENS_NAMES = 14936
    MAPI_HOME_ADDRESS_CITY = 14937
    MAPI_HOME_ADDRESS_COUNTRY = 14938
    MAPI_HOME_ADDRESS_POSTAL_CODE = 14939
    MAPI_HOME_ADDRESS_STATE_OR_PROVINCE = 14940
    MAPI_HOME_ADDRESS_STREET = 14941
    MAPI_HOME_ADDRESS_POST_OFFICE_BOX = 14942
    MAPI_OTHER_ADDRESS_CITY = 14943
    MAPI_OTHER_ADDRESS_COUNTRY = 14944
    MAPI_OTHER_ADDRESS_POSTAL_CODE = 14945
    MAPI_OTHER_ADDRESS_STATE_OR_PROVINCE = 14946
    MAPI_OTHER_ADDRESS_STREET = 14947
    MAPI_OTHER_ADDRESS_POST_OFFICE_BOX = 14948
    MAPI_STORE_PROVIDERS = 15616
    MAPI_AB_PROVIDERS = 15617
    MAPI_TRANSPORT_PROVIDERS = 15618
    MAPI_DEFAULT_PROFILE = 15620
    MAPI_AB_SEARCH_PATH = 15621
    MAPI_AB_DEFAULT_DIR = 15622
    MAPI_AB_DEFAULT_PAB = 15623
    MAPI_FILTERING_HOOKS = 15624
    MAPI_SERVICE_NAME = 15625
    MAPI_SERVICE_DLL_NAME = 15626
    MAPI_SERVICE_ENTRY_NAME = 15627
    MAPI_SERVICE_UID = 15628
    MAPI_SERVICE_EXTRA_UIDS = 15629
    MAPI_SERVICES = 15630
    MAPI_SERVICE_SUPPORT_FILES = 15631
    MAPI_SERVICE_DELETE_FILES = 15632
    MAPI_AB_SEARCH_PATH_UPDATE = 15633
    MAPI_PROFILE_NAME = 15634
    MAPI_IDENTITY_DISPLAY = 15872
    MAPI_IDENTITY_ENTRYID = 15873
    MAPI_RESOURCE_METHODS = 15874
    MAPI_RESOURCE_TYPE = 15875
    MAPI_STATUS_CODE = 15876
    MAPI_IDENTITY_SEARCH_KEY = 15877
    MAPI_OWN_STORE_ENTRYID = 15878
    MAPI_RESOURCE_PATH = 15879
    MAPI_STATUS_STRING = 15880
    MAPI_X400_DEFERRED_DELIVERY_CANCEL = 15881
    MAPI_HEADER_FOLDER_ENTRYID = 15882
    MAPI_REMOTE_PROGRESS = 15883
    MAPI_REMOTE_PROGRESS_TEXT = 15884
    MAPI_REMOTE_VALIDATE_OK = 15885
    MAPI_CONTROL_FLAGS = 16128
    MAPI_CONTROL_STRUCTURE = 16129
    MAPI_CONTROL_TYPE = 16130
    MAPI_DELTAX = 16131
    MAPI_DELTAY = 16132
    MAPI_XPOS = 16133
    MAPI_YPOS = 16134
    MAPI_CONTROL_ID = 16135
    MAPI_INITIAL_DETAILS_PANE = 16136
    UNCOMPRESSED_BODY = 16345
    MAPI_PRIMARY_SEND_ACCOUNT = 3624
    MAPI_NEXT_SEND_ACCT = 3625
    MAPI_INTERNET_REFERENCES = 4153
    MAPI_IN_REPLY_TO_ID = 4162
    MAPI_INTERNET_RETURN_PATH = 4166
    MAPI_ICON_INDEX = 4224
    MAPI_TARGET_ENTRY_ID = 12304
    MAPI_CONVERSATION_ID = 12307
    MAPI_STORE_UNICODE_MASK = 13327
    MAPI_INTERNET_CODEPAGE = 16350
    MAPI_MESSAGE_LOCALE_ID = 16369
    MAPI_CREATOR_NAME = 16376
    MAPI_CREATOR_ENTRY_ID = 16377
    MAPI_LAST_MODIFIER_ENTRY_ID = 16379
    MAPI_MESSAGE_CODEPAGE = 16381
    MAPI_INTERNET_MAIL_OVERRIDE_FORMAT = 22786
    MAPI_MESSAGE_EDITOR_FORMAT = 22793
    MAPI_SENDER_SMTP_ADDRESS = 23809
    MAPI_SENT_REPRESENTING_SMTP_ADDRESS = 23810
    MAPI_READ_RECEIPT_SMTP_ADDRESS = 23813
    MAPI_RECEIVED_BY_SMTP_ADDRESS = 23815
    MAPI_RECEIVED_REPRESENTING_SMTP_ADDRESS = 23816
    MAPI_SIP_ADDRESS = 24549
    MAPI_ATTACHMENT_LINK_ID = 32762
    MAPI_EXCEPTION_START_TIME = 32763
    MAPI_EXCEPTION_END_TIME = 32764
    MAPI_ATTACHMENT_FLAGS = 32765
    MAPI_ATTACHMENT_HIDDEN = 32766
    MAPI_ATTACHMENT_CONTACT_PHOTO = 32767
    MAPI_ID_SECURE_MIN = 26608
    MAPI_ID_SECURE_MAX = 26623
    codes = {MAPI_ACKNOWLEDGEMENT_MODE: 'MAPI_ACKNOWLEDGEMENT_MODE', 
       MAPI_ALTERNATE_RECIPIENT_ALLOWED: 'MAPI_ALTERNATE_RECIPIENT_ALLOWED', 
       MAPI_AUTHORIZING_USERS: 'MAPI_AUTHORIZING_USERS', 
       MAPI_AUTO_FORWARD_COMMENT: 'MAPI_AUTO_FORWARD_COMMENT', 
       MAPI_AUTO_FORWARDED: 'MAPI_AUTO_FORWARDED', 
       MAPI_CONTENT_CONFIDENTIALITY_ALGORITHM_ID: 'MAPI_CONTENT_CONFIDENTIALITY_ALGORITHM_ID', 
       MAPI_CONTENT_CORRELATOR: 'MAPI_CONTENT_CORRELATOR', 
       MAPI_CONTENT_IDENTIFIER: 'MAPI_CONTENT_IDENTIFIER', 
       MAPI_CONTENT_LENGTH: 'MAPI_CONTENT_LENGTH', 
       MAPI_CONTENT_RETURN_REQUESTED: 'MAPI_CONTENT_RETURN_REQUESTED', 
       MAPI_CONVERSATION_KEY: 'MAPI_CONVERSATION_KEY', 
       MAPI_CONVERSION_EITS: 'MAPI_CONVERSION_EITS', 
       MAPI_CONVERSION_WITH_LOSS_PROHIBITED: 'MAPI_CONVERSION_WITH_LOSS_PROHIBITED', 
       MAPI_CONVERTED_EITS: 'MAPI_CONVERTED_EITS', 
       MAPI_DEFERRED_DELIVERY_TIME: 'MAPI_DEFERRED_DELIVERY_TIME', 
       MAPI_DELIVER_TIME: 'MAPI_DELIVER_TIME', 
       MAPI_DISCARD_REASON: 'MAPI_DISCARD_REASON', 
       MAPI_DISCLOSURE_OF_RECIPIENTS: 'MAPI_DISCLOSURE_OF_RECIPIENTS', 
       MAPI_DL_EXPANSION_HISTORY: 'MAPI_DL_EXPANSION_HISTORY', 
       MAPI_DL_EXPANSION_PROHIBITED: 'MAPI_DL_EXPANSION_PROHIBITED', 
       MAPI_EXPIRY_TIME: 'MAPI_EXPIRY_TIME', 
       MAPI_IMPLICIT_CONVERSION_PROHIBITED: 'MAPI_IMPLICIT_CONVERSION_PROHIBITED', 
       MAPI_IMPORTANCE: 'MAPI_IMPORTANCE', 
       MAPI_IPM_ID: 'MAPI_IPM_ID', 
       MAPI_LATEST_DELIVERY_TIME: 'MAPI_LATEST_DELIVERY_TIME', 
       MAPI_MESSAGE_CLASS: 'MAPI_MESSAGE_CLASS', 
       MAPI_MESSAGE_DELIVERY_ID: 'MAPI_MESSAGE_DELIVERY_ID', 
       MAPI_MESSAGE_SECURITY_LABEL: 'MAPI_MESSAGE_SECURITY_LABEL', 
       MAPI_OBSOLETED_IPMS: 'MAPI_OBSOLETED_IPMS', 
       MAPI_ORIGINALLY_INTENDED_RECIPIENT_NAME: 'MAPI_ORIGINALLY_INTENDED_RECIPIENT_NAME', 
       MAPI_ORIGINAL_EITS: 'MAPI_ORIGINAL_EITS', 
       MAPI_ORIGINATOR_CERTIFICATE: 'MAPI_ORIGINATOR_CERTIFICATE', 
       MAPI_ORIGINATOR_DELIVERY_REPORT_REQUESTED: 'MAPI_ORIGINATOR_DELIVERY_REPORT_REQUESTED', 
       MAPI_ORIGINATOR_RETURN_ADDRESS: 'MAPI_ORIGINATOR_RETURN_ADDRESS', 
       MAPI_PARENT_KEY: 'MAPI_PARENT_KEY', 
       MAPI_PRIORITY: 'MAPI_PRIORITY', 
       MAPI_ORIGIN_CHECK: 'MAPI_ORIGIN_CHECK', 
       MAPI_PROOF_OF_SUBMISSION_REQUESTED: 'MAPI_PROOF_OF_SUBMISSION_REQUESTED', 
       MAPI_READ_RECEIPT_REQUESTED: 'MAPI_READ_RECEIPT_REQUESTED', 
       MAPI_RECEIPT_TIME: 'MAPI_RECEIPT_TIME', 
       MAPI_RECIPIENT_REASSIGNMENT_PROHIBITED: 'MAPI_RECIPIENT_REASSIGNMENT_PROHIBITED', 
       MAPI_REDIRECTION_HISTORY: 'MAPI_REDIRECTION_HISTORY', 
       MAPI_RELATED_IPMS: 'MAPI_RELATED_IPMS', 
       MAPI_ORIGINAL_SENSITIVITY: 'MAPI_ORIGINAL_SENSITIVITY', 
       MAPI_LANGUAGES: 'MAPI_LANGUAGES', 
       MAPI_REPLY_TIME: 'MAPI_REPLY_TIME', 
       MAPI_REPORT_TAG: 'MAPI_REPORT_TAG', 
       MAPI_REPORT_TIME: 'MAPI_REPORT_TIME', 
       MAPI_RETURNED_IPM: 'MAPI_RETURNED_IPM', 
       MAPI_SECURITY: 'MAPI_SECURITY', 
       MAPI_INCOMPLETE_COPY: 'MAPI_INCOMPLETE_COPY', 
       MAPI_SENSITIVITY: 'MAPI_SENSITIVITY', 
       MAPI_SUBJECT: 'MAPI_SUBJECT', 
       MAPI_SUBJECT_IPM: 'MAPI_SUBJECT_IPM', 
       MAPI_CLIENT_SUBMIT_TIME: 'MAPI_CLIENT_SUBMIT_TIME', 
       MAPI_REPORT_NAME: 'MAPI_REPORT_NAME', 
       MAPI_SENT_REPRESENTING_SEARCH_KEY: 'MAPI_SENT_REPRESENTING_SEARCH_KEY', 
       MAPI_X400_CONTENT_TYPE: 'MAPI_X400_CONTENT_TYPE', 
       MAPI_SUBJECT_PREFIX: 'MAPI_SUBJECT_PREFIX', 
       MAPI_NON_RECEIPT_REASON: 'MAPI_NON_RECEIPT_REASON', 
       MAPI_RECEIVED_BY_ENTRYID: 'MAPI_RECEIVED_BY_ENTRYID', 
       MAPI_RECEIVED_BY_NAME: 'MAPI_RECEIVED_BY_NAME', 
       MAPI_SENT_REPRESENTING_ENTRYID: 'MAPI_SENT_REPRESENTING_ENTRYID', 
       MAPI_SENT_REPRESENTING_NAME: 'MAPI_SENT_REPRESENTING_NAME', 
       MAPI_RCVD_REPRESENTING_ENTRYID: 'MAPI_RCVD_REPRESENTING_ENTRYID', 
       MAPI_RCVD_REPRESENTING_NAME: 'MAPI_RCVD_REPRESENTING_NAME', 
       MAPI_REPORT_ENTRYID: 'MAPI_REPORT_ENTRYID', 
       MAPI_READ_RECEIPT_ENTRYID: 'MAPI_READ_RECEIPT_ENTRYID', 
       MAPI_MESSAGE_SUBMISSION_ID: 'MAPI_MESSAGE_SUBMISSION_ID', 
       MAPI_PROVIDER_SUBMIT_TIME: 'MAPI_PROVIDER_SUBMIT_TIME', 
       MAPI_ORIGINAL_SUBJECT: 'MAPI_ORIGINAL_SUBJECT', 
       MAPI_DISC_VAL: 'MAPI_DISC_VAL', 
       MAPI_ORIG_MESSAGE_CLASS: 'MAPI_ORIG_MESSAGE_CLASS', 
       MAPI_ORIGINAL_AUTHOR_ENTRYID: 'MAPI_ORIGINAL_AUTHOR_ENTRYID', 
       MAPI_ORIGINAL_AUTHOR_NAME: 'MAPI_ORIGINAL_AUTHOR_NAME', 
       MAPI_ORIGINAL_SUBMIT_TIME: 'MAPI_ORIGINAL_SUBMIT_TIME', 
       MAPI_REPLY_RECIPIENT_ENTRIES: 'MAPI_REPLY_RECIPIENT_ENTRIES', 
       MAPI_REPLY_RECIPIENT_NAMES: 'MAPI_REPLY_RECIPIENT_NAMES', 
       MAPI_RECEIVED_BY_SEARCH_KEY: 'MAPI_RECEIVED_BY_SEARCH_KEY', 
       MAPI_RCVD_REPRESENTING_SEARCH_KEY: 'MAPI_RCVD_REPRESENTING_SEARCH_KEY', 
       MAPI_READ_RECEIPT_SEARCH_KEY: 'MAPI_READ_RECEIPT_SEARCH_KEY', 
       MAPI_REPORT_SEARCH_KEY: 'MAPI_REPORT_SEARCH_KEY', 
       MAPI_ORIGINAL_DELIVERY_TIME: 'MAPI_ORIGINAL_DELIVERY_TIME', 
       MAPI_ORIGINAL_AUTHOR_SEARCH_KEY: 'MAPI_ORIGINAL_AUTHOR_SEARCH_KEY', 
       MAPI_MESSAGE_TO_ME: 'MAPI_MESSAGE_TO_ME', 
       MAPI_MESSAGE_CC_ME: 'MAPI_MESSAGE_CC_ME', 
       MAPI_MESSAGE_RECIP_ME: 'MAPI_MESSAGE_RECIP_ME', 
       MAPI_ORIGINAL_SENDER_NAME: 'MAPI_ORIGINAL_SENDER_NAME', 
       MAPI_ORIGINAL_SENDER_ENTRYID: 'MAPI_ORIGINAL_SENDER_ENTRYID', 
       MAPI_ORIGINAL_SENDER_SEARCH_KEY: 'MAPI_ORIGINAL_SENDER_SEARCH_KEY', 
       MAPI_ORIGINAL_SENT_REPRESENTING_NAME: 'MAPI_ORIGINAL_SENT_REPRESENTING_NAME', 
       MAPI_ORIGINAL_SENT_REPRESENTING_ENTRYID: 'MAPI_ORIGINAL_SENT_REPRESENTING_ENTRYID', 
       MAPI_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY: 'MAPI_ORIGINAL_SENT_REPRESENTING_SEARCH_KEY', 
       MAPI_START_DATE: 'MAPI_START_DATE', 
       MAPI_END_DATE: 'MAPI_END_DATE', 
       MAPI_OWNER_APPT_ID: 'MAPI_OWNER_APPT_ID', 
       MAPI_RESPONSE_REQUESTED: 'MAPI_RESPONSE_REQUESTED', 
       MAPI_SENT_REPRESENTING_ADDRTYPE: 'MAPI_SENT_REPRESENTING_ADDRTYPE', 
       MAPI_SENT_REPRESENTING_EMAIL_ADDRESS: 'MAPI_SENT_REPRESENTING_EMAIL_ADDRESS', 
       MAPI_ORIGINAL_SENDER_ADDRTYPE: 'MAPI_ORIGINAL_SENDER_ADDRTYPE', 
       MAPI_ORIGINAL_SENDER_EMAIL_ADDRESS: 'MAPI_ORIGINAL_SENDER_EMAIL_ADDRESS', 
       MAPI_ORIGINAL_SENT_REPRESENTING_ADDRTYPE: 'MAPI_ORIGINAL_SENT_REPRESENTING_ADDRTYPE', 
       MAPI_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS: 'MAPI_ORIGINAL_SENT_REPRESENTING_EMAIL_ADDRESS', 
       MAPI_CONVERSATION_TOPIC: 'MAPI_CONVERSATION_TOPIC', 
       MAPI_CONVERSATION_INDEX: 'MAPI_CONVERSATION_INDEX', 
       MAPI_ORIGINAL_DISPLAY_BCC: 'MAPI_ORIGINAL_DISPLAY_BCC', 
       MAPI_ORIGINAL_DISPLAY_CC: 'MAPI_ORIGINAL_DISPLAY_CC', 
       MAPI_ORIGINAL_DISPLAY_TO: 'MAPI_ORIGINAL_DISPLAY_TO', 
       MAPI_RECEIVED_BY_ADDRTYPE: 'MAPI_RECEIVED_BY_ADDRTYPE', 
       MAPI_RECEIVED_BY_EMAIL_ADDRESS: 'MAPI_RECEIVED_BY_EMAIL_ADDRESS', 
       MAPI_RCVD_REPRESENTING_ADDRTYPE: 'MAPI_RCVD_REPRESENTING_ADDRTYPE', 
       MAPI_RCVD_REPRESENTING_EMAIL_ADDRESS: 'MAPI_RCVD_REPRESENTING_EMAIL_ADDRESS', 
       MAPI_ORIGINAL_AUTHOR_ADDRTYPE: 'MAPI_ORIGINAL_AUTHOR_ADDRTYPE', 
       MAPI_ORIGINAL_AUTHOR_EMAIL_ADDRESS: 'MAPI_ORIGINAL_AUTHOR_EMAIL_ADDRESS', 
       MAPI_ORIGINALLY_INTENDED_RECIP_ADDRTYPE: 'MAPI_ORIGINALLY_INTENDED_RECIP_ADDRTYPE', 
       MAPI_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS: 'MAPI_ORIGINALLY_INTENDED_RECIP_EMAIL_ADDRESS', 
       MAPI_TRANSPORT_MESSAGE_HEADERS: 'MAPI_TRANSPORT_MESSAGE_HEADERS', 
       MAPI_DELEGATION: 'MAPI_DELEGATION', 
       MAPI_TNEF_CORRELATION_KEY: 'MAPI_TNEF_CORRELATION_KEY', 
       MAPI_BODY: 'MAPI_BODY', 
       MAPI_REPORT_TEXT: 'MAPI_REPORT_TEXT', 
       MAPI_ORIGINATOR_AND_DL_EXPANSION_HISTORY: 'MAPI_ORIGINATOR_AND_DL_EXPANSION_HISTORY', 
       MAPI_REPORTING_DL_NAME: 'MAPI_REPORTING_DL_NAME', 
       MAPI_REPORTING_MTA_CERTIFICATE: 'MAPI_REPORTING_MTA_CERTIFICATE', 
       MAPI_RTF_SYNC_BODY_CRC: 'MAPI_RTF_SYNC_BODY_CRC', 
       MAPI_RTF_SYNC_BODY_COUNT: 'MAPI_RTF_SYNC_BODY_COUNT', 
       MAPI_RTF_SYNC_BODY_TAG: 'MAPI_RTF_SYNC_BODY_TAG', 
       MAPI_RTF_COMPRESSED: 'MAPI_RTF_COMPRESSED', 
       MAPI_RTF_SYNC_PREFIX_COUNT: 'MAPI_RTF_SYNC_PREFIX_COUNT', 
       MAPI_RTF_SYNC_TRAILING_COUNT: 'MAPI_RTF_SYNC_TRAILING_COUNT', 
       MAPI_ORIGINALLY_INTENDED_RECIP_ENTRYID: 'MAPI_ORIGINALLY_INTENDED_RECIP_ENTRYID', 
       MAPI_BODY_HTML: 'MAPI_BODY_HTML', 
       MAPI_SMTP_MESSAGE_ID: 'MAPI_SMTP_MESSAGE_ID', 
       MAPI_CONTENT_INTEGRITY_CHECK: 'MAPI_CONTENT_INTEGRITY_CHECK', 
       MAPI_EXPLICIT_CONVERSION: 'MAPI_EXPLICIT_CONVERSION', 
       MAPI_IPM_RETURN_REQUESTED: 'MAPI_IPM_RETURN_REQUESTED', 
       MAPI_MESSAGE_TOKEN: 'MAPI_MESSAGE_TOKEN', 
       MAPI_NDR_REASON_CODE: 'MAPI_NDR_REASON_CODE', 
       MAPI_NDR_DIAG_CODE: 'MAPI_NDR_DIAG_CODE', 
       MAPI_NON_RECEIPT_NOTIFICATION_REQUESTED: 'MAPI_NON_RECEIPT_NOTIFICATION_REQUESTED', 
       MAPI_DELIVERY_POINT: 'MAPI_DELIVERY_POINT', 
       MAPI_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED: 'MAPI_ORIGINATOR_NON_DELIVERY_REPORT_REQUESTED', 
       MAPI_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT: 'MAPI_ORIGINATOR_REQUESTED_ALTERNATE_RECIPIENT', 
       MAPI_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY: 'MAPI_PHYSICAL_DELIVERY_BUREAU_FAX_DELIVERY', 
       MAPI_PHYSICAL_DELIVERY_MODE: 'MAPI_PHYSICAL_DELIVERY_MODE', 
       MAPI_PHYSICAL_DELIVERY_REPORT_REQUEST: 'MAPI_PHYSICAL_DELIVERY_REPORT_REQUEST', 
       MAPI_PHYSICAL_FORWARDING_ADDRESS: 'MAPI_PHYSICAL_FORWARDING_ADDRESS', 
       MAPI_PHYSICAL_FORWARDING_ADDRESS_REQUESTED: 'MAPI_PHYSICAL_FORWARDING_ADDRESS_REQUESTED', 
       MAPI_PHYSICAL_FORWARDING_PROHIBITED: 'MAPI_PHYSICAL_FORWARDING_PROHIBITED', 
       MAPI_PHYSICAL_RENDITION_ATTRIBUTES: 'MAPI_PHYSICAL_RENDITION_ATTRIBUTES', 
       MAPI_PROOF_OF_DELIVERY: 'MAPI_PROOF_OF_DELIVERY', 
       MAPI_PROOF_OF_DELIVERY_REQUESTED: 'MAPI_PROOF_OF_DELIVERY_REQUESTED', 
       MAPI_RECIPIENT_CERTIFICATE: 'MAPI_RECIPIENT_CERTIFICATE', 
       MAPI_RECIPIENT_NUMBER_FOR_ADVICE: 'MAPI_RECIPIENT_NUMBER_FOR_ADVICE', 
       MAPI_RECIPIENT_TYPE: 'MAPI_RECIPIENT_TYPE', 
       MAPI_REGISTERED_MAIL_TYPE: 'MAPI_REGISTERED_MAIL_TYPE', 
       MAPI_REPLY_REQUESTED: 'MAPI_REPLY_REQUESTED', 
       MAPI_REQUESTED_DELIVERY_METHOD: 'MAPI_REQUESTED_DELIVERY_METHOD', 
       MAPI_SENDER_ENTRYID: 'MAPI_SENDER_ENTRYID', 
       MAPI_SENDER_NAME: 'MAPI_SENDER_NAME', 
       MAPI_SUPPLEMENTARY_INFO: 'MAPI_SUPPLEMENTARY_INFO', 
       MAPI_TYPE_OF_MTS_USER: 'MAPI_TYPE_OF_MTS_USER', 
       MAPI_SENDER_SEARCH_KEY: 'MAPI_SENDER_SEARCH_KEY', 
       MAPI_SENDER_ADDRTYPE: 'MAPI_SENDER_ADDRTYPE', 
       MAPI_SENDER_EMAIL_ADDRESS: 'MAPI_SENDER_EMAIL_ADDRESS', 
       MAPI_CURRENT_VERSION: 'MAPI_CURRENT_VERSION', 
       MAPI_DELETE_AFTER_SUBMIT: 'MAPI_DELETE_AFTER_SUBMIT', 
       MAPI_DISPLAY_BCC: 'MAPI_DISPLAY_BCC', 
       MAPI_DISPLAY_CC: 'MAPI_DISPLAY_CC', 
       MAPI_DISPLAY_TO: 'MAPI_DISPLAY_TO', 
       MAPI_PARENT_DISPLAY: 'MAPI_PARENT_DISPLAY', 
       MAPI_MESSAGE_DELIVERY_TIME: 'MAPI_MESSAGE_DELIVERY_TIME', 
       MAPI_MESSAGE_FLAGS: 'MAPI_MESSAGE_FLAGS', 
       MAPI_MESSAGE_SIZE: 'MAPI_MESSAGE_SIZE', 
       MAPI_PARENT_ENTRYID: 'MAPI_PARENT_ENTRYID', 
       MAPI_SENTMAIL_ENTRYID: 'MAPI_SENTMAIL_ENTRYID', 
       MAPI_CORRELATE: 'MAPI_CORRELATE', 
       MAPI_CORRELATE_MTSID: 'MAPI_CORRELATE_MTSID', 
       MAPI_DISCRETE_VALUES: 'MAPI_DISCRETE_VALUES', 
       MAPI_RESPONSIBILITY: 'MAPI_RESPONSIBILITY', 
       MAPI_SPOOLER_STATUS: 'MAPI_SPOOLER_STATUS', 
       MAPI_TRANSPORT_STATUS: 'MAPI_TRANSPORT_STATUS', 
       MAPI_MESSAGE_RECIPIENTS: 'MAPI_MESSAGE_RECIPIENTS', 
       MAPI_MESSAGE_ATTACHMENTS: 'MAPI_MESSAGE_ATTACHMENTS', 
       MAPI_SUBMIT_FLAGS: 'MAPI_SUBMIT_FLAGS', 
       MAPI_RECIPIENT_STATUS: 'MAPI_RECIPIENT_STATUS', 
       MAPI_TRANSPORT_KEY: 'MAPI_TRANSPORT_KEY', 
       MAPI_MSG_STATUS: 'MAPI_MSG_STATUS', 
       MAPI_MESSAGE_DOWNLOAD_TIME: 'MAPI_MESSAGE_DOWNLOAD_TIME', 
       MAPI_CREATION_VERSION: 'MAPI_CREATION_VERSION', 
       MAPI_MODIFY_VERSION: 'MAPI_MODIFY_VERSION', 
       MAPI_HASATTACH: 'MAPI_HASATTACH', 
       MAPI_BODY_CRC: 'MAPI_BODY_CRC', 
       MAPI_NORMALIZED_SUBJECT: 'MAPI_NORMALIZED_SUBJECT', 
       MAPI_RTF_IN_SYNC: 'MAPI_RTF_IN_SYNC', 
       MAPI_ATTACH_SIZE: 'MAPI_ATTACH_SIZE', 
       MAPI_ATTACH_NUM: 'MAPI_ATTACH_NUM', 
       MAPI_PREPROCESS: 'MAPI_PREPROCESS', 
       MAPI_ORIGINATING_MTA_CERTIFICATE: 'MAPI_ORIGINATING_MTA_CERTIFICATE', 
       MAPI_PROOF_OF_SUBMISSION: 'MAPI_PROOF_OF_SUBMISSION', 
       MAPI_ENTRYID: 'MAPI_ENTRYID', 
       MAPI_OBJECT_TYPE: 'MAPI_OBJECT_TYPE', 
       MAPI_ICON: 'MAPI_ICON', 
       MAPI_MINI_ICON: 'MAPI_MINI_ICON', 
       MAPI_STORE_ENTRYID: 'MAPI_STORE_ENTRYID', 
       MAPI_STORE_RECORD_KEY: 'MAPI_STORE_RECORD_KEY', 
       MAPI_RECORD_KEY: 'MAPI_RECORD_KEY', 
       MAPI_MAPPING_SIGNATURE: 'MAPI_MAPPING_SIGNATURE', 
       MAPI_ACCESS_LEVEL: 'MAPI_ACCESS_LEVEL', 
       MAPI_INSTANCE_KEY: 'MAPI_INSTANCE_KEY', 
       MAPI_ROW_TYPE: 'MAPI_ROW_TYPE', 
       MAPI_ACCESS: 'MAPI_ACCESS', 
       MAPI_ROWID: 'MAPI_ROWID', 
       MAPI_DISPLAY_NAME: 'MAPI_DISPLAY_NAME', 
       MAPI_ADDRTYPE: 'MAPI_ADDRTYPE', 
       MAPI_EMAIL_ADDRESS: 'MAPI_EMAIL_ADDRESS', 
       MAPI_COMMENT: 'MAPI_COMMENT', 
       MAPI_DEPTH: 'MAPI_DEPTH', 
       MAPI_PROVIDER_DISPLAY: 'MAPI_PROVIDER_DISPLAY', 
       MAPI_CREATION_TIME: 'MAPI_CREATION_TIME', 
       MAPI_LAST_MODIFICATION_TIME: 'MAPI_LAST_MODIFICATION_TIME', 
       MAPI_RESOURCE_FLAGS: 'MAPI_RESOURCE_FLAGS', 
       MAPI_PROVIDER_DLL_NAME: 'MAPI_PROVIDER_DLL_NAME', 
       MAPI_SEARCH_KEY: 'MAPI_SEARCH_KEY', 
       MAPI_PROVIDER_UID: 'MAPI_PROVIDER_UID', 
       MAPI_PROVIDER_ORDINAL: 'MAPI_PROVIDER_ORDINAL', 
       MAPI_FORM_VERSION: 'MAPI_FORM_VERSION', 
       MAPI_FORM_CLSID: 'MAPI_FORM_CLSID', 
       MAPI_FORM_CONTACT_NAME: 'MAPI_FORM_CONTACT_NAME', 
       MAPI_FORM_CATEGORY: 'MAPI_FORM_CATEGORY', 
       MAPI_FORM_CATEGORY_SUB: 'MAPI_FORM_CATEGORY_SUB', 
       MAPI_FORM_HOST_MAP: 'MAPI_FORM_HOST_MAP', 
       MAPI_FORM_HIDDEN: 'MAPI_FORM_HIDDEN', 
       MAPI_FORM_DESIGNER_NAME: 'MAPI_FORM_DESIGNER_NAME', 
       MAPI_FORM_DESIGNER_GUID: 'MAPI_FORM_DESIGNER_GUID', 
       MAPI_FORM_MESSAGE_BEHAVIOR: 'MAPI_FORM_MESSAGE_BEHAVIOR', 
       MAPI_DEFAULT_STORE: 'MAPI_DEFAULT_STORE', 
       MAPI_STORE_SUPPORT_MASK: 'MAPI_STORE_SUPPORT_MASK', 
       MAPI_STORE_STATE: 'MAPI_STORE_STATE', 
       MAPI_IPM_SUBTREE_SEARCH_KEY: 'MAPI_IPM_SUBTREE_SEARCH_KEY', 
       MAPI_IPM_OUTBOX_SEARCH_KEY: 'MAPI_IPM_OUTBOX_SEARCH_KEY', 
       MAPI_IPM_WASTEBASKET_SEARCH_KEY: 'MAPI_IPM_WASTEBASKET_SEARCH_KEY', 
       MAPI_IPM_SENTMAIL_SEARCH_KEY: 'MAPI_IPM_SENTMAIL_SEARCH_KEY', 
       MAPI_MDB_PROVIDER: 'MAPI_MDB_PROVIDER', 
       MAPI_RECEIVE_FOLDER_SETTINGS: 'MAPI_RECEIVE_FOLDER_SETTINGS', 
       MAPI_VALID_FOLDER_MASK: 'MAPI_VALID_FOLDER_MASK', 
       MAPI_IPM_SUBTREE_ENTRYID: 'MAPI_IPM_SUBTREE_ENTRYID', 
       MAPI_IPM_OUTBOX_ENTRYID: 'MAPI_IPM_OUTBOX_ENTRYID', 
       MAPI_IPM_WASTEBASKET_ENTRYID: 'MAPI_IPM_WASTEBASKET_ENTRYID', 
       MAPI_IPM_SENTMAIL_ENTRYID: 'MAPI_IPM_SENTMAIL_ENTRYID', 
       MAPI_VIEWS_ENTRYID: 'MAPI_VIEWS_ENTRYID', 
       MAPI_COMMON_VIEWS_ENTRYID: 'MAPI_COMMON_VIEWS_ENTRYID', 
       MAPI_FINDER_ENTRYID: 'MAPI_FINDER_ENTRYID', 
       MAPI_CONTAINER_FLAGS: 'MAPI_CONTAINER_FLAGS', 
       MAPI_FOLDER_TYPE: 'MAPI_FOLDER_TYPE', 
       MAPI_CONTENT_COUNT: 'MAPI_CONTENT_COUNT', 
       MAPI_CONTENT_UNREAD: 'MAPI_CONTENT_UNREAD', 
       MAPI_CREATE_TEMPLATES: 'MAPI_CREATE_TEMPLATES', 
       MAPI_DETAILS_TABLE: 'MAPI_DETAILS_TABLE', 
       MAPI_SEARCH: 'MAPI_SEARCH', 
       MAPI_SELECTABLE: 'MAPI_SELECTABLE', 
       MAPI_SUBFOLDERS: 'MAPI_SUBFOLDERS', 
       MAPI_STATUS: 'MAPI_STATUS', 
       MAPI_ANR: 'MAPI_ANR', 
       MAPI_CONTENTS_SORT_ORDER: 'MAPI_CONTENTS_SORT_ORDER', 
       MAPI_CONTAINER_HIERARCHY: 'MAPI_CONTAINER_HIERARCHY', 
       MAPI_CONTAINER_CONTENTS: 'MAPI_CONTAINER_CONTENTS', 
       MAPI_FOLDER_ASSOCIATED_CONTENTS: 'MAPI_FOLDER_ASSOCIATED_CONTENTS', 
       MAPI_DEF_CREATE_DL: 'MAPI_DEF_CREATE_DL', 
       MAPI_DEF_CREATE_MAILUSER: 'MAPI_DEF_CREATE_MAILUSER', 
       MAPI_CONTAINER_CLASS: 'MAPI_CONTAINER_CLASS', 
       MAPI_CONTAINER_MODIFY_VERSION: 'MAPI_CONTAINER_MODIFY_VERSION', 
       MAPI_AB_PROVIDER_ID: 'MAPI_AB_PROVIDER_ID', 
       MAPI_DEFAULT_VIEW_ENTRYID: 'MAPI_DEFAULT_VIEW_ENTRYID', 
       MAPI_ASSOC_CONTENT_COUNT: 'MAPI_ASSOC_CONTENT_COUNT', 
       MAPI_ATTACHMENT_X400_PARAMETERS: 'MAPI_ATTACHMENT_X400_PARAMETERS', 
       MAPI_ATTACH_DATA_OBJ: 'MAPI_ATTACH_DATA_OBJ', 
       MAPI_ATTACH_ENCODING: 'MAPI_ATTACH_ENCODING', 
       MAPI_ATTACH_EXTENSION: 'MAPI_ATTACH_EXTENSION', 
       MAPI_ATTACH_FILENAME: 'MAPI_ATTACH_FILENAME', 
       MAPI_ATTACH_METHOD: 'MAPI_ATTACH_METHOD', 
       MAPI_ATTACH_LONG_FILENAME: 'MAPI_ATTACH_LONG_FILENAME', 
       MAPI_ATTACH_PATHNAME: 'MAPI_ATTACH_PATHNAME', 
       MAPI_ATTACH_RENDERING: 'MAPI_ATTACH_RENDERING', 
       MAPI_ATTACH_TAG: 'MAPI_ATTACH_TAG', 
       MAPI_RENDERING_POSITION: 'MAPI_RENDERING_POSITION', 
       MAPI_ATTACH_TRANSPORT_NAME: 'MAPI_ATTACH_TRANSPORT_NAME', 
       MAPI_ATTACH_LONG_PATHNAME: 'MAPI_ATTACH_LONG_PATHNAME', 
       MAPI_ATTACH_MIME_TAG: 'MAPI_ATTACH_MIME_TAG', 
       MAPI_ATTACH_ADDITIONAL_INFO: 'MAPI_ATTACH_ADDITIONAL_INFO', 
       MAPI_ATTACH_MIME_SEQUENCE: 'MAPI_ATTACH_MIME_SEQUENCE', 
       MAPI_ATTACH_CONTENT_ID: 'MAPI_ATTACH_CONTENT_ID', 
       MAPI_ATTACH_CONTENT_LOCATION: 'MAPI_ATTACH_CONTENT_LOCATION', 
       MAPI_ATTACH_FLAGS: 'MAPI_ATTACH_FLAGS', 
       MAPI_DISPLAY_TYPE: 'MAPI_DISPLAY_TYPE', 
       MAPI_TEMPLATEID: 'MAPI_TEMPLATEID', 
       MAPI_PRIMARY_CAPABILITY: 'MAPI_PRIMARY_CAPABILITY', 
       MAPI_7BIT_DISPLAY_NAME: 'MAPI_7BIT_DISPLAY_NAME', 
       MAPI_ACCOUNT: 'MAPI_ACCOUNT', 
       MAPI_ALTERNATE_RECIPIENT: 'MAPI_ALTERNATE_RECIPIENT', 
       MAPI_CALLBACK_TELEPHONE_NUMBER: 'MAPI_CALLBACK_TELEPHONE_NUMBER', 
       MAPI_CONVERSION_PROHIBITED: 'MAPI_CONVERSION_PROHIBITED', 
       MAPI_DISCLOSE_RECIPIENTS: 'MAPI_DISCLOSE_RECIPIENTS', 
       MAPI_GENERATION: 'MAPI_GENERATION', 
       MAPI_GIVEN_NAME: 'MAPI_GIVEN_NAME', 
       MAPI_GOVERNMENT_ID_NUMBER: 'MAPI_GOVERNMENT_ID_NUMBER', 
       MAPI_BUSINESS_TELEPHONE_NUMBER: 'MAPI_BUSINESS_TELEPHONE_NUMBER', 
       MAPI_HOME_TELEPHONE_NUMBER: 'MAPI_HOME_TELEPHONE_NUMBER', 
       MAPI_INITIALS: 'MAPI_INITIALS', 
       MAPI_KEYWORD: 'MAPI_KEYWORD', 
       MAPI_LANGUAGE: 'MAPI_LANGUAGE', 
       MAPI_LOCATION: 'MAPI_LOCATION', 
       MAPI_MAIL_PERMISSION: 'MAPI_MAIL_PERMISSION', 
       MAPI_MHS_COMMON_NAME: 'MAPI_MHS_COMMON_NAME', 
       MAPI_ORGANIZATIONAL_ID_NUMBER: 'MAPI_ORGANIZATIONAL_ID_NUMBER', 
       MAPI_SURNAME: 'MAPI_SURNAME', 
       MAPI_ORIGINAL_ENTRYID: 'MAPI_ORIGINAL_ENTRYID', 
       MAPI_ORIGINAL_DISPLAY_NAME: 'MAPI_ORIGINAL_DISPLAY_NAME', 
       MAPI_ORIGINAL_SEARCH_KEY: 'MAPI_ORIGINAL_SEARCH_KEY', 
       MAPI_POSTAL_ADDRESS: 'MAPI_POSTAL_ADDRESS', 
       MAPI_COMPANY_NAME: 'MAPI_COMPANY_NAME', 
       MAPI_TITLE: 'MAPI_TITLE', 
       MAPI_DEPARTMENT_NAME: 'MAPI_DEPARTMENT_NAME', 
       MAPI_OFFICE_LOCATION: 'MAPI_OFFICE_LOCATION', 
       MAPI_PRIMARY_TELEPHONE_NUMBER: 'MAPI_PRIMARY_TELEPHONE_NUMBER', 
       MAPI_BUSINESS2_TELEPHONE_NUMBER: 'MAPI_BUSINESS2_TELEPHONE_NUMBER', 
       MAPI_MOBILE_TELEPHONE_NUMBER: 'MAPI_MOBILE_TELEPHONE_NUMBER', 
       MAPI_RADIO_TELEPHONE_NUMBER: 'MAPI_RADIO_TELEPHONE_NUMBER', 
       MAPI_CAR_TELEPHONE_NUMBER: 'MAPI_CAR_TELEPHONE_NUMBER', 
       MAPI_OTHER_TELEPHONE_NUMBER: 'MAPI_OTHER_TELEPHONE_NUMBER', 
       MAPI_TRANSMITABLE_DISPLAY_NAME: 'MAPI_TRANSMITABLE_DISPLAY_NAME', 
       MAPI_PAGER_TELEPHONE_NUMBER: 'MAPI_PAGER_TELEPHONE_NUMBER', 
       MAPI_USER_CERTIFICATE: 'MAPI_USER_CERTIFICATE', 
       MAPI_PRIMARY_FAX_NUMBER: 'MAPI_PRIMARY_FAX_NUMBER', 
       MAPI_BUSINESS_FAX_NUMBER: 'MAPI_BUSINESS_FAX_NUMBER', 
       MAPI_HOME_FAX_NUMBER: 'MAPI_HOME_FAX_NUMBER', 
       MAPI_COUNTRY: 'MAPI_COUNTRY', 
       MAPI_LOCALITY: 'MAPI_LOCALITY', 
       MAPI_STATE_OR_PROVINCE: 'MAPI_STATE_OR_PROVINCE', 
       MAPI_STREET_ADDRESS: 'MAPI_STREET_ADDRESS', 
       MAPI_POSTAL_CODE: 'MAPI_POSTAL_CODE', 
       MAPI_POST_OFFICE_BOX: 'MAPI_POST_OFFICE_BOX', 
       MAPI_TELEX_NUMBER: 'MAPI_TELEX_NUMBER', 
       MAPI_ISDN_NUMBER: 'MAPI_ISDN_NUMBER', 
       MAPI_ASSISTANT_TELEPHONE_NUMBER: 'MAPI_ASSISTANT_TELEPHONE_NUMBER', 
       MAPI_HOME2_TELEPHONE_NUMBER: 'MAPI_HOME2_TELEPHONE_NUMBER', 
       MAPI_ASSISTANT: 'MAPI_ASSISTANT', 
       MAPI_SEND_RICH_INFO: 'MAPI_SEND_RICH_INFO', 
       MAPI_WEDDING_ANNIVERSARY: 'MAPI_WEDDING_ANNIVERSARY', 
       MAPI_BIRTHDAY: 'MAPI_BIRTHDAY', 
       MAPI_HOBBIES: 'MAPI_HOBBIES', 
       MAPI_MIDDLE_NAME: 'MAPI_MIDDLE_NAME', 
       MAPI_DISPLAY_NAME_PREFIX: 'MAPI_DISPLAY_NAME_PREFIX', 
       MAPI_PROFESSION: 'MAPI_PROFESSION', 
       MAPI_PREFERRED_BY_NAME: 'MAPI_PREFERRED_BY_NAME', 
       MAPI_SPOUSE_NAME: 'MAPI_SPOUSE_NAME', 
       MAPI_COMPUTER_NETWORK_NAME: 'MAPI_COMPUTER_NETWORK_NAME', 
       MAPI_CUSTOMER_ID: 'MAPI_CUSTOMER_ID', 
       MAPI_TTYTDD_PHONE_NUMBER: 'MAPI_TTYTDD_PHONE_NUMBER', 
       MAPI_FTP_SITE: 'MAPI_FTP_SITE', 
       MAPI_GENDER: 'MAPI_GENDER', 
       MAPI_MANAGER_NAME: 'MAPI_MANAGER_NAME', 
       MAPI_NICKNAME: 'MAPI_NICKNAME', 
       MAPI_PERSONAL_HOME_PAGE: 'MAPI_PERSONAL_HOME_PAGE', 
       MAPI_BUSINESS_HOME_PAGE: 'MAPI_BUSINESS_HOME_PAGE', 
       MAPI_CONTACT_VERSION: 'MAPI_CONTACT_VERSION', 
       MAPI_CONTACT_ENTRYIDS: 'MAPI_CONTACT_ENTRYIDS', 
       MAPI_CONTACT_ADDRTYPES: 'MAPI_CONTACT_ADDRTYPES', 
       MAPI_CONTACT_DEFAULT_ADDRESS_INDEX: 'MAPI_CONTACT_DEFAULT_ADDRESS_INDEX', 
       MAPI_CONTACT_EMAIL_ADDRESSES: 'MAPI_CONTACT_EMAIL_ADDRESSES', 
       MAPI_COMPANY_MAIN_PHONE_NUMBER: 'MAPI_COMPANY_MAIN_PHONE_NUMBER', 
       MAPI_CHILDRENS_NAMES: 'MAPI_CHILDRENS_NAMES', 
       MAPI_HOME_ADDRESS_CITY: 'MAPI_HOME_ADDRESS_CITY', 
       MAPI_HOME_ADDRESS_COUNTRY: 'MAPI_HOME_ADDRESS_COUNTRY', 
       MAPI_HOME_ADDRESS_POSTAL_CODE: 'MAPI_HOME_ADDRESS_POSTAL_CODE', 
       MAPI_HOME_ADDRESS_STATE_OR_PROVINCE: 'MAPI_HOME_ADDRESS_STATE_OR_PROVINCE', 
       MAPI_HOME_ADDRESS_STREET: 'MAPI_HOME_ADDRESS_STREET', 
       MAPI_HOME_ADDRESS_POST_OFFICE_BOX: 'MAPI_HOME_ADDRESS_POST_OFFICE_BOX', 
       MAPI_OTHER_ADDRESS_CITY: 'MAPI_OTHER_ADDRESS_CITY', 
       MAPI_OTHER_ADDRESS_COUNTRY: 'MAPI_OTHER_ADDRESS_COUNTRY', 
       MAPI_OTHER_ADDRESS_POSTAL_CODE: 'MAPI_OTHER_ADDRESS_POSTAL_CODE', 
       MAPI_OTHER_ADDRESS_STATE_OR_PROVINCE: 'MAPI_OTHER_ADDRESS_STATE_OR_PROVINCE', 
       MAPI_OTHER_ADDRESS_STREET: 'MAPI_OTHER_ADDRESS_STREET', 
       MAPI_OTHER_ADDRESS_POST_OFFICE_BOX: 'MAPI_OTHER_ADDRESS_POST_OFFICE_BOX', 
       MAPI_STORE_PROVIDERS: 'MAPI_STORE_PROVIDERS', 
       MAPI_AB_PROVIDERS: 'MAPI_AB_PROVIDERS', 
       MAPI_TRANSPORT_PROVIDERS: 'MAPI_TRANSPORT_PROVIDERS', 
       MAPI_DEFAULT_PROFILE: 'MAPI_DEFAULT_PROFILE', 
       MAPI_AB_SEARCH_PATH: 'MAPI_AB_SEARCH_PATH', 
       MAPI_AB_DEFAULT_DIR: 'MAPI_AB_DEFAULT_DIR', 
       MAPI_AB_DEFAULT_PAB: 'MAPI_AB_DEFAULT_PAB', 
       MAPI_FILTERING_HOOKS: 'MAPI_FILTERING_HOOKS', 
       MAPI_SERVICE_NAME: 'MAPI_SERVICE_NAME', 
       MAPI_SERVICE_DLL_NAME: 'MAPI_SERVICE_DLL_NAME', 
       MAPI_SERVICE_ENTRY_NAME: 'MAPI_SERVICE_ENTRY_NAME', 
       MAPI_SERVICE_UID: 'MAPI_SERVICE_UID', 
       MAPI_SERVICE_EXTRA_UIDS: 'MAPI_SERVICE_EXTRA_UIDS', 
       MAPI_SERVICES: 'MAPI_SERVICES', 
       MAPI_SERVICE_SUPPORT_FILES: 'MAPI_SERVICE_SUPPORT_FILES', 
       MAPI_SERVICE_DELETE_FILES: 'MAPI_SERVICE_DELETE_FILES', 
       MAPI_AB_SEARCH_PATH_UPDATE: 'MAPI_AB_SEARCH_PATH_UPDATE', 
       MAPI_PROFILE_NAME: 'MAPI_PROFILE_NAME', 
       MAPI_IDENTITY_DISPLAY: 'MAPI_IDENTITY_DISPLAY', 
       MAPI_IDENTITY_ENTRYID: 'MAPI_IDENTITY_ENTRYID', 
       MAPI_RESOURCE_METHODS: 'MAPI_RESOURCE_METHODS', 
       MAPI_RESOURCE_TYPE: 'MAPI_RESOURCE_TYPE', 
       MAPI_STATUS_CODE: 'MAPI_STATUS_CODE', 
       MAPI_IDENTITY_SEARCH_KEY: 'MAPI_IDENTITY_SEARCH_KEY', 
       MAPI_OWN_STORE_ENTRYID: 'MAPI_OWN_STORE_ENTRYID', 
       MAPI_RESOURCE_PATH: 'MAPI_RESOURCE_PATH', 
       MAPI_STATUS_STRING: 'MAPI_STATUS_STRING', 
       MAPI_X400_DEFERRED_DELIVERY_CANCEL: 'MAPI_X400_DEFERRED_DELIVERY_CANCEL', 
       MAPI_HEADER_FOLDER_ENTRYID: 'MAPI_HEADER_FOLDER_ENTRYID', 
       MAPI_REMOTE_PROGRESS: 'MAPI_REMOTE_PROGRESS', 
       MAPI_REMOTE_PROGRESS_TEXT: 'MAPI_REMOTE_PROGRESS_TEXT', 
       MAPI_REMOTE_VALIDATE_OK: 'MAPI_REMOTE_VALIDATE_OK', 
       MAPI_CONTROL_FLAGS: 'MAPI_CONTROL_FLAGS', 
       MAPI_CONTROL_STRUCTURE: 'MAPI_CONTROL_STRUCTURE', 
       MAPI_CONTROL_TYPE: 'MAPI_CONTROL_TYPE', 
       MAPI_DELTAX: 'MAPI_DELTAX', 
       MAPI_DELTAY: 'MAPI_DELTAY', 
       MAPI_XPOS: 'MAPI_XPOS', 
       MAPI_YPOS: 'MAPI_YPOS', 
       MAPI_CONTROL_ID: 'MAPI_CONTROL_ID', 
       MAPI_INITIAL_DETAILS_PANE: 'MAPI_INITIAL_DETAILS_PANE', 
       UNCOMPRESSED_BODY: 'UNCOMPRESSED_BODY', 
       MAPI_PRIMARY_SEND_ACCOUNT: 'MAPI_PRIMARY_SEND_ACCOUNT', 
       MAPI_NEXT_SEND_ACCT: 'MAPI_NEXT_SEND_ACCT', 
       MAPI_INTERNET_REFERENCES: 'MAPI_INTERNET_REFERENCES', 
       MAPI_IN_REPLY_TO_ID: 'MAPI_IN_REPLY_TO_ID', 
       MAPI_INTERNET_RETURN_PATH: 'MAPI_INTERNET_RETURN_PATH', 
       MAPI_ICON_INDEX: 'MAPI_ICON_INDEX', 
       MAPI_TARGET_ENTRY_ID: 'MAPI_TARGET_ENTRY_ID', 
       MAPI_CONVERSATION_ID: 'MAPI_CONVERSATION_ID', 
       MAPI_STORE_UNICODE_MASK: 'MAPI_STORE_UNICODE_MASK', 
       MAPI_INTERNET_CODEPAGE: 'MAPI_INTERNET_CODEPAGE', 
       MAPI_MESSAGE_LOCALE_ID: 'MAPI_MESSAGE_LOCALE_ID', 
       MAPI_CREATOR_NAME: 'MAPI_CREATOR_NAME', 
       MAPI_CREATOR_ENTRY_ID: 'MAPI_CREATOR_ENTRY_ID', 
       MAPI_LAST_MODIFIER_ENTRY_ID: 'MAPI_LAST_MODIFIER_ENTRY_ID', 
       MAPI_MESSAGE_CODEPAGE: 'MAPI_MESSAGE_CODEPAGE', 
       MAPI_INTERNET_MAIL_OVERRIDE_FORMAT: 'MAPI_INTERNET_MAIL_OVERRIDE_FORMAT', 
       MAPI_MESSAGE_EDITOR_FORMAT: 'MAPI_MESSAGE_EDITOR_FORMAT', 
       MAPI_SENDER_SMTP_ADDRESS: 'MAPI_SENDER_SMTP_ADDRESS', 
       MAPI_SENT_REPRESENTING_SMTP_ADDRESS: 'MAPI_SENT_REPRESENTING_SMTP_ADDRESS', 
       MAPI_READ_RECEIPT_SMTP_ADDRESS: 'MAPI_READ_RECEIPT_SMTP_ADDRESS', 
       MAPI_RECEIVED_BY_SMTP_ADDRESS: 'MAPI_RECEIVED_BY_SMTP_ADDRESS', 
       MAPI_RECEIVED_REPRESENTING_SMTP_ADDRESS: 'MAPI_RECEIVED_REPRESENTING_SMTP_ADDRESS', 
       MAPI_SIP_ADDRESS: 'MAPI_SIP_ADDRESS', 
       MAPI_ATTACHMENT_LINK_ID: 'MAPI_ATTACHMENT_LINK_ID', 
       MAPI_EXCEPTION_START_TIME: 'MAPI_EXCEPTION_START_TIME', 
       MAPI_EXCEPTION_END_TIME: 'MAPI_EXCEPTION_END_TIME', 
       MAPI_ATTACHMENT_FLAGS: 'MAPI_ATTACHMENT_FLAGS', 
       MAPI_ATTACHMENT_HIDDEN: 'MAPI_ATTACHMENT_HIDDEN', 
       MAPI_ATTACHMENT_CONTACT_PHOTO: 'MAPI_ATTACHMENT_CONTACT_PHOTO', 
       MAPI_ID_SECURE_MIN: 'MAPI_ID_SECURE_MIN', 
       MAPI_ID_SECURE_MAX: 'MAPI_ID_SECURE_MAX'}
    OutlookGuid = '05133f00aa00da98101b450b6ed8da90'
    AppointmentGuid = '46000000000000c00000000000062002'

    def __init__(self, attr_type, name, data, guid_id, guid_name=None, guid_prop=None):
        self.attr_type = attr_type
        self.name = name
        self.raw_data = data
        self.guid = guid_id
        self.guid_name = guid_name
        self.guid_prop = guid_prop
        if self.guid_name:
            self.guid_name = self.guid_name.rstrip('\x00')

    @property
    def data(self):
        if self.attr_type == SZMAPI_NULL:
            return
        else:
            if self.attr_type == SZMAPI_SHORT:
                return int16(self.raw_data)
            else:
                if self.attr_type == SZMAPI_INT:
                    return int32(self.raw_data)
                if self.attr_type == SZMAPI_FLOAT:
                    return float32(self.raw_data)
                if self.attr_type == SZMAPI_DOUBLE:
                    return dbl64(self.raw_data)
                if self.attr_type == SZMAPI_CURRENCY:
                    return Decimal(int64(self.raw_data)) / Decimal(10000)
                if self.attr_type == SZMAPI_APPTIME:
                    return apptime(self.raw_data)
                if self.attr_type == SZMAPI_ERROR:
                    return uint32(self.raw_data)
                if self.attr_type == SZMAPI_BOOLEAN:
                    return bool(uint16(self.raw_data))
                if self.attr_type == SZMAPI_INT8BYTE:
                    return int8(self.raw_data)
                if self.attr_type == SZMAPI_SYSTIME:
                    return systime(self.raw_data)
                if self.attr_type == SZMAPI_CLSID:
                    return guid(self.raw_data)
                if self.attr_type == SZMAPI_BINARY:
                    return ('').join([ s.rstrip('\x00') for s in self.raw_data ])
                if self.attr_type in (SZMAPI_STRING, SZMAPI_UNICODE_STRING):
                    return ('').join([ s.rstrip('\x00') for s in self.raw_data ])
                return self.raw_data

            return

    @property
    def name_str(self):
        return self.guid_name or TNEFMAPI_Attribute.codes.get(self.name or self.guid_prop, hex(self.guid_prop or self.name))

    def __str__(self):
        return '<ATTR: %s>' % self.name_str