# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Volumes/Ozgur/Dropbox/Sites/django-manifest/manifest/urls.py
# Compiled at: 2019-10-15 15:40:17
# Size of source mod 2**32: 4475 bytes
""" Manifest URLs
"""
import django.contrib.auth as auth_views
from django.urls import re_path
from django.views.generic import TemplateView
from manifest import defaults, views
from manifest.forms import PictureUploadForm, RegionUpdateForm
urlpatterns = [
 re_path('^login/$',
   (views.AuthLoginView.as_view()),
   name='auth_login'),
 re_path('^logout/$',
   (views.AuthLogoutView.as_view()),
   name='auth_logout'),
 re_path('^register/$',
   (views.AuthRegisterView.as_view()),
   name='auth_register'),
 re_path('^register/complete/$',
   TemplateView.as_view(template_name='manifest/auth_register_complete.html',
   extra_context={'activation_required':defaults.MANIFEST_ACTIVATION_REQUIRED, 
  'activation_days':defaults.MANIFEST_ACTIVATION_DAYS}),
   name='auth_register_complete'),
 re_path('^activate/(?P<username>\\w+)/(?P<token>\\w+)/$',
   (views.AuthActivateView.as_view()),
   name='auth_activate'),
 re_path('^disabled/$',
   TemplateView.as_view(template_name='manifest/auth_disabled.html'),
   name='auth_disabled'),
 re_path('^password/reset/$',
   auth_views.PasswordResetView.as_view(template_name='manifest/password_reset_form.html',
   email_template_name='manifest/emails/password_reset_message.txt'),
   name='password_reset'),
 re_path('^password/reset/done/$',
   auth_views.PasswordResetDoneView.as_view(template_name='manifest/password_reset_done.html'),
   name='password_reset_done'),
 re_path('^password/reset/(?P<uidb64>[0-9A-Za-z_\\-]+)/(?P<token>.+)/$',
   auth_views.PasswordResetConfirmView.as_view(template_name='manifest/password_reset_confirm.html'),
   name='password_reset_confirm'),
 re_path('^password/reset/complete/$',
   auth_views.PasswordResetCompleteView.as_view(template_name='manifest/password_reset_complete.html'),
   name='password_reset_complete'),
 re_path('^profile/$',
   (views.AuthProfileView.as_view()),
   name='user_profile'),
 re_path('^profile/setting/$',
   views.AuthProfileView.as_view(template_name='manifest/profile_settings.html'),
   name='profile_settings'),
 re_path('^profile/update/$',
   (views.ProfileUpdateView.as_view()),
   name='profile_update'),
 re_path('^profile/picture/$',
   views.ProfileUpdateView.as_view(form_class=PictureUploadForm,
   template_name='manifest/picture_upload.html'),
   name='picture_upload'),
 re_path('^profile/region/$',
   views.ProfileUpdateView.as_view(form_class=RegionUpdateForm,
   template_name='manifest/region_update.html'),
   name='region_update'),
 re_path('^email/change/$',
   (views.EmailChangeView.as_view()),
   name='email_change'),
 re_path('^email/change/done/$',
   views.AuthProfileView.as_view(template_name='manifest/email_change_done.html'),
   name='email_change_done'),
 re_path('^email/change/(?P<username>\\w+)/(?P<token>\\w+)/$',
   (views.EmailChangeConfirmView.as_view()),
   name='email_change_confirm'),
 re_path('^email/change/complete/$',
   TemplateView.as_view(template_name='manifest/email_change_complete.html'),
   name='email_change_complete'),
 re_path('^password/change/$',
   (views.PasswordChangeView.as_view()),
   name='password_change'),
 re_path('^password/change/done/$',
   TemplateView.as_view(template_name='manifest/password_change_complete.html'),
   name='password_change_done'),
 re_path('^users/$',
   (views.UserListView.as_view()),
   name='user_list'),
 re_path('^users/(?P<username>\\w+)/$',
   (views.UserDetailView.as_view()),
   name='user_detail')]