# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/aestrivex/anaconda3/lib/python3.7/site-packages/bct/citations.py
# Compiled at: 2020-04-27 14:47:22
# Size of source mod 2**32: 13894 bytes
from __future__ import unicode_literals
from .version import __version__
from datetime import datetime
BCTPY = '\n@misc{{bctpy,\n    publisher = {{GitHub}},\n    title = {{bctpy v{version}: Brain Connectivity Toolbox for Python}},\n    url = {{https://github.com/aestrivex/bctpy}},\n    author = {{LaPlante, Roan and others}},\n    note = {{[Online; accessed {datestamp}]}},\n}}\n'.format(version=__version__,
  datestamp=(datetime.utcnow().strftime('%Y-%m-%d'))).strip()
NEWMAN2002 = '\n@article{newman2002spread,\n  title = {Spread of epidemic disease on networks},\n  author = {Newman, M. E. J.},\n  journal = {Phys. Rev. E},\n  volume = {66},\n  issue = {1},\n  pages = {016128},\n  numpages = {11},\n  year = {2002},\n  month = {Jul},\n  publisher = {American Physical Society},\n  doi = {10.1103/PhysRevE.66.016128},\n  url = {https://link.aps.org/doi/10.1103/PhysRevE.66.016128}\n}\n'.strip()
FOSTER2010 = '\n@article{foster2010edge,\n  title={Edge direction and the structure of networks},\n  author={Foster, Jacob G and Foster, David V and Grassberger, Peter and Paczuski, Maya},\n  journal={Proceedings of the National Academy of Sciences},\n  volume={107},\n  number={24},\n  pages={10815--10820},\n  year={2010},\n  publisher={National Acad Sciences}\n}\n'.strip()
HIDALGO2007 = "\n@article{hidalgo2007product,\n  title={The product space conditions the development of nations},\n  author={Hidalgo, C{\\'e}sar A and Klinger, Bailey and Barab{\\'a}si, A-L and Hausmann, Ricardo},\n  journal={Science},\n  volume={317},\n  number={5837},\n  pages={482--487},\n  year={2007},\n  publisher={American Association for the Advancement of Science}\n}\n".strip()
HAGMANN2008 = '\n@article{hagmann2008mapping,\n  title={Mapping the structural core of human cerebral cortex},\n  author={Hagmann, Patric and Cammoun, Leila and Gigandet, Xavier and Meuli, Reto and Honey, Christopher J and Wedeen, Van J and Sporns, Olaf},\n  journal={PLoS biology},\n  volume={6},\n  number={7},\n  pages={e159},\n  year={2008},\n  publisher={Public Library of Science}\n}\n\n'.strip()
BRANDES2001 = '\n@article{brandes2008variants,\n  title={On variants of shortest-path betweenness centrality and their generic computation},\n  author={Brandes, Ulrik},\n  journal={Social Networks},\n  volume={30},\n  number={2},\n  pages={136--145},\n  year={2008},\n  publisher={Elsevier}\n}\n'.strip()
KINTALI2008 = '\n@article{kintali2008betweenness,\n  title={Betweenness centrality: Algorithms and lower bounds},\n  author={Kintali, Shiva},\n  journal={arXiv preprint arXiv:0809.1906},\n  year={2008}\n}\n'.strip()
WATTS1998 = "\n@article{watts1998collective,\n  title={Collective dynamics of `small-world' networks},\n  author={Watts, Duncan J and Strogatz, Steven H},\n  journal={nature},\n  volume={393},\n  number={6684},\n  pages={440},\n  year={1998},\n  publisher={Nature Publishing Group}\n}\n".strip()
ONNELA2005 = '\n@article{onnela2005intensity,\n  title={Intensity and coherence of motifs in weighted complex networks},\n  author={Onnela, Jukka-Pekka and Saram{\\"a}ki, Jari and Kert{\\\'e}sz, J{\\\'a}nos and Kaski, Kimmo},\n  journal={Physical Review E},\n  volume={71},\n  number={6},\n  pages={065103},\n  year={2005},\n  publisher={APS}\n}\n'.strip()
FAGIOLO2007 = '\n@article{fagiolo2007clustering,\n  title={Clustering in complex directed networks},\n  author={Fagiolo, Giorgio},\n  journal={Physical Review E},\n  volume={76},\n  number={2},\n  pages={026107},\n  year={2007},\n  publisher={APS}\n}\n'.strip()
LANCICHINETTI2012 = '\n@article{lancichinetti2012consensus,\n  title={Consensus clustering in complex networks},\n  author={Lancichinetti, Andrea and Fortunato, Santo},\n  journal={Scientific reports},\n  volume={2},\n  pages={336},\n  year={2012},\n  publisher={Nature Publishing Group}\n}\n'.strip()
SHANNON1948 = '\n@article{shannon1948mathematical,\n  title={A mathematical theory of communication},\n  author={Shannon, Claude Elwood},\n  journal={Bell system technical journal},\n  volume={27},\n  number={3},\n  pages={379--423},\n  year={1948},\n  publisher={Wiley Online Library}\n}\n'.strip()
RUBINOV2011 = '\n@article{rubinov2011weight,\n  title={Weight-conserving characterization of complex functional brain networks},\n  author={Rubinov, Mikail and Sporns, Olaf},\n  journal={Neuroimage},\n  volume={56},\n  number={4},\n  pages={2068--2079},\n  year={2011},\n  publisher={Elsevier}\n}\n'.strip()
EASLY2010 = '\n@book{easley2010networks,\n  title={Networks, crowds, and markets},\n  author={Easley, David and Kleinberg, Jon and others},\n  volume={8},\n  year={2010},\n  publisher={Cambridge university press Cambridge}\n}\n'.strip()
LATORA2001 = '\n@article{latora2001efficient,\n  title={Efficient behavior of small-world networks},\n  author={Latora, Vito and Marchiori, Massimo},\n  journal={Physical review letters},\n  volume={87},\n  number={19},\n  pages={198701},\n  year={2001},\n  publisher={APS}\n}\n'.strip()
RUBINOV2010 = '\n@article{rubinov2010complex,\n  title={Complex network measures of brain connectivity: uses and interpretations},\n  author={Rubinov, Mikail and Sporns, Olaf},\n  journal={Neuroimage},\n  volume={52},\n  number={3},\n  pages={1059--1069},\n  year={2010},\n  publisher={Elsevier}\n}\n'.strip()
NEWMAN2016 = '\n@article{newman2016mathematics,\n  title={Mathematics of networks},\n  author={Newman, Mark EJ},\n  journal={The new Palgrave dictionary of economics},\n  pages={1--8},\n  year={2016},\n  publisher={Springer}\n}\n'.strip()
HONEY2007 = '\n@article{honey2007network,\n  title={Network structure of cerebral cortex shapes functional connectivity on multiple time scales},\n  author={Honey, Christopher J and K{\\"o}tter, Rolf and Breakspear, Michael and Sporns, Olaf},\n  journal={Proceedings of the National Academy of Sciences},\n  volume={104},\n  number={24},\n  pages={10240--10245},\n  year={2007},\n  publisher={National Acad Sciences}\n}\n'
YIP2007 = '\n@article{yip2007gene,\n  title={Gene network interconnectedness and the generalized topological overlap measure},\n  author={Yip, Andy M and Horvath, Steve},\n  journal={BMC bioinformatics},\n  volume={8},\n  number={1},\n  pages={22},\n  year={2007},\n  publisher={BioMed Central}\n}\n'.strip()
RAVASZ2002 = "\n@article{ravasz2002hierarchical,\n  title={Hierarchical organization of modularity in metabolic networks},\n  author={Ravasz, Erzs{\\'e}bet and Somera, Anna Lisa and Mongru, Dale A and Oltvai, Zolt{\\'a}n N and Barab{\\'a}si, A-L},\n  journal={science},\n  volume={297},\n  number={5586},\n  pages={1551--1555},\n  year={2002},\n  publisher={American Association for the Advancement of Science}\n}\n".strip()
MASLOV2002 = '\n@article{maslov2002specificity,\n  title={Specificity and stability in topology of protein networks},\n  author={Maslov, Sergei and Sneppen, Kim},\n  journal={Science},\n  volume={296},\n  number={5569},\n  pages={910--913},\n  year={2002},\n  publisher={American Association for the Advancement of Science}\n}\n'.strip()
SPORNS2004 = '\n@article{sporns2004small,\n  title={The small world of the cerebral cortex},\n  author={Sporns, Olaf and Zwi, Jonathan D},\n  journal={Neuroinformatics},\n  volume={2},\n  number={2},\n  pages={145--162},\n  year={2004},\n  publisher={Springer}\n}\n'.strip()
LEICHT2008 = '\n@article{leicht2008community,\n  title={Community structure in directed networks},\n  author={Leicht, Elizabeth A and Newman, Mark EJ},\n  journal={Physical review letters},\n  volume={100},\n  number={11},\n  pages={118703},\n  year={2008},\n  publisher={APS}\n}\n'.strip()
REICHARDT2006 = '\n@article{reichardt2006statistical,\n  title={Statistical mechanics of community detection},\n  author={Reichardt, J{\\"o}rg and Bornholdt, Stefan},\n  journal={Physical Review E},\n  volume={74},\n  number={1},\n  pages={016110},\n  year={2006},\n  publisher={APS}\n}\n'.strip()
GOOD2010 = '\n@article{good2010performance,\n  title={Performance of modularity maximization in practical contexts},\n  author={Good, Benjamin H and De Montjoye, Yves-Alexandre and Clauset, Aaron},\n  journal={Physical Review E},\n  volume={81},\n  number={4},\n  pages={046106},\n  year={2010},\n  publisher={APS}\n}\n'.strip()
SUN2008 = "\n@article{sun2009improved,\n  title={Improved community structure detection using a modified fine-tuning strategy},\n  author={Sun, Yudong and Danila, Bogdan and Josi{'c}, K and Bassler, Kevin E},\n  journal={EPL (Europhysics Letters)},\n  volume={86},\n  number={2},\n  pages={28004},\n  year={2009},\n  publisher={IOP Publishing}\n}\n".strip()
BLONDEL2008 = '\n@article{blondel2008fast,\n  title={Fast unfolding of communities in large networks},\n  author={Blondel, Vincent D and Guillaume, Jean-Loup and Lambiotte, Renaud and Lefebvre, Etienne},\n  journal={Journal of statistical mechanics: theory and experiment},\n  volume={2008},\n  number={10},\n  pages={P10008},\n  year={2008},\n  publisher={IOP Publishing}\n}\n'.strip()
GUIMERA2005 = '\n@article{guimera2005functional,\n  title={Functional cartography of complex metabolic networks},\n  author={Guimera, Roger and Amaral, Luis A Nunes},\n  journal={nature},\n  volume={433},\n  number={7028},\n  pages={895},\n  year={2005},\n  publisher={Nature Publishing Group}\n}\n'.strip()
ZALESKY2010 = '\n@article{zalesky2010network,\n  title={Network-based statistic: identifying differences in brain networks},\n  author={Zalesky, Andrew and Fornito, Alex and Bullmore, Edward T},\n  journal={Neuroimage},\n  volume={53},\n  number={4},\n  pages={1197--1207},\n  year={2010},\n  publisher={Elsevier}\n}\n'.strip()
MORRISON2005 = '\n@article{morrison2005generank,\n  title={GeneRank: using search engine technology for the analysis of microarray experiments},\n  author={Morrison, Julie L and Breitling, Rainer and Higham, Desmond J and Gilbert, David R},\n  journal={BMC bioinformatics},\n  volume={6},\n  number={1},\n  pages={233},\n  year={2005},\n  publisher={BioMed Central}\n}\n'.strip()
BOLDI2009 = '\n@article{boldi2009pagerank,\n  title={PageRank: Functional dependencies.},\n  author={Boldi, Paolo and Santini, Massimo and Vigna, Sebastiano},\n  journal={ACM Trans. Inf. Syst.},\n  volume={27},\n  number={4},\n  pages={19--1},\n  year={2009},\n  publisher={Citeseer}\n}\n'.strip()
MEILA2007 = '\n@article{meila2007comparing,\n  title={Comparing clusterings -- an information based distance},\n  author={Meil{\\={a}}, Marina},\n  journal={Journal of multivariate analysis},\n  volume={98},\n  number={5},\n  pages={873--895},\n  year={2007},\n  publisher={Elsevier}\n}\n'.strip()
BASSETT2010 = '\n@article{bassett2010efficient,\n  title={Efficient physical embedding of topologically complex information processing networks in brains and computer circuits},\n  author={Bassett, Danielle S and Greenfield, Daniel L and Meyer-Lindenberg, Andreas and Weinberger, Daniel R and Moore, Simon W and Bullmore, Edward T},\n  journal={PLoS computational biology},\n  volume={6},\n  number={4},\n  pages={e1000748},\n  year={2010},\n  publisher={Public Library of Science}\n}\n'.strip()
COLIZZA2006 = '\n@article{colizza2006detecting,\n  title={Detecting rich-club ordering in complex networks},\n  author={Colizza, Vittoria and Flammini, Alessandro and Serrano, M Angeles and Vespignani, Alessandro},\n  journal={Nature physics},\n  volume={2},\n  number={2},\n  pages={110},\n  year={2006},\n  publisher={Nature Publishing Group}\n}\n'.strip()
OPSAHL2008 = '\n@article{opsahl2008prominence,\n  title={Prominence and control: the weighted rich-club effect},\n  author={Opsahl, Tore and Colizza, Vittoria and Panzarasa, Pietro and Ramasco, Jose J},\n  journal={Physical review letters},\n  volume={101},\n  number={16},\n  pages={168702},\n  year={2008},\n  publisher={APS}\n}\n'.strip()
HEUVEL2011 = '\n@article{van2011rich,\n  title={Rich-club organization of the human connectome},\n  author={Van Den Heuvel, Martijn P and Sporns, Olaf},\n  journal={Journal of Neuroscience},\n  volume={31},\n  number={44},\n  pages={15775--15786},\n  year={2011},\n  publisher={Soc Neuroscience}\n}\n'.strip()
ESTRADA2005 = '\n@article{estrada2005subgraph,\n  title={Subgraph centrality in complex networks},\n  author={Estrada, Ernesto and Rodriguez-Velazquez, Juan A},\n  journal={Physical Review E},\n  volume={71},\n  number={5},\n  pages={056103},\n  year={2005},\n  publisher={APS}\n}\n'.strip()
ESTRADA2010 = '\n@article{estrada2010network,\n  title={Network properties revealed through matrix functions},\n  author={Estrada, Ernesto and Higham, Desmond J},\n  journal={SIAM review},\n  volume={52},\n  number={4},\n  pages={696--714},\n  year={2010},\n  publisher={SIAM}\n}\n'.strip()
HUMPHRIES2008 = "\n@article{humphries2008network,\n  title={Network `small-world-ness': a quantitative method for determining canonical network equivalence},\n  author={Humphries, Mark D and Gurney, Kevin},\n  journal={PloS one},\n  volume={3},\n  number={4},\n  pages={e0002051},\n  year={2008},\n  publisher={Public Library of Science}\n}\n".strip()
ZHANG2005 = '\n@article{zhang2005general,\n  title={A general framework for weighted gene co-expression network analysis},\n  author={Zhang, Bin and Horvath, Steve},\n  journal={Statistical applications in genetics and molecular biology},\n  volume={4},\n  number={1},\n  year={2005},\n  publisher={De Gruyter}\n}\n'.strip()
COSTANTINI2014 = '\n@article{costantini2014generalization,\n  title={Generalization of clustering coefficients to signed correlation networks},\n  author={Costantini, Giulio and Perugini, Marco},\n  journal={PloS one},\n  volume={9},\n  number={2},\n  pages={e88669},\n  year={2014},\n  publisher={Public Library of Science}\n}\n'.strip()
BETZEL2016 = "\n@article{betzel2016generative,\n  title={Generative models of the human connectome},\n  author={Betzel, Richard F and Avena-Koenigsberger, Andrea and Go{\\~n}i, Joaqu{\\'\\i}n and He, Ye and De Reus, Marcel A and Griffa, Alessandra and V{\\'e}rtes, Petra E and Mi{\\v{s}}ic, Bratislav and Thiran, Jean-Philippe and Hagmann, Patric and others},\n  journal={Neuroimage},\n  volume={124},\n  pages={1054--1064},\n  year={2016},\n  publisher={Elsevier}\n}\n".strip()