# uncompyle6 version 3.7.4
# Python bytecode 3.5 (3350)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/mfi/mytools/muteria/muteria/configmanager/defaults/common_defaults.py
# Compiled at: 2019-12-05 09:47:28
# Size of source mod 2**32: 8243 bytes
""" Defaults parameters that are common to all languages
"""
from __future__ import print_function
from muteria.configmanager.configurations import SessionMode
from muteria.configmanager.configurations import TestcaseToolsConfig
from muteria.configmanager.configurations import CriteriaToolsConfig
from muteria.configmanager.configurations import ToolUserCustom
from muteria.drivers.criteria import TestCriteria
from muteria.drivers.criteria import CriteriaToolType
from muteria.drivers.testgeneration import TestToolType
EXECUTION_CLEANSTART = False
RUN_MODE = None
ENABLED_CRITERIA = []
GET_PASSFAIL_OUTPUT_SUMMARY = True
CRITERIA_WITH_OUTPUT_SUMMARY = []
SINGLE_REPO_PARALLELISM = 1
EXECUTE_ONLY_CURENT_CHECKPOINT_META_TASK = False
RESTART_CURRENT_EXECUTING_META_TASKS = False
RE_EXECUTE_FROM_CHECKPOINT_META_TASKS = []
OUTPUT_ROOT_DIR = None
LOG_DEBUG = False
GENERATE_HTML_REPORT = True
OUTPUT_CRITERIA_SCORES = True
CRITERIA_SCORE_BY_TOOL = True
OUTPUT_CRITERIA_SUBSUMPTION_SCORE = True
OUTPUT_CRITERIA_COVERED_ELEMENTS = False
OUTPUT_CRITERIA_UNCOVERED_ELEMENTS = True
DETAILED_ELEMENTS_OUTPUT = False
OUTPUT_CRITERIA_SUBSUMING_ELEM_NUM = True
OUTPUT_STATS_HISTORY = True
PROGRAMMING_LANGUAGE = None
REPOSITORY_ROOT_DIR = None
REPO_EXECUTABLE_RELATIVE_PATHS = None
TARGET_SOURCE_INTERMEDIATE_CODE_MAP = None
TARGET_CLASSES_NAMES = None
TARGET_METHODS_BY_TARGET_CLASSES = None
DEVELOPER_TESTS_LIST = None
CUSTOM_DEV_TEST_RUNNER_FUNCTION = None
CUSTOM_DEV_TEST_PROGRAM_WRAPPER_CLASS = None
CUSTOM_DEV_TEST_RUNNER_MODULE = None
CODE_BUILDER_FUNCTION = None
CODE_BUILDER_MODULE = None
DEVELOPER_TESTS_ENABLED = True
GENERATED_TESTS_ENABLED = True
STOP_TESTS_EXECUTION_ON_FAILURE = False
DISCARD_FLAKY_TESTS = True
TEST_TOOL_TYPES_SCHEDULING = [
 (
  TestToolType.USE_ONLY_CODE,),
 (
  TestToolType.USE_CODE_AND_TESTS,)]
TESTCASE_TOOLS_CONFIGS = []
REPORT_NUMBER_OF_TESTS_GENERATED = True
REPORT_NUMBER_OF_DUPLICATED_TESTS = True
CRITERIA_TOOLS_CONFIGS_BY_CRITERIA = {}
CRITERIA_SEQUENCE = None
CRITERIA_REQUIRING_OUTDIFF_WITH_PROGRAM = None
RUN_FAILING_TESTS_WITH_CRITERIA = []
RUN_PASSING_TESTS_WITH_CRITERIA = []
CRITERIA_RESTRICTION_ENABLED = True
CRITERIA_ELEM_SELECTIONS = {}
ONLY_EXECUTE_SELECTED_CRITERIA_ELEM = True
MAX_CRITERIA_ELEM_SELECTION_NUM_PERCENT = '100%'
CRITERIA_TESTGEN_GUIDANCE = {}
CRITERIA_EXECUTION_OPTIMIZERS = {}
COVER_CRITERIA_ELEMENTS_ONCE = False