# uncompyle6 version 3.7.4
# Python bytecode 3.2 (3180)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/pgp/packets/constants.py
# Compiled at: 2015-08-31 08:17:33
PUBLIC_KEY_ENCRYPTED_SESSION_KEY_PACKET_TYPE = 1
SIGNATURE_PACKET_TYPE = 2
SYMMETRIC_KEY_ENCRYPTED_SESSION_KEY_PACKET_TYPE = 3
ONE_PASS_SIGNATURE_PACKET_TYPE = 4
SECRET_KEY_PACKET_TYPE = 5
PUBLIC_KEY_PACKET_TYPE = 6
SECRET_SUBKEY_PACKET_TYPE = 7
COMPRESSED_DATA_PACKET_TYPE = 8
SYMMETRICALLY_ENCRYPTED_DATA_PACKET_TYPE = 9
MARKER_PACKET_TYPE = 10
LITERAL_DATA_PACKET_TYPE = 11
TRUST_PACKET_TYPE = 12
USER_ID_PACKET_TYPE = 13
PUBLIC_SUBKEY_PACKET_TYPE = 14
USER_ATTRIBUTE_PACKET_TYPE = 17
SYMMETRICALLY_ENCRYPTED_AND_INTEGRITY_PROTECTED_DATA_PACKET_TYPE = 18
MODIFICATION_DETECTION_CODE_PACKET_TYPE = 19
OLD_COMMENT_PACKET_TYPE = 16
GPG_COMMENT_PACKET_TYPE = 61
GPG_CONTROL_PACKET_TYPE = 63
DATA_TYPES = (
 COMPRESSED_DATA_PACKET_TYPE,
 SYMMETRICALLY_ENCRYPTED_DATA_PACKET_TYPE,
 LITERAL_DATA_PACKET_TYPE,
 SYMMETRICALLY_ENCRYPTED_AND_INTEGRITY_PROTECTED_DATA_PACKET_TYPE)
NEW_PACKET_HEADER_TYPE = 1
OLD_PACKET_HEADER_TYPE = 2
SIGNATURE_OF_A_BINARY_DOCUMENT = 0
SIGNATURE_OF_A_CANONICAL_TEXT_DOCUMENT = 1
STANDALONE_SIGNATURE = 2
GENERIC_CERTIFICATION = 16
PERSONA_CERTIFICATION = 17
CASUAL_CERTIFICATION = 18
POSITIVE_CERTIFICATION = 19
SUBKEY_BINDING_SIGNATURE = 24
PRIMARY_KEY_BINDING_SIGNATURE = 25
SIGNATURE_DIRECTLY_ON_A_KEY = 31
KEY_REVOCATION_SIGNATURE = 32
SUBKEY_REVOCATION_SIGNATURE = 40
CERTIFICATION_REVOCATION_SIGNATURE = 48
TIMESTAMP_SIGNATURE = 64
THIRD_PARTY_CONFIRMATION_SIGNATURE = 80
CREATION_TIME_SUBPACKET_TYPE = 2
EXPIRATION_SECONDS_SUBPACKET_TYPE = 3
EXPORTABLE_SUBPACKET_TYPE = 4
TRUST_SUBPACKET_TYPE = 5
REGULAR_EXPRESSION_SUBPACKET_TYPE = 6
REVOCABLE_SUBPACKET_TYPE = 7
KEY_EXPIRATION_TIME_SUBPACKET_TYPE = 9
PREFERRED_SYMMETRIC_ALGORITHMS_SUBPACKET_TYPE = 11
REVOCATION_KEY_SUBPACKET_TYPE = 12
ISSUER_KEY_ID_SUBPACKET_TYPE = 16
NOTATION_SUBPACKET_TYPE = 20
PREFERRED_HASH_ALGORITHMS_SUBPACKET_TYPE = 21
PREFERRED_COMPRESSION_ALGORITHMS_SUBPACKET_TYPE = 22
KEY_SERVER_PREFERENCES_SUBPACKET_TYPE = 23
PREFERRED_KEY_SERVER_SUBPACKET_TYPE = 24
PRIMARY_USER_ID_SUBPACKET_TYPE = 25
POLICY_URI_SUBPACKET_TYPE = 26
KEY_FLAGS_SUBPACKET_TYPE = 27
ISSUERS_USER_ID_SUBPACKET_TYPE = 28
REVOCATION_REASON_SUBPACKET_TYPE = 29
FEATURES_SUBPACKET_TYPE = 30
TARGET_SUBPACKET_TYPE = 31
EMBEDDED_SIGNATURE_SUBPACKET_TYPE = 32
ADDITIONAL_RECIPIENT_REQUEST_SUBPACKET_TYPE = 10
IMAGE_ATTRIBUTE_SUBPACKET_TYPE = 1
JPEG_IMAGE_FORMAT = 1
human_signature_types = {0: 'Signature of a binary document', 
 1: 'Signature of a canonical text document', 
 2: 'Standalone signature', 
 16: 'Generic certification of a User ID and Public-Key packet', 
 17: 'Persona certification of a User ID and Public-Key packet', 
 18: 'Casual certification of a User ID and Public-Key packet', 
 19: 'Positive certification of a User ID and Public-Key packet', 
 24: 'Subkey Binding Signature', 
 25: 'Primary Key Binding Signature', 
 31: 'Signature directly on a key', 
 32: 'Key revocation signature', 
 40: 'Subkey revocation signature', 
 48: 'Certification revocation signature', 
 64: 'Timestamp signature', 
 80: 'Third-Party Confirmation signature'}