# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/solstice/core/defines.py
# Compiled at: 2019-10-05 11:59:30
# Size of source mod 2**32: 3633 bytes
"""
Module that contains all constant definitions used by Solstice
"""
from __future__ import print_function, division, absolute_import
__author__ = 'Tomas Poveda'
__license__ = 'MIT'
__maintainer__ = 'Tomas Poveda'
__email__ = 'tpovedatd@gmail.com'
from artellapipe.core import defines
SOLSTICE_CONFIGURATION_ENV = 'SOLSTICE_PROJECT_CONFIGURATIONS_FOLDER'
SOLSTICE_TAGGER_FILE_NAME = 'tagger.json'
SOLSTICE_PROP_ASSETS = 'Props'
SOLSTICE_BACKGROUND_ELEMENTS_ASSETS = 'Background Elements'
SOLSTICE_CHARACTERS_ASSETS = 'Characters'
SOLSTICE_TEXTURES_ASSET_TYPE = defines.ARTELLA_TEXTURES_ASSET_TYPE
SOLSTICE_MODEL_ASSET_TYPE = defines.ARTELLA_MODEL_ASSET_TYPE
SOLSTICE_SHADING_ASSET_TYPE = defines.ARTELLA_SHADING_ASSET_TYPE
SOLSTICE_RIG_ASSET_TYPE = defines.ARTELLA_RIG_ASSET_TYPE
SOLSTICE_GROOM_ASSET_TYPE = defines.ARTELLA_GROOM_ASSET_TYPE
SOLSTICE_ALEMBIC_EXTENSION = '.abc'
SOLSTICE_MODEL_EXTENSION = '.ma'
SOLSTICE_TEXTURE_EXTENSIONS = [
 '.tx', '.png', '.jpg', '.jpeg']
SOLSTICE_SHADING_EXTENSION = '.ma'
SOLSTICE_RIG_EXTENSION = '.ma'
SOLSTICE_STANDIN_EXTENSION = '.ass'
SOLSTICE_LAYOUT_EXTENSION = '.layout'
SOLSTICE_ANIMATION_EXTENSION = '.anim'
SOLSTICE_FX_EXTENSION = '.fx'
SOLSTICE_LIGHTING_EXTENSION = '.light'
SOLSTICE_SCENE_TAG_TYPE = 'Scene'
SOLSTICE_PROP_TAG_TYPE = 'Prop'
SOLSTICE_CHARACTER_TAG_TYPE = 'Character'
SOLSTICE_BACKGROUND_ELEMENT_TAG_TYPE = 'Background Element'
SOLSTICE_LIGHT_RIG_TAG_TYPE = 'Light Rig'
SOLSTICE_MODEL_TAG_TYPE = 'Model'
SOLSTICE_ANIMATION_TAG_TYPE = 'Animation'
SOLSTICE_SHADING_TAG_TYPE = 'Shading'
SOLSTICE_CLOTH_TAG_TYPE = 'Cloth'
SOLSTICE_GROOM_TAG_TYPE = 'Groom'
SOLSTICE_CAMERA_TAG_TYPE = 'Camera'
SOLSTICE_LAYOUT_SHOT_FILE_TYPE = 'Layout'
SOLSTICE_ANIMATION_SHOT_FILE_TYPE = 'Animation'
SOLSTICE_FX_SHOT_FILE_TYPE = 'FX'
SOLSTICE_LIGHTING_SHOT_FILE_TYPE = 'Lighting'
SOLSTICE_TRANSFORM_OVERRIDE_EXTENSION = '.ovxform'