# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win-amd64\egg\robopython\pygatt\backends\bgapi\constants.py
# Compiled at: 2020-03-04 11:05:12
ble_address_type = {'gap_address_type_public': 0, 'gap_address_type_random': 1}
gap_discoverable_mode = {'non_discoverable': 0, 
   'limited_discoverable': 1, 
   'general_discoverable': 2, 
   'broadcast': 3, 
   'user_data': 4, 
   'enhanced_broadcasting': 128}
gap_connectable_mode = {'non_connectable': 0, 
   'directed_connectable': 1, 
   'undirected_connectable': 2, 
   'scannable_non_connectable': 3}
gap_discover_mode = {'limited': 0, 
   'generic': 1, 
   'observation': 2}
bonding = {'do_not_create_bonding': 0, 
   'create_bonding': 1}
bondable = {'no': 0, 
   'yes': 1}
connection_status_flag = {'connected': 1, 
   'encrypted': 2, 
   'completed': 4, 
   'parameters_change': 8}
scan_response_packet_type = {0: 'connectable_advertisement_packet', 
   2: 'non-connectable_advertisement_packet', 
   4: 'scan_response_packet', 
   6: 'discoverable_advertisement_packet'}
scan_response_data_type = {1: 'flags', 
   2: 'incomplete_list_16-bit_service_class_uuids', 
   3: 'complete_list_16-bit_service_class_uuids', 
   4: 'incomplete_list_32-bit_service_class_uuids', 
   5: 'complete_list_32-bit_service_class_uuids', 
   6: 'incomplete_list_128-bit_service_class_uuids', 
   7: 'complete_list_128-bit_service_class_uuids', 
   8: 'shortened_local_name', 
   9: 'complete_local_name', 
   10: 'tx_power_level', 
   13: 'class_of_device', 
   14: 'simple_pairing_hash_c/c-192', 
   15: 'simple_pairing_randomizer_r/r-192', 
   16: 'device_id/security_manager_tk_value', 
   17: 'security_manager_out_of_band_flags', 
   18: 'slave_connection_interval_range', 
   20: 'list_of_16-bit_service_solicitation_uuids', 
   31: 'list_of_32-bit_service_solicitation_uuids', 
   21: 'list_of_128-bit_service_solicitation_uuids', 
   22: 'service_data/service_data-16-bit_uuid', 
   32: 'service_data-32-bit_uuid', 
   33: 'service_data-128-bit_uuid', 
   34: 'LE_secure_connections_confirmation_value', 
   35: 'LE_secure_connections_random_value', 
   23: 'public_target_address', 
   24: 'random_target_address', 
   25: 'appearance', 
   26: 'advertising_interval', 
   27: 'LE_bluetooth_device_address', 
   28: 'LE_role', 
   29: 'simple_pairing_hash_c-256', 
   30: 'simple_pairing_randomizer_r-256', 
   61: '3D_information_data', 
   255: 'manufacturer_specific_data'}
gatt_service_uuid = {'generic_access_profile': bytearray([24, 0]), 
   'generic_attribute_profile': bytearray([24, 1])}
gatt_attribute_type_uuid = {'primary_service': bytearray([40, 0]), 
   'secondary_service': bytearray([40, 1]), 
   'include': bytearray([40, 2]), 
   'characteristic': bytearray([40, 3])}
gatt_characteristic_descriptor_uuid = {'characteristic_extended_properties': bytearray([41, 0]), 
   'characteristic_user_description': bytearray([41, 1]), 
   'client_characteristic_configuration': bytearray([41, 2]), 
   'server_characteristic_configuration': bytearray([41, 3]), 
   'characteristic_format': bytearray([41, 4]), 
   'characteristic_aggregate_format': bytearray([41, 5])}
gatt_characteristic_type_uuid = {'aerobic_heart_rate_lower_limit': bytearray([42, 126]), 
   'aerobic_heart_rate_upper_limit': bytearray([42, 132]), 
   'aerobic_threshold': bytearray([42, 127]), 
   'age': bytearray([42, 128]), 
   'aggregate': bytearray([42, 90]), 
   'alert_category_id': bytearray([42, 67]), 
   'alert_category_id_bit_mask': bytearray([42, 66]), 
   'alert_level': bytearray([42, 6]), 
   'alert_notification_control_point': bytearray([42, 68]), 
   'alert_status': bytearray([42, 63]), 
   'altitude': bytearray([42, 179]), 
   'anaerobic_heart_rate_lower_limit': bytearray([42, 129]), 
   'anaerobic_heart_rate_upper_limit': bytearray([42, 130]), 
   'anaerobic_threshold': bytearray([42, 131]), 
   'analog': bytearray([42, 88]), 
   'apparent_wind_direction': bytearray([42, 115]), 
   'apparent_wind_speed': bytearray([42, 114]), 
   'appearance': bytearray([42, 1]), 
   'barometric_pressure_trend': bytearray([42, 163]), 
   'battery_level': bytearray([42, 25]), 
   'blood_pressure_feature': bytearray([42, 73]), 
   'blood_pressure_measurement': bytearray([42, 53]), 
   'body_composition_feature': bytearray([42, 155]), 
   'body_composition_measurement': bytearray([42, 156]), 
   'body_sensor_location': bytearray([42, 56]), 
   'bond_management_control_point': bytearray([42, 164]), 
   'bond_management_feature': bytearray([42, 165]), 
   'boot_keyboard_input_report': bytearray([42, 34]), 
   'boot_keyboard_output_report': bytearray([42, 50]), 
   'boot_mouse_input_report': bytearray([42, 51]), 
   'central_address_resolution_support': bytearray([42, 166]), 
   'cgm_feature': bytearray([42, 168]), 
   'cgm_measurement': bytearray([42, 167]), 
   'cgm_session_run_time': bytearray([42, 171]), 
   'cgm_session_start_time': bytearray([42, 170]), 
   'cgm_specific_ops_control_point': bytearray([42, 172]), 
   'cgm_status': bytearray([42, 169]), 
   'csc_feature': bytearray([42, 92]), 
   'csc_measurement': bytearray([42, 91]), 
   'current_time': bytearray([42, 43]), 
   'cycling_power_control_point': bytearray([42, 102]), 
   'cycling_power_feature': bytearray([42, 101]), 
   'cycling_power_measurement': bytearray([42, 99]), 
   'cycling_power_vector': bytearray([42, 100]), 
   'database_change_increment': bytearray([42, 153]), 
   'date_of_birth': bytearray([42, 133]), 
   'date_of_threshold_assessment': bytearray([42, 134]), 
   'date_time': bytearray([42, 8]), 
   'day_date_time': bytearray([42, 10]), 
   'day_of_week': bytearray([42, 9]), 
   'descriptor_value_changed': bytearray([42, 125]), 
   'device_name': bytearray([42, 0]), 
   'dew_point': bytearray([42, 123]), 
   'digital': bytearray([42, 86]), 
   'dst_offset': bytearray([42, 13]), 
   'elevation': bytearray([42, 108]), 
   'email_address': bytearray([42, 135]), 
   'exact_time_256': bytearray([42, 12]), 
   'fat_burn_heart_rate_lower_limit': bytearray([42, 136]), 
   'fat_burn_heart_rate_upper_limit': bytearray([42, 137]), 
   'firmware_revision_string': bytearray([42, 38]), 
   'first_name': bytearray([42, 138]), 
   'five_zone_heart_rate_limits': bytearray([42, 139]), 
   'floor_number': bytearray([42, 178]), 
   'gender': bytearray([42, 140]), 
   'glucose_feature': bytearray([42, 81]), 
   'glucose_measurement': bytearray([42, 24]), 
   'glucose_measurement_context': bytearray([42, 52]), 
   'gust_factor': bytearray([42, 116]), 
   'hardware_revision_string': bytearray([42, 39]), 
   'heart_rate_control_point': bytearray([42, 57]), 
   'heart_rate_max': bytearray([42, 141]), 
   'heart_rate_measurement': bytearray([42, 55]), 
   'heat_index': bytearray([42, 122]), 
   'height': bytearray([42, 142]), 
   'hid_control_point': bytearray([42, 76]), 
   'hid_information': bytearray([42, 74]), 
   'hip_circumference': bytearray([42, 143]), 
   'http_control_point': bytearray([42, 186]), 
   'http_entity_body': bytearray([42, 185]), 
   'http_headers': bytearray([42, 183]), 
   'http_status_code': bytearray([42, 184]), 
   'https_security': bytearray([42, 187]), 
   'humidity': bytearray([42, 111]), 
   'ieee_11073-20601_regulatory_certification_data_list': bytearray([42, 42]), 
   'indoor_positioning_configuration': bytearray([42, 173]), 
   'intermediate_cuff_pressure': bytearray([42, 54]), 
   'intermediate_temperature': bytearray([42, 30]), 
   'irradiance': bytearray([42, 119]), 
   'language': bytearray([42, 162]), 
   'last_name': bytearray([42, 144]), 
   'latitude': bytearray([42, 174]), 
   'ln_control_point': bytearray([42, 107]), 
   'ln_feature': bytearray([42, 106]), 
   'local_east_coordinate': bytearray([42, 177]), 
   'local_north_coordinate': bytearray([42, 176]), 
   'local_time_information': bytearray([42, 15]), 
   'location_and_speed': bytearray([42, 103]), 
   'location_name': bytearray([42, 181]), 
   'longitude': bytearray([42, 175]), 
   'magnetic_declination': bytearray([42, 44]), 
   'magnetic_flux_density_2D': bytearray([42, 160]), 
   'magnetic_flux_density_3D': bytearray([42, 161]), 
   'manufacturer_name_string': bytearray([42, 41]), 
   'maximum_recommended_heart_rate': bytearray([42, 145]), 
   'measurement_interval': bytearray([42, 33]), 
   'model_number_string': bytearray([42, 36]), 
   'navigation': bytearray([42, 104]), 
   'new_alert': bytearray([42, 70]), 
   'object_action_control_point': bytearray([42, 197]), 
   'object_changed': bytearray([42, 200]), 
   'object_first_created': bytearray([42, 193]), 
   'object_id': bytearray([42, 195]), 
   'object_last_modified': bytearray([42, 194]), 
   'object_list_control_point': bytearray([42, 198]), 
   'object_list_filter': bytearray([42, 199]), 
   'object_name': bytearray([42, 190]), 
   'object_properties': bytearray([42, 196]), 
   'object_size': bytearray([42, 192]), 
   'object_type': bytearray([42, 191]), 
   'ots_feature': bytearray([42, 189]), 
   'peripheral_preferred_connection_parameters': bytearray([42, 4]), 
   'peripheral_privacy_flag': bytearray([42, 2]), 
   'plx_continuous_measurement': bytearray([42, 95]), 
   'plx_features': bytearray([42, 96]), 
   'plx_spot_check_measurement': bytearray([42, 94]), 
   'pnp_id': bytearray([42, 80]), 
   'pollen_concentration': bytearray([42, 117]), 
   'position_quality': bytearray([42, 105]), 
   'pressure': bytearray([42, 109]), 
   'protocol_mode': bytearray([42, 78]), 
   'rainfall': bytearray([42, 120]), 
   'reconnection_address': bytearray([42, 3]), 
   'record_access_control_point': bytearray([42, 82]), 
   'reference_time_information': bytearray([42, 20]), 
   'report': bytearray([42, 77]), 
   'report_map': bytearray([42, 75]), 
   'resting_heart_rate': bytearray([42, 146]), 
   'ringer_control_point': bytearray([42, 64]), 
   'ringer_setting': bytearray([42, 65]), 
   'rsc_feature': bytearray([42, 84]), 
   'rsc_measurement': bytearray([42, 83]), 
   'sc_control_point': bytearray([42, 85]), 
   'scan_interval_window': bytearray([42, 79]), 
   'scan_refresh': bytearray([42, 49]), 
   'sensor_location': bytearray([42, 93]), 
   'serial_number_string': bytearray([42, 37]), 
   'service_changed': bytearray([42, 5]), 
   'software_revision_string': bytearray([42, 40]), 
   'sport_type_for_aerobic_and_anaerobic_thresholds': bytearray([42, 147]), 
   'supported_new_alert_category': bytearray([42, 71]), 
   'supported_unread_alert_category': bytearray([42, 72]), 
   'system_id': bytearray([42, 35]), 
   'tds_control_point': bytearray([42, 188]), 
   'temperature': bytearray([42, 110]), 
   'temperature_measurement': bytearray([42, 28]), 
   'temperature_type': bytearray([42, 29]), 
   'three_zone_heart_rate_limits': bytearray([42, 148]), 
   'time_accuracy': bytearray([42, 18]), 
   'time_source': bytearray([42, 19]), 
   'time_update_control_point': bytearray([42, 22]), 
   'time_update_state': bytearray([42, 23]), 
   'time_with_dst': bytearray([42, 17]), 
   'time_zone': bytearray([42, 14]), 
   'true_wind_direction': bytearray([42, 113]), 
   'true_wind_speed': bytearray([42, 112]), 
   'two_zone_heart_rate_limit': bytearray([42, 149]), 
   'tx_power_level': bytearray([42, 7]), 
   'uncertainty': bytearray([42, 180]), 
   'unread_alert_status': bytearray([42, 69]), 
   'uri': bytearray([42, 182]), 
   'user_control_point': bytearray([42, 159]), 
   'user_index': bytearray([42, 154]), 
   'uv_index': bytearray([42, 118]), 
   'vo2_max': bytearray([42, 150]), 
   'waist_circumference': bytearray([42, 151]), 
   'weight': bytearray([42, 152]), 
   'weight_measurement': bytearray([42, 157]), 
   'weight_scale_feature': bytearray([42, 158]), 
   'wind_chill': bytearray([42, 121])}