# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Users/romainegele/Documents/Argonne/deephyper/build/lib/deephyper/core/plot/single.py
# Compiled at: 2019-07-10 12:45:57
# Size of source mod 2**32: 1422 bytes
"""Deephyper analytics - single study documentation

usage:

::

    $ deephyper-analytics parse ppo_test/ppo_test_382DS/deephyper.log
    $ deephyper-analytics single ppo_test_2019-05-07_14.json

"""
import os, argparse
from deephyper.core.plot.jn_loader import NbEdit
HERE = os.path.dirname(os.path.abspath(__file__))

def single_analytics(path_to_data_file, nb_name):
    editor = NbEdit((os.path.join(HERE, 'stub/single_analytics.ipynb')), path_to_save=f"{nb_name}.ipynb")
    try:
        venv_name = os.environ.get('VIRTUAL_ENV').split('/')[(-1)]
        editor.setkernel(venv_name)
    except:
        pass

    editor.edit(0, '{{path_to_data_file}}', path_to_data_file)
    editor.edit(1, '{{path_to_data_file}}', f"'{path_to_data_file}'")
    editor.write()
    editor.execute()


def add_subparser(subparsers):
    subparser_name = 'single'
    function_to_call = main
    parser_parse = subparsers.add_parser(subparser_name,
      help='Tool to generate analytics on a single NAS experiment (jupyter notebook).')
    parser_parse.add_argument('-p', '--path', type=str, help='A Json file generated by "deephyper-analytics parse".')
    parser_parse.add_argument('-n', '--name', type=str, default='dh-analytics-single', help='Jupyter notebook name.')
    return (
     subparser_name, function_to_call)


def main(path, name, *args, **kwargs):
    single_analytics(path_to_data_file=path, nb_name=name)