# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /root/venv_27/lib/python2.7/site-packages/fbsd_gpio/constant.py
# Compiled at: 2016-04-02 17:56:08
GPIO_PIN_INPUT = 1
GPIO_PIN_OUTPUT = 2
GPIO_PIN_OPENDRAIN = 4
GPIO_PIN_PUSHPULL = 8
GPIO_PIN_TRISTATE = 16
GPIO_PIN_PULLUP = 32
GPIO_PIN_PULLDOWN = 64
GPIO_PIN_INVIN = 128
GPIO_PIN_INVOUT = 256
GPIO_PIN_PULSTATE = 512
GPIO_CAPS = [
 GPIO_PIN_INPUT,
 GPIO_PIN_OUTPUT,
 GPIO_PIN_OPENDRAIN,
 GPIO_PIN_PUSHPULL,
 GPIO_PIN_TRISTATE,
 GPIO_PIN_PULLUP,
 GPIO_PIN_PULLDOWN,
 GPIO_PIN_INVIN,
 GPIO_PIN_INVOUT,
 GPIO_PIN_PULSTATE]
GPIO_VALUE_LOW = 0
GPIO_VALUE_HIGH = 1
GPIO_VALUES = [
 GPIO_VALUE_LOW, GPIO_VALUE_HIGH]
GPIO_EVENT_FALLING = 0
GPIO_EVENT_RISING = 1
GPIO_EVENTS = [
 GPIO_EVENT_RISING, GPIO_EVENT_FALLING]