# uncompyle6 version 3.6.7
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: /home/bill/py3/.virtualenvs/pytest/lib/python2.7/site-packages/Csys/abbr2state.py
# Compiled at: 2006-01-02 20:22:27
__doc__ = 'USPS State Abbreviations to State Names\n\n$Id: abbr2state.py,v 1.1 2006/01/03 01:22:27 csoftmgr Exp $'
__version__ = '$Revision: 1.1 $'[11:-2]
abbr2state = {'AA': 'Armed Forces Americas', 
   'AE': 'Armed Forces Middle East', 
   'AK': 'Alaska', 
   'AL': 'Alabama', 
   'AP': 'Armed Forces Pacific', 
   'AR': 'Arkansas', 
   'AS': 'American Samoa', 
   'AZ': 'Arizona', 
   'CA': 'California', 
   'CO': 'Colorado', 
   'CT': 'Connecticut', 
   'DC': 'District of Columbia', 
   'DE': 'Delaware', 
   'FL': 'Florida', 
   'FM': 'Federated States of Micronesia', 
   'GA': 'Georgia', 
   'GU': 'Guam', 
   'HI': 'Hawaii', 
   'IA': 'Iowa', 
   'ID': 'Idaho', 
   'IL': 'Illinois', 
   'IN': 'Indiana', 
   'KS': 'Kansas', 
   'KY': 'Kentucky', 
   'LA': 'Louisiana', 
   'MA': 'Massachusetts', 
   'MD': 'Maryland', 
   'ME': 'Maine', 
   'MH': 'Marshall Islands', 
   'MI': 'Michigan', 
   'MN': 'Minnesota', 
   'MO': 'Missouri', 
   'MP': 'Northern Mariana Islands', 
   'MS': 'Mississippi', 
   'MT': 'Montana', 
   'NC': 'North Carolina', 
   'ND': 'North Dakota', 
   'NE': 'Nebraska', 
   'NH': 'New Hampshire', 
   'NJ': 'New Jersey', 
   'NM': 'New Mexico', 
   'NV': 'Nevada', 
   'NY': 'New York', 
   'OH': 'Ohio', 
   'OK': 'Oklahoma', 
   'OR': 'Oregon', 
   'PA': 'Pennsylvania', 
   'PR': 'Puerto Rico', 
   'PW': 'Palau', 
   'RI': 'Rhode Island', 
   'SC': 'South Carolina', 
   'SD': 'South Dakota', 
   'TN': 'Tennessee', 
   'TX': 'Texas', 
   'UT': 'Utah', 
   'VA': 'Virginia', 
   'VI': 'Virgin Islands', 
   'VT': 'Vermont', 
   'WA': 'Washington', 
   'WI': 'Wisconsin', 
   'WV': 'West Virginia', 
   'WY': 'Wyoming'}