# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.9-x86_64/egg/ncloud_server/model/create_member_server_image_request.py
# Compiled at: 2020-05-13 01:24:46
"""
    server

    OpenAPI spec version: 2019-10-17T10:28:43Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
import pprint, re, six

class CreateMemberServerImageRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    swagger_types = {'member_server_image_description': 'str', 
       'member_server_image_name': 'str', 
       'server_instance_no': 'str'}
    attribute_map = {'member_server_image_description': 'memberServerImageDescription', 
       'member_server_image_name': 'memberServerImageName', 
       'server_instance_no': 'serverInstanceNo'}

    def __init__(self, member_server_image_description=None, member_server_image_name=None, server_instance_no=None):
        """CreateMemberServerImageRequest - a model defined in Swagger"""
        self._member_server_image_description = None
        self._member_server_image_name = None
        self._server_instance_no = None
        self.discriminator = None
        if member_server_image_description is not None:
            self.member_server_image_description = member_server_image_description
        if member_server_image_name is not None:
            self.member_server_image_name = member_server_image_name
        self.server_instance_no = server_instance_no
        return

    @property
    def member_server_image_description(self):
        u"""Gets the member_server_image_description of this CreateMemberServerImageRequest.  # noqa: E501

        회원서버이미지설명  # noqa: E501

        :return: The member_server_image_description of this CreateMemberServerImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._member_server_image_description

    @member_server_image_description.setter
    def member_server_image_description(self, member_server_image_description):
        u"""Sets the member_server_image_description of this CreateMemberServerImageRequest.

        회원서버이미지설명  # noqa: E501

        :param member_server_image_description: The member_server_image_description of this CreateMemberServerImageRequest.  # noqa: E501
        :type: str
        """
        self._member_server_image_description = member_server_image_description

    @property
    def member_server_image_name(self):
        u"""Gets the member_server_image_name of this CreateMemberServerImageRequest.  # noqa: E501

        회원서버이미지명  # noqa: E501

        :return: The member_server_image_name of this CreateMemberServerImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._member_server_image_name

    @member_server_image_name.setter
    def member_server_image_name(self, member_server_image_name):
        u"""Sets the member_server_image_name of this CreateMemberServerImageRequest.

        회원서버이미지명  # noqa: E501

        :param member_server_image_name: The member_server_image_name of this CreateMemberServerImageRequest.  # noqa: E501
        :type: str
        """
        self._member_server_image_name = member_server_image_name

    @property
    def server_instance_no(self):
        u"""Gets the server_instance_no of this CreateMemberServerImageRequest.  # noqa: E501

        서버인스턴스번호  # noqa: E501

        :return: The server_instance_no of this CreateMemberServerImageRequest.  # noqa: E501
        :rtype: str
        """
        return self._server_instance_no

    @server_instance_no.setter
    def server_instance_no(self, server_instance_no):
        u"""Sets the server_instance_no of this CreateMemberServerImageRequest.

        서버인스턴스번호  # noqa: E501

        :param server_instance_no: The server_instance_no of this CreateMemberServerImageRequest.  # noqa: E501
        :type: str
        """
        if server_instance_no is None:
            raise ValueError('Invalid value for `server_instance_no`, must not be `None`')
        self._server_instance_no = server_instance_no
        return

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}
        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(lambda x: x.to_dict() if hasattr(x, 'to_dict') else x, value))
            elif hasattr(value, 'to_dict'):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(lambda item: (item[0], item[1].to_dict()) if hasattr(item[1], 'to_dict') else item, value.items()))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateMemberServerImageRequest):
            return False
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other