# uncompyle6 version 3.6.7
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: build/bdist.macosx-10.7-x86_64/egg/airflow/lineage/backend/atlas/typedefs.py
# Compiled at: 2019-09-11 02:44:38
# Size of source mod 2**32: 3922 bytes
operator_typedef = {'enumDefs':[],  'structDefs':[],  'classificationDefs':[],  'entityDefs':[
  {'superTypes':[
    'Process'], 
   'name':'airflow_operator', 
   'description':'Airflow Operator', 
   'createdBy':'airflow', 
   'updatedBy':'airflow', 
   'attributeDefs':[
    {'name':'dag_id', 
     'isOptional':False, 
     'isUnique':False, 
     'isIndexable':True, 
     'typeName':'string', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'task_id', 
     'isOptional':False, 
     'isUnique':False, 
     'isIndexable':True, 
     'typeName':'string', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'command', 
     'isOptional':True, 
     'isUnique':False, 
     'isIndexable':False, 
     'typeName':'string', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'conn_id', 
     'isOptional':True, 
     'isUnique':False, 
     'isIndexable':False, 
     'typeName':'string', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'execution_date', 
     'isOptional':False, 
     'isUnique':False, 
     'isIndexable':True, 
     'typeName':'date', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'start_date', 
     'isOptional':True, 
     'isUnique':False, 
     'isIndexable':False, 
     'typeName':'date', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0},
    {'name':'end_date', 
     'isOptional':True, 
     'isUnique':False, 
     'isIndexable':False, 
     'typeName':'date', 
     'valuesMaxCount':1, 
     'cardinality':'SINGLE', 
     'valuesMinCount':0}]}]}