# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\py_mysql\lib\mysql\connector\charsets.py
# Compiled at: 2017-12-07 02:34:36
# Size of source mod 2**32: 12326 bytes
_GENERATED_ON = '2015-08-24'
_MYSQL_VERSION = (5, 7, 8)
MYSQL_CHARACTER_SETS = [
 None,
 ('big5', 'big5_chinese_ci', True),
 ('latin2', 'latin2_czech_cs', False),
 ('dec8', 'dec8_swedish_ci', True),
 ('cp850', 'cp850_general_ci', True),
 ('latin1', 'latin1_german1_ci', False),
 ('hp8', 'hp8_english_ci', True),
 ('koi8r', 'koi8r_general_ci', True),
 ('latin1', 'latin1_swedish_ci', True),
 ('latin2', 'latin2_general_ci', True),
 ('swe7', 'swe7_swedish_ci', True),
 ('ascii', 'ascii_general_ci', True),
 ('ujis', 'ujis_japanese_ci', True),
 ('sjis', 'sjis_japanese_ci', True),
 ('cp1251', 'cp1251_bulgarian_ci', False),
 ('latin1', 'latin1_danish_ci', False),
 ('hebrew', 'hebrew_general_ci', True),
 None,
 ('tis620', 'tis620_thai_ci', True),
 ('euckr', 'euckr_korean_ci', True),
 ('latin7', 'latin7_estonian_cs', False),
 ('latin2', 'latin2_hungarian_ci', False),
 ('koi8u', 'koi8u_general_ci', True),
 ('cp1251', 'cp1251_ukrainian_ci', False),
 ('gb2312', 'gb2312_chinese_ci', True),
 ('greek', 'greek_general_ci', True),
 ('cp1250', 'cp1250_general_ci', True),
 ('latin2', 'latin2_croatian_ci', False),
 ('gbk', 'gbk_chinese_ci', True),
 ('cp1257', 'cp1257_lithuanian_ci', False),
 ('latin5', 'latin5_turkish_ci', True),
 ('latin1', 'latin1_german2_ci', False),
 ('armscii8', 'armscii8_general_ci', True),
 ('utf8', 'utf8_general_ci', True),
 ('cp1250', 'cp1250_czech_cs', False),
 ('ucs2', 'ucs2_general_ci', True),
 ('cp866', 'cp866_general_ci', True),
 ('keybcs2', 'keybcs2_general_ci', True),
 ('macce', 'macce_general_ci', True),
 ('macroman', 'macroman_general_ci', True),
 ('cp852', 'cp852_general_ci', True),
 ('latin7', 'latin7_general_ci', True),
 ('latin7', 'latin7_general_cs', False),
 ('macce', 'macce_bin', False),
 ('cp1250', 'cp1250_croatian_ci', False),
 ('utf8mb4', 'utf8mb4_general_ci', True),
 ('utf8mb4', 'utf8mb4_bin', False),
 ('latin1', 'latin1_bin', False),
 ('latin1', 'latin1_general_ci', False),
 ('latin1', 'latin1_general_cs', False),
 ('cp1251', 'cp1251_bin', False),
 ('cp1251', 'cp1251_general_ci', True),
 ('cp1251', 'cp1251_general_cs', False),
 ('macroman', 'macroman_bin', False),
 ('utf16', 'utf16_general_ci', True),
 ('utf16', 'utf16_bin', False),
 ('utf16le', 'utf16le_general_ci', True),
 ('cp1256', 'cp1256_general_ci', True),
 ('cp1257', 'cp1257_bin', False),
 ('cp1257', 'cp1257_general_ci', True),
 ('utf32', 'utf32_general_ci', True),
 ('utf32', 'utf32_bin', False),
 ('utf16le', 'utf16le_bin', False),
 ('binary', 'binary', True),
 ('armscii8', 'armscii8_bin', False),
 ('ascii', 'ascii_bin', False),
 ('cp1250', 'cp1250_bin', False),
 ('cp1256', 'cp1256_bin', False),
 ('cp866', 'cp866_bin', False),
 ('dec8', 'dec8_bin', False),
 ('greek', 'greek_bin', False),
 ('hebrew', 'hebrew_bin', False),
 ('hp8', 'hp8_bin', False),
 ('keybcs2', 'keybcs2_bin', False),
 ('koi8r', 'koi8r_bin', False),
 ('koi8u', 'koi8u_bin', False),
 None,
 ('latin2', 'latin2_bin', False),
 ('latin5', 'latin5_bin', False),
 ('latin7', 'latin7_bin', False),
 ('cp850', 'cp850_bin', False),
 ('cp852', 'cp852_bin', False),
 ('swe7', 'swe7_bin', False),
 ('utf8', 'utf8_bin', False),
 ('big5', 'big5_bin', False),
 ('euckr', 'euckr_bin', False),
 ('gb2312', 'gb2312_bin', False),
 ('gbk', 'gbk_bin', False),
 ('sjis', 'sjis_bin', False),
 ('tis620', 'tis620_bin', False),
 ('ucs2', 'ucs2_bin', False),
 ('ujis', 'ujis_bin', False),
 ('geostd8', 'geostd8_general_ci', True),
 ('geostd8', 'geostd8_bin', False),
 ('latin1', 'latin1_spanish_ci', False),
 ('cp932', 'cp932_japanese_ci', True),
 ('cp932', 'cp932_bin', False),
 ('eucjpms', 'eucjpms_japanese_ci', True),
 ('eucjpms', 'eucjpms_bin', False),
 ('cp1250', 'cp1250_polish_ci', False),
 None,
 ('utf16', 'utf16_unicode_ci', False),
 ('utf16', 'utf16_icelandic_ci', False),
 ('utf16', 'utf16_latvian_ci', False),
 ('utf16', 'utf16_romanian_ci', False),
 ('utf16', 'utf16_slovenian_ci', False),
 ('utf16', 'utf16_polish_ci', False),
 ('utf16', 'utf16_estonian_ci', False),
 ('utf16', 'utf16_spanish_ci', False),
 ('utf16', 'utf16_swedish_ci', False),
 ('utf16', 'utf16_turkish_ci', False),
 ('utf16', 'utf16_czech_ci', False),
 ('utf16', 'utf16_danish_ci', False),
 ('utf16', 'utf16_lithuanian_ci', False),
 ('utf16', 'utf16_slovak_ci', False),
 ('utf16', 'utf16_spanish2_ci', False),
 ('utf16', 'utf16_roman_ci', False),
 ('utf16', 'utf16_persian_ci', False),
 ('utf16', 'utf16_esperanto_ci', False),
 ('utf16', 'utf16_hungarian_ci', False),
 ('utf16', 'utf16_sinhala_ci', False),
 ('utf16', 'utf16_german2_ci', False),
 ('utf16', 'utf16_croatian_ci', False),
 ('utf16', 'utf16_unicode_520_ci', False),
 ('utf16', 'utf16_vietnamese_ci', False),
 None,
 None,
 None,
 ('ucs2', 'ucs2_unicode_ci', False),
 ('ucs2', 'ucs2_icelandic_ci', False),
 ('ucs2', 'ucs2_latvian_ci', False),
 ('ucs2', 'ucs2_romanian_ci', False),
 ('ucs2', 'ucs2_slovenian_ci', False),
 ('ucs2', 'ucs2_polish_ci', False),
 ('ucs2', 'ucs2_estonian_ci', False),
 ('ucs2', 'ucs2_spanish_ci', False),
 ('ucs2', 'ucs2_swedish_ci', False),
 ('ucs2', 'ucs2_turkish_ci', False),
 ('ucs2', 'ucs2_czech_ci', False),
 ('ucs2', 'ucs2_danish_ci', False),
 ('ucs2', 'ucs2_lithuanian_ci', False),
 ('ucs2', 'ucs2_slovak_ci', False),
 ('ucs2', 'ucs2_spanish2_ci', False),
 ('ucs2', 'ucs2_roman_ci', False),
 ('ucs2', 'ucs2_persian_ci', False),
 ('ucs2', 'ucs2_esperanto_ci', False),
 ('ucs2', 'ucs2_hungarian_ci', False),
 ('ucs2', 'ucs2_sinhala_ci', False),
 ('ucs2', 'ucs2_german2_ci', False),
 ('ucs2', 'ucs2_croatian_ci', False),
 ('ucs2', 'ucs2_unicode_520_ci', False),
 ('ucs2', 'ucs2_vietnamese_ci', False),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ('ucs2', 'ucs2_general_mysql500_ci', False),
 ('utf32', 'utf32_unicode_ci', False),
 ('utf32', 'utf32_icelandic_ci', False),
 ('utf32', 'utf32_latvian_ci', False),
 ('utf32', 'utf32_romanian_ci', False),
 ('utf32', 'utf32_slovenian_ci', False),
 ('utf32', 'utf32_polish_ci', False),
 ('utf32', 'utf32_estonian_ci', False),
 ('utf32', 'utf32_spanish_ci', False),
 ('utf32', 'utf32_swedish_ci', False),
 ('utf32', 'utf32_turkish_ci', False),
 ('utf32', 'utf32_czech_ci', False),
 ('utf32', 'utf32_danish_ci', False),
 ('utf32', 'utf32_lithuanian_ci', False),
 ('utf32', 'utf32_slovak_ci', False),
 ('utf32', 'utf32_spanish2_ci', False),
 ('utf32', 'utf32_roman_ci', False),
 ('utf32', 'utf32_persian_ci', False),
 ('utf32', 'utf32_esperanto_ci', False),
 ('utf32', 'utf32_hungarian_ci', False),
 ('utf32', 'utf32_sinhala_ci', False),
 ('utf32', 'utf32_german2_ci', False),
 ('utf32', 'utf32_croatian_ci', False),
 ('utf32', 'utf32_unicode_520_ci', False),
 ('utf32', 'utf32_vietnamese_ci', False),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ('utf8', 'utf8_unicode_ci', False),
 ('utf8', 'utf8_icelandic_ci', False),
 ('utf8', 'utf8_latvian_ci', False),
 ('utf8', 'utf8_romanian_ci', False),
 ('utf8', 'utf8_slovenian_ci', False),
 ('utf8', 'utf8_polish_ci', False),
 ('utf8', 'utf8_estonian_ci', False),
 ('utf8', 'utf8_spanish_ci', False),
 ('utf8', 'utf8_swedish_ci', False),
 ('utf8', 'utf8_turkish_ci', False),
 ('utf8', 'utf8_czech_ci', False),
 ('utf8', 'utf8_danish_ci', False),
 ('utf8', 'utf8_lithuanian_ci', False),
 ('utf8', 'utf8_slovak_ci', False),
 ('utf8', 'utf8_spanish2_ci', False),
 ('utf8', 'utf8_roman_ci', False),
 ('utf8', 'utf8_persian_ci', False),
 ('utf8', 'utf8_esperanto_ci', False),
 ('utf8', 'utf8_hungarian_ci', False),
 ('utf8', 'utf8_sinhala_ci', False),
 ('utf8', 'utf8_german2_ci', False),
 ('utf8', 'utf8_croatian_ci', False),
 ('utf8', 'utf8_unicode_520_ci', False),
 ('utf8', 'utf8_vietnamese_ci', False),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 ('utf8', 'utf8_general_mysql500_ci', False),
 ('utf8mb4', 'utf8mb4_unicode_ci', False),
 ('utf8mb4', 'utf8mb4_icelandic_ci', False),
 ('utf8mb4', 'utf8mb4_latvian_ci', False),
 ('utf8mb4', 'utf8mb4_romanian_ci', False),
 ('utf8mb4', 'utf8mb4_slovenian_ci', False),
 ('utf8mb4', 'utf8mb4_polish_ci', False),
 ('utf8mb4', 'utf8mb4_estonian_ci', False),
 ('utf8mb4', 'utf8mb4_spanish_ci', False),
 ('utf8mb4', 'utf8mb4_swedish_ci', False),
 ('utf8mb4', 'utf8mb4_turkish_ci', False),
 ('utf8mb4', 'utf8mb4_czech_ci', False),
 ('utf8mb4', 'utf8mb4_danish_ci', False),
 ('utf8mb4', 'utf8mb4_lithuanian_ci', False),
 ('utf8mb4', 'utf8mb4_slovak_ci', False),
 ('utf8mb4', 'utf8mb4_spanish2_ci', False),
 ('utf8mb4', 'utf8mb4_roman_ci', False),
 ('utf8mb4', 'utf8mb4_persian_ci', False),
 ('utf8mb4', 'utf8mb4_esperanto_ci', False),
 ('utf8mb4', 'utf8mb4_hungarian_ci', False),
 ('utf8mb4', 'utf8mb4_sinhala_ci', False),
 ('utf8mb4', 'utf8mb4_german2_ci', False),
 ('utf8mb4', 'utf8mb4_croatian_ci', False),
 ('utf8mb4', 'utf8mb4_unicode_520_ci', False),
 ('utf8mb4', 'utf8mb4_vietnamese_ci', False),
 ('gb18030', 'gb18030_chinese_ci', True),
 ('gb18030', 'gb18030_bin', False),
 ('gb18030', 'gb18030_unicode_520_ci', False)]