# uncompyle6 version 3.7.4
# Python bytecode 3.7 (3394)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.12-x86_64/egg/util/arguments.py
# Compiled at: 2019-06-06 17:58:19
# Size of source mod 2**32: 1890 bytes
import argparse
version = '0.7.10'
parser = argparse.ArgumentParser()
parser.add_argument('-v', '--version', action='version', version=version)
parser.add_argument('-i', '--instance', help='The URL of the 1Desk instance',
  required=True)
parser.add_argument('-u', '--username', help='Email address of user account to login',
  required=True)
parser.add_argument('-p', '--password', help='Password of user account to login',
  required=True)
parser.add_argument('-c', '--client', help='Client CODE in 1Desk instance, must exist, defaults to IPsoft if not given',
  default='IPsoft',
  required=False)
parser.add_argument('-f', '--category', help='Category name in 1Desk instance, must exist in client given',
  required=False)
parser.add_argument('-l', '--log', help='Option to set the log level',
  required=False,
  default='INFO')
parser.add_argument('-d', '--directory', help='Local directory to read/write automata from/to',
  required=False)
parser.add_argument('-I', '--ignorecert', help='Skip SSL verification to ignore certificate errors, only use with hostnames you trust!',
  action='store_true',
  required=False)
parser.add_argument('-g', '--ignoregenerated', help='Ignores automata generated by tickets',
  action='store_true',
  required=False)
parser.add_argument('--retry', help='Number of times to retry failed HTTP requests',
  required=False,
  default=0)