# uncompyle6 version 3.6.7
# Python bytecode 3.8 (3413)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: build\bdist.win-amd64\egg\braces\const.py
# Compiled at: 2020-04-20 15:52:10
# Size of source mod 2**32: 1385 bytes
import token as TOKEN
__all__ = ('EXCEPT', 'INDENT', 'NEWLINE', 'TOKEN')
TOKEN.COLONEQUAL = 255
INDENT = '    '
NEWLINE = {
 TOKEN.NEWLINE, TOKEN.NL}
EXCEPT = {
 TOKEN.NEWLINE,
 TOKEN.NL,
 TOKEN.LPAR,
 TOKEN.LSQB,
 TOKEN.COLON,
 TOKEN.COMMA,
 TOKEN.SEMI,
 TOKEN.PLUS,
 TOKEN.MINUS,
 TOKEN.STAR,
 TOKEN.SLASH,
 TOKEN.VBAR,
 TOKEN.AMPER,
 TOKEN.LESS,
 TOKEN.GREATER,
 TOKEN.EQUAL,
 TOKEN.DOT,
 TOKEN.PERCENT,
 TOKEN.LBRACE,
 TOKEN.EQEQUAL,
 TOKEN.NOTEQUAL,
 TOKEN.LESSEQUAL,
 TOKEN.GREATEREQUAL,
 TOKEN.TILDE,
 TOKEN.CIRCUMFLEX,
 TOKEN.LEFTSHIFT,
 TOKEN.RIGHTSHIFT,
 TOKEN.DOUBLESTAR,
 TOKEN.PLUSEQUAL,
 TOKEN.MINEQUAL,
 TOKEN.STAREQUAL,
 TOKEN.SLASHEQUAL,
 TOKEN.PERCENTEQUAL,
 TOKEN.AMPEREQUAL,
 TOKEN.VBAREQUAL,
 TOKEN.CIRCUMFLEXEQUAL,
 TOKEN.LEFTSHIFTEQUAL,
 TOKEN.RIGHTSHIFTEQUAL,
 TOKEN.DOUBLESTAREQUAL,
 TOKEN.DOUBLESLASH,
 TOKEN.DOUBLESLASHEQUAL,
 TOKEN.AT,
 TOKEN.ATEQUAL,
 TOKEN.RARROW,
 TOKEN.COLONEQUAL}