# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/trac_captcha/release.py
# Compiled at: 2011-03-30 05:00:40
name = 'TracCaptcha'
version = '0.3.1'
description = 'pluggable captcha infrastructure for Trac with reCAPTCHA included'
long_description = '\nTracCaptcha is a Trac plugin to embed a captcha in the ticket page in addition \nto Trac\'s regular permission checks so that spammers are kept out.\n\n**"It just works":** Installation and configuration is very simple, just \ninstall the egg and put two configuration options in your trac.ini. No \ndatabase changes required.\n\n**Batteries included:** The popular reCAPTCHA system is supported out of the box.\nTechnically it\'s a plugin - if you don\'t like it you\'re free to use any other \nplugin while still leverage the benefits from the general captcha \ninfrastructure.\n\n**Does not annoy users:** After the user entered the captcha once, he does not have\nto solve the captcha again for the same ticket when he just clicks \'preview\'.\nAlso you can configure exempt certain users or groups (e.g. \'all authenticated \nusers\') from the captchas just by using Trac\'s permission system.\n\n**Easy to extend:** Protecting an additional page with a captcha is very \nsimple. Implementing captchas for the ticket module took only 20 lines of code! \nCaptchas for the DiscussionPlugin needed 21 lines of code!\n\n**Easy to write custom captchas:** If you don\'t like reCAPTCHA, you can still \nuse the generic infrastructure with all its features: You implement the code to \ngenerate the captcha and validate the user\'s input. TracCaptcha will take care \nof displaying your plugin in all supported pages!\n\n\nChangelog\n******************************\n\n0.3.1 (30.03.2011)\n====================\n- add config option to omit noscript section for recaptcha to enforce Javascript\n  support for users\n\n0.3 (25.03.2011)\n====================\n- add more debug logging about CAPTCHA display and accepted/rejected solutions \n  to identify better how spammers managed to file a spam ticket\n\n0.2.2 (04.02.2011)\n====================\n- fix tests on current Trac trunk (0.13dev)\n- fix: TICKET_ADMIN looses other ticket-related permissions on Trac < 0.13\n  thanks to Anton V. for reporting\n\n0.2.1 (10.11.2010)\n====================\n- fix "installation" as egg file in Trac plugins folder\n\n0.2 (10.07.2010)\n====================\n- integration in 3rd party Trac plugins: TracDiscussionPlugin and \n  AccountManager (registration only)\n- reCAPTCHA: select widget theme via trac.ini (requires simplejson for \n  Python 2.3-2.5)\n- reCAPTCHA: display the widget in the user\'s locale (if translation is provided\n  by the reCAPTCHA service)\n- reCAPTCHA: use HTTPS to include script files if Trac page was served with \n  HTTPS\n- reCAPTCHA: show link for reCAPTCHA signup if no keys configured\n- reCAPTCHA: use new Google URLs\n\n0.1 (25.06.2010)\n==================\n - initial release\n'
author = 'Felix Schwarz'
author_email = 'felix.schwarz@oss.schwarz.eu'
url = 'http://www.schwarz.eu/opensource/projects/trac_captcha'
download_url = 'http://www.schwarz.eu/opensource/projects/%(name)s/download/%(version)s/%(name)s-%(version)s.tar.gz' % dict(name=name, version=version)
_copyright = '2010 Felix Schwarz'
license = 'MIT'