# uncompyle6 version 3.6.7
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: /home/lucy/lib/python2.7/site-packages/cheerio/goodbye.py
# Compiled at: 2014-08-26 03:11:45
goodbyes = [
 'totsiens (afrikaans)',
 'lamtumir͓ (albanian)',
 'saз olun (azerbaijani)',
 'agur (basque)',
 'zbogom (bosnian)',
 'ad͑u (catalan)',
 'panamilit (cebuano)',
 '\U00050615\U00104701 (chinese simplified)',
 'sbohem (czech)',
 'farvel (danish)',
 'afscheid (dutch)',
 'goodbye (american english)',
 'pip pip cheerio! (british english)',
 'adia͕ (esperanto)',
 'hʹvasti (estonian)',
 'paalam na (filipino)',
 'n̈́kemiin (finnish)',
 'au revoir (french)',
 'adeus (galician)',
 'auf Wiedersehen (german)',
 'ᙡᙵᜄᙗᙷ (greek)',
 'orevwa (haitian creole)',
 'sai wata rana (hausa)',
 '❑✴✥✵ (hebrew)',
 'sib ntsib dua (hmong)',
 'bͲcsͲ (hungarian)',
 'kve͠ja (icelandic)',
 'selamat tinggal (indonesian)',
 'beannacht (irish)',
 'addio (italian)',
 'さようなら (japanese)',
 'pamit (javanese)',
 'vale (latin)',
 'ardievas (latvian)',
 'sudie (lithuanian)',
 'addiju (maltese)',
 'poroporoaki (maori)',
 'farvel (norwegian)',
 'żegnaj (polish)',
 'adeus (portuguese)',
 'la revedere (romanian)',
 'zbohom (slovak)',
 'poslovite (slovenian)',
 'nabdgelyo (somali)',
 'adiͣs (spanish)',
 'kwaheri (swahili)',
 'gʹle gʹle (turkish)',
 'hwyl fawr (welsh)',
 'o dab𗌕 (yoruba)']
colors = [
 '\x1b[1;30m',
 '\x1b[1;31m',
 '\x1b[1;32m',
 '\x1b[1;33m',
 '\x1b[1;34m',
 '\x1b[1;35m',
 '\x1b[1;36m',
 '\x1b[1;37m']