# uncompyle6 version 3.7.4
# Python bytecode 3.3 (3230)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /usr/local/lib/python3.3/dist-packages/hiddev/usages.py
# Compiled at: 2013-10-26 13:05:26
# Size of source mod 2**32: 46935 bytes
""" USB HID Usages Database """

def getUsageName(id, quote_names=False, vendor=None, model=None):
    page_id = id >> 16
    func_id = id & 65535
    page, functions = USAGES.get(page_id, (None, None))
    if page:
        if functions:
            func = functions.get(func_id) if isinstance(functions, dict) else functions(func_id)
            if func:
                if quote_names:
                    return '"' + func + '"'
                return func
            else:
                return '{0}:{1:04x}'.format(page, func_id)
        else:
            return '{0}:{1:04x}'.format(page, func_id)
    else:
        page, functions = VENDOR_SPECIFIC.get((vendor, model), {}).get(page_id, (None,
                                                                                 None))
        if page and functions and func_id in functions:
            return functions[func_id]
        else:
            return '{0:04x}:{1:04x}'.format(page_id, func_id)
    return


def getUsageId(page, function):
    if isinstance(page, int):
        page_id = page
        pagename, functions = USAGES[page_id]
    else:
        page = page.replace(' ', '')
        for page_id, (pagename, functions) in USAGES.items():
            if pagename == page:
                break
        else:
            raise ValueError('Usage Page {0!r} unknown'.format(page))

    if isinstance(function, int):
        function_id = function
    else:
        if isinstance(functions, dict):
            for function_id, functionname in functions.items():
                if functionname == function:
                    break
            else:
                raise ValueError('Usage {0!r} in page {1!r} unknown'.format(function, page))

        else:
            raise ValueError('Usage page {0!r} not enumerable'.format(page))
    return page_id << 16 | function_id & 65535


REVISION = 112
USAGES = {1: (
     'GenericDesktop',
     {1: 'Pointer', 
      2: 'Mouse', 
      4: 'Joystick', 
      5: 'Game Pad', 
      6: 'Keyboard', 
      7: 'Keypad', 
      8: 'Multi-axis Controller', 
      48: 'X', 
      49: 'Y', 
      50: 'Z', 
      51: 'Rx', 
      52: 'Ry', 
      53: 'Rz', 
      54: 'Slider', 
      55: 'Dial', 
      56: 'Wheel', 
      57: 'Hat switch', 
      58: 'Counted Buffer', 
      59: 'Byte Count', 
      60: 'Motion Wakeup', 
      61: 'Start', 
      62: 'Select', 
      64: 'Vx', 
      65: 'Vy', 
      66: 'Vz', 
      67: 'Vbrx', 
      68: 'Vbry', 
      69: 'Vbrz', 
      70: 'Vno', 
      71: 'Feature Notification', 
      128: 'System Control', 
      129: 'System Power Down', 
      130: 'System Sleep', 
      131: 'System Wake Up', 
      132: 'System Context Menu', 
      133: 'System Main Menu', 
      134: 'System App Menu', 
      135: 'System Menu Help', 
      136: 'System Menu Exit', 
      137: 'System Menu Select', 
      138: 'System Menu Right', 
      139: 'System Menu Left', 
      140: 'System Menu Up', 
      141: 'System Menu Down', 
      142: 'System Cold Restart', 
      143: 'System Warm Restart', 
      144: 'D-pad Up', 
      145: 'D-pad Down', 
      146: 'D-pad Right', 
      147: 'D-pad Left', 
      160: 'System Dock', 
      161: 'System Undock', 
      162: 'System Setup', 
      163: 'System Break', 
      164: 'System Debugger Break', 
      165: 'Application Break', 
      166: 'Application Debugger Break', 
      167: 'System Speaker Mute', 
      168: 'System Hibernate', 
      176: 'System Display Invert', 
      177: 'System Display Internal', 
      178: 'System Display External', 
      179: 'System Display Both', 
      180: 'System Display Dual', 
      181: 'System Display Toggle Int/Ext', 
      182: 'System System Display Swap Primary/Secondary', 
      183: 'System Display LCD Autoscale'}), 
 2: (
     'SimulationControls',
     {1: 'Flight Simulation Device', 
      2: 'Automobile Simulation Device', 
      3: 'Tank Simulation Device', 
      4: 'Spaceship Simulation Device', 
      5: 'Submarine Simulation Device', 
      6: 'Sailing Simulation Device', 
      7: 'Motorcycle Simulation Device', 
      8: 'Sports Simulation Device', 
      9: 'Airplane Simulation Device', 
      10: 'Helicopter Simulation Device', 
      11: 'Magic Carpet Simulation Device', 
      12: 'Bicycle Simulation Device', 
      32: 'Flight Control Stick', 
      33: 'Flight Stick', 
      34: 'Cyclic Control', 
      35: 'Cyclic Trim', 
      36: 'Flight Yoke', 
      37: 'Track Control', 
      176: 'Aileron', 
      177: 'Aileron Trim', 
      178: 'Anti-Torque Control', 
      179: 'Autopilot Enable', 
      180: 'Chaff Release', 
      181: 'Collective Control', 
      182: 'Dive Brake', 
      183: 'Electronic Countermeasures', 
      184: 'Elevator', 
      185: 'Elevator Trim', 
      186: 'Rudder', 
      187: 'Throttle', 
      188: 'Flight Communications', 
      189: 'Flare Release', 
      190: 'Landing Gear', 
      191: 'Toe Brake', 
      192: 'Trigger', 
      193: 'Weapons Arm', 
      194: 'Weapons Select', 
      195: 'Wing Flaps', 
      196: 'Accelerator', 
      197: 'Brake', 
      198: 'Clutch', 
      199: 'Shifter', 
      200: 'Steering', 
      201: 'Turret Direction', 
      202: 'Barrel Elevation', 
      203: 'Dive Plane', 
      204: 'Ballast', 
      205: 'Bicycle Crank', 
      206: 'Handle Bars', 
      207: 'Front Brake', 
      208: 'Rear Brake'}), 
 3: (
     'VRControls',
     {1: 'Belt', 
      2: 'Body Suit', 
      3: 'Flexor', 
      4: 'Glove', 
      5: 'Head Tracker', 
      6: 'Head Mounted Display', 
      7: 'Hand Tracker', 
      8: 'Oculometer', 
      9: 'Vest', 
      10: 'Animatronic Device', 
      32: 'Stereo Enable', 
      33: 'Display Enable'}), 
 4: (
     'SportControls',
     {1: 'Baseball Bat', 
      2: 'Golf Club', 
      3: 'Rowing Machine', 
      4: 'Treadmill', 
      48: 'Oar', 
      49: 'Slope', 
      50: 'Rate', 
      51: 'Stick Speed', 
      52: 'Stick Face Angle', 
      53: 'Stick Heel/Toe', 
      54: 'Stick Follow Through', 
      55: 'Stick Tempo', 
      56: 'Stick Type', 
      57: 'Stick Height', 
      80: 'Putter', 
      81: '1 Iron', 
      82: '2 Iron', 
      83: '3 Iron', 
      84: '4 Iron', 
      85: '5 Iron', 
      86: '6 Iron', 
      87: '7 Iron', 
      88: '8 Iron', 
      89: '9 Iron', 
      90: '10 Iron', 
      91: '11 Iron', 
      92: 'Sand Wedge', 
      93: 'Loft Wedge', 
      94: 'Power Wedge', 
      95: '1 Wood', 
      96: '3 Wood', 
      97: '5 Wood', 
      97: '7 Wood', 
      97: '9 Wood'}), 
 5: (
     'GameControls',
     {1: '3D Game Controller', 
      2: 'Pinball Device', 
      3: 'Gun Device', 
      32: 'Point of View', 
      33: 'Turn Right/Left', 
      34: 'Pitch Forward/Backward', 
      35: 'Roll Right/Left', 
      36: 'Move Right/Left', 
      37: 'Move Forward/Backward', 
      38: 'Move Up/Down', 
      39: 'Lean Right/Left', 
      40: 'Lean Forward/Backward', 
      41: 'Height of POV', 
      42: 'Flipper', 
      43: 'Secondary Flipper', 
      44: 'Bump', 
      45: 'New Game', 
      46: 'Shoot Ball', 
      47: 'Player', 
      48: 'Gun Bolt', 
      49: 'Gun Clip', 
      50: 'Gun Selector', 
      51: 'Gun Single Shot', 
      52: 'Gun Burst', 
      53: 'Gun Automatic', 
      54: 'Gun Safety', 
      55: 'Gamepad Fire/Jump', 
      57: 'Gamepad Trigger'}), 
 6: (
     'GenericDeviceControls',
     {32: 'Battery Strength', 
      33: 'Wireless Channel', 
      34: 'Wireless ID', 
      35: 'Discover Wireless Control', 
      36: 'Security Code Character Entered', 
      37: 'Security Code Character Erased', 
      38: 'Security Code Cleared'}), 
 7: (
     'Keyboard',
     {1: 'Keyboard ErrorRollOver', 
      2: 'Keyboard POSTFail', 
      3: 'Keyboard ErrorUndefined', 
      4: 'Keyboard A', 
      5: 'Keyboard B', 
      6: 'Keyboard C', 
      7: 'Keyboard D', 
      8: 'Keyboard E', 
      9: 'Keyboard F', 
      10: 'Keyboard G', 
      11: 'Keyboard H', 
      12: 'Keyboard I', 
      13: 'Keyboard J', 
      14: 'Keyboard K', 
      15: 'Keyboard L', 
      16: 'Keyboard M', 
      17: 'Keyboard N', 
      18: 'Keyboard O', 
      19: 'Keyboard P', 
      20: 'Keyboard Q', 
      21: 'Keyboard R', 
      22: 'Keyboard S', 
      23: 'Keyboard T', 
      24: 'Keyboard U', 
      25: 'Keyboard V', 
      26: 'Keyboard W', 
      27: 'Keyboard X', 
      28: 'Keyboard Y', 
      29: 'Keyboard Z', 
      30: 'Keyboard 1', 
      31: 'Keyboard 2', 
      32: 'Keyboard 3', 
      33: 'Keyboard 4', 
      34: 'Keyboard 5', 
      35: 'Keyboard 6', 
      36: 'Keyboard 7', 
      37: 'Keyboard 8', 
      38: 'Keyboard 9', 
      39: 'Keyboard 0', 
      40: 'Keyboard ENTER', 
      41: 'Keyboard ESCAPE', 
      42: 'Keyboard DELETE', 
      43: 'Keyboard Tab', 
      44: 'Keyboard Spacebar', 
      45: 'Keyboard -', 
      46: 'Keyboard =', 
      47: 'Keyboard [', 
      48: 'Keyboard ]', 
      49: 'Keyboard \\', 
      50: 'Keyboard #', 
      51: 'Keyboard ;', 
      52: "Keyboard '", 
      53: 'Keyboard `', 
      54: 'Keyboard ,', 
      55: 'Keyboard .', 
      56: 'Keyboard /', 
      57: 'Keyboard Caps Lock', 
      58: 'Keyboard F1', 
      59: 'Keyboard F2', 
      60: 'Keyboard F3', 
      61: 'Keyboard F4', 
      62: 'Keyboard F5', 
      63: 'Keyboard F6', 
      64: 'Keyboard F7', 
      65: 'Keyboard F8', 
      66: 'Keyboard F9', 
      67: 'Keyboard F10', 
      68: 'Keyboard F11', 
      69: 'Keyboard F12', 
      70: 'Keyboard PrintScreen', 
      71: 'Keyboard Scroll Lock', 
      72: 'Keyboard Pause', 
      73: 'Keyboard Insert', 
      74: 'Keyboard Home', 
      75: 'Keyboard PageUp', 
      76: 'Keyboard Delete Forward', 
      77: 'Keyboard End', 
      78: 'Keyboard PageDown', 
      79: 'Keyboard RightArrow', 
      80: 'Keyboard LeftArrow', 
      81: 'Keyboard DownArrow', 
      82: 'Keyboard UpArrow', 
      83: 'Keyboard Num Lock', 
      84: 'Keypad /', 
      85: 'Keypad * ', 
      86: 'Keypad - ', 
      87: 'Keypad + ', 
      88: 'Keypad ENTER ', 
      89: 'Keypad 1', 
      90: 'Keypad 2', 
      91: 'Keypad 3', 
      92: 'Keypad 4', 
      93: 'Keypad 5', 
      94: 'Keypad 6', 
      95: 'Keypad 7', 
      96: 'Keypad 8', 
      97: 'Keypad 9', 
      98: 'Keypad 0', 
      99: 'Keypad .', 
      100: 'Keyboard Non-US \\', 
      101: 'Keyboard Application', 
      102: 'Keyboard Power', 
      103: 'Keypad =', 
      104: 'Keyboard F13', 
      105: 'Keyboard F14', 
      106: 'Keyboard F15', 
      107: 'Keyboard F16', 
      108: 'Keyboard F17', 
      109: 'Keyboard F18', 
      110: 'Keyboard F19', 
      111: 'Keyboard F20', 
      112: 'Keyboard F21', 
      113: 'Keyboard F22', 
      114: 'Keyboard F23', 
      115: 'Keyboard F24', 
      116: 'Keyboard Execute', 
      117: 'Keyboard Help', 
      118: 'Keyboard Menu', 
      119: 'Keyboard Select', 
      120: 'Keyboard Stop', 
      121: 'Keyboard Again', 
      122: 'Keyboard Undo', 
      123: 'Keyboard Cut', 
      124: 'Keyboard Copy', 
      125: 'Keyboard Paste', 
      126: 'Keyboard Find', 
      127: 'Keyboard Mute', 
      128: 'Keyboard Volume Up', 
      129: 'Keyboard Volume Down', 
      130: 'Keyboard Locking Caps Lock', 
      131: 'Keyboard Locking Num Lock', 
      132: 'Keyboard Locking Scroll Lock', 
      133: 'Keypad Comma', 
      134: 'Keypad Equal Sign', 
      135: 'Keyboard International1', 
      136: 'Keyboard International2', 
      137: 'Keyboard International3', 
      138: 'Keyboard International4', 
      139: 'Keyboard International5', 
      140: 'Keyboard International6', 
      141: 'Keyboard International7', 
      142: 'Keyboard International8', 
      143: 'Keyboard International9', 
      144: 'Keyboard LANG125', 
      145: 'Keyboard LANG226', 
      146: 'Keyboard LANG330', 
      147: 'Keyboard LANG431', 
      148: 'Keyboard LANG532', 
      149: 'Keyboard LANG68', 
      150: 'Keyboard LANG78', 
      151: 'Keyboard LANG88', 
      152: 'Keyboard LANG98', 
      153: 'Keyboard Alternate Erase', 
      154: 'Keyboard SysReq/Attention', 
      155: 'Keyboard Cancel', 
      156: 'Keyboard Clear', 
      157: 'Keyboard Prior', 
      158: 'Keyboard Return', 
      159: 'Keyboard Separator', 
      160: 'Keyboard Out', 
      161: 'Keyboard Oper', 
      162: 'Keyboard Clear/Again', 
      163: 'Keyboard CrSel/Props', 
      164: 'Keyboard ExSel', 
      176: 'Keypad 00', 
      177: 'Keypad 000', 
      178: 'Thousands Separator', 
      179: 'Decimal Separator', 
      180: 'Currency Unit', 
      181: 'Currency Sub-unit', 
      182: 'Keypad (', 
      183: 'Keypad )', 
      184: 'Keypad {', 
      185: 'Keypad }', 
      186: 'Keypad Tab', 
      187: 'Keypad Backspace', 
      188: 'Keypad A', 
      189: 'Keypad B', 
      190: 'Keypad C', 
      191: 'Keypad D', 
      192: 'Keypad E', 
      193: 'Keypad F', 
      194: 'Keypad XOR', 
      195: 'Keypad ^', 
      196: 'Keypad %', 
      197: 'Keypad <', 
      198: 'Keypad >', 
      199: 'Keypad &', 
      200: 'Keypad &&', 
      201: 'Keypad |', 
      202: 'Keypad ||', 
      203: 'Keypad :', 
      204: 'Keypad #', 
      205: 'Keypad Space', 
      206: 'Keypad @', 
      207: 'Keypad !', 
      208: 'Keypad Memory Store', 
      209: 'Keypad Memory Recall', 
      210: 'Keypad Memory Clear', 
      211: 'Keypad Memory Add', 
      212: 'Keypad Memory Subtract', 
      213: 'Keypad Memory Multiply', 
      214: 'Keypad Memory Divide', 
      215: 'Keypad +/-', 
      216: 'Keypad Clear', 
      217: 'Keypad Clear Entry', 
      218: 'Keypad Binary', 
      219: 'Keypad Octal', 
      220: 'Keypad Decimal', 
      221: 'Keypad Hexadecimal', 
      224: 'Keyboard LeftControl', 
      225: 'Keyboard LeftShift', 
      226: 'Keyboard LeftAlt', 
      227: 'Keyboard Left GUI', 
      228: 'Keyboard RightControl', 
      229: 'Keyboard RightShift ', 
      230: 'Keyboard RightAlt', 
      231: 'Keyboard Right GUI '}), 
 8: (
     'LED',
     {1: 'Num Lock', 
      2: 'Caps Lock', 
      3: 'Scroll Lock', 
      4: 'Compose', 
      5: 'Kana', 
      6: 'Power', 
      7: 'Shift', 
      8: 'Do Not Disturb', 
      9: 'Mute', 
      10: 'Tone Enable', 
      11: 'High Cut Filter', 
      12: 'Low Cut Filter', 
      13: 'Equalizer Enable', 
      14: 'Sound Field On', 
      15: 'Surround On', 
      16: 'Repeat', 
      17: 'Stereo', 
      18: 'Sampling Rate Detect', 
      19: 'Spinning', 
      20: 'CAV', 
      21: 'CLV', 
      22: 'Recording Format Detect', 
      23: 'Off-Hook', 
      24: 'Ring', 
      25: 'Message Waiting', 
      26: 'Data Mode', 
      27: 'Battery Operation', 
      28: 'Battery OK', 
      29: 'Battery Low', 
      30: 'Speaker', 
      31: 'Head Set', 
      32: 'Hold', 
      33: 'Microphone', 
      34: 'Coverage', 
      35: 'Night Mode', 
      36: 'Send Calls', 
      37: 'Call Pickup', 
      38: 'Conference', 
      39: 'Stand-by', 
      40: 'Camera On', 
      41: 'Camera Off', 
      42: 'On-Line', 
      43: 'Off-Line', 
      44: 'Busy', 
      45: 'Ready', 
      46: 'Paper-Out', 
      47: 'Paper-Jam', 
      48: 'Remote', 
      49: 'Forward', 
      50: 'Reverse', 
      51: 'Stop', 
      52: 'Rewind', 
      53: 'Fast Forward', 
      54: 'Play', 
      55: 'Pause', 
      56: 'Record', 
      57: 'Error', 
      58: 'Usage Selected Indicator', 
      59: 'Usage In Use Indicator', 
      60: 'Usage Multi Mode Indicator', 
      61: 'Indicator On', 
      62: 'Indicator Flash', 
      63: 'Indicator Slow Blink', 
      64: 'Indicator Fast Blink', 
      65: 'Indicator Off', 
      66: 'Flash On Time', 
      67: 'Slow Blink On Time', 
      68: 'Slow Blink Off Time', 
      69: 'Fast Blink On Time', 
      70: 'Fast Blink Off Time', 
      71: 'Usage Indicator Color', 
      72: 'Indicator Red', 
      73: 'Indicator Green', 
      74: 'Indicator Amber', 
      75: 'Generic Indicator', 
      76: 'System Suspend', 
      77: 'External Power Connected'}), 
 9: (
     'Button', lambda i: 'Button {0}'.format(i) if i != 0 else 'No button pressed'), 
 10: (
      'Ordinal', lambda i: 'Instance {0}'.format(i) if i != 0 else '0000'), 
 11: (
      'Telephony',
      {1: 'Phone', 
       2: 'Answering Machine', 
       3: 'Message Controls', 
       4: 'Handset', 
       5: 'Headset', 
       6: 'Telephony Key Pad', 
       7: 'Programmable Button', 
       32: 'Hook Switch', 
       33: 'Flash', 
       34: 'Feature', 
       35: 'Hold', 
       36: 'Redial', 
       37: 'Transfer', 
       38: 'Drop', 
       39: 'Park', 
       40: 'Forward Calls', 
       41: 'Alternate Function', 
       42: 'Line', 
       43: 'Speaker Phone', 
       44: 'Conference', 
       45: 'Ring Enable', 
       46: 'Ring Select', 
       47: 'Phone Mute', 
       48: 'Caller ID', 
       49: 'Send', 
       80: 'Speed Dial', 
       81: 'Store Number', 
       82: 'Recall Number', 
       83: 'Phone Directory', 
       112: 'Voice Mail', 
       113: 'Screen Calls', 
       114: 'Do Not Disturb', 
       115: 'Message', 
       116: 'Answer On/Off', 
       144: 'Inside Dial Tone', 
       145: 'Outside Dial Tone', 
       146: 'Inside Ring Tone', 
       147: 'Outside Ring Tone', 
       148: 'Priority Ring Tone', 
       149: 'Inside Ringback', 
       150: 'Priority Ringback', 
       151: 'Line Busy Tone', 
       152: 'Reorder Tone', 
       153: 'Call Waiting Tone', 
       154: 'Confirmation Tone 1', 
       155: 'Confirmation Tone 2', 
       156: 'Tones Off', 
       157: 'Outside Ringback', 
       158: 'Ringer', 
       176: 'Phone Key 0', 
       177: 'Phone Key 1', 
       178: 'Phone Key 2', 
       179: 'Phone Key 3', 
       180: 'Phone Key 4', 
       181: 'Phone Key 5', 
       182: 'Phone Key 6', 
       183: 'Phone Key 7', 
       184: 'Phone Key 8', 
       185: 'Phone Key 9', 
       186: 'Phone Key Star', 
       187: 'Phone Key Pound', 
       188: 'Phone Key A', 
       189: 'Phone Key B', 
       190: 'Phone Key C', 
       191: 'Phone Key D'}), 
 12: (
      'Consumer',
      {1: 'Consumer Control', 
       2: 'Numeric Key Pad', 
       3: 'Programmable Buttons', 
       4: 'Microphone', 
       5: 'Headphone', 
       6: 'Graphic Equalizer', 
       32: '+10', 
       33: '+100', 
       34: 'AM/PM', 
       48: 'Power', 
       49: 'Reset', 
       50: 'Sleep', 
       51: 'Sleep After', 
       52: 'Sleep Mode', 
       53: 'Illumination', 
       54: 'Function Buttons', 
       64: 'Menu', 
       65: 'Menu Pick', 
       66: 'Menu Up', 
       67: 'Menu Down', 
       68: 'Menu Left', 
       69: 'Menu Right', 
       70: 'Menu Escape', 
       71: 'Menu Value Increase', 
       72: 'Menu Value Decrease', 
       96: 'Data On Screen', 
       97: 'Closed Caption', 
       98: 'Closed Caption Select', 
       99: 'VCR/TV', 
       100: 'Broadcast Mode', 
       101: 'Snapshot', 
       102: 'Still', 
       128: 'Selection', 
       129: 'Assign Selection', 
       130: 'Mode Step', 
       131: 'Recall Last', 
       132: 'Enter Channel', 
       133: 'Order Movie', 
       134: 'Channel', 
       135: 'Media Selection', 
       136: 'Media Select Computer', 
       137: 'Media Select TV', 
       138: 'Media Select WWW', 
       139: 'Media Select DVD', 
       140: 'Media Select Telephone', 
       141: 'Media Select Program Guide', 
       142: 'Media Select Video Phone', 
       143: 'Media Select Games', 
       144: 'Media Select Messages', 
       145: 'Media Select CD', 
       146: 'Media Select VCR', 
       147: 'Media Select Tuner', 
       148: 'Quit', 
       149: 'Help', 
       150: 'Media Select Tape', 
       151: 'Media Select Cable', 
       152: 'Media Select Satellite', 
       153: 'Media Select Security', 
       154: 'Media Select Home', 
       155: 'Media Select Call', 
       156: 'Channel Increment', 
       157: 'Channel Decrement', 
       158: 'Media Select SAP', 
       160: 'VCR Plus', 
       161: 'Once', 
       162: 'Daily', 
       163: 'Weekly', 
       164: 'Monthly', 
       176: 'Play', 
       177: 'Pause', 
       178: 'Record', 
       179: 'Fast Forward', 
       180: 'Rewind', 
       181: 'Scan Next Track', 
       182: 'Scan Previous Track', 
       183: 'Stop', 
       184: 'Eject', 
       185: 'Random Play', 
       186: 'Select Disc', 
       187: 'Enter Disc', 
       188: 'Repeat', 
       189: 'Tracking', 
       190: 'Track Normal', 
       191: 'Slow Tracking', 
       192: 'Frame Forward', 
       193: 'Frame Back', 
       194: 'Mark', 
       195: 'Clear Mark', 
       196: 'Repeat From Mark', 
       197: 'Return To Mark', 
       198: 'Search Mark Forward', 
       199: 'Search Mark Backwards', 
       200: 'Counter Reset', 
       201: 'Show Counter', 
       202: 'Tracking Increment', 
       203: 'Tracking Decrement', 
       204: 'Stop/Eject', 
       205: 'Play/Pause', 
       206: 'Play/Skip', 
       224: 'Volume', 
       225: 'Balance', 
       226: 'Mute', 
       227: 'Bass', 
       228: 'Treble', 
       229: 'Bass Boost', 
       230: 'Surround Mode', 
       231: 'Loudness', 
       232: 'MPX', 
       233: 'Volume Increment', 
       234: 'Volume Decrement', 
       240: 'Speed Select', 
       241: 'Playback Speed', 
       242: 'Standard Play', 
       243: 'Long Play', 
       244: 'Extended Play', 
       245: 'Slow', 
       256: 'Fan Enable', 
       257: 'Fan Speed', 
       258: 'Light Enable', 
       259: 'Light Illumination Level', 
       260: 'Climate Control Enable', 
       261: 'Room Temperature', 
       262: 'Security Enable', 
       263: 'Fire Alarm', 
       264: 'Police Alarm', 
       265: 'Proximity', 
       266: 'Motion', 
       267: 'Duress Alarm', 
       268: 'Holdup Alarm', 
       269: 'Medical Alarm', 
       336: 'Balance Right', 
       337: 'Balance Left', 
       338: 'Bass Increment', 
       339: 'Bass Decrement', 
       340: 'Treble Increment', 
       341: 'Treble Decrement', 
       352: 'Speaker System', 
       353: 'Channel Left', 
       354: 'Channel Right', 
       355: 'Channel Center', 
       356: 'Channel Front', 
       357: 'Channel Center Front', 
       358: 'Channel Side', 
       359: 'Channel Surround', 
       360: 'Channel Low Frequency Enhancement', 
       361: 'Channel Top', 
       362: 'Channel Unknown', 
       368: 'Sub-channel', 
       369: 'Sub-channel Increment', 
       370: 'Sub-channel Decrement', 
       371: 'Alternate Audio Increment', 
       372: 'Alternate Audio Decrement', 
       384: 'Application Launch Buttons', 
       385: 'AL Launch Button Configuration Tool', 
       386: 'AL Programmable Button Configuration', 
       387: 'AL Consumer Control Configuration', 
       388: 'AL Word Processor', 
       389: 'AL Text Editor', 
       390: 'AL Spreadsheet', 
       391: 'AL Graphics Editor', 
       392: 'AL Presentation App', 
       393: 'AL Database App', 
       394: 'AL Email Reader', 
       395: 'AL Newsreader', 
       396: 'AL Voicemail', 
       397: 'AL Contacts/Address Book', 
       398: 'AL Calendar/Schedule', 
       399: 'AL Task/Project Manager', 
       400: 'AL Log/Journal/Timecard', 
       401: 'AL Checkbook/Finance', 
       402: 'AL Calculator', 
       403: 'AL A/V Capture/Playback', 
       404: 'AL Local Machine Browser', 
       405: 'AL LAN/WAN Browser', 
       406: 'AL Internet Browser', 
       407: 'AL Remote Networking/ISP Connect', 
       408: 'AL Network Conference', 
       409: 'AL Network Chat', 
       410: 'AL Telephony/Dialer', 
       411: 'AL Logon', 
       412: 'AL Logoff', 
       413: 'AL Logon/Logoff', 
       414: 'AL Terminal Lock/Screensaver', 
       415: 'AL Control Panel', 
       416: 'AL Command Line Processor/Run Sel', 
       417: 'AL Process/Task Manager', 
       418: 'AL Select Task/Application', 
       419: 'AL Next Task/Application', 
       420: 'AL Previous Task/Application', 
       421: 'AL Preemptive Halt Task/Application', 
       422: 'AL Integrated Help Center', 
       423: 'AL Documents', 
       424: 'AL Thesaurus', 
       425: 'AL Dictionary', 
       426: 'AL Desktop', 
       427: 'AL Spell Check', 
       428: 'AL Grammar Check', 
       429: 'AL Wireless Status', 
       430: 'AL Keyboard Layout', 
       431: 'AL Virus Protection', 
       432: 'AL Encryption', 
       433: 'AL Screen Saver', 
       434: 'AL Alarms', 
       435: 'AL Clock', 
       436: 'AL File Browser', 
       437: 'AL Power Status', 
       512: 'Generic GUI Application Controls', 
       513: 'AC New', 
       514: 'AC Open', 
       515: 'AC Close', 
       516: 'AC Exit', 
       517: 'AC Maximize', 
       518: 'AC Minimize', 
       519: 'AC Save', 
       520: 'AC Print', 
       521: 'AC Properties', 
       538: 'AC Undo', 
       539: 'AC Copy', 
       540: 'AC Cut', 
       541: 'AC Paste', 
       542: 'AC Select All', 
       543: 'AC Find', 
       544: 'AC Find and Replace', 
       545: 'AC Search', 
       546: 'AC Go To', 
       547: 'AC Home', 
       548: 'AC Back', 
       549: 'AC Forward', 
       550: 'AC Stop', 
       551: 'AC Refresh', 
       552: 'AC Previous Link', 
       553: 'AC Next Link', 
       554: 'AC Bookmarks', 
       555: 'AC History', 
       556: 'AC Subscriptions', 
       557: 'AC Zoom In', 
       558: 'AC Zoom Out', 
       559: 'AC Zoom', 
       560: 'AC Full Screen View', 
       561: 'AC Normal View', 
       562: 'AC View Toggle', 
       563: 'AC Scroll Up', 
       564: 'AC Scroll Down', 
       565: 'AC Scroll', 
       566: 'AC Pan Left', 
       567: 'AC Pan Right', 
       568: 'AC Pan', 
       569: 'AC New Window', 
       570: 'AC Tile Horizontally', 
       571: 'AC Tile Vertically', 
       572: 'AC Format', 
       573: 'AC Edit', 
       574: 'AC Bold', 
       575: 'AC Italics', 
       576: 'AC Underline', 
       577: 'AC Strikethrough', 
       578: 'AC Subscript', 
       579: 'AC Superscript', 
       580: 'AC All Caps', 
       581: 'AC Rotate', 
       582: 'AC Resize', 
       583: 'AC Flip horizontal', 
       584: 'AC Flip Vertical', 
       585: 'AC Mirror Horizontal', 
       586: 'AC Mirror Vertical', 
       587: 'AC Font Select', 
       588: 'AC Font Color', 
       589: 'AC Font Size', 
       590: 'AC Justify Left', 
       591: 'AC Justify Center H', 
       592: 'AC Justify Right', 
       593: 'AC Justify Block H', 
       594: 'AC Justify Top', 
       595: 'AC Justify Center V', 
       596: 'AC Justify Bottom', 
       597: 'AC Justify Block V', 
       598: 'AC Indent Decrease', 
       599: 'AC Indent Increase', 
       600: 'AC Numbered List', 
       601: 'AC Restart Numbering', 
       602: 'AC Bulleted List', 
       603: 'AC Promote', 
       604: 'AC Demote', 
       605: 'AC Yes', 
       606: 'AC No', 
       607: 'AC Cancel', 
       608: 'AC Catalog', 
       609: 'AC Buy/Checkout', 
       610: 'AC Add to Cart', 
       611: 'AC Expand', 
       612: 'AC Expand All', 
       613: 'AC Collapse', 
       614: 'AC Collapse All', 
       615: 'AC Print Preview', 
       616: 'AC Paste Special', 
       617: 'AC Insert Mode', 
       618: 'AC Delete', 
       619: 'AC Lock', 
       620: 'AC Unlock', 
       621: 'AC Protect', 
       622: 'AC Unprotect', 
       623: 'AC Attach Comment', 
       624: 'AC Delete Comment', 
       625: 'AC View Comment', 
       626: 'AC Select Word', 
       627: 'AC Select Sentence', 
       628: 'AC Select Paragraph', 
       629: 'AC Select Column', 
       630: 'AC Select Row', 
       631: 'AC Select Table', 
       632: 'AC Select Object', 
       633: 'AC Redo/Repeat', 
       634: 'AC Sort', 
       635: 'AC Sort Ascending', 
       636: 'AC Sort Descending', 
       637: 'AC Filter', 
       638: 'AC Set Clock', 
       639: 'AC View Clock', 
       640: 'AC Select Time Zone', 
       641: 'AC Edit Time Zones', 
       642: 'AC Set Alarm', 
       643: 'AC Clear Alarm', 
       644: 'AC Snooze Alarm', 
       645: 'AC Reset Alarm', 
       646: 'AC Synchronize', 
       647: 'AC Send/Receive', 
       648: 'AC Send To', 
       649: 'AC Reply', 
       650: 'AC Reply All', 
       651: 'AC Forward Msg', 
       652: 'AC Send', 
       653: 'AC Attach File', 
       654: 'AC Upload', 
       655: 'AC Download (Save Target As)', 
       656: 'AC Set Borders', 
       657: 'AC Insert Row', 
       658: 'AC Insert Column', 
       659: 'AC Insert File', 
       660: 'AC Insert Picture', 
       661: 'AC Insert Object', 
       662: 'AC Insert Symbol', 
       663: 'AC Save and Close', 
       664: 'AC Rename', 
       665: 'AC Merge', 
       666: 'AC Split', 
       667: 'AC Disribute Horizontally', 
       668: 'AC Distribute Vertically'}), 
 13: (
      'Digitizer',
      {1: 'Digitizer', 
       2: 'Pen', 
       3: 'Light Pen', 
       4: 'Touch Screen', 
       5: 'Touch Pad', 
       6: 'White Board', 
       7: 'Coordinate Measuring Machine', 
       8: '3D Digitizer', 
       9: 'Stereo Plotter', 
       10: 'Articulated Arm', 
       11: 'Armature', 
       12: 'Multiple Point Digitizer', 
       13: 'Free Space Wand', 
       32: 'Stylus', 
       33: 'Puck', 
       34: 'Finger', 
       48: 'Tip Pressure', 
       49: 'Barrel Pressure', 
       50: 'In Range', 
       51: 'Touch', 
       52: 'Untouch', 
       53: 'Tap', 
       54: 'Quality', 
       55: 'Data Valid', 
       56: 'Transducer Index', 
       57: 'Tablet Function Keys', 
       58: 'Program Change Keys', 
       59: 'Battery Strength', 
       60: 'Invert', 
       61: 'X Tilt', 
       62: 'Y Tilt', 
       63: 'Azimuth', 
       64: 'Altitude', 
       65: 'Twist', 
       66: 'Tip Switch', 
       67: 'Secondary Tip Switch', 
       68: 'Barrel Switch', 
       69: 'Eraser', 
       70: 'Tablet Pick'}), 
 15: (
      'PhysicalInputDevice',
      {1: 'Physical Interface Device', 
       32: 'Normal', 
       33: 'Set Effect Report', 
       34: 'Effect Block Index', 
       35: 'Parameter Block Offset', 
       36: 'ROM Flag', 
       37: 'Effect Type', 
       38: 'ET Constant Force', 
       39: 'ET Ramp', 
       40: 'ET Custom Force Data', 
       48: 'ET Square', 
       49: 'ET Sine', 
       50: 'ET Triangle', 
       51: 'ET Sawtooth Up', 
       52: 'ET Sawtooth Down', 
       64: 'ET Spring', 
       65: 'ET Damper', 
       66: 'ET Inertia', 
       67: 'ET Friction', 
       80: 'Duration', 
       81: 'Sample Period', 
       82: 'Gain', 
       83: 'Trigger Button', 
       84: 'Trigger Repeat Interval', 
       85: 'Axes Enable', 
       86: 'Direction Enable', 
       87: 'Direction', 
       88: 'Type Specific Block Offset', 
       89: 'Block Type', 
       90: 'Set Envelope Report', 
       91: 'Attack Level', 
       92: 'Attack Time', 
       93: 'Fade Level', 
       94: 'Fade Time', 
       95: 'Set Condition Report', 
       96: 'CP Offset', 
       97: 'Positive Coefficient', 
       98: 'Negative Coefficient', 
       99: 'Positive Saturation', 
       100: 'Negative Saturation', 
       101: 'Dead Band', 
       102: 'Download Force Sample', 
       103: 'Isoch Custom Force Enable', 
       104: 'Custom Force Data Report', 
       105: 'Custom Force Data', 
       106: 'Custom Force Vendor Defined Data', 
       107: 'Set Custom Force Report', 
       108: 'Custom Force Data Offset', 
       109: 'Sample Count', 
       110: 'Set Periodic Report', 
       111: 'Offset', 
       112: 'Magnitude', 
       113: 'Phase', 
       114: 'Period', 
       115: 'Set Constant Force Report', 
       116: 'Set Ramp Force Report', 
       117: 'Ramp Start', 
       118: 'Ramp End', 
       119: 'Effect Operation Report', 
       120: 'Effect Operation', 
       121: 'Op Effect Start', 
       122: 'Op Effect Start Solo', 
       123: 'Op Effect Stop', 
       124: 'Loop Count', 
       125: 'Device Gain Report', 
       126: 'Device Gain', 
       127: 'PID Pool Report', 
       128: 'RAM Pool Size', 
       129: 'ROM Pool Size', 
       130: 'ROM Effect Block Count', 
       131: 'Simultaneous Effects Max', 
       132: 'Pool Alignment', 
       133: 'PID Pool Move Report', 
       134: 'Move Source', 
       135: 'Move Destination', 
       136: 'Move Length', 
       137: 'PID Block Load Report', 
       139: 'Block Load Status', 
       140: 'Block Load Success', 
       141: 'Block Load Full', 
       142: 'Block Load error', 
       143: 'Block Handle', 
       144: 'PID Block Free Report', 
       145: 'Type Specific Block Handle', 
       146: 'PID State Report', 
       148: 'Effect Playing', 
       149: 'PID Device Control Report', 
       150: 'PID Device Control', 
       151: 'DC Enable Actuators', 
       152: 'DC Disable Actuators', 
       153: 'DC Stop All Effects', 
       154: 'DC Device Reset', 
       155: 'DC Device Pause', 
       156: 'DC Device Continue', 
       159: 'Device Paused', 
       160: 'Actuators Enabled', 
       164: 'Safety Switch', 
       165: 'Actuator Override Switch', 
       166: 'Actuator Power', 
       167: 'Start Delay', 
       168: 'Parameter Block Size', 
       169: 'Device Managed Pool', 
       170: 'Shared Parameter Blocks', 
       171: 'Create New Effect Report', 
       172: 'RAM Pool Available'}), 
 16: ('Unicode', None), 
 20: (
      'AlphanumericDisplay',
      {1: 'Alphanumeric Display', 
       2: 'Bitmapped Display', 
       32: 'Display Attributes Report', 
       33: 'ASCII Character Set', 
       34: 'Data Read Back', 
       35: 'Font Read Back', 
       36: 'Display Control Report', 
       37: 'Clear Display', 
       38: 'Display Enable', 
       39: 'Screen Saver Delay', 
       40: 'Screen Saver Enable', 
       41: 'Vertical Scroll', 
       42: 'Horizontal Scroll', 
       43: 'Character Report', 
       44: 'Display Data', 
       45: 'Display Status', 
       46: 'Stat Not Ready', 
       47: 'Stat Ready', 
       48: 'Err Not a loadable character', 
       49: 'Err Font data cannot be read', 
       50: 'Cursor Position Report', 
       51: 'Row', 
       52: 'Column', 
       53: 'Rows', 
       54: 'Columns', 
       55: 'Cursor Pixel Positioning', 
       56: 'Cursor Mode', 
       57: 'Cursor Enable', 
       58: 'Cursor Blink', 
       59: 'Font Report', 
       60: 'Font Data', 
       61: 'Character Width', 
       62: 'Character Height', 
       63: 'Character Spacing Horizontal', 
       64: 'Character Spacing Vertical', 
       65: 'Unicode Character Set', 
       66: 'Font 7-Segment', 
       67: '7-Segment Direct Map', 
       68: 'Font 14-Segment', 
       69: '14-Segment Direct Map', 
       70: 'Display Brightness', 
       71: 'Display Contrast', 
       72: 'Character Attribute', 
       73: 'Attribute Readback', 
       74: 'Attribute Data', 
       75: 'Char Attr Enhance', 
       76: 'Char Attr Underline', 
       77: 'Char Attr Blink', 
       128: 'Bitmap Size X', 
       129: 'Bitmap Size Y', 
       131: 'Bit Depth Format', 
       132: 'Display Orientation', 
       133: 'Palette Report', 
       134: 'Palette Data Size', 
       135: 'Palette Data Offset', 
       136: 'Palette Data', 
       138: 'Blit Report', 
       139: 'Blit Rectangle X1', 
       140: 'Blit Rectangle Y1', 
       141: 'Blit Rectangle X2', 
       142: 'Blit Rectangle Y2', 
       143: 'Blit Data', 
       144: 'Soft Button', 
       145: 'Soft Button ID', 
       146: 'Soft Button Side', 
       147: 'Soft Button Offset 1', 
       148: 'Soft Button Offset 2', 
       149: 'Soft Button Report'}), 
 64: (
      'MedicalInstrument',
      {1: 'Medical Ultrasound', 
       32: 'VCR/Acquisition', 
       33: 'Freeze/Thaw', 
       34: 'Clip Store', 
       35: 'Update', 
       36: 'Next', 
       37: 'Save', 
       38: 'Print', 
       39: 'Microphone Enable', 
       64: 'Cine', 
       65: 'Transmit Power', 
       66: 'Volume', 
       67: 'Focus', 
       68: 'Depth', 
       96: 'Soft Step - Primary', 
       97: 'Soft Step - Secondary', 
       112: 'Depth Gain Compensation', 
       128: 'Zoom Select', 
       129: 'Zoom Adjust', 
       130: 'Spectral Doppler Mode Select', 
       131: 'Spectral Doppler Adjust', 
       132: 'Color Doppler Mode Select', 
       133: 'Color Doppler Adjust', 
       134: 'Motion Mode Select', 
       135: 'Motion Mode Adjust', 
       136: '2-D Mode Select', 
       137: '2-D Mode Adjust', 
       160: 'Soft Control Select', 
       161: 'Soft Control Adjust'}), 
 128: (
       'Monitor',
       {1: 'Monitor Control', 
        2: 'EDID Information', 
        3: 'VDIF Information', 
        4: 'VESA Version'}), 
 129: (
       'EnumeratedValues', lambda i: 'ENUM {0}'.format(i) if i != 0 else '0000'), 
 130: (
       'VESAControls',
       {16: 'Brightness', 
        18: 'Contrast', 
        22: 'Red Video Gain', 
        24: 'Green Video Gain', 
        26: 'Blue Video Gain', 
        28: 'Focus', 
        32: 'Horizontal Position', 
        34: 'Horizontal Size', 
        36: 'Horizontal Pincushion', 
        38: 'Horizontal Pincushion Balance', 
        40: 'Horizontal Misconvergence', 
        42: 'Horizontal Linearity', 
        44: 'Horizontal Linearity Balance', 
        48: 'Vertical Position', 
        50: 'Vertical Size', 
        52: 'Vertical Pincushion', 
        54: 'Vertical Pincushion Balance', 
        56: 'Vertical Misconvergence', 
        58: 'Vertical Linearity', 
        60: 'Vertical Linearity Balance', 
        64: 'Parallelogram Distortion', 
        66: 'Trapezoidal Distortion', 
        68: 'Tilt', 
        70: 'Top Corner Distortion Control', 
        72: 'Top Corner Distortion Balance', 
        74: 'Bottom Corner Distortion Control', 
        76: 'Bottom Corner Distortion Balance', 
        86: 'Horizontal Moiré', 
        88: 'Vertical Moiré', 
        108: 'Red Video Black Level', 
        110: 'Green Video Black Level', 
        112: 'Blue Video Black Level', 
        94: 'Input Level Select', 
        96: 'Input Source Select', 
        202: 'On Screen Display', 
        212: 'StereoMode', 
        162: 'Auto Size Center', 
        164: 'Polarity Horizontal Synchronization', 
        166: 'Polarity Vertical Synchronization', 
        168: 'Synchronization Type', 
        170: 'Screen Orientation', 
        172: 'Horizontal Frequency', 
        174: 'Vertical Frequency', 
        1: 'Degauss', 
        176: 'Settings Save/Reset'}), 
 132: (
       'Power',
       {1: 'iName', 
        2: 'PresentStatus', 
        3: 'ChangedStatus', 
        4: 'UPS', 
        5: 'PowerSupply', 
        16: 'BatterySystem', 
        17: 'BatterySystemID', 
        18: 'Battery', 
        19: 'BatteryID', 
        20: 'Charger', 
        21: 'ChargerID', 
        22: 'PowerConverter', 
        23: 'PowerConverterID', 
        24: 'OutletSystem', 
        25: 'OutletSystemID', 
        26: 'Input', 
        27: 'InputID', 
        28: 'Output', 
        29: 'OutputID', 
        30: 'Flow', 
        31: 'FlowID', 
        32: 'Outlet', 
        33: 'OutletID', 
        34: 'Gang', 
        35: 'GangID', 
        36: 'PowerSummary', 
        37: 'PowerSummaryID', 
        48: 'Voltage', 
        49: 'Current', 
        50: 'Frequency', 
        51: 'ApparentPower', 
        52: 'ActivePower', 
        53: 'PercentLoad', 
        54: 'Temperature', 
        55: 'Humidity', 
        56: 'BadCount', 
        64: 'ConfigVoltage', 
        65: 'ConfigCurrent', 
        66: 'ConfigFrequency', 
        67: 'ConfigApparentPower', 
        68: 'ConfigActivePower', 
        69: 'ConfigPercentLoad', 
        70: 'ConfigTemperature', 
        71: 'ConfigHumidity', 
        80: 'SwitchOnControl', 
        81: 'SwitchOffControl', 
        82: 'ToggleControl', 
        83: 'LowVoltageTransfer', 
        84: 'HighVoltageTransfer', 
        85: 'DelayBeforeReboot', 
        86: 'DelayBeforeStartup', 
        87: 'DelayBeforeShutdown', 
        88: 'Test', 
        89: 'ModuleReset', 
        90: 'AudibleAlarmControl', 
        96: 'Present', 
        97: 'Good', 
        98: 'InternalFailure', 
        99: 'VoltageOutOfRange', 
        100: 'FrequencyOutOfRange', 
        101: 'Overload', 
        102: 'OverCharged', 
        103: 'OverTemperature', 
        104: 'ShutdownRequested', 
        105: 'ShutdownImminent', 
        107: 'SwitchOn/Off', 
        108: 'Switchable', 
        109: 'Used', 
        110: 'Boost', 
        111: 'Buck', 
        112: 'Initialized', 
        113: 'Tested', 
        114: 'AwaitingPower', 
        115: 'CommunicationLost', 
        253: 'iManufacturer', 
        254: 'iProduct', 
        255: 'iserialNumber'}), 
 133: (
       'Battery',
       {1: 'SMBBatteryMode', 
        2: 'SMBBatteryStatus', 
        3: 'SMBAlarmWarning', 
        4: 'SMBChargerMode', 
        5: 'SMBChargerStatus', 
        6: 'SMBChargerSpecInfo', 
        7: 'SMBSelectorState', 
        8: 'SMBSelectorPresets', 
        9: 'SMBSelectorInfo', 
        16: 'OptionalMfgFunction1', 
        17: 'OptionalMfgFunction2', 
        18: 'OptionalMfgFunction3', 
        19: 'OptionalMfgFunction4', 
        20: 'OptionalMfgFunction5', 
        21: 'ConnectionToSMBus', 
        22: 'OutputConnection', 
        23: 'ChargerConnection', 
        24: 'BatteryInsertion', 
        25: 'Usenext', 
        26: 'OKToUse', 
        27: 'BatterySupported', 
        28: 'SelectorRevision', 
        29: 'ChargingIndicator', 
        40: 'ManufacturerAccess', 
        41: 'RemainingCapacityLimit', 
        42: 'RemainingTimeLimit', 
        43: 'AtRate', 
        44: 'CapacityMode', 
        45: 'BroadcastToCharger', 
        46: 'PrimaryBattery', 
        47: 'ChargeController', 
        64: 'TerminateCharge', 
        65: 'TerminateDischarge', 
        66: 'BelowRemainingCapacityLimit', 
        67: 'RemainingTimeLimitExpired', 
        68: 'Charging', 
        69: 'Discharging', 
        70: 'FullyCharged', 
        71: 'FullyDischarged', 
        72: 'ConditioningFlag', 
        73: 'AtRateOK', 
        74: 'SMBErrorCode', 
        75: 'NeedReplacement', 
        96: 'AtRateTimeToFull', 
        97: 'AtRateTimeToEmpty', 
        98: 'AverageCurrent', 
        99: 'Maxerror', 
        100: 'RelativeStateOfCharge', 
        101: 'AbsoluteStateOfCharge', 
        102: 'RemainingCapacity', 
        103: 'FullChargeCapacity', 
        104: 'RunTimeToEmpty', 
        105: 'AverageTimeToEmpty', 
        106: 'AverageTimeToFull', 
        107: 'CycleCount', 
        128: 'BattPackModelLevel', 
        129: 'InternalChargeController', 
        130: 'PrimaryBatterySupport', 
        131: 'DesignCapacity', 
        132: 'SpecificationInfo', 
        133: 'ManufacturerDate', 
        134: 'SerialNumber', 
        135: 'iManufacturerName', 
        136: 'iDevicename', 
        137: 'iDeviceChemistery', 
        138: 'ManufacturerData', 
        139: 'Rechargable', 
        140: 'WarningCapacityLimit', 
        141: 'CapacityGranularity1', 
        142: 'CapacityGranularity2', 
        143: 'iOEMInformation', 
        192: 'InhibitCharge', 
        193: 'EnablePolling', 
        194: 'ResetToZero', 
        208: 'ACPresent', 
        209: 'BatteryPresent', 
        210: 'PowerFail', 
        211: 'AlarmInhibited', 
        212: 'ThermistorUnderRange', 
        213: 'ThermistorHot', 
        214: 'ThermistorCold', 
        215: 'ThermistorOverRange', 
        216: 'VoltageOutOfRange', 
        217: 'CurrentOutOfRange', 
        218: 'CurrentNotRegulated', 
        219: 'VoltageNotRegulated', 
        220: 'MasterMode', 
        240: 'ChargerSelectorSupport', 
        241: 'ChargerSpec', 
        242: 'Level2', 
        243: 'Level3'}), 
 140: (
       'BarCodeScanner',
       {1: 'Bar Code Badge Reader', 
        2: 'Bar Code Scanner', 
        3: 'Dumb Bar Code Scanner', 
        4: 'Cordless Scanner Base', 
        5: 'Bar Code Scanner Cradle', 
        16: 'Attribute Report', 
        17: 'Settings Report', 
        18: 'Scanned Data Report', 
        19: 'Raw Scanned Data Report', 
        20: 'Trigger Report', 
        21: 'Status Report', 
        22: 'UPC/EAN Control Report', 
        23: 'EAN 2/3 Label Control Report', 
        24: 'Code 39 Control Report', 
        25: 'Interleaved 2 of 5 Control Report', 
        26: 'Standard 2 of 5 Control Report', 
        27: 'MSI Plessey Control Report', 
        28: 'Codabar Control Report', 
        29: 'Code 128 Control Report', 
        30: 'Misc 1D Control Report', 
        31: '2D Control Report', 
        48: 'Aiming/Pointer Mode', 
        49: 'Bar Code Present Sensor', 
        50: 'Class 1A Laser', 
        51: 'Class 2 Laser', 
        52: 'Heater Present', 
        53: 'Contact Scanner', 
        54: 'Electronic Article Surveillance Notification', 
        55: 'Constant Electronic Article Surveillance', 
        56: 'Error Indication', 
        57: 'Fixed Beeper', 
        58: 'Good Decode Indication', 
        59: 'Hands Free Scanning', 
        60: 'Intrinsically Safe', 
        61: 'Klasse Eins Laser', 
        62: 'Long Range Scanner', 
        63: 'Mirror Speed Control', 
        64: 'Not On File Indication', 
        65: 'Programmable Beeper', 
        66: 'Triggerless', 
        67: 'Wand', 
        68: 'Water Resistant', 
        69: 'Multi-Range Scanner', 
        70: 'Proximity Sensor', 
        77: 'Fragment Decoding', 
        78: 'Scanner Read Confidence', 
        79: 'Data Prefix', 
        80: 'Prefix AIMI', 
        81: 'Prefix None', 
        82: 'Prefix Proprietary', 
        85: 'Active Time', 
        86: 'Aiming Laser Pattern', 
        87: 'Bar Code Present', 
        88: 'Beeper State', 
        89: 'Laser On Time', 
        90: 'Laser State', 
        91: 'Lockout Time', 
        92: 'Motor State', 
        93: 'Motor Timeout', 
        94: 'Power On Reset Scanner', 
        95: 'Prevent Read of Barcodes', 
        96: 'Initiate Barcode Read', 
        97: 'Trigger State', 
        98: 'Trigger Mode', 
        99: 'Trigger Mode Blinking Laser On', 
        100: 'Trigger Mode Continuous Laser On', 
        101: 'Trigger Mode Laser on while Pulled', 
        102: 'Trigger Mode Laser stays on after Trigger release', 
        109: 'Commit Parameters to NVM', 
        110: 'Parameter Scanning', 
        111: 'Parameters Changed', 
        112: 'Set parameter default values', 
        117: 'Scanner In Cradle', 
        118: 'Scanner In Range', 
        122: 'Aim Duration', 
        123: 'Good Read Lamp Duration', 
        124: 'Good Read Lamp Intensity', 
        125: 'Good Read LED', 
        126: 'Good Read Tone Frequency', 
        127: 'Good Read Tone Length', 
        128: 'Good Read Tone Volume', 
        130: 'No Read Message', 
        131: 'Not on File Volume', 
        132: 'Powerup Beep', 
        133: 'Sound Error Beep', 
        134: 'Sound Good Read Beep', 
        135: 'Sound Not On File Beep', 
        136: 'Good Read When to Write', 
        137: 'GRWTI After Decode', 
        138: 'GRWTI Beep/Lamp after transmit', 
        139: 'GRWTI No Beep/Lamp use at all', 
        145: 'Bookland EAN', 
        146: 'Convert EAN 8 to 13 Type', 
        147: 'Convert UPC A to EAN-13', 
        148: 'Convert UPC-E to A', 
        149: 'EAN-13', 
        150: 'EAN-8', 
        151: 'EAN-99 128_Mandatory', 
        152: 'EAN-99 P5/128_Optional', 
        154: 'UPC/EAN', 
        155: 'UPC/EAN Coupon Code', 
        156: 'UPC/EAN Periodicals', 
        157: 'UPC-A', 
        158: 'UPC-A with 128 Mandatory', 
        159: 'UPC-A with 128 Optional', 
        160: 'UPC-A with P5 Optional', 
        161: 'UPC-E', 
        162: 'UPC-E1', 
        169: 'Periodical', 
        170: 'Periodical Auto-Discriminate + 2', 
        171: 'Periodical Only Decode with + 2', 
        172: 'Periodical Ignore + 2', 
        173: 'Periodical Auto-Discriminate + 5', 
        174: 'Periodical Only Decode with + 5', 
        175: 'Periodical Ignore + 5', 
        176: 'Check', 
        177: 'Check Disable Price', 
        178: 'Check Enable 4 digit Price', 
        179: 'Check Enable 5 digit Price', 
        180: 'Check Enable European 4 digit Price', 
        181: 'Check Enable European 5 digit Price', 
        183: 'EAN Two Label', 
        184: 'EAN Three Label', 
        185: 'EAN 8 Flag Digit 1', 
        186: 'EAN 8 Flag Digit 2', 
        187: 'EAN 8 Flag Digit 3', 
        188: 'EAN 13 Flag Digit 1', 
        189: 'EAN 13 Flag Digit 2', 
        190: 'EAN 13 Flag Digit 3', 
        191: 'Add EAN 2/3 Label Definition', 
        192: 'Clear all EAN 2/3 Label Definitions', 
        195: 'Codabar', 
        196: 'Code 128', 
        199: 'Code 39', 
        200: 'Code 93', 
        201: 'Full ASCII Conversion', 
        202: 'Interleaved 2 of 5', 
        203: 'Italian Pharmacy Code', 
        204: 'MSI/Plessey', 
        205: 'Standard 2 of 5 IATA', 
        206: 'Standard 2 of 5', 
        211: 'Transmit Start/Stop', 
        212: 'Tri-Optic', 
        213: 'UCC/EAN-128', 
        214: 'Check Digit', 
        215: 'Check Digit Disable', 
        216: 'Check Digit Enable Interleaved 2 of 5 OPCC', 
        217: 'Check Digit Enable Interleaved 2 of 5 USS', 
        218: 'Check Digit Enable Standard 2 of 5 OPCC', 
        219: 'Check Digit Enable Standard 2 of 5 USS', 
        220: 'Check Digit Enable One MSI Plessey', 
        221: 'Check Digit Enable Two MSI Plessey', 
        222: 'Check Digit Codabar Enable', 
        223: 'Check Digit Code 39 Enable', 
        240: 'Transmit Check Digit', 
        241: 'Disable Check Digit Transmit', 
        242: 'Enable Check Digit Transmit', 
        251: 'Symbology Identifier 1', 
        252: 'Symbology Identifier 2', 
        253: 'Symbology Identifier 3', 
        254: 'Decoded Data', 
        255: 'Decode Data Continued', 
        256: 'Bar Space Data', 
        257: 'Scanner Data Accuracy', 
        258: 'Raw Data Polarity', 
        259: 'Polarity Inverted Bar Code', 
        260: 'Polarity Normal Bar Code', 
        262: 'Minimum Length to Decode', 
        263: 'Maximum Length to Decode', 
        264: 'First Discrete Length to Decode', 
        265: 'Second Discrete Length to Decode', 
        266: 'Data Length Method', 
        267: 'DL Method Read any', 
        268: 'DL Method Check in Range', 
        269: 'DL Method Check for Discrete', 
        272: 'Aztec Code', 
        273: 'BC412', 
        274: 'Channel Code', 
        275: 'Code 16', 
        276: 'Code 32', 
        277: 'Code 49', 
        278: 'Code One', 
        279: 'Colorcode', 
        280: 'Data Matrix', 
        281: 'MaxiCode', 
        282: 'MicroPDF', 
        283: 'PDF-417', 
        284: 'PosiCode', 
        285: 'QR Code', 
        286: 'SuperCode', 
        287: 'UltraCode', 
        288: 'USD-5', 
        289: 'VeriCode'}), 
 141: (
       'Scale',
       {1: 'Weighing Device', 
        32: 'Scale Device', 
        33: 'Scale Class I Metric', 
        34: 'Scale Class I Metric', 
        35: 'Scale Class II Metric', 
        36: 'Scale Class III Metric', 
        37: 'Scale Class IIIL Metric', 
        38: 'Scale Class IV Metric', 
        39: 'Scale Class III English', 
        40: 'Scale Class IIIL English', 
        41: 'Scale Class IV English', 
        42: 'Scale Class Generic', 
        48: 'Scale Attribute Report', 
        49: 'Scale Control Report', 
        50: 'Scale Data Report', 
        51: 'Scale Status Report', 
        52: 'Scale Weight Limit Report', 
        53: 'Scale Statistics Report', 
        64: 'Data Weight', 
        65: 'Data Scaling', 
        80: 'Weight Unit', 
        81: 'Weight Unit Milligram', 
        82: 'Weight Unit Gram', 
        83: 'Weight Unit Kilogram', 
        84: 'Weight Unit Carats', 
        85: 'Weight Unit Taels', 
        86: 'Weight Unit Grains', 
        87: 'Weight Unit Pennyweights', 
        88: 'Weight Unit Metric Ton', 
        89: 'Weight Unit Avoir Ton', 
        90: 'Weight Unit Troy Ounce', 
        91: 'Weight Unit Ounce', 
        92: 'Weight Unit Pound', 
        96: 'Calibration Count', 
        97: 'Re-Zero Count', 
        112: 'Scale Status', 
        113: 'Scale Status Fault', 
        114: 'Scale Status Stable at Center of Zero', 
        115: 'Scale Status In Motion', 
        116: 'Scale Status Weight Stable', 
        117: 'Scale Status Under Zero', 
        118: 'Scale Status Over Weight Limit', 
        119: 'Scale Status Requires Calibration', 
        120: 'Scale Status Requires Rezeroing', 
        128: 'Zero Scale', 
        129: 'Enforced Zero Return'}), 
 142: (
       'MagneticStripeReading',
       {1: 'MSR Device Read-Only', 
        17: 'Track 1 Length', 
        18: 'Track 2 Length', 
        19: 'Track 3 Length', 
        20: 'Track JIS Length', 
        32: 'Track Data', 
        33: 'Track 1 Data', 
        34: 'Track 2 Data', 
        35: 'Track 3 Data', 
        36: 'Track JIS Data'}), 
 144: ('Camera Control', None), 
 145: (
       'Arcade',
       {1: 'General Purpose IO Card', 
        2: 'Coin Door', 
        3: 'Watchdog Timer', 
        48: 'General Purpose Analog Input State', 
        49: 'General Purpose Digital Input State', 
        50: 'General Purpose Optical Input State', 
        51: 'General Purpose Digital Output State', 
        52: 'Number of Coin Doors', 
        53: 'Coin Drawer Drop Count', 
        54: 'Coin Drawer Start', 
        55: 'Coin Drawer Service', 
        56: 'Coin Drawer Tilt', 
        57: 'Coin Door Test', 
        64: 'Coin Door Lockout', 
        65: 'Watchdog Timeout', 
        66: 'Watchdog Action', 
        67: 'Watchdog Reboot', 
        68: 'Watchdog Restart', 
        69: 'Alarm Input', 
        70: 'Coin Door Counter', 
        71: 'I/O Direction Mapping', 
        72: 'Set I/O Direction', 
        73: 'Extended Optical Input State', 
        74: 'Pin Pad Input State', 
        75: 'Pin Pad Status', 
        76: 'Pin Pad Output', 
        77: 'Pin Pad Command'})}
VENDOR_SPECIFIC = {(1389, 2): {65280: (
                     'EIZOMonitor',
                     {184: 'EIZO Monitor Enable', 
                      15: 'EIZO Monitor Buttons', 
                      21: 'EIZO Monitor Preset'})}, 
 (1133, 49697): {65280: (
                         'LogitechG15',
                         {1: 'G15 Key Press', 
                          2: 'G15 Gaming Mode'})}, 
 (1133, 49698): {65280: (
                         'LogitechG15_2',
                         {2: 'G15 Special Keys 1', 
                          3: 'G15 Special Keys 2', 
                          4: 'G15 Backlight Controls', 
                          6: 'G15 LCD Pixel Block'})}}