# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.13-x86_64/egg/reviewboard/webapi/errors.py
# Compiled at: 2020-02-11 04:03:57
from __future__ import unicode_literals
from djblets.webapi.errors import WebAPIError
UNSPECIFIED_DIFF_REVISION = WebAPIError(200, b'Diff revision not specified.', http_status=400)
INVALID_DIFF_REVISION = WebAPIError(201, b'Invalid diff revision.', http_status=404)
INVALID_ACTION = WebAPIError(202, b'Invalid action specified.', http_status=400)
INVALID_CHANGE_NUMBER = WebAPIError(203, b'The commit ID specified could not be found.', http_status=404)
CHANGE_NUMBER_IN_USE = WebAPIError(204, b'The commit ID specified has already been used.', http_status=409)
MISSING_REPOSITORY = WebAPIError(205, b'There was no repository found at the specified path.', http_status=400)
INVALID_REPOSITORY = WebAPIError(206, b'The repository path specified is not in the list of known repositories.', http_status=400)
REPO_FILE_NOT_FOUND = WebAPIError(207, b'The file was not found in the repository.', http_status=400)
INVALID_USER = WebAPIError(208, b'User does not exist.', http_status=400)
REPO_NOT_IMPLEMENTED = WebAPIError(209, b'The specified repository is not able to perform this action.', http_status=501)
REPO_INFO_ERROR = WebAPIError(210, b'There was an error fetching extended information for this repository.', http_status=500)
NOTHING_TO_PUBLISH = WebAPIError(211, b'You attempted to publish a review request without any modifications.', http_status=400)
EMPTY_CHANGESET = WebAPIError(212, b'The commit ID specified represents an empty changeset.', http_status=400)
SERVER_CONFIG_ERROR = WebAPIError(213, b'There was an error storing configuration on the server.', http_status=500)
BAD_HOST_KEY = WebAPIError(214, b'The SSH key on the host does ot match the stored key.', http_status=403)
UNVERIFIED_HOST_KEY = WebAPIError(215, b'The SSH key on the host is unverified.', http_status=403)
UNVERIFIED_HOST_CERT = WebAPIError(216, b'The HTTPS certificate on the host is unverified.', http_status=403)
MISSING_USER_KEY = WebAPIError(217, b'A public SSH key was requested, but no SSH key was available to send.', http_status=403)
REPO_AUTHENTICATION_ERROR = WebAPIError(218, b'Unable to authenticate with the repository using the provided credentials.', http_status=403)
DIFF_EMPTY = WebAPIError(219, b'The specified diff file is empty.', http_status=400)
DIFF_TOO_BIG = WebAPIError(220, b'The specified diff file is too large.', http_status=400)
FILE_RETRIEVAL_ERROR = WebAPIError(221, b'There was an error fetching a source file.', http_status=500)
HOSTINGSVC_AUTH_ERROR = WebAPIError(222, b'There was an error authorizing with a service.', http_status=403)
GROUP_ALREADY_EXISTS = WebAPIError(223, b'A group with this name already exists.', http_status=409)
DIFF_PARSE_ERROR = WebAPIError(224, b'The specified diff file could not be parsed.', http_status=400)
PUBLISH_ERROR = WebAPIError(225, b'An error occurred during publishing.', http_status=500)
USER_QUERY_ERROR = WebAPIError(226, b'An error occurred querying the user list.', http_status=500)
COMMIT_ID_ALREADY_EXISTS = WebAPIError(227, b'Review request with this commit ID already exists in the repository.', http_status=409)
TOKEN_GENERATION_FAILED = WebAPIError(228, b'There was an error generating the API token. Please try again.', http_status=500)
REPOSITORY_ALREADY_EXISTS = WebAPIError(229, b'A repository with this name already exists.', http_status=409)
CLOSE_ERROR = WebAPIError(230, b'An error occurred while closing the review request.', http_status=500)
REOPEN_ERROR = WebAPIError(231, b'An error occurred while reopening the review request.', http_status=500)
REVOKE_SHIP_IT_ERROR = WebAPIError(232, b'An error occurred while revoking the Ship It for a review.', http_status=500)