# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.macosx-10.13-x86_64/egg/reviewboard/webapi/tests/mimetypes.py
# Compiled at: 2020-02-11 04:03:57
from __future__ import unicode_literals

def _build_mimetype(resource_name, fmt=b'json'):
    return b'application/vnd.reviewboard.org.%s+%s' % (resource_name, fmt)


api_token_list_mimetype = _build_mimetype(b'api-tokens')
api_token_item_mimetype = _build_mimetype(b'api-token')
archived_item_mimetype = _build_mimetype(b'archived-review-request')
change_list_mimetype = _build_mimetype(b'review-request-changes')
change_item_mimetype = _build_mimetype(b'review-request-change')
diff_context_mimetype = _build_mimetype(b'diff-context')
default_reviewer_list_mimetype = _build_mimetype(b'default-reviewers')
default_reviewer_item_mimetype = _build_mimetype(b'default-reviewer')
diff_list_mimetype = _build_mimetype(b'diffs')
diff_item_mimetype = _build_mimetype(b'diff')
diff_file_attachment_list_mimetype = _build_mimetype(b'diff-file-attachments')
diff_file_attachment_item_mimetype = _build_mimetype(b'diff-file-attachment')
draft_file_attachment_list_mimetype = _build_mimetype(b'draft-file-attachments')
draft_file_attachment_item_mimetype = _build_mimetype(b'draft-file-attachment')
error_mimetype = _build_mimetype(b'error')
file_attachment_list_mimetype = _build_mimetype(b'file-attachments')
file_attachment_item_mimetype = _build_mimetype(b'file-attachment')
file_attachment_comment_list_mimetype = _build_mimetype(b'file-attachment-comments')
file_attachment_comment_item_mimetype = _build_mimetype(b'file-attachment-comment')
filediff_list_mimetype = _build_mimetype(b'files')
filediff_item_mimetype = _build_mimetype(b'file')
filediff_comment_list_mimetype = _build_mimetype(b'file-diff-comments')
filediff_comment_item_mimetype = _build_mimetype(b'file-diff-comment')
general_comment_list_mimetype = _build_mimetype(b'general-comments')
general_comment_item_mimetype = _build_mimetype(b'general-comment')
hosting_service_list_mimetype = _build_mimetype(b'hosting-services')
hosting_service_item_mimetype = _build_mimetype(b'hosting-service')
hosting_service_account_list_mimetype = _build_mimetype(b'hosting-service-accounts')
hosting_service_account_item_mimetype = _build_mimetype(b'hosting-service-account')
oauth_app_list_mimetype = _build_mimetype(b'oauth-apps')
oauth_app_item_mimetype = _build_mimetype(b'oauth-app')
oauth_token_list_mimetype = _build_mimetype(b'oauth-tokens')
oauth_token_item_mimetype = _build_mimetype(b'oauth-token')
original_file_mimetype = b'text/plain'
patched_file_mimetype = b'text/plain'
remote_repository_list_mimetype = _build_mimetype(b'remote-repositories')
remote_repository_item_mimetype = _build_mimetype(b'remote-repository')
repository_list_mimetype = _build_mimetype(b'repositories')
repository_item_mimetype = _build_mimetype(b'repository')
repository_branches_item_mimetype = _build_mimetype(b'repository-branches')
repository_commits_item_mimetype = _build_mimetype(b'repository-commits')
repository_info_item_mimetype = _build_mimetype(b'repository-info')
review_list_mimetype = _build_mimetype(b'reviews')
review_item_mimetype = _build_mimetype(b'review')
review_diff_comment_list_mimetype = _build_mimetype(b'review-diff-comments')
review_diff_comment_item_mimetype = _build_mimetype(b'review-diff-comment')
review_group_list_mimetype = _build_mimetype(b'review-groups')
review_group_item_mimetype = _build_mimetype(b'review-group')
review_group_user_list_mimetype = _build_mimetype(b'review-group-users')
review_group_user_item_mimetype = _build_mimetype(b'review-group-user')
review_reply_list_mimetype = _build_mimetype(b'review-replies')
review_reply_item_mimetype = _build_mimetype(b'review-reply')
review_request_last_update_mimetype = _build_mimetype(b'last-update')
review_reply_diff_comment_list_mimetype = _build_mimetype(b'review-reply-diff-comments')
review_reply_diff_comment_item_mimetype = _build_mimetype(b'review-reply-diff-comment')
review_reply_file_attachment_comment_list_mimetype = _build_mimetype(b'review-reply-file-attachment-comments')
review_reply_file_attachment_comment_item_mimetype = _build_mimetype(b'review-reply-file-attachment-comment')
review_reply_general_comment_list_mimetype = _build_mimetype(b'review-reply-general-comments')
review_reply_general_comment_item_mimetype = _build_mimetype(b'review-reply-general-comment')
review_reply_screenshot_comment_list_mimetype = _build_mimetype(b'review-reply-screenshot-comments')
review_reply_screenshot_comment_item_mimetype = _build_mimetype(b'review-reply-screenshot-comment')
review_request_list_mimetype = _build_mimetype(b'review-requests')
review_request_item_mimetype = _build_mimetype(b'review-request')
review_request_draft_item_mimetype = _build_mimetype(b'review-request-draft')
root_item_mimetype = _build_mimetype(b'root')
screenshot_list_mimetype = _build_mimetype(b'screenshots')
screenshot_item_mimetype = _build_mimetype(b'screenshot')
screenshot_comment_list_mimetype = _build_mimetype(b'screenshot-comments')
screenshot_comment_item_mimetype = _build_mimetype(b'screenshot-comment')
screenshot_draft_item_mimetype = _build_mimetype(b'draft-screenshot')
screenshot_draft_list_mimetype = _build_mimetype(b'draft-screenshots')
search_mimetype = _build_mimetype(b'search')
server_info_mimetype = _build_mimetype(b'server-info')
session_mimetype = _build_mimetype(b'session')
status_update_list_mimetype = _build_mimetype(b'status-updates')
status_update_item_mimetype = _build_mimetype(b'status-update')
user_list_mimetype = _build_mimetype(b'users')
user_item_mimetype = _build_mimetype(b'user')
user_file_attachment_list_mimetype = _build_mimetype(b'user-file-attachments')
user_file_attachment_item_mimetype = _build_mimetype(b'user-file-attachment')
validate_diff_mimetype = _build_mimetype(b'diff-validation')
watched_review_group_list_mimetype = _build_mimetype(b'watched-review-groups')
watched_review_group_item_mimetype = _build_mimetype(b'watched-review-group')
watched_review_request_item_mimetype = _build_mimetype(b'watched-review-request')
watched_review_request_list_mimetype = _build_mimetype(b'watched-review-requests')
webhook_list_mimetype = _build_mimetype(b'webhooks')
webhook_item_mimetype = _build_mimetype(b'webhook')