# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: troy/constants.py
# Compiled at: 2014-02-24 20:40:00
__author__ = 'TROY Development Team'
__copyright__ = 'Copyright 2013, RADICAL'
__license__ = 'MIT'
DEFAULT = 'default'
AUTO = 'auto'
AUTOMATIC = AUTO
DESCRIBED = 'Described'
PLANNED = 'Planned'
TRANSLATED = 'Translated'
BOUND = 'Bound'
DISPATCHED = 'Dispatched'
DONE = 'Done'
FAILED = 'Failed'
CANCELED = 'Canceled'
UNKNOWN = 'Unknown'
DESCRIBED = 'Described'
TRANSLATED = 'Translated'
BOUND = 'Bound'
DISPATCHED = 'Dispatched'
DONE = 'Done'
FAILED = 'Failed'
CANCELED = 'Canceled'
UNKNOWN = 'Unknown'
DESCRIBED = 'Described'
BOUND = 'Bound'
DISPATCHED = 'Dispatched'
PENDING = 'Pending'
RUNNING = 'Running'
DONE = 'Done'
FAILED = 'Failed'
CANCELED = 'Canceled'
UNKNOWN = 'Unknown'
DESCRIBED = 'Described'
TRANSLATED = 'Translated'
SCHEDULED = 'Scheduled'
PROVISIONED = 'Provisioned'
COMPLETED = 'Completed'
CANCELED = 'Canceled'
FAILED = 'Failed'
UNKNOWN = 'Unknown'
DESCRIBED = 'Described'
BOUND = 'Bound'
PROVISIONED = 'Provisioned'
COMPLETED = 'Completed'
CANCELED = 'Canceled'
FAILED = 'Failed'
UNKNOWN = 'Unknown'
EARLY = 'Early'
LATE = 'Late'
UPPER_LIMIT = 'Upper'
LOWER_LIMIT = 'Lower'
UNLIMITED = 'Unlimited'