# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Users/erhu/project/gitrepo/hep-sdk/venv/lib/python3.6/site-packages/test/test_create_pay_cache_response.py
# Compiled at: 2019-06-20 12:20:18
# Size of source mod 2**32: 929 bytes
"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import absolute_import
import unittest, hep_rest_api
from models.create_pay_cache_response import CreatePayCacheResponse
from hep_rest_api.rest import ApiException

class TestCreatePayCacheResponse(unittest.TestCase):
    __doc__ = 'CreatePayCacheResponse unit test stubs'

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreatePayCacheResponse(self):
        """Test CreatePayCacheResponse"""
        pass


if __name__ == '__main__':
    unittest.main()