# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /Users/erhu/project/gitrepo/hep-sdk/venv/lib/python3.6/site-packages/test/test_proof_reward.py
# Compiled at: 2019-07-08 08:56:14
# Size of source mod 2**32: 837 bytes
"""
    HEP REST API

    The REST API for HEP protocol  # noqa: E501

    OpenAPI spec version: v1
    Contact: xiawu@zeuux.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import absolute_import
import unittest, hep_rest_api
from models.proof_reward import ProofReward
from hep_rest_api.rest import ApiException

class TestProofReward(unittest.TestCase):
    __doc__ = 'ProofReward unit test stubs'

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProofReward(self):
        """Test ProofReward"""
        pass


if __name__ == '__main__':
    unittest.main()