# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/stein/Projekte/eclipse/django-dynamic-link/dynamicLink/version.py
# Compiled at: 2016-07-22 06:27:55
VERSION = (0, 5, 7, 1)
RELEASE_DJANGO = ((1, 2), (1, 3), (1, 4))
PYTHON_MIN = (2, 4)
REQUIRES = '\ndjango-dynamic-link 0.5.5 => Django 1.2, 1.3 :: Python >= 2.4 :: Example project: Django 1.3\ndjango-dynamic-link 0.6.x => Django 1.2, 1.3, 1.4(Python 2.5) :: Python >= 2.4 :: Example project: Django 1.4, Python 2.5\n\n(for an actual release visit http://pypi.python.org/pypi/django-dynamic-link/)\n'
APPLICATION_NAME = 'Dynamic Link'
VERSION_str = str(VERSION[:3]).strip('()').replace(',', '.').replace(' ', '')
VERSION_INFO = '\nVersion: %s\nModification date: 03.08.2011\n\nHints:\n- 0.5.7.1   meta-data update\n- 0.5.6.2   settings.py in example project modified. Now it should work correct with Django 1.4\n- 0.5.6.1   Time zone bug changes\n- 0.5.6     Example Project runs with Django 1.4\n- 0.5.5     dynamicLink.CKISNT() function added.\n- 0.5.4.1   Changes in setup.py - READM will now also be installed. Now if a package\n            is installed than help(dynamicLink) outputs the README.\n- 0.5.4     Bugfix: Installation failed on Windows in spite of "/" on the end\n            of recursive-include in MANIFEST.\n            Now changed from "recursive-include folder/ *" to "recursive-include folder *"\n- 0.5.3     New stable release with updated readme.\n- 0.5.2.2   structure of repository changed - src folder removed so readme is\n            on the top level\n- 0.5.2.1   In templates sentences changed.\n- 0.5.2     stable - general Django dependences in setup removed\n- 0.5.1     new stable\n- 0.5.0.2   some text in templates changed\n- 0.5.0.1   correct readme and example settings.py\n- 0.5.0     some changes - stable release\n- 0.4.9.4   install_requires in setup.py modified\n- 0.4.9.3   old data removed\n- 0.4.9.2   dl_settings removed\n- 0.4.9.1   Readme updated\n- 0.4.9     Tested with Django 1.2 u. 1.3\n- 0.4.8.4   Some small changes\n- 0.4.8.3   Some small changes\n- 0.4.8     Runs now under Django 1.3\n- 0.4.7   - Presettings can now be overwrite in the presettings.py in the project\n            folder, or directly in the global settings.py, or in a file\n            called dl_settings.py in the same directory as manage.py.\n            - django-dynamic-link now runs with python below version 2.6\n- 0.4.6 -   changes in setup.py to avoid to install the example project.\n- 0.4.5 -   Small adjustments at the example project.\n- 0.4.4 -   1. Because of incomplete setup.py the last distributed package\n            does\'t contained temples and language files.\n            2. Readme updated.\n            3. Example project added.\n- 0.4.3 -   ImportError in admin.py solved.\n- 0.4.2 -   setup.py created. Now listed in pypi.\n- 0.4.1 -   Remove small bug with links created with the action menu.\n\nTODO:\n    - write more unittests\n' % (VERSION_str,)