# uncompyle6 version 3.7.4
# Python bytecode 2.6 (62161)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build\bdist.win32\egg\sy85\data\patches.py
# Compiled at: 2010-04-11 18:31:39
from itertools import chain
PERF_OFFSET = 330
MULTI_OFFSET = 65536
PERF_DATA_LEN = 168
PERF_NAME_LEN = 8
PERF_NAME_OFFSET = 49
LAYER_DATA_OFFSET = 60
LAYER_DATA_LEN = 27
VCE_DATA_LEN = 162
VCE_NAME_LEN = 8
VCE_NAME_OFFSET = 49
DVCE_DATA_LEN = 552
NUM_PERF = 64
NUM_VCE = 64
NUM_MULTI = 10
NUM_WAVE = 64
PATCH_BANKS = {'perf': [
          ('I1', 'Internal I'),
          ('I2', 'Internal II')], 
   'voice': [
           ('I1', 'Internal I'),
           ('I2', 'Internal II'),
           ('I3', 'Internal III'),
           ('I4', 'Internal IV')]}
WAVEFORM_BANKS = [
 ('P1', 'Preset 1'),
 ('P2', 'Preset 2'),
 ('C', 'Card'),
 ('I', 'Internal')]
TG500_PRESET_PERF_NAMES = [
 [
  'CO Dream ',
  'KY Piano ',
  'SP Aztec ',
  'SC Wyrz ',
  'CH Choir ',
  'BA Pick1 ',
  'ST Rosin ',
  'BR Stab ',
  'CO Soire ',
  'OR Bee ',
  'SP Lush ',
  'SC Rude ',
  'CH Breth ',
  'BA Swap ',
  'ST Octvs ',
  'BR Pro5 ',
  'CO Orch ',
  'KY Digi1 ',
  'SP Faery ',
  'SC Talk ',
  'CH OohAh ',
  'BA Pick2 ',
  'ST Pitz ',
  'BR Sfz ',
  'CO Sable ',
  'KY Roady ',
  'SP Slide ',
  'SC Klav ',
  'CH Vespa ',
  'BA -Fret ',
  'ST Rings ',
  'BR Forte ',
  'CO Jazzr ',
  'OR Gimme ',
  'SP Lite ',
  'SC Buzz ',
  'CH Munch ',
  'BA Rezzo ',
  'ST Dark ',
  'BR Saw ',
  'CO E.S.P ',
  'KY Elek ',
  'SP Stars ',
  'SC Snaps ',
  'CH Abyss ',
  'BA Mini ',
  'ST 2002 ',
  'BR Obie ',
  'CO Pnooh ',
  'OR Nave ',
  'SP Ace ',
  'SC Point ',
  'CH Comet ',
  'BA Guppy ',
  'ST Big ',
  'BR Fatti ',
  'CO Inca ',
  'KY Funky ',
  'SP Vekta ',
  'SC Pizza ',
  'CH Oral ',
  'BA Doom ',
  'ST Tron ',
  'BR Swell '],
 [
  'CO Ncert ',
  'KY Loud ',
  'SP Carol ',
  'SL Mitey ',
  'ME Orion ',
  'GT Amped ',
  'SE Rolls ',
  'WN Tenor ',
  'CO DXStr ',
  'OR Sine ',
  'SP Venus ',
  'SL Chick ',
  'ME Glitz ',
  'GT Strat ',
  'SE C-tar ',
  'WN Sacks ',
  'CO Stass ',
  'KY Digi2 ',
  'SP Whino ',
  'SL L7 ',
  'ME Honto ',
  'GT Phunk ',
  'SE Xeno ',
  'WN Alto ',
  'CO Megin ',
  'KY Jerry ',
  'SP Hinx ',
  'SL Eazy ',
  'ME Mars ',
  'GT Rock ',
  'SE Storm ',
  'WN Panic ',
  'CO Gospl ',
  'OR Cheap ',
  'SP Pluto ',
  'SC Clank ',
  'ME Ecko ',
  'GT Harm ',
  'SE Zoom ',
  'BR Reeds ',
  'CO Ethos ',
  'KY PnoMW ',
  'SP Synth ',
  'FI Santo ',
  'ME Alien ',
  'GT El12 ',
  'SE Delay ',
  'BR Lips ',
  'CO Kings ',
  'KY Calio ',
  'SP Anlog ',
  'SC Wind ',
  'ME Spark ',
  'GT 12Str ',
  'SE Flies ',
  'BR Miles ',
  'CO Happi ',
  'KY Digi3 ',
  'SP Arpeg ',
  'TP Bells ',
  'ME Hit ',
  'GT Acstc ',
  'SE Hero ',
  'BR Fanfr ']]
TG500_INT_PERF_NAMES = [
 [
  'CO Aster ',
  'AP Piano ',
  'SP Mtrix ',
  'SC Skank ',
  'ME Sprk2 ',
  'BA Drive ',
  'BR Fnfr2 ',
  'SE Devil ',
  'ST Moin ',
  'FI Dulcm ',
  'CO Bells ',
  'KY Knock ',
  'SP Fanta ',
  'SC Elec1 ',
  'ME Gokrk ',
  'BA Susud ',
  'BR Forth ',
  'SE Swmp ',
  'ST Legat ',
  'GT Pedal ',
  'CO Gloom ',
  'OR Cool ',
  'SP Flash ',
  'SC Gob ',
  'ME Max ',
  'BA Sldge ',
  'BR Synth ',
  'SE Wall ',
  'ST Accat ',
  'GT Steel ',
  'CO India ',
  'OR Rock ',
  'SP Atrio ',
  'SC Woody ',
  'ME Chorl ',
  'GT Round ',
  'BR Sfz2 ',
  'SE Rado ',
  'ST LgSm ',
  'SL Meteo ',
  'CO Clock ',
  'OR Mite ',
  'SP Wind ',
  'SC Arred ',
  'ME Chom ',
  'CO FMpad ',
  'BR Tpts ',
  'SE Indst ',
  'CO Nuage ',
  'SP Lodge ',
  'SC Oz ',
  'CO Japan ',
  'KY Hrpzi ',
  'SL Sqsaw ',
  'BR CShrn ',
  'CO Laura ',
  'CO Orch2 ',
  'ME Hits ',
  'ST Solo ',
  'CO Soul ',
  'GT Wires ',
  'OR Pan ',
  'BR 3 Osc ',
  'CO Fire']]
PRESET_VOICE_NAMES = [
 [
  'AP Grand',
  'AP Chors',
  'AP Dance',
  'AP Rock',
  'AP Tack',
  'AP Touch',
  'BA Wood',
  'BA Pitz',
  'BA Fingr',
  'BA Frtls',
  'BA Pick1',
  'BA Pick2',
  'BA Slap',
  'BA Thump',
  'BA Syn 1',
  'BA Syn 2',
  'BA Syn 3',
  'BA Syn 4',
  'BA Syn 5',
  'BA Syn 6',
  'BA Syn 7',
  'BA Syn 8',
  'BA Syn 9',
  'BA Syn 10',
  'BA Syn 11',
  'BA Syn 12',
  'BR Trump',
  'BR Mute',
  'BR Horn',
  'BR Tromb',
  'BR Tuba',
  'BR TpEns',
  'BR Tpts',
  'BR TpSfz',
  'BR Stab',
  'BR EnsSF',
  'BR East',
  'BR Syn 1',
  'BR Syn 2',
  'BR Syn 3',
  'BR Syn 4',
  'BR Saw',
  'BR SawSF',
  'BR Swell',
  'BR Tooth',
  'BR Rezz',
  'BR Toto',
  'BR Wow',
  'CH Aah',
  'CH Ooh',
  'CH Pure',
  'CH Breth',
  'CH Ghost',
  'CH Quire',
  'CH Vespa',
  'CH Vocod',
  'Fl Blue1',
  'Fl Blue2',
  'Fl Dudel',
  'Fl DulcD',
  'Fl DulcM',
  'Fl Harp',
  'Fl Kalim',
  'DR Kit'],
 [
  'Fl Lip',
  'Fl Sitar',
  'GT Nylon',
  'GT Dark',
  'GT Steel',
  'GT 12Str',
  'GT Jazz',
  'GT Strt1',
  'GT Strt2',
  'GT Strt3',
  'GT Mute',
  'GT Harm',
  'GT Comp1',
  'GT Comp2',
  'GT Dist',
  'GT Warm',
  'GT Wah',
  'GT Feed',
  'KY EP 1',
  'KY EP 2',
  'KY EP 3',
  'KY EP 4',
  'KY EP 5',
  'KY EP 6',
  'KY EP 7',
  'KY EP 8',
  'KY EP 9',
  'KY EP 10',
  'KY EP 11',
  'KY EP 12',
  'KY Clav1',
  'KY Clav2',
  'KY Hrpsi',
  'KY Acrdn',
  'KY Cali1',
  'KY Cali2',
  'ME Bottl',
  'ME Gizmo',
  'ME Grind',
  'ME Hand',
  'ME Kali',
  'ME Mello',
  'ME Orch1',
  'ME Orch2',
  'ME OrchR',
  'ME Soro',
  'ME Templ',
  'ME Tink',
  'ME Tomi',
  'ME Voics',
  'OR Jaz B',
  'OR Smoke',
  'OR Airy',
  'OR Dist',
  'OR Cheap',
  'OR Pipes',
  'OR Click',
  'OR Perc',
  'SC Aha!',
  'SC Bari',
  'SC Bell',
  'SC Clav',
  'SC Digi1',
  'DR Zones'],
 [
  'SC Digi2',
  'SC Digi3',
  'SC Ecko',
  'SC Fingr',
  'SC Housy',
  'SC Jrney',
  'SC Metal',
  'SC Mute',
  'SC Pan',
  'SC Perc',
  'SC Rezz',
  'SC Spike',
  'SC Sqiff',
  'SC Synnr',
  'SC Topia',
  'SC Vocal',
  'SC Vox',
  'SC Wires',
  'SC Wondr',
  'SE Alert',
  'SE Templ',
  'SE BDup',
  'SE Chou',
  'SE Demon',
  'SE Dropr',
  'SE Gobln',
  'SE Heli',
  'SE Hell',
  'SE Hyena',
  'SE Indus',
  'SE It',
  'SE Noize',
  'SE Pops',
  'SE Rain',
  'SE Rezo',
  'SE S&H',
  'SE Star',
  'SE Up&Up',
  'SE Wind',
  'SL Cutty',
  'SL Digi',
  'SL Dist',
  'SL Hamma',
  'SL Lead',
  'SL Lyle',
  'SL Pulse',
  'SL Saw 1',
  'SL Saw 2',
  'SL Squar',
  'SL Sync',
  'SL Whisl',
  'SP Abyss',
  'SP Big',
  'SP Exita',
  'SP Freqs',
  'SP Glass',
  'SP Goner',
  'SP Hyper',
  'SP Makro',
  'SP Mello',
  'SP Movie',
  'SP Nasty',
  'SP Nehan',
  'DR GMIDI'],
 [
  'SP Paddy',
  'SP Phaze',
  'SP Poly',
  'SP SawSt',
  'SP Slow',
  'SP Smoky',
  'SP Space',
  'SP Sqare',
  'SP Sweep',
  'SP Sweet',
  'SP Vizon',
  'SP Wine',
  'ST Violn',
  'ST JeanL',
  'ST Sectn',
  'ST Power',
  'ST Deep',
  'ST Dark',
  'ST Brite',
  'ST Arco',
  'ST Sfz',
  'ST Pizz',
  'ST Tron',
  'ST Anlog',
  'ST Sizzl',
  'ST Synth',
  'ST Thin',
  'ST Combo',
  'TP Glock',
  'TP Xylo',
  'TP Vibes',
  'TP Tubal',
  'TP Hands',
  'TP Siam',
  'TP Steel',
  'TP Loggy',
  'TP Bambu',
  'TP Mrmba',
  'TP Timp',
  'TP Syn',
  'TP SynDr',
  'TP Tinkl',
  'TP Agone',
  'TP Angle',
  'WN Sopr',
  'WN Alto',
  'WN Tenor',
  'WN Bari',
  'WN SaxSF',
  'WN Picc',
  'WN Flute',
  'WN Pan',
  'WN Clari',
  'WN Oboe',
  'WN Basso',
  'WN Recor',
  'WN Breth',
  'Ml Crash',
  'MI EPNP',
  'Ml Hiss',
  'Ml Ride',
  'MW EGBia',
  'AT EGBia',
  'DR Efect']]
TG500_INTERNAL_VOICE_NAMES = [
 [
  'AP Brite',
  'AP Dark',
  'AP Chrs2',
  'BA Pluck',
  'BA Soul',
  'BA Stick',
  'BA Low',
  'BA Head',
  'BA Tri',
  'BR Punch',
  'BR TpSf1',
  'BR Movin',
  'BR Ruber',
  'BR CS80',
  'BR Strai',
  'BR Lush',
  'BR TpSf2',
  'CH Quiet',
  'CH Kwire',
  'CH Spirt',
  'CHAnalg',
  'CH VoxPc',
  'DR Tom',
  'Fl Banjo',
  'Fl Koto',
  'Fl Sitr2',
  'Fl Tamba',
  'GT Fingr',
  'GT Amod',
  'GT Strat',
  'GT Pedal',
  'GT Dist2',
  'KY Hrpzi',
  'KY EP 13',
  'KY EP 14',
  'KY EP 15',
  'KY EP 16',
  'KY EP 17',
  'KY EP 18',
  'KY Harm',
  'KY SyClv',
  'ME Bnshe',
  'ME Bubbl',
  'ME Hit',
  'ME Marin',
  'ME Mojo',
  'ME Poot',
  'ME Sweep',
  'ME Tabla',
  'ME Treml',
  'ME Angel',
  'ME Whisl',
  'OR Door0',
  'OR Jazz',
  'OR Pipe',
  'OR Rock',
  'OR Smoth',
  'SC Anti',
  'SC Bell2',
  'SC Bhind',
  'SC Blot',
  'SC Chop',
  'SC Klav',
  'DR Revrs'],
 [
  'SC Hool',
  'SC Hand',
  'SC WooDX',
  'SC Wire',
  'SC Pain',
  'SC Pluck',
  'SC Reflx',
  'SC Sprkl',
  'SC Thumb',
  'SC Uzzy',
  'SC Vxcla',
  'SC Walk',
  'SC Wits',
  'SC Wow',
  'SE Alien',
  'SE Clox',
  'SE Crck',
  'SE Crsh',
  'SE Duel',
  'SE Fear',
  'SE Roll',
  'SE Lava',
  'SE Laze',
  'SE Mono',
  'SE Saw',
  'SE Swmp',
  'SE Vaqum',
  'SE Vektr',
  'SE Zip',
  'SL lck',
  'SL 2VCO1',
  'SL Ash',
  'SL Glnt',
  'SL Oth',
  'SL Sqsaw',
  'SL Ut',
  'SP 1980',
  'SP Decay',
  'SP Ear',
  'SP Glas2',
  'SP It',
  'SP Lash',
  'SP Latt',
  'SP Lonly',
  'SP Lyle',
  'SP Melo',
  'SP Nsty2',
  'SP Oscil',
  'SP Ray',
  'SP SloMo',
  'ST Cello',
  'ST Cntra',
  'ST Chamb',
  'ST Arco2',
  'ST High',
  'ST Anlg2',
  'TP Bell',
  'TP Clock',
  'TP GSvib',
  'TP Tabla',
  'TP Boink',
  'WN Flut1',
  'WN Flut2',
  'DR Voice']]
WAVEFORMS = {'Preset 1': [
              (
               'Piano',
               ('Piano', )),
              (
               'Key',
               ('HardEp', 'HardEpLp', 'SoftEp', 'SoftEpLp', 'SynthEp', 'SynthEpLp', 'Clavi 1', 'Clavi 1Lp',
 'Clavi 2', 'Clavi 2Lp', 'Harpsi', 'HarpsiLp', 'Acrdion', 'AcrdionLp', 'Organ 1',
 'Organ 1Lp', 'PrcOrg1', 'PrcOrg1Lp', 'PrcOrg2', 'PrcOrg2Lp', 'RockOrg', 'Pipe Wv',
 'Pipe WvLp')),
              (
               'Brass',
               ('Trumpet', 'TrumpetLp', 'MuteTp', 'MuteTpLp', 'Trombone', 'TromBneLp', 'Horn', 'Tuba',
 'TpEns', 'TpEnsLp', 'BrsEns', 'BrsEnsLp')),
              (
               'Woodwind',
               ('Baritone', 'BaritneLp', 'Tenor', 'TenorLp', 'AltoSax', 'AltoSaxLp', 'Soprano', 'SopranoLp',
 'Clarinet', 'Bassoon', 'Oboe', 'EngHorn', 'Piccolo', 'Recorder', 'Flute', 'Panflute',
 'PnFluteLp')),
              (
               'String',
               ('Strings1', 'Strngs1Lp', 'Strings2', 'Violin', 'Viola', 'Pizz')),
              (
               'Acoustic Guitar',
               ('GtrSteel', 'GtrStelLp', 'GtrNyln', 'GtrNylnLp', '12String', '12StrngLp')),
              (
               'Electric Guitar',
               ('EgSngl1', 'EgSngl1Lp', 'EgSngl2', 'EgSngl2Lp', 'EgMute1', 'EgMute2', 'EgComp', 'EgCompLp',
 'EgHarm1', 'EgHarm1Lp', 'EgHarm2', 'EgHarm2Lp')),
              (
               'Bass',
               ('WoodBass', 'FingBs', 'FingBsLp', 'PickBs1', 'PickBs1Lp', 'PickBs2', 'PickBs2Lp',
 'FretLess', 'FretLs Lp', 'ThumpBs', 'ThumpBsLp', 'SlapBs', 'SlapBsLp')),
              (
               'Folk instruments',
               ('Dulcimer', 'DulcimrD', 'DlcmSplt', 'Kalimba', 'Sitar', 'Harp')),
              (
               'Synthesizer',
               ('SynBrs1', 'SynBrs1Lp', 'SynBrs2', 'SynBrs2Lp', 'SynBrs3', 'SynBrs3Lp', 'SynBrs4',
 'SynBrs4Lp', 'SynBrsWv', 'SynBs1', 'SynBs1Lp', 'SynBs2', 'SynBs2Lp', 'SynBs3', 'SynBs3Lp',
 'SynBs4', 'SynBs4Lp', 'SynBs5', 'SynBs5Lp', 'SynBs6', 'SynBs6Lp', 'SynBs7', 'SynBs7Lp',
 'SynBs8', 'SynBs8Lp', 'SynBs9', 'SynBs9Lp', 'SynBs10', 'SynBs10Lp', 'Pad 1', 'Pad 1Lp',
 'Pad 2', 'Pad 3', 'Pad 4', 'Pad 5', 'SynLead1', 'SynLead2', 'SynStWv', 'DistWv',
 'DistWvLp')),
              (
               'Choir',
               ('ChoirAa', 'ChoirAaLp', 'ChoirOo', 'ChoirOoLp', 'Itopia')),
              (
               'Ideophone',
               ('Glocken', 'HandBell', 'HndBellLp', 'Marimba', 'SteelDrm', 'Tubular', 'TubularLp',
 'Vibes', 'Xylophon')),
              (
               'Drum',
               ('BD1', 'BD2', 'BD3', 'BD4', 'BD5', 'BD6', 'BD7', 'BD8', 'SD1', 'SD2', 'SD3', 'SD4',
 'SD5', 'SD6', 'SD7', 'SD8', 'SD9', 'SD side', 'Tom1', 'Tom2', 'HH Open', 'HH Pedal',
 'HH light', 'HH mid', 'HH heavy', 'Crash', 'Ride', 'RideBell', 'AnlgTom', 'HHopAnlg',
 'HHclAnlg', 'Scratch', 'RezClick', 'VcDrmBD', 'VcDrmSD')),
              (
               'Percussion',
               ('AgogoHi', 'Bongo', 'Cabasa', 'CongaLo', 'CongaMt', 'CongaSlp', 'AnaConga', 'Clap',
 'Clave', 'AnaCwbl', 'Cowbell', 'Maracas', 'Tmbrine', 'Timpani', 'TemplBlk', 'Timbale',
 'Timbale2', 'Triangle', 'Whistle')),
              (
               'Special effect',
               ('SE Bottle', 'E.P. Np', 'Bamboo', 'Temp Ra', 'Typist', 'VoiceAtk', 'ChouCho', 'Vox Bell',
 'Mellow', 'Bell Mix', 'Seq1', 'Seq2', 'OrchHit1', 'OrchHit2', 'Noise')),
              (
               'Oscillator',
               ('AnlgSaw1', 'AnlgSaw2', 'Pulse 10', 'Pulse 25', 'Pulse 50', 'Digital1', 'Digital2',
 'Digital3', 'Digital4', 'Digital5', 'Digital6', 'Digital7', 'Digital8', 'Digital9',
 'Digitl10', 'Digitl11', 'Digitl12', 'DigiVox1', 'DigiVox2', 'DigiVox3', 'DigiVox4',
 'DigiVox5', 'DigiWild', 'Tri', 'Sin'))], 
   'Preset 2': [
              (
               'Piano',
               ('Piano2', )),
              (
               'Key',
               ('SynClavi', )),
              (
               'Brass',
               ('Trumpet2', 'TrmPet2LP')),
              (
               'Woodwind',
               ('Flute2', )),
              (
               'String',
               ('Chamber', 'Cello', 'CelloLp', 'CntraBs', 'CntraBsLp')),
              (
               'Acoustic Guitar',
               ('GtrFngr', 'GtrFngrLp')),
              (
               'Electric Guitar',
               ('EgHumBk', 'EgHumBkLp')),
              (
               'Ideophone',
               ('Celesta', )),
              (
               'Drum',
               ('Drum BD9', 'Brush', 'SD10', 'Tom3', 'Tom4', 'Tom5', 'VcDrmHHc', 'VcDrmHHo', 'Chaina')),
              (
               'Percussion',
               ('Perc. Guiro', 'Guiro2', 'Tabla', 'Tabla2', 'Cuica H', 'Cuica L', 'VibraSlp')),
              (
               'Special effects',
               ('OrchHit3', 'BellRing', 'Seq3')),
              (
               'Oscillator',
               ('LongSaw', 'SawSqu', 'SquSaw', 'BellWv', 'BellWv2', 'EpWv1', 'EpWv2', 'EpWv3', 'EpWv4',
 'EpWv5', 'EpWv6', 'VoxG2Wv', 'VoxE3Wv', 'OrgWv1', 'OrgWv2', 'OrgWv3'))], 
   'Card': [], 'Internal': []}
WAVEFORM_NAMES = [ list(chain(*(x[1] for x in WAVEFORMS[bank]))) for bank in (x[1] for x in WAVEFORM_BANKS) ]
del chain
del bank
CS_PARAMETERS = [
 'No_Assign',
 'CT_MW_Pmod',
 'CT_MW_Amod',
 'CT_MW_Fmod',
 'CT_MW_Coff',
 'CT_MW_EGBs',
 'CT_FC_Pmod',
 'CT_FC_Amod',
 'CT_FC_Fmod',
 'CT_FC_Coff',
 'CT_FC_EGBs',
 'CT_AT_Pmod',
 'CT_AT_Amod',
 'CT_AT_Fmod',
 'CT_AT_Coff',
 'CT_AT_EGBs',
 'CT_AT_PtBs',
 'CT_PBRange',
 'CT_VLLoLim',
 'TotalLevel',
 'EF_SendLvl',
 'OS_FrqFine',
 'OS_Random',
 'PEG_Rate1',
 'PEG_Rate2',
 'PEG_Rate3',
 'PEG_RlsRt',
 'PEG_Level0',
 'PEG_Level1',
 'PEG_Level2',
 'PEG_Level3',
 'PEG_RlsLvl',
 'PEG_Range',
 'PEG_LvlVel',
 'PEG_RtVel',
 'LFO_Speed',
 'LFO_Delay',
 'LFO_Pmod',
 'LFO_Amod',
 'LFO_Fmod',
 'LFO_Wave',
 'LFO_Phase',
 'LFO_SpdVel',
 'LFO_SpdRnd',
 'AEG_Rate1',
 'AEG_Rate2',
 'AEG_Rate3',
 'AEG_Rate4',
 'AEG_RlsRt',
 'AEG_Level2',
 'AEG_Level3',
 'AEG_LvlVel',
 'AEG_RtVel',
 'FLT_Reso',
 'FLT_CofVel',
 'FLT_ARVel',
 'FLT_Band',
 'FLT_CofFrq',
 'FLT_Rate1',
 'FLT_Rate2',
 'FLT_Rate3',
 'FLT_Rate4',
 'FLT_RlsRt1',
 'FLT_RlsRt2',
 'FLT_Level0',
 'FLT_Level1',
 'FLT_Level2',
 'FLT_Level3',
 'FLT_Level4',
 'FLT_RlsLv1',
 'FLT_RlsLv2',
 'OS_NoteSft',
 'FLT_BPLvl1',
 'FLT_BPLvl2',
 'FLT_BPLvl3',
 'FLT_BPLvl4']