# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/vortex/repos/FENIX-MAPS/geobricks/geobricks_rest_engine/geobricks_rest_engine/config/rest_settings.py
# Compiled at: 2015-04-01 10:54:45
settings = {'settings': {'debug': False, 
                'host': 'localhost', 
                'port': 5555, 
                'modules': [
                          {'description': 'geobricks_common', 
                             'path_to_the_config': 'geobricks_common.config.config', 
                             'path_to_the_blueprint': 'geobricks_common.rest.common_rest', 
                             'path_to_the_config': 'geobricks_common.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/common'},
                          {'description': 'GIS Raster', 
                             'path_to_the_config': 'geobricks_gis_raster.config.config'},
                          {'description': 'GIS Vector', 
                             'path_to_the_config': 'geobricks_gis_vector.config.config'},
                          {'description': 'Geocoding', 
                             'path_to_the_blueprint': 'geobricks_geocoding.rest.geocoding_rest', 
                             'path_to_the_config': 'geobricks_geocoding.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/geocoding'},
                          {'description': 'Map Classify', 
                             'path_to_the_blueprint': 'geobricks_mapclassify.rest.mapclassify_rest', 
                             'path_to_the_config': 'geobricks_mapclassify.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/mapclassify'},
                          {'description': 'SpatialQuery', 
                             'path_to_the_blueprint': 'geobricks_spatial_query.rest.spatial_query_rest', 
                             'path_to_the_config': 'geobricks_spatial_query.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/spatialquery'},
                          {'description': 'Metadata Manager', 
                             'path_to_the_blueprint': 'geobricks_metadata_manager.rest.metadata_manager_rest', 
                             'path_to_the_config': 'geobricks_metadata_manager.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/metadata'},
                          {'description': 'Distribution', 
                             'path_to_the_blueprint': 'geobricks_distribution.rest.distribution_rest', 
                             'path_to_the_config': 'geobricks_distribution.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/distribution'},
                          {'description': 'Geostatistics', 
                             'path_to_the_blueprint': 'geobricks_geostatistics.rest.geostatistics_rest', 
                             'path_to_the_config': 'geobricks_geostatistics.config.config', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/geostatistics'},
                          {'description': 'DBMS', 
                             'path_to_the_blueprint': 'geobricks_dbms.rest.dbms_rest', 
                             'path_to_the_config': 'geobricks_dbms.config.dbms_config', 
                             'blueprint_name': 'dbms', 
                             'url_prefix': '/dbms'},
                          {'description': 'geobricks_processing', 
                             'path_to_the_config': 'geobricks_processing.config.config', 
                             'path_to_the_blueprint': 'geobricks_processing.rest.processing_rest', 
                             'blueprint_name': 'app', 
                             'url_prefix': '/processing'},
                          {'description': 'MODIS', 
                             'path_to_the_blueprint': 'geobricks_modis.rest.modis_rest', 
                             'path_to_the_config': 'geobricks_modis.config.modis_config', 
                             'blueprint_name': 'modis', 
                             'url_prefix': '/browse/modis'},
                          {'description': 'DOWNLOAD', 
                             'path_to_the_blueprint': 'geobricks_downloader.rest.downloader_rest', 
                             'path_to_the_config': 'geobricks_downloader.config.downloader_config', 
                             'blueprint_name': 'downloader', 
                             'url_prefix': '/download'}]}}