# uncompyle6 version 3.7.4
# Python bytecode 3.5 (3350)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: build/bdist.linux-x86_64/egg/test/test_process.py
# Compiled at: 2020-02-03 04:38:52
# Size of source mod 2**32: 914 bytes
"""
    Oliver API

    Oliver API in the cloud service  # noqa: E501

    OpenAPI spec version: 3.6.0
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
from __future__ import absolute_import
import unittest, behavioral_signals_swagger_client
from behavioral_signals_swagger_client.models.process import Process
from behavioral_signals_swagger_client.rest import ApiException

class TestProcess(unittest.TestCase):
    __doc__ = 'Process unit test stubs'

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcess(self):
        """Test Process"""
        pass


if __name__ == '__main__':
    unittest.main()