# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /tmp/pip-build-ed191__6/docutils/docutils/parsers/rst/languages/fa.py
# Compiled at: 2020-01-10 16:25:35
# Size of source mod 2**32: 3294 bytes
"""
Persian-language mappings for language-dependent features of
reStructuredText.
"""
__docformat__ = 'reStructuredText'
directives = {'توجه':'attention', 
 'احتیاط':'caution', 
 'کد':'code', 
 'بلوک-کد':'code', 
 'کد-منبع':'code', 
 'خطر':'danger', 
 'خطا':'error', 
 'راهنما':'hint', 
 'مهم':'important', 
 'یادداشت':'note', 
 'نکته':'tip', 
 'اخطار':'warning', 
 'تذکر':'admonition', 
 'نوار-کناری':'sidebar', 
 'موضوع':'topic', 
 'بلوک-خط':'line-block', 
 'تلفظ-پردازش-شده':'parsed-literal', 
 'سر-فصل':'rubric', 
 'کتیبه':'epigraph', 
 'نکات-برجسته':'highlights', 
 'نقل-قول':'pull-quote', 
 'ترکیب':'compound', 
 'ظرف':'container', 
 'جدول':'table', 
 'جدول-csv':'csv-table', 
 'جدول-لیست':'list-table', 
 'متا':'meta', 
 'ریاضی':'math', 
 'تصویر':'image', 
 'شکل':'figure', 
 'شامل':'include', 
 'خام':'raw', 
 'جایگزین':'replace', 
 'یونیکد':'unicode', 
 'تاریخ':'date', 
 'کلاس':'class', 
 'قانون':'role', 
 'قانون-پیش\u200cفرض':'default-role', 
 'عنوان':'title', 
 'محتوا':'contents', 
 'شماره-فصل':'sectnum', 
 'شماره\u200cگذاری-فصل':'sectnum', 
 'سرآیند':'header', 
 'پاصفحه':'footer', 
 'یادداشت-هدف':'target-notes'}
roles = {'مخفف':'abbreviation', 
 'سرنام':'acronym', 
 'کد':'code', 
 'شاخص':'index', 
 'زیرنویس':'subscript', 
 'بالانویس':'superscript', 
 'عنوان':'title-reference', 
 'نیرو':'pep-reference', 
 'rfc-reference (translation required)':'rfc-reference', 
 'تاکید':'emphasis', 
 'قوی':'strong', 
 'لفظی':'literal', 
 'ریاضی':'math', 
 'منبع-نام\u200cگذاری':'named-reference', 
 'منبع-ناشناس':'anonymous-reference', 
 'منبع-پانویس':'footnote-reference', 
 'منبع-نقل\u200cفول':'citation-reference', 
 'منبع-جایگزینی':'substitution-reference', 
 'هدف':'target', 
 'منبع-uri':'uri-reference', 
 'uri':'uri-reference', 
 'url':'uri-reference', 
 'خام':'raw'}