# uncompyle6 version 3.7.4
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /tmp/pip-build-ed191__6/docutils/docutils/parsers/rst/languages/sv.py
# Compiled at: 2020-01-10 16:25:35
# Size of source mod 2**32: 3267 bytes
"""
Swedish language mappings for language-dependent features of reStructuredText.
"""
__docformat__ = 'reStructuredText'
directives = {'observera':'attention', 
 'akta':'caution', 
 'kod':'code', 
 'fara':'danger', 
 'fel':'error', 
 'vink':'hint', 
 'viktigt':'important', 
 'notera':'note', 
 'tips':'tip', 
 'varning':'warning', 
 'anmärkning':'admonition', 
 'sidorad':'sidebar', 
 'ämne':'topic', 
 'tema':'topic', 
 'rad-block':'line-block', 
 'parsed-literal (translation required)':'parsed-literal', 
 'rubrik':'rubric', 
 'epigraf':'epigraph', 
 'höjdpunkter':'highlights', 
 'pull-quote (translation required)':'pull-quote', 
 'sammansatt':'compound', 
 'container':'container', 
 'tabell':'table', 
 'csv-tabell':'csv-table', 
 'list-tabell':'list-table', 
 'meta':'meta', 
 'matematik':'math', 
 'bild':'image', 
 'figur':'figure', 
 'inkludera':'include', 
 'rå':'raw', 
 'ersätta':'replace', 
 'unicode':'unicode', 
 'datum':'date', 
 'klass':'class', 
 'roll':'role', 
 'standardroll':'default-role', 
 'titel':'title', 
 'innehåll':'contents', 
 'sektionsnumrering':'sectnum', 
 'target-notes (translation required)':'target-notes', 
 'sidhuvud':'header', 
 'sidfot':'footer'}
roles = {'förkortning':'abbreviation', 
 'akronym':'acronym', 
 'kod':'code', 
 'index':'index', 
 'nedsänkt':'subscript', 
 'upphöjd':'superscript', 
 'titel-referens':'title-reference', 
 'pep-referens':'pep-reference', 
 'rfc-referens':'rfc-reference', 
 'betoning':'emphasis', 
 'stark':'strong', 
 'bokstavlig':'literal', 
 'matematik':'math', 
 'namngiven-referens':'named-reference', 
 'anonym-referens':'anonymous-reference', 
 'fotnot-referens':'footnote-reference', 
 'citat-referens':'citation-reference', 
 'ersättnings-referens':'substitution-reference', 
 'mål':'target', 
 'uri-referens':'uri-reference', 
 'rå':'raw'}