# uncompyle6 version 3.7.4
# Python bytecode 2.7 (62211)
# Decompiled from: Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
# [GCC 8.4.0]
# Embedded file name: /home/ana/dev/dexy-viewer/dexy_viewer/__init__.py
# Compiled at: 2013-08-03 02:31:41
from dexy.plugin import Command
from middleware import StaticMiddleware
import socket, web

class ViewerCommand(Command):
    """
    Starts a web.py application which lets you preview the snippets generated
    by your previous dexy run.
    """
    aliases = [
     'viewer']
    NAMESPACE = 'viewer'


def viewer_command(port=8090):
    """
    Starts a web.py application which lets you preview the snippets generated by your previous dexy run.
    """
    import app as viewer
    func = viewer.app.wsgifunc()
    server_address = ('0.0.0.0', port)
    func = StaticMiddleware(func)
    func = web.httpserver.LogMiddleware(func)
    server = web.httpserver.WSGIServer(server_address, func)
    print 'launching viewer at http://%s:%d/' % server_address
    print 'type ctrl+c to stop the server.'
    try:
        server.start()
    except KeyboardInterrupt:
        server.stop()
    except socket.error:
        print 'ERROR port %s already in use, server not started' % port


def ping_command():
    print 'pong'