# uncompyle6 version 3.6.7
# Python bytecode 3.6 (3379)
# Decompiled from: Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: /home/postlund/pyatv_dev/pyatv/pyatv/mrp/protobuf/LanguageOption_pb2.py
# Compiled at: 2019-09-30 07:18:14
# Size of source mod 2**32: 3668 bytes
import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor.FileDescriptor(name='pyatv/mrp/protobuf/LanguageOption.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=(_b('\n\'pyatv/mrp/protobuf/LanguageOption.proto"u\n\x0eLanguageOption\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x13\n\x0blanguageTag\x18\x02 \x01(\t\x12\x17\n\x0fcharacteristics\x18\x03 \x03(\t\x12\x13\n\x0bdisplayName\x18\x04 \x01(\t\x12\x12\n\nidentifier\x18\x05 \x01(\t')))
_LANGUAGEOPTION = _descriptor.Descriptor(name='LanguageOption',
  full_name='LanguageOption',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
 _descriptor.FieldDescriptor(name='type',
   full_name='LanguageOption.type',
   index=0,
   number=1,
   type=5,
   cpp_type=1,
   label=1,
   has_default_value=False,
   default_value=0,
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='languageTag',
   full_name='LanguageOption.languageTag',
   index=1,
   number=2,
   type=9,
   cpp_type=9,
   label=1,
   has_default_value=False,
   default_value=(_b('').decode('utf-8')),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='characteristics',
   full_name='LanguageOption.characteristics',
   index=2,
   number=3,
   type=9,
   cpp_type=9,
   label=3,
   has_default_value=False,
   default_value=[],
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='displayName',
   full_name='LanguageOption.displayName',
   index=3,
   number=4,
   type=9,
   cpp_type=9,
   label=1,
   has_default_value=False,
   default_value=(_b('').decode('utf-8')),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR),
 _descriptor.FieldDescriptor(name='identifier',
   full_name='LanguageOption.identifier',
   index=4,
   number=5,
   type=9,
   cpp_type=9,
   label=1,
   has_default_value=False,
   default_value=(_b('').decode('utf-8')),
   message_type=None,
   enum_type=None,
   containing_type=None,
   is_extension=False,
   extension_scope=None,
   serialized_options=None,
   file=DESCRIPTOR)],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[],
  serialized_start=43,
  serialized_end=160)
DESCRIPTOR.message_types_by_name['LanguageOption'] = _LANGUAGEOPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
LanguageOption = _reflection.GeneratedProtocolMessageType('LanguageOption', (_message.Message,), {'DESCRIPTOR':_LANGUAGEOPTION, 
 '__module__':'pyatv.mrp.protobuf.LanguageOption_pb2'})
_sym_db.RegisterMessage(LanguageOption)